import { describe,it,expect,afterEach,vi } from 'vitest'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import { MemoryStore } from './store'
import { scheduledRunAlerts,checkSchedulerHealth } from './alerts'
import { alertSummary } from '../domain/operationalAlerts'
import { ProviderFailure } from '../domain/providerFailure'
import { ClientCredentialsGenesys } from './providers'
import { executeServerRun,schedulerTick,type RunnerDeps } from './runner'
import { createApi } from './api'
import { seedForms } from '../domain/forms'
import { sampleLibrary } from '../domain/conversations'
import { fixtureEvaluation } from '../fixtures/evaluationFixture'
import type { PolicyRun,InteractionPolicy } from '../domain/types'
const now='2026-10-01T12:00:00.000Z',later='2026-10-01T16:00:00.000Z'
const policy:InteractionPolicy={id:'p',name:'Policy',description:'',enabled:true,criteria:{anyOf:[[{field:'channel',operator:'equals',value:'voice'}]]},evaluationFormIds:[seedForms[0].id]}
const run=(status:PolicyRun['status']='failed'):PolicyRun=>({id:'run',policyId:'p',policySnapshot:policy,source:'genesys-cloud',executionMode:'scheduled',startedAt:now,completedAt:now,status,candidateConversationCount:0,matchedConversationCount:0,formsAssigned:[],evaluationsRequested:0,evaluationsSucceeded:0,evaluationsFailed:0,failures:[]})
const servers:Server[]=[]
afterEach(async()=>{for(const s of servers.splice(0))await new Promise<void>(resolve=>s.close(()=>resolve()))})
const deps=(store=new MemoryStore()):RunnerDeps=>({store,now:()=>new Date(now),genesys:{list:async()=>({conversations:[],page:1,pageSize:25,total:0,hasMore:false}),load:async()=>sampleLibrary[0].conversation,withQueueNames:async c=>c},jev:{evaluate:async request=>fixtureEvaluation(request)}})
describe('durable operational alerts',()=>{
 it.each([['failed','SCHEDULED_RUN_FAILED','ERROR'],['partial-failure','SCHEDULED_RUN_PARTIAL','WARNING']] as const)('alerts on %s scheduled runs',async(status,type,severity)=>{const store=new MemoryStore();await scheduledRunAlerts(store,run(status),now);expect(await store.alerts()).toEqual([expect.objectContaining({type,severity,status:'OPEN',runId:'run'})])})
 it('does not create failure alerts on success or manual runs',async()=>{const store=new MemoryStore();await scheduledRunAlerts(store,run('completed'),now);await scheduledRunAlerts(store,{...run(),executionMode:'manual'},now);expect(await store.alerts()).toEqual([])})
 it.each(['GENESYS_AUTH_FAILURE','GENESYS_QUERY_FAILURE','JEV_FAILURE'] as const)('uses structured %s classification and excludes raw details',async code=>{const store=new MemoryStore();await scheduledRunAlerts(store,{...run(),failures:[{conversationId:'private-id',code,reason:'Bearer SECRET private transcript full text'}]},now);expect((await store.alerts()).some(a=>a.type===code)).toBe(true);expect(JSON.stringify(await store.alerts())).not.toMatch(/SECRET|private transcript|Bearer|private-id/)})
 it('does not infer provider errors from arbitrary free text',async()=>{const store=new MemoryStore();await scheduledRunAlerts(store,{...run(),failures:[{conversationId:'',reason:'auth token jev failed'}]},now);expect(await store.alerts()).toHaveLength(1)})
 it('deduplicates concurrent reports, retains acknowledgement and opens a new recurrence',async()=>{const store=new MemoryStore();await Promise.all(Array.from({length:5},()=>scheduledRunAlerts(store,run(),now)));const [a]=await store.alerts();expect(a.occurrences).toBe(5);await store.transitionAlert(a.id,'ACKNOWLEDGED',now,{userId:'op'});await scheduledRunAlerts(store,{...run(),id:'next'},later);expect((await store.alert(a.id))!.status).toBe('ACKNOWLEDGED');expect((await store.alert(a.id))!.runId).toBe('next');await store.transitionAlert(a.id,'RESOLVED',later,{userId:'op'});await scheduledRunAlerts(store,run(),later);expect(await store.alerts()).toHaveLength(2);expect((await store.alerts()).filter(a=>a.status==='OPEN')).toHaveLength(1)})
 it('acknowledges and resolves idempotently with audit timestamps',async()=>{const store=new MemoryStore();await scheduledRunAlerts(store,run(),now);const [a]=await store.alerts();await store.transitionAlert(a.id,'ACKNOWLEDGED',now,{userId:'op'});await store.transitionAlert(a.id,'ACKNOWLEDGED',later,{userId:'other'});await store.transitionAlert(a.id,'RESOLVED',later,{userId:'op'});await store.transitionAlert(a.id,'RESOLVED',later,{userId:'other'});const saved=await store.alert(a.id);expect(saved).toMatchObject({acknowledgedAt:now,resolvedAt:later,acknowledgedBy:{userId:'op'},resolvedBy:{userId:'op'}});expect(saved!.events).toHaveLength(3)})
 it.each([['voice','LOW_TRANSCRIPT_AVAILABILITY'],['email','LOW_DIGITAL_CONTENT_AVAILABILITY'],['messaging','LOW_DIGITAL_CONTENT_AVAILABILITY']] as const)('alerts on low %s availability with sufficient sample',async(channel,type)=>{const store=new MemoryStore();await scheduledRunAlerts(store,{...run('completed'),policySnapshot:{...policy,criteria:{anyOf:[[{field:'channel',operator:'equals',value:channel}]]}},sampledConversationIds:['1','2','3','4','5'],evaluableCount:3},now);expect((await store.alerts())[0]).toMatchObject({type,metadata:{sampled:5,available:3,availability:.6}})})
 it('does not alert on tiny samples or adequate availability',async()=>{const store=new MemoryStore();for(const [sampled,available] of [[4,0],[10,7]])await scheduledRunAlerts(store,{...run('completed'),sampledConversationIds:Array.from({length:sampled},(_,i)=>String(i)),evaluableCount:available},now);expect(await store.alerts()).toEqual([])})
 it('auto-resolves provider alerts only where a later run proves recovery',async()=>{const store=new MemoryStore();await scheduledRunAlerts(store,{...run(),failures:[{conversationId:'',code:'GENESYS_AUTH_FAILURE',reason:'x'},{conversationId:'',code:'JEV_FAILURE',reason:'x'}]},now);await scheduledRunAlerts(store,run('completed'),later);expect((await store.alerts()).find(a=>a.type==='GENESYS_AUTH_FAILURE')!.status).toBe('RESOLVED');expect((await store.alerts()).find(a=>a.type==='JEV_FAILURE')!.status).toBe('OPEN');await scheduledRunAlerts(store,{...run('completed'),evaluationsSucceeded:1},later);expect((await store.alerts()).find(a=>a.type==='JEV_FAILURE')!.status).toBe('RESOLVED');expect((await store.alerts()).find(a=>a.type==='SCHEDULED_RUN_FAILED')!.status).toBe('OPEN')})
 it('checks scheduler activity, including no-work healthy ticks and first-install grace',async()=>{const store=new MemoryStore();await checkSchedulerHealth(store,now,true);expect(await store.alerts()).toEqual([]);await checkSchedulerHealth(store,later,true);expect((await store.alerts())[0].type).toBe('SCHEDULER_STALE');await schedulerTick({...deps(store),now:()=>new Date(later)});expect((await store.alerts())[0].status).toBe('RESOLVED');expect((await store.schedulerHealth())!.lastSuccessfulTickAt).toBe(later);await checkSchedulerHealth(store,'2026-10-01T18:00:00Z',true);expect(alertSummary(await store.alerts()).openAlertCount).toBe(0)})
 it('does not flag an unconfigured scheduler',async()=>{const store=new MemoryStore();await checkSchedulerHealth(store,now,false);await checkSchedulerHealth(store,later,false);expect(await store.schedulerHealth()).toBeUndefined();expect(await store.alerts()).toEqual([])})
 it('classifies real provider HTTP authentication/query boundaries without network',async()=>{const auth=new ClientCredentialsGenesys('eu-west-1','id','secret',async()=>new Response('{}',{status:401}));await expect(auth.list({from:'2026-09-28T00:00:00Z',to:'2026-09-29T00:00:00Z',page:1,pageSize:25})).rejects.toMatchObject({code:'GENESYS_AUTH_FAILURE'});const query=new ClientCredentialsGenesys('eu-west-1','id','secret',async url=>String(url).includes('/oauth/token')?new Response(JSON.stringify({access_token:'token',expires_in:3600})):new Response('{}',{status:500}));await expect(query.list({from:'2026-09-28T00:00:00Z',to:'2026-09-29T00:00:00Z',page:1,pageSize:25})).rejects.toMatchObject({code:'GENESYS_QUERY_FAILURE'})})
 it('integrates planning failures and Jev failures with scheduled execution',async()=>{const d=deps(),store=d.store;await store.putForm(seedForms[0]);d.genesys.list=async()=>{throw new ProviderFailure('GENESYS_AUTH_FAILURE','auth')};const period={periodStart:'2026-09-28T00:00:00Z',periodEnd:'2026-09-29T00:00:00Z'};await expect(executeServerRun(d,policy,period,'auth','scheduled')).rejects.toThrow('auth');expect((await store.alerts()).map(a=>a.type)).toContain('GENESYS_AUTH_FAILURE');const c={...sampleLibrary[0].conversation,channel:'voice',startedAt:'2026-09-28T12:00:00Z'};d.genesys.list=async()=>({conversations:[c],page:1,pageSize:25,total:1,hasMore:false});d.genesys.load=async()=>c;d.jev.evaluate=vi.fn(async()=>{throw Error('private transcript secret')});await executeServerRun(d,policy,period,'jev','scheduled');expect((await store.alerts()).map(a=>a.type)).toContain('JEV_FAILURE');expect(JSON.stringify(await store.alerts())).not.toContain('private transcript secret')})
 it('authenticates APIs, filters and pages alerts, derives actor from server and keeps public health anonymous',async()=>{
  const d=deps(),store=d.store;await scheduledRunAlerts(store,run(),now);await scheduledRunAlerts(store,{...run('partial-failure'),policyId:'other'},now)
  const server=createApi(d,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['trusted']),schedulerEmail:'scheduler',schedulerAudience:'api'},async()=>new Response(JSON.stringify({id:'trusted',name:'Operator'})));servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={Authorization:'Bearer user','Content-Type':'application/json'}
  expect((await fetch(`${base}/api/alerts`)).status).toBe(401);const list=await (await fetch(`${base}/api/alerts?severity=ERROR&policy=p&limit=1`,{headers})).json();expect(list.items).toHaveLength(1);const a=list.items[0];expect((await fetch(`${base}/api/alerts/${a.id}`,{headers})).status).toBe(200)
  await fetch(`${base}/api/alerts/${a.id}/acknowledge`,{method:'POST',headers,body:JSON.stringify({actor:{userId:'forged'}})});expect((await store.alert(a.id))!.acknowledgedBy).toEqual({userId:'trusted',displayName:'Operator'});await fetch(`${base}/api/alerts/${a.id}/resolve`,{method:'POST',headers});expect((await store.alert(a.id))!.resolvedBy!.userId).toBe('trusted')
  const health=await (await fetch(`${base}/api/monitoring-health`,{headers})).json();expect(health).toMatchObject({openAlertCount:1,errorAlertCount:0,warningAlertCount:1});const pub=await (await fetch(`${base}/health`)).json();expect(pub).toEqual({status:'ok',schemaVersion:1});expect((await fetch(`${base}/api/alerts?status=invalid`,{headers})).status).toBe(400)
  expect((await (await fetch(`${base}/api/alerts?limit=1`,{headers})).json()).nextCursor).toBeTruthy();expect((await fetch(`${base}/api/alerts/missing`,{headers})).status).toBe(404)
 })
})
