import { afterEach,describe,expect,it } from 'vitest'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import { createApi } from './api'
import { MemoryStore } from './store'
import { seedAnswerSets } from '../domain/seedAnswerSets'
import { nextAnswerSetVersion, transitionAnswerSet } from '../domain/answerSets'
import { exportDefinition } from '../domain/portability'
import type { AnswerSetAsset } from '../domain/types'
import type { AuditEvent, Role } from '../domain/governance'
const now='2026-10-03T10:00:00.000Z',servers:Server[]=[]
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(r=>s.close(()=>r()))))})
async function fixture(){
 const store=new MemoryStore(),server=createApi({store,now:()=>new Date(now),genesys:{list:async()=>{throw Error('No Genesys')},load:async()=>{throw Error('No Genesys')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('No Jev')}}},{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['owner','author','reviewer','viewer']),bootstrapAdminId:'owner',schedulerEmail:'scheduler',schedulerAudience:'https://fixture'},async(_url,init)=>new Response(JSON.stringify({id:(init?.headers as Record<string,string>).Authorization.replace('Bearer ','')})))
 servers.push(server);await new Promise<void>(r=>server.listen(0,r));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`
 const call=(user:string,path:string,method='GET',value?:unknown)=>fetch(base+path,{method,headers:{...(user?{Authorization:`Bearer ${user}`}:{ }),'Content-Type':'application/json'},body:value===undefined?undefined:JSON.stringify(value)})
 for(const role of ['AUTHOR','REVIEWER','VIEWER'] as Role[])expect((await call('owner',`/api/roles/${role.toLowerCase()}`,'PUT',{role})).status).toBe(200)
 const draft={...structuredClone(seedAnswerSets[1]),status:'DRAFT' as const}
 const put=(a:AnswerSetAsset,user='author')=>call(user,`/api/answer-sets/${a.id}`,'PUT',a)
 return {store,call,draft,put}
}
describe('Answer Set durable authoring API',()=>{
 it('paginates empty/saved libraries with forms permissions and no production seed',async()=>{const {store,call,draft,put}=await fixture();expect((await call('','/api/answer-sets')).status).toBe(401);expect((await store.query('answerSetAssets',100)).items).toEqual([]);expect((await put(draft)).status).toBe(200);const v2=nextAnswerSetVersion(draft,[draft],now);expect((await put(v2)).status).toBe(200);for(const user of ['owner','author','reviewer','viewer']){const p=await call(user,'/api/answer-sets?limit=1');expect(p.status).toBe(200);const first=await p.json();expect(first.items[0].id).toBe(draft.id);const second=await (await call(user,`/api/answer-sets?limit=1&cursor=${first.nextCursor}`)).json();expect(second.items[0].id).toBe(v2.id);expect(second.nextCursor).toBeUndefined()}expect((await call('author',`/api/answer-sets/${draft.id}`)).status).toBe(200)})
 it('saves drafts, publishes, rejects mutations, creates new versions and retires safely',async()=>{const {store,draft,put}=await fixture();expect((await put(draft)).status).toBe(200);const p=transitionAnswerSet(draft,'PUBLISHED',now);expect((await put(p)).status).toBe(200);const bad=await put({...p,name:'Mutation'});expect(bad.status).toBe(400);expect((await bad.json()).error).toContain('immutable');expect((await put({...p,status:'DRAFT'})).status).toBe(400);const v2=nextAnswerSetVersion(p,[p],now);expect((await put(v2)).status).toBe(200);expect((await put(transitionAnswerSet(v2,'PUBLISHED',now))).status).toBe(200);expect((await put(transitionAnswerSet(p,'RETIRED',now))).status).toBe(200);expect((await store.answerSet(p.id))?.options).toEqual(p.options);expect((await store.answerSet(v2.id))?.status).toBe('PUBLISHED')})
 it('blocks reviewer/viewer mutation including lifecycle/import/delete',async()=>{const {call,draft,put}=await fixture();expect((await put(draft,'owner')).status).toBe(200);for(const user of ['reviewer','viewer']){for(const a of [draft,transitionAnswerSet(draft,'PUBLISHED',now)])expect((await put(a,user)).status).toBe(403);expect((await call(user,'/api/answer-sets/import','POST',exportDefinition('answer-set',draft))).status).toBe(403);expect((await call(user,`/api/answer-sets/${draft.id}`,'DELETE')).status).toBe(403)}expect((await call('author',`/api/answer-sets/${draft.id}`,'DELETE')).status).toBe(404)})
 it('enforces family/version uniqueness, stable base type and request bounds',async()=>{const {call,draft,put}=await fixture();expect((await put(draft)).status).toBe(200);const conflict=await put({...draft,id:'conflict'});expect(conflict.status).toBe(400);expect((await conflict.json()).error).toContain('already exists');const v2=nextAnswerSetVersion(draft,[draft],now);expect((await put({...v2,type:'score'})).status).toBe(400);for(const q of ['limit=101','limit=0','limit=abc','cursor=bad/path'])expect((await call('author',`/api/answer-sets?${q}`)).status).toBe(400);expect((await put({...draft,name:'x'.repeat(100001)})).status).toBe(400);expect((await put({...draft,options:[]})).status).toBe(400);expect((await call('author','/api/answer-sets/wrong','PUT',draft)).status).toBe(400)})
 it('imports to a new draft family and audits safe lifecycle metadata/history',async()=>{const {store,call,draft,put}=await fixture();expect((await put(draft)).status).toBe(200);const p=transitionAnswerSet(draft,'PUBLISHED',now);await put(p);const v2=nextAnswerSetVersion(p,[p],now);await put(v2);await put(transitionAnswerSet(p,'RETIRED',now));const response=await call('author','/api/answer-sets/import','POST',exportDefinition('answer-set',p));expect(response.status).toBe(201);const {item}=await response.json();expect(item).toMatchObject({status:'DRAFT',version:1});expect(item.familyId).toBe(item.id);expect(item.id).not.toBe(p.id);expect(item.options).toEqual(p.options);const events=(await store.query<AuditEvent>('auditEvents',100)).items.filter(e=>e.resourceType==='answer_set');expect(events.map(e=>e.action)).toEqual(expect.arrayContaining(['answer_set.create','answer_set.publish','answer_set.new_version','answer_set.retire','answer_set.imported']));expect(events.every(e=>e.actor.userId==='author')).toBe(true);expect(JSON.stringify(events)).not.toMatch(/Clear|Partly clear|options|accessToken/);const h=await call('author',`/api/history?resourceType=answer_set&resourceId=${p.id}`);expect(h.status).toBe(200);expect((await h.json()).items.length).toBeGreaterThan(0);for(const bad of [{schemaVersion:2}, {schema:'wrong'}])expect((await call('author','/api/answer-sets/import','POST',{...exportDefinition('answer-set',p),...bad})).status).toBe(400)})
})
