import { fixtureEvaluation } from '../fixtures/evaluationFixture'
import { afterEach,describe,it,expect } from 'vitest'
import { createApi } from './api'
import { MemoryStore } from './store'
import type { RunnerDeps } from './runner'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import { seedForms } from '../domain/forms'
import { sampleLibrary } from '../domain/conversations'
import type { Conversation, InteractionPolicy } from '../domain/types'
const servers:Server[]=[]
afterEach(async()=>{await Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve()))))})
async function fixture(){const store=new MemoryStore();const deps:RunnerDeps={store,genesys:{list:async()=>({conversations:[],page:1,pageSize:25,total:0,hasMore:false}),load:async()=>{throw Error('no')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('no')}},now:()=>new Date('2026-09-30T00:00:00Z')};const server=createApi(deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['allowed']),schedulerEmail:'aqm-scheduler@example.com',schedulerAudience:'https://aqm.example.com'},async()=>new Response(JSON.stringify({id:'allowed'}),{status:200}));servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));return `http://127.0.0.1:${(server.address() as AddressInfo).port}`}
describe('AQM API authorization',()=>{
  it('pages collections and rejects published form edits or draft policy pins',async()=>{const base=await fixture();const headers={Authorization:'Bearer token','Content-Type':'application/json'};const form=seedForms[0];const put=(path:string,value:unknown)=>fetch(`${base}${path}`,{method:'PUT',headers,body:JSON.stringify(value)});expect((await put(`/api/forms/${form.id}`,form)).status).toBe(200);const changed={...form,name:'Changed after publish'};expect((await put(`/api/forms/${form.id}`,changed)).status).toBe(400);const page=await (await fetch(`${base}/api/forms?limit=1`,{headers})).json() as {items:typeof seedForms;scanned:number};expect(page.items).toHaveLength(1);expect(page.scanned).toBe(1);const policy:InteractionPolicy={id:'p',name:'P',description:'',enabled:true,criteria:{anyOf:[]},evaluationFormIds:['missing']};expect((await put('/api/policies/p',{...policy,expectedVersion:null})).status).toBe(400)})

  it('allows only the configured Pages origin for CORS and requires user auth',async()=>{const base=await fixture();const good=await fetch(`${base}/api/policies`,{method:'OPTIONS',headers:{Origin:'https://simonridd.github.io'}});expect(good.status).toBe(204);expect(good.headers.get('access-control-allow-origin')).toBe('https://simonridd.github.io');const bad=await fetch(`${base}/api/policies`,{method:'OPTIONS',headers:{Origin:'https://evil.example'}});expect(bad.status).toBe(403);expect(bad.headers.get('access-control-allow-origin')).toBeNull();expect((await fetch(`${base}/api/policies`)).status).toBe(401);expect((await fetch(`${base}/api/policies`,{headers:{Authorization:'Bearer token'}})).status).toBe(200)})
  it('provides authenticated dependency health and run detail without secret fields',async()=>{const base=await fixture(),headers={Authorization:'Bearer token'};expect((await fetch(`${base}/api/monitoring-health`)).status).toBe(401);const health=await fetch(`${base}/api/monitoring-health`,{headers});expect(health.status).toBe(200);const body=await health.json() as {api:string;firestore:string;genesysAutomation:{status:string};jev:{status:string};scheduler:{status:string};runCounts:Record<string,number>};expect(body.api).toBe('healthy');expect(body.firestore).toBe('available');expect(body.genesysAutomation.status).toBe('unverified');expect(body.jev.status).toBe('unverified');expect(body.scheduler.status).toBe('configured_unverified');expect(JSON.stringify(body)).not.toMatch(/secret|token|key/i);expect((await fetch(`${base}/api/runs/does_not_exist`,{headers})).status).toBe(404)})
  it('keeps form test routes authorized and separate from production history',async()=>{const base=await fixture(),id='sandbox_1',form={...seedForms[0],status:'DRAFT' as const,enabled:false},headers={Authorization:'Bearer token','Content-Type':'application/json'};const input={id,form,source:'synthetic',selectedConversationIds:[sampleLibrary[0].conversation.conversationId],sampleConfiguration:{strategy:'manual',count:1}};expect((await fetch(`${base}/api/form-tests/${id}`,{method:'POST',body:JSON.stringify(input)})).status).toBe(401);const response=await fetch(`${base}/api/form-tests/${id}`,{method:'POST',headers,body:JSON.stringify(input)});expect(response.status).toBe(200);const body=await response.json() as {run:{status:string;failures:unknown[]}};expect(body.run.status).toBe('failed');expect(body.run.failures).toHaveLength(1);const history=await (await fetch(`${base}/api/form-tests`,{headers})).json() as {items:unknown[]};expect(history.items).toHaveLength(1);const evaluations=await (await fetch(`${base}/api/evaluations`,{headers})).json() as {items:unknown[]};expect(evaluations.items).toHaveLength(0);expect((await fetch(`${base}/api/form-tests/${id}`,{method:'DELETE',headers})).status).toBe(200)})
  it('does not accept browser bearer authorization on internal scheduler route',async()=>{const base=await fixture();const response=await fetch(`${base}/internal/scheduler/tick`,{method:'POST',headers:{Authorization:'Bearer browser-token'}});expect(response.status).toBe(403);expect(await response.text()).not.toContain('secret')})
  it('requires a fresh preview before manual server execution',async()=>{
    const store=new MemoryStore(),form=seedForms[0]
    const policy:InteractionPolicy={id:'policy',name:'Voice',description:'',enabled:true,version:1,criteria:{anyOf:[[{field:'channel',operator:'equals',value:'voice'}]]},evaluationFormIds:[form.id]}
    const conversation:Conversation={conversationId:'12345678-1234-1234-1234-123456789abc',startedAt:'2026-09-28T12:00:00Z',channel:'voice',agent:{id:'a',name:'Agent'},customer:{id:'b',name:'Customer'},metadata:{source:'genesys-cloud'},messages:[{id:'m',timestamp:'2026-09-28T12:00:01Z',speaker:'customer',text:'private transcript'}]}
    await store.putForm(form);await store.putPolicy(policy)
    const deps:RunnerDeps={store,genesys:{list:async()=>({conversations:[conversation],page:1,pageSize:25,total:1,hasMore:false}),load:async()=>conversation,withQueueNames:async c=>c},jev:{evaluate:async(request:import("../domain/types").EvaluationRequest)=>fixtureEvaluation(request)},now:()=>new Date('2026-09-30T00:00:00Z')}
    const server=createApi(deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['allowed']),schedulerEmail:'aqm-scheduler@example.com',schedulerAudience:'https://aqm.example.com'},async()=>new Response(JSON.stringify({id:'allowed'}),{status:200}));servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`
    const period={periodStart:'2026-09-28T00:00:00Z',periodEnd:'2026-09-29T00:00:00Z'},headers={Authorization:'Bearer user-token','Content-Type':'application/json'}
    const post=(route:string,payload:unknown)=>fetch(`${base}${route}`,{method:'POST',headers,body:JSON.stringify(payload)})
    const preview=await post('/api/policies/policy/plan',{period});expect(preview.status).toBe(200);const plan=await preview.json() as {fingerprint:string;expectedEvaluations:number};expect(plan.expectedEvaluations).toBe(1)
    expect((await post('/api/policies/policy/run',{period,fingerprint:'wrong'})).status).toBe(409)
    const executed=await post('/api/policies/policy/run',{period,fingerprint:plan.fingerprint});expect(executed.status).toBe(200)
    expect((await store.evaluations())).toHaveLength(1);expect(JSON.stringify(await store.evaluations())).not.toContain('private transcript')
  })
})
it('email relay enforces the user allowlist and forwards that same PKCE identity without using automation credentials',async()=>{
 const store=new MemoryStore(),requests:Array<{url:string;authorization:string|undefined}>=[]
 const conversationId='22222222-2222-4222-8222-222222222222',recordingId='44444444-4444-4444-8444-444444444444',sessionId='33333333-3333-4333-8333-333333333333'
 const deps:RunnerDeps={store,now:()=>new Date(),genesys:{list:async()=>{throw Error('Automation must not be used')},load:async()=>{throw Error('Automation must not be used')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('Jev must not be used')}}}
 const fetcher:typeof fetch=async(input,init)=>{const url=String(input),authorization=(init?.headers as Record<string,string>)?.Authorization;requests.push({url,authorization});let value:unknown
 if(url.endsWith('/users/me'))value={id:authorization==='Bearer allowed-pkce'?'allowed':'denied'}
 else if(url.endsWith('/details'))value={conversationId,conversationStart:'2026-09-30T12:00:00Z',conversationEnd:'2026-09-30T12:10:00Z',participants:[{purpose:'external',sessions:[{sessionId,mediaType:'email',addressSelf:'customer@example.com'}]}]}
 else if(url.includes('/recordings?'))value=[{id:recordingId,media:'email'}]
 else value={id:recordingId,sessionId,emailTranscript:[{id:'one',time:'2026-09-30T12:01:00Z',from:{email:'customer@example.com'},textBody:'Private normalized body',attachments:[{url:'https://private.example/secret'}]}]}
 return new Response(JSON.stringify(value),{status:200})}
 const server=createApi(deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['allowed']),schedulerEmail:'scheduler@example.com',schedulerAudience:'https://aqm.example.com'},fetcher);servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/conversations/${conversationId}/email`
 expect((await fetch(url)).status).toBe(401);expect((await fetch(url,{headers:{Authorization:'Bearer denied-pkce'}})).status).toBe(401)
 const response=await fetch(url,{headers:{Authorization:'Bearer allowed-pkce'}});expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');const value=await response.json() as Conversation;expect(value.messages[0].text).toBe('Private normalized body');expect(JSON.stringify(value)).not.toMatch(/secret|attachments|pkce/)
 expect(requests.filter(r=>!r.url.endsWith('/users/me')).every(r=>r.authorization==='Bearer allowed-pkce')).toBe(true);expect(await store.evaluations()).toEqual([])
})

it('messaging relay enforces the user allowlist and forwards that same PKCE identity without using automation credentials',async()=>{
 const store=new MemoryStore(),requests:Array<{url:string;authorization:string|undefined}>=[]
 const conversationId='22222222-2222-4222-8222-222222222222',recordingId='44444444-4444-4444-8444-444444444444',sessionId='33333333-3333-4333-8333-333333333333'
 const deps:RunnerDeps={store,now:()=>new Date(),genesys:{list:async()=>{throw Error('Automation must not be used')},load:async()=>{throw Error('Automation must not be used')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('Jev must not be used')}}}
 const fetcher:typeof fetch=async(input,init)=>{const url=String(input),authorization=(init?.headers as Record<string,string>)?.Authorization;requests.push({url,authorization});let value:unknown
 if(url.endsWith('/users/me'))value={id:authorization==='Bearer allowed-pkce'?'allowed':'denied'}
 else if(url.endsWith('/details'))value={conversationId,conversationStart:'2026-09-30T12:00:00Z',conversationEnd:'2026-09-30T12:10:00Z',participants:[{purpose:'external',sessions:[{sessionId,mediaType:'message',addressSelf:'customer@example.com'}]}]}
 else if(url.endsWith('/bulk'))value={entities:[{id:'one',conversationId,timestamp:'2026-09-30T12:01:00Z',direction:'inbound',normalizedMessage:{type:'Text',text:'Private normalized body',content:[{contentType:'Attachment',attachment:{url:'https://private.example/secret'}}]}}]}
 else if(url.endsWith(`/conversations/messages/${conversationId}`))value={id:conversationId,participants:[{id:'p',purpose:'external',messages:[{messageId:'one'}]}]}
 else value={id:recordingId,sessionId,emailTranscript:[{id:'one',time:'2026-09-30T12:01:00Z',from:{email:'customer@example.com'},textBody:'Private normalized body',attachments:[{url:'https://private.example/secret'}]}]}
 return new Response(JSON.stringify(value),{status:200})}
 const server=createApi(deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['allowed']),schedulerEmail:'scheduler@example.com',schedulerAudience:'https://aqm.example.com'},fetcher);servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));const url=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/conversations/${conversationId}/digital`
 expect((await fetch(url)).status).toBe(401);expect((await fetch(url,{headers:{Authorization:'Bearer denied-pkce'}})).status).toBe(401)
 const response=await fetch(url,{headers:{Authorization:'Bearer allowed-pkce'}});expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');const value=await response.json() as Conversation;expect(value.messages[0].text).toBe('Private normalized body');expect(JSON.stringify(value)).not.toMatch(/secret|attachments|pkce/)
 expect(requests.filter(r=>!r.url.endsWith('/users/me')).every(r=>r.authorization==='Bearer allowed-pkce')).toBe(true);expect(await store.evaluations()).toEqual([])
})
