import {afterEach,expect,it} from 'vitest'
import type {Server} from 'node:http'
import type {AddressInfo} from 'node:net'
import {createApi} from './api'
import {MemoryStore} from './store'
import {seedForms} from '../domain/forms'
import {seedGroupAssets} from '../domain/seedGroupAssets'
import {exportDefinition} from '../domain/portability'
import type {RunnerDeps} from './runner'
import type {AuditEvent} from '../domain/governance'
const servers:Server[]=[]
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(r=>s.close(()=>r()))))})
async function fixture(){const store=new MemoryStore(),deps:RunnerDeps={store,now:()=>new Date('2026-10-02T10:00:00Z'),genesys:{list:async()=>{throw Error('No Genesys')},load:async()=>{throw Error('No Genesys')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('No Jev')}}};const server=createApi(deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['owner','viewer']),bootstrapAdminId:'owner',schedulerEmail:'scheduler',schedulerAudience:'fixture'},async(_,init)=>new Response(JSON.stringify({id:(init?.headers as Record<string,string>).Authorization.replace('Bearer ','')})));servers.push(server);await new Promise<void>(r=>server.listen(0,r));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;const call=(path:string,method:string,value:unknown,user='owner')=>fetch(base+path,{method,headers:{Authorization:`Bearer ${user}`,'Content-Type':'application/json'},body:JSON.stringify(value)});return {store,call}}
it('durably saves DRAFT/TESTING without transitions; published definitions stay immutable; failed save leaves server unchanged',async()=>{const {store,call}=await fixture();for(const status of ['DRAFT','TESTING'] as const){const form={...structuredClone(seedForms[0]),id:status,status,enabled:false};await store.putForm(form);const saved={...form,name:'Edited',updatedAt:'2026-10-02T10:00:00Z'};expect((await call(`/api/forms/${status}`,'PUT',saved)).status).toBe(200);expect(await store.form(status)).toEqual(saved);expect((await call(`/api/forms/${status}`,'PUT',{...saved,scoring:{...saved.scoring,passScore:2}})).status).toBe(400);expect(await store.form(status)).toEqual(saved)}const published={...structuredClone(seedForms[0]),status:'PUBLISHED' as const};await store.putForm(published);expect((await call(`/api/forms/${published.id}`,'PUT',{...published,name:'Changed'})).status).toBe(400);const events=(await store.query<AuditEvent>('auditEvents',100)).items;expect(events.filter(e=>e.action==='form.draft_saved')).toHaveLength(2)})
it('clones/imports server-authoritatively with safe audit events and read/write permissions',async()=>{const {store,call}=await fixture(),source={...structuredClone(seedForms[0]),status:'PUBLISHED' as const};await store.putForm(source);expect((await call(`/api/forms/${source.id}/clone`,'POST',{},'viewer')).status).toBe(403);expect((await call('/api/forms/import','POST',exportDefinition('form',source),'viewer')).status).toBe(403);expect((await call('/api/question-groups/import','POST',exportDefinition('group',seedGroupAssets[0]),'viewer')).status).toBe(403);const clone=await (await call(`/api/forms/${source.id}/clone`,'POST',{id:source.id,status:'PUBLISHED',owner:'viewer'})).json();expect(clone.item).toMatchObject({familyId:clone.item.id,status:'DRAFT',version:1,enabled:false});expect(clone.item.id).not.toBe(source.id);expect(await store.form(source.id)).toEqual(source);const imported=await (await call('/api/forms/import','POST',exportDefinition('form',source))).json();expect(imported.item).toMatchObject({status:'DRAFT',enabled:false,version:1});expect(imported.item.familyId).toBe(imported.item.id);const group=await(await call('/api/question-groups/import','POST',exportDefinition('group',seedGroupAssets[0]))).json();expect(group.item).toMatchObject({status:'DRAFT',version:1,familyId:group.item.id});expect((await call('/api/forms/import','POST',{schemaVersion:100})).status).toBe(400);expect(await store.evaluations()).toEqual([]);expect(await store.policies()).toEqual([]);const events=(await store.query<AuditEvent>('auditEvents',100)).items;expect(events.map(e=>e.action)).toEqual(expect.arrayContaining(['form.cloned','form.imported','group.imported']));expect(JSON.stringify(events)).not.toContain('instructions')})
