import { describe, expect, it, vi } from 'vitest'
import { MemoryStore } from './store'
import { evaluateManual } from './manualEvaluations'
import { executeServerRun, planServerRun, evaluationId, executionClaimId } from './runner'
import { executeFormTest } from './formTests'
import { fixtureEvaluation } from '../fixtures/evaluationFixture'
import { seedForms } from '../domain/forms'
import { sampleLibrary } from '../domain/conversations'
import type { EvaluationForm, EvaluationRequest, InteractionPolicy } from '../domain/types'
import type { RunnerDeps } from './runner'
const now='2026-10-01T12:00:00Z',period={periodStart:'2026-09-29T00:00:00Z',periodEnd:'2026-09-30T00:00:00Z'}
function setup(){
  const store=new MemoryStore(),base=structuredClone(seedForms[0]),first=base.questions[0],second=base.questions[1]
  const form:EvaluationForm={...base,status:'PUBLISHED',questions:[{...first,groupId:'opening'},{...second,groupId:'resolution',condition:{kind:'question_credit',questionId:first.id,operator:'greater_than_or_equal',value:.67}}],groups:[{id:'opening',name:'Opening'},{id:'resolution',name:'Resolution'}]}
  const conversation={...structuredClone(sampleLibrary[0].conversation),conversationId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',channel:'voice',metadata:{source:'genesys-cloud',status:'Completed',queue:'Customer Service'}}
  const evaluate=vi.fn(async(request:EvaluationRequest)=>fixtureEvaluation(request))
  const deps:RunnerDeps={store,genesys:{load:async()=>conversation,list:async()=>({conversations:[conversation],page:1,pageSize:25,total:1,hasMore:false}),withQueueNames:async c=>c},jev:{evaluate},now:()=>new Date(now)}
  const policy:InteractionPolicy={id:'voice',name:'Voice',description:'',enabled:true,criteria:{anyOf:[[{field:'channel',operator:'equals',value:'voice'}]]},evaluationFormIds:[form.id]}
  return {store,form,conversation,evaluate,deps,policy}
}
describe('all production routes share conditional orchestration and paid-call reservations',()=>{
  it('manual evaluation persists one complete snapshot and actual two requests',async()=>{const f=setup();await f.store.putForm(f.form);const input={source:'genesys-cloud',conversationId:f.conversation.conversationId,formId:f.form.id,formVersion:f.form.version};const result=await evaluateManual(f.deps,input);expect(result.status).toBe('created');expect(result.record!.providerRequestCount).toBe(2);expect(result.record!.groupResults!.map(g=>g.name)).toEqual(['Opening','Resolution']);expect(result.record!.form).toEqual(f.form);expect((await evaluateManual(f.deps,input)).status).toBe('duplicate');expect(f.evaluate).toHaveBeenCalledTimes(2)})
  it('uncertain second wave preserves the slot/progress and never repeats either wave',async()=>{const f=setup();await f.store.putForm(f.form);f.evaluate.mockImplementationOnce(async request=>fixtureEvaluation(request)).mockRejectedValueOnce(Error('Second wave interrupted'));const input={source:'genesys-cloud',conversationId:f.conversation.conversationId,formId:f.form.id,formVersion:f.form.version};expect((await evaluateManual(f.deps,input)).status).toBe('uncertain');expect((await evaluateManual(f.deps,input)).status).toBe('uncertain');expect(f.evaluate).toHaveBeenCalledTimes(2);expect(await f.store.evaluations()).toEqual([])})
  it.each(['manual','scheduled'] as const)('%s policy planning separates assignments/max requests and persists actual wave requests',async trigger=>{const f=setup();await f.store.putForm(f.form);const prepared=await planServerRun(f.deps,f.policy,period);expect(prepared.plan.expectedEvaluations).toBe(1);expect(prepared.plan.maximumProviderRequests).toBe(2);expect(f.evaluate).not.toHaveBeenCalled();const run=await executeServerRun(f.deps,f.policy,period,`run_${trigger}`,trigger,prepared);expect(run).toMatchObject({status:'completed',evaluationsRequested:1,evaluationsSucceeded:1,maximumProviderRequests:2,actualProviderRequests:2});expect((await f.store.evaluations())[0].providerRequestCount).toBe(2)})
  it('policy retry skips an uncertain multi-wave slot and retains charged progress',async()=>{const f=setup();await f.store.putForm(f.form);f.evaluate.mockImplementationOnce(async request=>fixtureEvaluation(request)).mockRejectedValueOnce(Error('Wave 2 uncertain'));const run=await executeServerRun(f.deps,f.policy,period,'run_uncertain','manual');expect(run.actualProviderRequests).toBe(2);const slot=await f.store.evaluationSlot(evaluationId(executionClaimId(f.policy,period),f.conversation.conversationId,f.form));expect(slot).toMatchObject({status:'started',providerRequestCount:2});const retry=await executeServerRun(f.deps,f.policy,period,'run_uncertain','manual');expect(retry.actualProviderRequests).toBe(2);expect(f.evaluate).toHaveBeenCalledTimes(2)})
  it('durable Form Test branches and records actual requests without production analytics',async()=>{const f=setup(),form={...f.form,status:'DRAFT' as const,enabled:false},input={id:'conditional_test',form,source:'synthetic' as const,selectedConversationIds:[sampleLibrary[0].conversation.conversationId],sampleConfiguration:{strategy:'manual' as const,count:1}};const run=await executeFormTest(f.deps,input);expect(run).toMatchObject({status:'completed',evaluationAssignments:1,expectedRequests:2,actualProviderRequests:2});expect(run.results[0].purpose).toBe('FORM_TEST');expect(run.results[0].questions.every(q=>q.status==='ANSWERED')).toBe(true);await executeFormTest(f.deps,input);expect(f.evaluate).toHaveBeenCalledTimes(2);expect(await f.store.evaluations()).toEqual([]);expect(await f.store.runs()).toEqual([])})
  it('uncertain second Form Test wave returns the same failed logical test without spending again',async()=>{const f=setup();f.evaluate.mockImplementationOnce(async request=>fixtureEvaluation(request)).mockRejectedValueOnce(Error('Uncertain second wave'));const input={id:'uncertain_test',form:f.form,source:'synthetic' as const,selectedConversationIds:[sampleLibrary[0].conversation.conversationId],sampleConfiguration:{strategy:'manual' as const,count:1}};const run=await executeFormTest(f.deps,input);expect(run).toMatchObject({status:'failed',actualProviderRequests:2});expect((await executeFormTest(f.deps,input)).id).toBe(run.id);expect(f.evaluate).toHaveBeenCalledTimes(2)})
})
