import { fixtureEvaluation } from '../fixtures/evaluationFixture'
import { describe,expect,it,vi } from 'vitest'
import { MemoryStore } from './store'
import { executeFormTest } from './formTests'
import { sampleLibrary } from '../domain/conversations'
import { seedForms } from '../domain/forms'
import type { RunnerDeps } from './runner'
describe('durable form tests',()=>{
  it('accepts a draft snapshot, isolates records, and never repeats a paid request for the same ID',async()=>{const store=new MemoryStore(),conversation=sampleLibrary[0].conversation,form={...structuredClone(seedForms[0]),status:'DRAFT' as const,enabled:false};const jev=vi.fn(async(request:import("../domain/types").EvaluationRequest)=>fixtureEvaluation(request));const deps:RunnerDeps={store,genesys:{list:async()=>{throw Error('unused')},load:async()=>{throw Error('unused')},withQueueNames:async items=>items},jev:{evaluate:jev},now:()=>new Date('2026-09-30T12:00:00Z')};const input={id:'test_1',form,source:'synthetic' as const,selectedConversationIds:[conversation.conversationId],sampleConfiguration:{strategy:'manual' as const,count:1}};const run=await executeFormTest(deps,input);expect(run.status).toBe('completed');expect(run.results[0].purpose).toBe('FORM_TEST');expect(run.formSnapshot.status).toBe('DRAFT');expect(await store.evaluations()).toEqual([]);expect(await store.runs()).toEqual([]);expect(JSON.stringify(run)).not.toContain(conversation.messages[0].text);await executeFormTest(deps,input);expect(jev).toHaveBeenCalledTimes(1)})
  it('does not repeat Jev after an ambiguous persistence failure',async()=>{const store=new MemoryStore(),conversation=sampleLibrary[0].conversation,form=seedForms[0];const jev=vi.fn(async(request:import("../domain/types").EvaluationRequest)=>fixtureEvaluation(request));const deps:RunnerDeps={store,genesys:{list:async()=>{throw Error('unused')},load:async()=>{throw Error('unused')},withQueueNames:async items=>items},jev:{evaluate:jev},now:()=>new Date('2026-09-30T12:00:00Z')};const input={id:'test_uncertain',form,source:'synthetic' as const,selectedConversationIds:[conversation.conversationId],sampleConfiguration:{strategy:'manual' as const,count:1}};const put=store.putFormTestRun.bind(store);vi.spyOn(store,'putFormTestRun').mockImplementationOnce(put).mockRejectedValueOnce(new Error('Firestore write interrupted'));await expect(executeFormTest(deps,input)).rejects.toThrow('Firestore');const prior=await executeFormTest(deps,input);expect(prior.status).toBe('running');expect(jev).toHaveBeenCalledTimes(1)})
  it('rejects a reused ID with a changed sample',async()=>{const store=new MemoryStore(),form=seedForms[0];const deps:RunnerDeps={store,genesys:{list:async()=>{throw Error('unused')},load:async()=>{throw Error('unused')},withQueueNames:async items=>items},jev:{evaluate:async()=>{throw Error('blocked')}},now:()=>new Date('2026-09-30T12:00:00Z')};const input={id:'test_2',form,source:'synthetic' as const,selectedConversationIds:[sampleLibrary[0].conversation.conversationId],sampleConfiguration:{strategy:'manual' as const,count:1}};await executeFormTest(deps,input);await expect(executeFormTest(deps,{...input,selectedConversationIds:[sampleLibrary[1].conversation.conversationId]})).rejects.toThrow('already bound')})
})
