import { afterEach,describe,it,expect,vi } from 'vitest'
import { createApi } from './api'
import { MemoryStore } from './store'
import { evaluateManual } from './manualEvaluations'
import type { RunnerDeps } from './runner'
import { recordEvaluation } from '../domain/evaluations'
import { seedForms } from '../domain/forms'
import { sampleLibrary } from '../domain/conversations'
import type { EvaluationResult } from '../domain/types'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
const servers:Server[]=[]
afterEach(async()=>{await Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve()))))})
async function fixture(){const store=new MemoryStore(),form=structuredClone(seedForms[0]);await store.putForm(form);const conversation={...structuredClone(sampleLibrary[0].conversation),conversationId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',metadata:{source:'genesys-cloud',status:'Completed'}};const output:EvaluationResult={conversationId:conversation.conversationId,scorecardId:form.id,scorecardVersion:form.version,evaluatedAt:'2026-09-30T12:00:00Z',provider:'typesafe',model:'fake',questions:[],overallScore:.8,countedWeight:1,rawResponse:{private:'not retained'}};const load=vi.fn(async()=>conversation),jev=vi.fn(async()=>output);const deps:RunnerDeps={store,genesys:{list:async()=>{throw Error('unused')},load,withQueueNames:async items=>items},jev:{evaluate:jev},now:()=>new Date('2026-09-30T12:00:00Z')};return {deps,store,form,conversation,output,load,jev,input:{source:'genesys-cloud' as const,conversationId:conversation.conversationId,formId:form.id,formVersion:form.version}}}
describe('manual production evaluation',()=>{
  it('loads server Genesys transcript and authoritative exact form, persists manual production record without transcript or raw response',async()=>{const f=await fixture();const result=await evaluateManual(f.deps,f.input);expect(result.status).toBe('created');expect(f.load).toHaveBeenCalledWith(f.conversation.conversationId);expect(f.jev.mock.calls[0]).toBeDefined();const [request]=f.jev.mock.calls[0] as unknown as [{scorecard:{id:string;version:number};conversation:typeof f.conversation}];expect(request.scorecard.id).toBe(f.form.id);expect(request.scorecard.version).toBe(f.form.version);expect(request.conversation.messages).toEqual(f.conversation.messages);expect(result.record).toMatchObject({purpose:'PRODUCTION',executionMode:'manual',conversationSource:'genesys-cloud',form:f.form});expect(await f.store.evaluations()).toEqual([result.record]);expect(JSON.stringify(await f.store.evaluations())).not.toContain(f.conversation.messages[0].text);expect(JSON.stringify(result)).not.toContain('not retained')})
  it('returns existing production evaluation without Genesys or another Jev call',async()=>{const f=await fixture();const first=await evaluateManual(f.deps,f.input);const again=await evaluateManual(f.deps,f.input);expect(again.status).toBe('duplicate');expect(again.record?.id).toBe(first.record?.id);expect(f.jev).toHaveBeenCalledTimes(1);expect(f.load).toHaveBeenCalledTimes(1)})
  it('detects equivalent prior policy/scheduled production evaluations',async()=>{const f=await fixture();await f.store.putEvaluation(recordEvaluation(f.conversation,f.form,f.output,[],'policy-record',{executionMode:'scheduled',conversationSource:'genesys-cloud'}));expect((await evaluateManual(f.deps,f.input)).status).toBe('duplicate');expect(f.jev).not.toHaveBeenCalled()})
  it('does not suppress production with FORM_TEST results',async()=>{const f=await fixture();await f.store.putEvaluation({...recordEvaluation(f.conversation,f.form,f.output,[],'sandbox'),purpose:'FORM_TEST'});expect((await evaluateManual(f.deps,f.input)).status).toBe('created');expect(f.jev).toHaveBeenCalledTimes(1)})
  it('rejects drafts, disabled, retired and recreated forms before provider calls',async()=>{for(const change of [{status:'DRAFT' as const},{enabled:false},{status:'RETIRED' as const},{origin:'genesys-recreated' as const}]){const f=await fixture();await f.store.putForm({...f.form,...change});await expect(evaluateManual(f.deps,f.input)).rejects.toThrow(/published|review-only/);expect(f.load).not.toHaveBeenCalled();expect(f.jev).not.toHaveBeenCalled()}})
  it('requires the exact version and refuses browser form/transcript injection or re-evaluation flags',async()=>{const f=await fixture();await expect(evaluateManual(f.deps,{...f.input,formVersion:99})).rejects.toThrow('Exact published');for(const extra of [{form:f.form},{transcript:'modified'},{reEvaluate:true}])await expect(evaluateManual(f.deps,{...f.input,...extra})).rejects.toThrow('only');expect(f.jev).not.toHaveBeenCalled()})
  it('rejects unsupported sources and invalid identities',async()=>{const f=await fixture();for(const change of [{source:'uploaded'},{conversationId:'bad-id'},{formId:'../bad'},{formVersion:0},{formVersion:'1'}])await expect(evaluateManual(f.deps,{...f.input,...change})).rejects.toThrow();expect(f.load).not.toHaveBeenCalled()})
  it('supports the built-in synthetic source without consulting Genesys',async()=>{const f=await fixture();const result=await evaluateManual(f.deps,{...f.input,source:'synthetic',conversationId:sampleLibrary[0].conversation.conversationId});expect(result.record?.conversationSource).toBe('synthetic');expect(f.load).not.toHaveBeenCalled();expect(f.jev).toHaveBeenCalledTimes(1)})
  it('coalesces concurrent manual calls using a durable reservation',async()=>{const f=await fixture();const results=await Promise.all([evaluateManual(f.deps,f.input),evaluateManual(f.deps,f.input)]);expect(results.some(result=>result.status==='created')).toBe(true);expect(f.jev).toHaveBeenCalledTimes(1);expect(await f.store.evaluations()).toHaveLength(1)})
  it('retains uncertain reservations after Jev or persistence failure without retries',async()=>{for(const stage of ['jev','persist']){const f=await fixture();if(stage==='jev')f.jev.mockRejectedValueOnce(Error('provider failure PRIVATE'));else vi.spyOn(f.store,'completeEvaluation').mockRejectedValueOnce(Error('store failure PRIVATE'));const first=await evaluateManual(f.deps,f.input);expect(first.status).toBe('uncertain');expect(JSON.stringify(first)).not.toContain('PRIVATE');expect((await evaluateManual(f.deps,f.input)).status).toBe('uncertain');expect(f.jev).toHaveBeenCalledTimes(1)}})
  it('does not reserve unavailable transcripts; safe retrieval can be retried',async()=>{const f=await fixture();f.load.mockResolvedValueOnce({...f.conversation,messages:[]});await expect(evaluateManual(f.deps,f.input)).rejects.toThrow('unavailable');expect((await evaluateManual(f.deps,f.input)).status).toBe('created');expect(f.jev).toHaveBeenCalledTimes(1)})
  it('protects the HTTP route, bounds input bytes and exposes durable results to Explorer and analytics',async()=>{const f=await fixture();const server=createApi(f.deps,{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['allowed']),schedulerEmail:'scheduler@example.com',schedulerAudience:'https://aqm.example'},async()=>new Response(JSON.stringify({id:'allowed'})));servers.push(server);await new Promise<void>(resolve=>server.listen(0,resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`,headers={Authorization:'Bearer fixture-token','Content-Type':'application/json'};const post=(payload:unknown,auth=true)=>fetch(`${base}/api/evaluations/manual`,{method:'POST',headers:auth?headers:{},body:JSON.stringify(payload)});expect((await post(f.input,false)).status).toBe(401);expect((await post({...f.input,extra:'x'.repeat(100_001)})).status).toBe(400);expect((await post(f.input)).status).toBe(200);const duplicate=await (await post(f.input)).json() as {status:string};expect(duplicate.status).toBe('duplicate');expect(f.jev).toHaveBeenCalledTimes(1);const explorer=await (await fetch(`${base}/api/evaluations`,{headers})).json() as {items:unknown[]};expect(explorer.items).toHaveLength(1);const analytics=await fetch(`${base}/api/analytics?mode=manual`,{headers});expect(analytics.status).toBe(200);expect((await analytics.json() as {metrics:{evaluations:number}}).metrics.evaluations).toBe(1)})
})
