import { describe,expect,it,vi,afterEach } from 'vitest'
import { createHmac } from 'node:crypto'
import { MemoryStore,FirestoreStore } from './store'
import type { Firestore } from 'firebase-admin/firestore'
import { auditContext } from './audit'
import { defaultGovernance } from '../domain/governance'
import { scanPurge } from './governance'
import { deliveryId,destinationInput,ruleInput,safeDestination,routeNotifications,dispatchNotifications,requestTest,notificationTick } from './notifications'
import { DeliveryError,WebhookProvider,EmailProvider,ResendAdapter,renderEmail,validateWebhookUrl,publicAddress,webhookSignature,type SecureRequest } from './notificationProviders'
import type { NotificationDelivery,NotificationDestination,NotificationRule } from '../domain/notifications'
import type { AlertInput } from '../domain/operationalAlerts'
const now='2026-10-02T12:00:00.000Z',ref='projects/genesys-aqm-2026/secrets/aqm-notification-webhook/versions/latest'
const input:AlertInput={dedupKey:'failure:policy',type:'SCHEDULED_RUN_FAILED',severity:'ERROR',title:'secret customer transcript',message:'Bearer hidden',source:'scheduled-run',policyId:'policy',metadata:{sampled:5}}
const destination:NotificationDestination={id:'dest',name:'Operations',type:'WEBHOOK',enabled:true,configuration:{urlSecretRef:ref},createdAt:'2026-10-01T00:00:00.000Z',updatedAt:now}
const rule:NotificationRule={id:'rule',name:'Critical',enabled:true,severities:['ERROR'],alertTypes:[],destinationIds:['dest'],notifyOnResolution:false,createdAt:destination.createdAt,updatedAt:now}
const publicDns=async()=>[{address:'8.8.8.8',family:4}]
async function fixture(r:Partial<NotificationRule>={},d:Partial<NotificationDestination>={}){const store=new MemoryStore();await store.atomic([{collection:'notificationDestinations',id:'dest',value:{...destination,...d},expected:undefined},{collection:'notificationRules',id:'rule',value:{...rule,...r},expected:undefined}]);const alert=await store.upsertAlert(input,now);return{store,alert}}
const list=(store:MemoryStore)=>store.query<NotificationDelivery>('notificationDeliveries',100).then(p=>p.items)
afterEach(()=>vi.restoreAllMocks())
describe('notification routing and lifecycle',()=>{
 it.each([{severities:['WARNING']},{alertTypes:['JEV_FAILURE']},{enabled:false},{policyId:'other'}])('criteria AND together: %j',async r=>{const{store}=await fixture(r as Partial<NotificationRule>);await routeNotifications(store,now);expect(await list(store)).toEqual([])})
 it('no rule means no delivery',async()=>{const store=new MemoryStore();await store.upsertAlert(input,now);await routeNotifications(store,now);expect(await list(store)).toEqual([])})
 it('disabled destination means no delivery',async()=>{const{store}=await fixture({}, {enabled:false});await routeNotifications(store,now);expect(await list(store)).toEqual([])})
 it('matches severity, type, policy and multiple destinations',async()=>{const{store}=await fixture({destinationIds:['dest','email'],alertTypes:['SCHEDULED_RUN_FAILED'],policyId:'policy'});await store.atomic([{collection:'notificationDestinations',id:'email',value:{...destination,id:'email',type:'EMAIL'},expected:undefined}]);await routeNotifications(store,now);expect((await list(store)).map(d=>d.channel).sort()).toEqual(['EMAIL','WEBHOOK'])})
 it('OPEN is atomic, updates and acknowledgement do not create more events/deliveries',async()=>{const{store,alert}=await fixture();await routeNotifications(store,now);await store.upsertAlert({...input,metadata:{sampled:10}},now);await store.transitionAlert(alert.id,'ACKNOWLEDGED',now,{userId:'owner'});await routeNotifications(store,now);expect(await list(store)).toHaveLength(1);expect((await store.query('notificationEvents',10)).items).toHaveLength(1);expect((await list(store))[0].id).toBe(deliveryId(alert.id,'rule','dest','OPEN'))})
 it.each([false,true])('resolution option %s sends exactly once',async notifyOnResolution=>{const{store,alert}=await fixture({notifyOnResolution});const send=vi.fn(async()=>{}),providers={WEBHOOK:{send},EMAIL:{send}};await notificationTick(store,providers,()=>new Date(now));await store.transitionAlert(alert.id,'RESOLVED',now);await store.transitionAlert(alert.id,'RESOLVED',now);await notificationTick(store,providers,()=>new Date(now));await notificationTick(store,providers,()=>new Date(now));expect(send).toHaveBeenCalledTimes(notifyOnResolution?2:1);expect((await list(store)).filter(d=>d.event==='RESOLVED')).toHaveLength(notifyOnResolution?1:0)})
 it('new rules do not backfill prior alerts',async()=>{const{store}=await fixture({createdAt:'2026-10-03T00:00:00.000Z'});await routeNotifications(store,now);expect(await list(store)).toHaveLength(0)})
 it('resolution does not notify a rule which never notified OPEN',async()=>{const{store,alert}=await fixture({enabled:false,notifyOnResolution:true});await routeNotifications(store,now);const prior=await store.governanceRead<NotificationRule>('notificationRules','rule');await store.atomic([{collection:'notificationRules',id:'rule',expected:prior,value:{...prior,enabled:true}}]);await store.transitionAlert(alert.id,'RESOLVED',now);await routeNotifications(store,now);expect(await list(store)).toHaveLength(0)})
 it('reopening a resolved problem has a new alert identity',async()=>{const{store,alert}=await fixture();await routeNotifications(store,now);await store.transitionAlert(alert.id,'RESOLVED',now);const next=await store.upsertAlert(input,now);await routeNotifications(store,now);expect(next.id).not.toBe(alert.id);expect(await list(store)).toHaveLength(2)})
 it('Firestore captures outbox event in the alert transaction',async()=>{const writes:unknown[]=[];const tx={get:async()=>({exists:false,data:()=>undefined}),set:(...v:unknown[])=>writes.push(v),create:(...v:unknown[])=>writes.push(v)};const db={collection:(name:string)=>({doc:(id:string)=>({name,id})}),runTransaction:async(fn:(t:typeof tx)=>unknown)=>fn(tx)};const store=new FirestoreStore(db as unknown as Firestore);await store.upsertAlert(input,now);expect(writes).toHaveLength(3);expect(JSON.stringify(writes)).toContain('notificationEvents');expect(JSON.stringify(writes)).not.toContain('secret customer transcript\",\"message\":\"Bearer hidden\",\"status')})
})
describe('durable delivery',()=>{
 it('success, delivered is never resent and duplicate dispatch is serialized',async()=>{const{store}=await fixture();await routeNotifications(store,now);const send=vi.fn(async()=>{}),providers={WEBHOOK:{send},EMAIL:{send}};await Promise.all([dispatchNotifications(store,providers,()=>new Date(now)),dispatchNotifications(store,providers,()=>new Date(now))]);await dispatchNotifications(store,providers,()=>new Date('2027-01-01T00:00:00Z'));expect(send).toHaveBeenCalledTimes(1);expect((await list(store))[0]).toMatchObject({state:'DELIVERED',attemptCount:1,nextAttemptAt:undefined,deliveredAt:now})})
 it.each([['TIMEOUT',true],['CONNECTION_FAILURE',true],['HTTP_429',true],['HTTP_500',true],['HTTP_400',false],['HTTP_401',false],['HTTP_403',false],['HTTP_404',false],['INVALID_CONFIGURATION',false]])('%s correctly retries or terminates',async(code,retry)=>{const{store}=await fixture();await routeNotifications(store,now);const send=async()=>{throw new DeliveryError(code as string,retry as boolean)};await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date(now));expect((await list(store))[0]).toMatchObject({state:retry?'RETRYING':'FAILED',lastErrorCode:code,nextAttemptAt:retry?'2026-10-02T12:05:00.000Z':undefined})})
 it('finite retries survive reload and have fixed 5m/30m/2h delays',async()=>{const{store}=await fixture();await routeNotifications(store,now);const send=vi.fn(async()=>{throw new DeliveryError('HTTP_500',true)}),providers={WEBHOOK:{send},EMAIL:{send}};let active=store;for(const [index,time]of [now,'2026-10-02T12:05:00.000Z','2026-10-02T12:35:00.000Z','2026-10-02T14:35:00.000Z'].entries()){if(index===1){const reload=new MemoryStore();for(const c of ['notificationDestinations','notificationRules','notificationDeliveries'] as const)for(const row of (await active.query<{id:string}>(c,100)).items)await reload.atomic([{collection:c,id:row.id,value:row,expected:undefined}]);active=reload}await dispatchNotifications(active,providers,()=>new Date(time));expect((await list(active))[0].attemptCount).toBe(index+1)}expect((await list(active))[0]).toMatchObject({state:'FAILED',attemptCount:4,nextAttemptAt:undefined});await dispatchNotifications(active,providers,()=>new Date('2027-01-01'));expect(send).toHaveBeenCalledTimes(4)})
 it('disabled configuration suppresses pending deliveries',async()=>{const{store}=await fixture();await routeNotifications(store,now);const prior=await store.governanceRead('notificationDestinations','dest');await store.atomic([{collection:'notificationDestinations',id:'dest',expected:prior,value:{...destination,enabled:false}}]);const send=vi.fn();await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date(now));expect(send).not.toHaveBeenCalled();expect((await list(store))[0].state).toBe('SUPPRESSED')})
 it('untrusted provider failures persist only static safe codes, never log',async()=>{const{store}=await fixture();await routeNotifications(store,now);const log=vi.spyOn(console,'error'),send=async()=>{throw Error('https://secret.example/token Bearer customer transcript')};await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date(now));expect(JSON.stringify(await list(store))).not.toMatch(/Bearer|customer transcript|secret.example/);expect(log).not.toHaveBeenCalled()})
 it('TEST creates audited delivery without OperationalAlert',async()=>{const{store}=await fixture();const before=(await store.alerts()).length;await auditContext.run({actor:{userId:'owner'},now,correlationId:'test'},()=>requestTest(store,'dest',now));expect((await store.alerts()).length).toBe(before);expect((await list(store))[0]).toMatchObject({event:'TEST',payload:{test:true}});const audits=await store.query('auditEvents',100);expect(JSON.stringify(audits)).toContain('notification_test.requested');expect(JSON.stringify(audits)).not.toContain('secret')})
 it('retention purges only old terminal deliveries',async()=>{const{store}=await fixture();const test=await requestTest(store,'dest',now);for(const state of ['PENDING','RETRYING','DELIVERED','FAILED','SUPPRESSED'] as const)await store.atomic([{collection:'notificationDeliveries',id:state,value:{...test,id:state,state,updatedAt:'2025-01-01T00:00:00Z'},expected:undefined}]);const scan=await scanPurge(store,{...defaultGovernance,notificationDeliveryRetentionDays:30},now);expect(scan.writes.filter(w=>w.collection==='notificationDeliveries').map(w=>w.id).sort()).toEqual(['DELIVERED','FAILED','SUPPRESSED']);expect((await scanPurge(store,defaultGovernance,now)).counts.notificationDeliveries).toBe(0)})
})
describe('webhook security and protocol',()=>{
 it.each(['http://example.com','https://localhost','https://127.0.0.1','https://[::1]','https://10.0.0.1','https://172.16.0.1','https://192.168.1.1','https://169.254.169.254','https://metadata.google.internal','file:///tmp/a','https://user:secret@example.com','https://example.com:8443','https://[::ffff:127.0.0.1]'])('rejects %s',async url=>{await expect(validateWebhookUrl(url,publicDns)).rejects.toMatchObject({code:'UNSAFE_DESTINATION'})})
 it('rejects DNS private answers and mixed public/private answers',async()=>{for(const addresses of [[{address:'10.0.0.1',family:4}],[{address:'8.8.8.8',family:4},{address:'169.254.169.254',family:4}]])await expect(validateWebhookUrl('https://public.example',async()=>addresses)).rejects.toMatchObject({code:'UNSAFE_DESTINATION'})})
 it('pins validated public IP and sends stable payload, idempotency key and timestamp signature',async()=>{const{store}=await fixture();await routeNotifications(store,now);const d=(await list(store))[0],transport=vi.fn(async()=>200),secrets=vi.fn(async r=>r===ref?'https://public.example/secret-token':'hmac-key');const p=new WebhookProvider(secrets,transport,publicDns,()=>new Date(now));await p.send({...destination,configuration:{urlSecretRef:ref,signingSecretRef:ref.replace('webhook','signing')}},d);const sent=transport.mock.calls[0] as unknown as [SecureRequest];expect(sent[0].address).toBe('8.8.8.8');expect(sent[0].headers['Idempotency-Key']).toBe(d.id);expect(sent[0].headers['X-AQM-Signature']).toBe(`sha256=${createHmac('sha256','hmac-key').update(`${sent[0].headers['X-AQM-Timestamp']}.${sent[0].body}`).digest('hex')}`);expect(sent[0].body).not.toMatch(/transcript|Bearer|secret-token|hmac-key/);expect(webhookSignature(sent[0].body,'key','1')).not.toBe(webhookSignature(sent[0].body,'key','2'))})
 it('redirects are rejected without a second request',async()=>{const{store}=await fixture();await routeNotifications(store,now);const transport=vi.fn(async()=>302);await expect(new WebhookProvider(async()=> 'https://public.example',transport,publicDns).send(destination,(await list(store))[0])).rejects.toMatchObject({code:'REDIRECT_REJECTED'});expect(transport).toHaveBeenCalledTimes(1)})
 it('rejects reserved addresses and IPv6 transition mechanisms',()=>{for(const address of ['0.0.0.0','100.64.0.1','192.0.0.8','198.18.0.1','224.0.0.1','fc00::1','fe80::1','2001:db8::1','2002:a00:1::','2001:0::1'])expect(publicAddress(address),address).toBe(false);expect(publicAddress('2606:4700:4700::1111')).toBe(true)})
 it('configuration projects safe metadata and audit excludes secret references',async()=>{const d=destinationInput({...destination,configuration:{urlSecretRef:ref,signingSecretRef:ref}},now);expect(JSON.stringify(safeDestination(d))).not.toContain(ref);expect(safeDestination(d)).toMatchObject({configured:true,signed:true});const store=new MemoryStore();await auditContext.run({actor:{userId:'owner'},now,correlationId:'fixture'},async()=>{await store.atomic([{collection:'notificationDestinations',id:d.id,value:d,expected:undefined}]);await store.atomic([{collection:'notificationDestinations',id:d.id,value:{...d,enabled:false,configuration:{urlSecretRef:ref.replace('latest','1')}},expected:d}])});const audits=JSON.stringify(await store.query('auditEvents',100));expect(audits).not.toContain(ref);expect(audits).toContain('secret_reference_changed');expect(audits).toContain('notification_destination.disable')})
 it('rejects raw URLs or API keys in configuration',()=>{expect(()=>destinationInput({...destination,configuration:{url:'https://secret.example',urlSecretRef:ref}},now)).toThrow();expect(()=>ruleInput({...rule,severities:[]},now)).toThrow()})
})
describe('provider-free email adapter',()=>{
 const emailDest:NotificationDestination={...destination,type:'EMAIL',configuration:{provider:'RESEND',from:'aqm@example.com',to:['ops@example.com'],apiKeySecretRef:ref}}
 it('renders concise content and delivers with destination addressing and idempotency',async()=>{const{store}=await fixture();const d=await requestTest(store,'dest',now),send=vi.fn(async()=>{});await new EmailProvider(async()=> 'api-secret',{send}).send(emailDest,d);expect(send).toHaveBeenCalledWith(expect.objectContaining({from:'aqm@example.com',to:['ops@example.com'],idempotencyKey:d.id,apiKey:'api-secret',subject:'[Genesys AQM] TEST — Test notification'}));expect(renderEmail(d).text).toContain('no OperationalAlert');expect(renderEmail(d).text).not.toContain('api-secret')})
 it.each([[200,false,false],[429,true,true],[500,true,true],[400,true,false],[401,true,false]])('Resend status %s',async(status,failed,transient)=>{const adapter=new ResendAdapter(async()=>status as number,publicDns),work=adapter.send({from:'a@example.com',to:['b@example.com'],subject:'AQM',text:'Safe summary',idempotencyKey:'key',apiKey:'secret'});if(failed)await expect(work).rejects.toMatchObject({transient});else await expect(work).resolves.toBeUndefined()})
 it('sanitized alert rendering excludes arbitrary text',async()=>{const{store}=await fixture();await routeNotifications(store,now);const v=renderEmail((await list(store))[0]);expect(v.subject).toBe('[Genesys AQM] ERROR — Scheduled run failed');expect(v.text).not.toMatch(/customer|Bearer|stack/i)})
 it('email uses durable dispatcher idempotency',async()=>{const{store}=await fixture({},emailDest);const send=vi.fn(async()=>{}),provider=new EmailProvider(async()=> 'key',{send});await notificationTick(store,{WEBHOOK:provider,EMAIL:provider},()=>new Date(now));await notificationTick(store,{WEBHOOK:provider,EMAIL:provider},()=>new Date(now));expect(send).toHaveBeenCalledTimes(1)})
})
it('a crashed attempt lease expires and recovery respects the finite attempt budget',async()=>{const{store}=await fixture();await routeNotifications(store,now);const original=(await list(store))[0],claimed={...original,state:'RETRYING' as const,leaseOwner:'crashed',attemptCount:4,nextAttemptAt:'2026-10-02T12:01:00.000Z'};await store.atomic([{collection:'notificationDeliveries',id:claimed.id,expected:original,value:claimed}]);const send=vi.fn();await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date('2026-10-02T12:00:30.000Z'));expect(send).not.toHaveBeenCalled();await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date('2026-10-02T12:01:00.000Z'));expect(send).not.toHaveBeenCalled();expect((await list(store))[0]).toMatchObject({state:'FAILED',lastErrorCode:'ATTEMPTS_EXHAUSTED',attemptCount:4})})
it('resolution waits for OPEN success without spending external attempt budget',async()=>{const{store,alert}=await fixture({notifyOnResolution:true});await routeNotifications(store,now);await store.transitionAlert(alert.id,'RESOLVED',now);await routeNotifications(store,now);const open=(await list(store)).find(d=>d.event==='OPEN')!;await store.atomic([{collection:'notificationDeliveries',id:open.id,expected:open,value:{...open,nextAttemptAt:'2026-10-03T00:00:00.000Z'}}]);const send=vi.fn();await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date(now));expect(send).not.toHaveBeenCalled();expect((await list(store)).find(d=>d.event==='RESOLVED')).toMatchObject({state:'PENDING',attemptCount:0,nextAttemptAt:'2026-10-02T12:05:00.000Z'})})
it('last delivery health is durable and not derived from a paginated history window',async()=>{const{store}=await fixture();const d=await requestTest(store,'dest',now),send=async()=>{};await dispatchNotifications(store,{WEBHOOK:{send},EMAIL:{send}},()=>new Date(now));expect(await store.governanceRead('notificationDestinationHealth','dest')).toMatchObject({deliveryId:d.id,state:'DELIVERED'});expect(await store.notificationHealth(now)).toEqual({pending:0,failed24h:0,lastSuccessfulAt:now})})
it('DNS timeout and errors are bounded and sanitized',async()=>{vi.useFakeTimers();try{const p=validateWebhookUrl('https://public.example',()=>new Promise(()=>{})),assertion=expect(p).rejects.toMatchObject({code:'DNS_TIMEOUT',transient:true});await vi.advanceTimersByTimeAsync(3000);await assertion;await expect(validateWebhookUrl('https://public.example',async()=>{throw Error('raw host secret')})).rejects.toMatchObject({code:'DNS_FAILURE',transient:true})}finally{vi.useRealTimers()}})
