import { afterEach,it,expect,vi } from 'vitest'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import {createApi}from './api'
import{MemoryStore}from'./store'
import type{RunnerDeps}from'./runner'
import type{NotificationDestination}from'../domain/notifications'
const servers:Server[]=[],now='2026-10-02T12:00:00.000Z',ref='projects/genesys-aqm-2026/secrets/aqm-notification-url/versions/latest'
afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(r=>s.close(()=>r()))))})
async function fixture(){const store=new MemoryStore(),paid=vi.fn(async()=>{throw Error('Paid provider prohibited')}),deps:RunnerDeps={store,now:()=>new Date(now),genesys:{list:paid,load:paid,withQueueNames:async c=>c},jev:{evaluate:paid}};const server=createApi(deps,{origin:'https://example.com',region:'eu-west-1',allowedUserIds:new Set(['owner','author','reviewer','viewer']),bootstrapAdminId:'owner',schedulerEmail:'scheduler',schedulerAudience:'https://example.com'},async(_u,init)=>new Response(JSON.stringify({id:(init?.headers as Record<string,string>).Authorization.slice(7)})));servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address()as AddressInfo).port}`;const call=(actor:string,path:string,method='GET',value?:unknown)=>fetch(base+path,{method,headers:{Authorization:'Bearer '+actor,'Content-Type':'application/json'},body:value===undefined?undefined:JSON.stringify(value)});for(const role of ['AUTHOR','REVIEWER','VIEWER'])await call('owner','/api/roles/'+role.toLowerCase(),'PUT',{role});return{store,call,paid}}
const dest={id:'dest',name:'Operations',type:'WEBHOOK',enabled:true,configuration:{urlSecretRef:ref,signingSecretRef:ref}}
it('ADMIN configuration, safe output, edited refs preserve server values, test is queued and audited',async()=>{const{store,call,paid}=await fixture();let r=await call('owner','/api/notifications/destinations/dest','PUT',dest);expect(r.status).toBe(200);const v=await r.json();expect(v.item).toMatchObject({configured:true,signed:true});expect(JSON.stringify(v)).not.toContain(ref);r=await call('owner','/api/notifications/destinations');expect(JSON.stringify(await r.json())).not.toContain(ref);expect((await call('owner','/api/notifications/destinations/dest','PUT',{...dest,name:'Edited',configuration:{}})).status).toBe(200);expect((await store.governanceRead<NotificationDestination>('notificationDestinations','dest'))?.configuration.urlSecretRef).toBe(ref);r=await call('owner','/api/notifications/rules/rule','PUT',{id:'rule',name:'Critical',enabled:true,severities:['ERROR'],alertTypes:[],destinationIds:['dest']});expect(r.status).toBe(200);r=await call('owner','/api/notifications/destinations/dest/test','POST');expect(r.status).toBe(202);expect((await r.json()).item).toMatchObject({event:'TEST',state:'PENDING'});expect(await store.alerts()).toHaveLength(0);expect(JSON.stringify(await store.query('auditEvents',100))).not.toContain(ref);expect(paid).not.toHaveBeenCalled();expect((await(await call('owner','/api/notifications/deliveries')).json()).items[0]).not.toHaveProperty('payload')})
it('AUTHOR read only; REVIEWER/VIEWER configuration forbidden; all roles can inspect safe alert status',async()=>{const{call}=await fixture();await call('owner','/api/notifications/destinations/dest','PUT',dest);expect((await call('author','/api/notifications/destinations')).status).toBe(200);for(const user of ['author','reviewer','viewer'])for(const [path,method] of [['/api/notifications/destinations/dest','PUT'],['/api/notifications/rules/rule','PUT'],['/api/notifications/destinations/dest/test','POST']])expect((await call(user,path,method,dest)).status).toBe(403);for(const user of ['reviewer','viewer'])expect((await call(user,'/api/notifications/destinations')).status).toBe(403);for(const user of ['author','reviewer','viewer'])expect((await call(user,'/api/alerts/fixture/notifications')).status).toBe(200)})
it('rejects arbitrary metadata/raw secrets, missing destinations and invalid pagination',async()=>{const{call}=await fixture();expect((await call('owner','/api/notifications/destinations/dest','PUT',{...dest,configuration:{urlSecretRef:ref,url:'https://token'}})).status).toBe(400);expect((await call('owner','/api/notifications/rules/rule','PUT',{id:'rule',name:'Invalid',enabled:true,severities:['ERROR'],alertTypes:[],destinationIds:['missing']})).status).toBe(400);expect((await call('owner','/api/notifications/deliveries?limit=1000000')).status).toBe(400);expect((await call('owner','/api/alerts/fixture/notifications?limit=1000000')).status).toBe(400)})
it('notification tick retains scheduler OIDC protection',async()=>{const{call,paid}=await fixture();for(const method of ['GET','POST'])expect((await call('owner','/internal/notifications/tick',method)).status).toBe(403);expect(paid).not.toHaveBeenCalled()})
