import { describe,it,expect,vi } from 'vitest'
import { operationalOverview,providerEvidence } from './overview'
import { MemoryStore } from './store'
import { overviewFixture,overviewNow,overviewAuthority,fixtureRun } from '../fixtures/overviewFixture'
import { reviewFixture } from '../fixtures/reviewFixture'
import { createApi } from './api'
import { rolePermissions, type Role } from '../domain/governance'
import type { RunnerDeps } from './runner'
import type { AddressInfo } from 'node:net'
const snapshot=(s:MemoryStore,days:7|30=7)=>operationalOverview(s,overviewNow,days,overviewAuthority,true)
describe('bounded operational overview',()=>{
 it('timestamps one consistent 7-day analytics window with current health and workload',async()=>{const store=await overviewFixture(),s=await snapshot(store);expect(s.generatedAt).toBe(overviewNow);expect(s.range).toEqual({days:7,from:'2026-09-25T12:00:00.000Z',to:overviewNow});expect(s.analytics).toMatchObject({complete:true,data:{quality:{evaluations:1,conversations:1,averageScore:.8,passRate:1,criticalFailures:0},coverage:{eligible:20,sampled:10,evaluable:6,evaluated:4,failed:3,samplingCoverage:.5,evaluationCoverage:.2},qualityTrend:[{key:'2026-10-01',count:1,averageScore:.8}],runCounts:{completed:1,failed:1,partial:0}}});expect(s.reviews).toEqual({complete:true,data:{open:4,dueSoon:1,overdue:1,escalated:1,unassigned:1}});expect(s.health).toMatchObject({complete:true,data:{api:'healthy',firestore:'available',scheduler:{status:'healthy'},genesysAutomation:{status:'unverified'},jev:{status:'error'}}});expect(s.alerts).toMatchObject({complete:true,data:{openAlerts:3,errors:2,warnings:1,items:[{severity:'ERROR'},{severity:'ERROR'},{severity:'WARNING'}]}})})
 it('uses 30 days consistently for quality, coverage, trend and outcomes',async()=>{const store=await overviewFixture(),s=await snapshot(store,30);expect(s.range.from).toBe('2026-09-02T12:00:00.000Z');expect(s.analytics).toMatchObject({complete:true,data:{quality:{evaluations:2,averageScore:expect.closeTo(.6),passRate:.5,criticalFailures:1},coverage:{eligible:30,sampled:15,evaluated:6},runCounts:{completed:2,failed:1}}});if(s.analytics.complete)expect(s.analytics.data.qualityTrend.map(d=>d.key)).toEqual(['2026-09-15','2026-10-01']);expect(s.reviews).toEqual((await snapshot(store,7)).reviews)})
 it('orders upcoming schedules and durable recent runs and finds the last successful unattended run',async()=>{const s=await snapshot(await overviewFixture());expect(s.schedules).toMatchObject({complete:true,data:{nextRunAt:'2026-10-03T01:00:00.000Z',items:[{id:'next'},{id:'later'}]}});expect(s.recentRuns).toMatchObject({complete:true,data:{lastRun:{id:'manual_recent'},items:[{id:'manual_recent'},{id:'scheduled_recent'},{id:'scheduled_older'}]}});expect(s.lastAutomatedRun).toMatchObject({complete:true,data:{id:'scheduled_recent',trigger:'scheduled',status:'completed'}})})
 it('finds unattended proof beyond the recent 20 runs and bounds response lists',async()=>{const store=await overviewFixture();for(let i=0;i<25;i++)await store.putRun(fixtureRun(`new_${i}`,`2026-10-02T10:${String(i).padStart(2,'0')}:00.000Z`,'completed','manual'));const s=await snapshot(store);expect(s.lastAutomatedRun).toMatchObject({complete:true,data:{id:'scheduled_recent'}});if(s.recentRuns.complete)expect(s.recentRuns.data.items).toHaveLength(5)})
 it('reports notification counts independently, including genuine zeros',async()=>{const store=await overviewFixture(false);vi.spyOn(store,'notificationHealth').mockResolvedValue({pending:2,failed24h:1,lastSuccessfulAt:'2026-10-01T14:00:00Z'});expect((await snapshot(store)).notifications).toEqual({complete:true,data:{pending:2,failed24h:1,lastSuccessfulAt:'2026-10-01T14:00:00Z'}});const empty=await snapshot(new MemoryStore());expect(empty.notifications).toEqual({complete:true,data:{pending:0,failed24h:0,lastSuccessfulAt:null}});expect(empty.analytics).toMatchObject({complete:true,data:{quality:{evaluations:0,averageScore:null,passRate:null},coverage:{eligible:0,samplingCoverage:null}}});expect(empty.reviews).toMatchObject({complete:true,data:{open:0}});expect(empty.alerts).toMatchObject({complete:true,data:{openAlerts:0}});expect(empty.lastAutomatedRun).toEqual({complete:true,data:null})})
 it('refuses partial analytics and workload at their 2000-evaluation ceiling',async()=>{const store=new MemoryStore(),record=reviewFixture();for(let i=0;i<2001;i++)await store.putEvaluation({...record,id:`r_${String(i).padStart(4,'0')}`});const s=await snapshot(store);expect(s.analytics).toEqual({complete:false,status:'incomplete',reason:'Indexed aggregation required.'});expect(s.reviews).toEqual({complete:false,status:'incomplete',reason:'Indexed aggregation required.'});expect(s.health.complete).toBe(true);expect(s.notifications.complete).toBe(true)})
 it('refuses partial active reviews, roles, runs, alerts and schedules',async()=>{const store=await overviewFixture(),query=store.query.bind(store);vi.spyOn(store,'activeReviewPage').mockImplementation(async(limit)=>({items:Array.from({length:limit},(_,i)=>({id:String(i)} as never)),nextCursor:'more',scanned:limit}));expect((await snapshot(store)).reviews).toMatchObject({complete:false,status:'incomplete'});vi.spyOn(store,'query').mockImplementation(async(c,limit,cursor)=>c==='policyRuns'||c==='schedules'||c==='roleAssignments'?{items:Array.from({length:limit},()=>fixtureRun('r')) as never,nextCursor:'more',scanned:limit}:query(c,limit,cursor));vi.spyOn(store,'activeAlertPage').mockImplementation(async(limit)=>({items:Array.from({length:limit},()=>({severity:'ERROR'} as never)),nextCursor:'more',scanned:limit}));const s=await snapshot(store);for(const section of [s.analytics,s.lastAutomatedRun,s.alerts,s.schedules])expect(section).toMatchObject({complete:false,status:'incomplete'})})
 it('contains section failures, hides raw diagnostics and never replaces unavailable data with zero',async()=>{const store=await overviewFixture();vi.spyOn(store,'query').mockRejectedValue(Error('private provider secret'));vi.spyOn(store,'notificationHealth').mockRejectedValue(Error('private notification token'));const s=await snapshot(store);expect(s.health.complete).toBe(true);expect(s.recentRuns.complete).toBe(true);expect(s.analytics).toEqual({complete:false,status:'unavailable',reason:'Section temporarily unavailable.'});expect(s.notifications).toEqual({complete:false,status:'unavailable',reason:'Section temporarily unavailable.'});expect(JSON.stringify(s)).not.toContain('private')})
 it('does not serialize transcripts, review answers/notes, governance, raw responses or alert diagnostics, and never writes',async()=>{const store=await overviewFixture();const record=await store.evaluation('recent');await store.putEvaluation({...record!,rawResponse:{secret:'private raw provider payload'},transcript:'private transcript'} as never);const review=await store.review('escalated');await store.atomic([{collection:'humanReviews',id:'escalated',expected:review,value:{...review,notes:'private review notes',answers:[{value:'private human answer'}]}}]);for(const method of ['putRun','upsertAlert','transitionAlert','recordSchedulerHealth','atomic','syncReviewSla'] as const)vi.spyOn(store,method).mockRejectedValue(Error('Overview must be read-only'));const query=vi.spyOn(store,'query'),health=vi.spyOn(store,'healthSnapshot');const s=await snapshot(store),serialized=JSON.stringify(s);expect(serialized).not.toMatch(/private|notes|questions|rawResponse|accessToken|clientSecret|reviewSla|notificationRules|events|answers|"transcript"/i);expect(health).toHaveBeenCalledTimes(1);expect(query.mock.calls.filter(([c,,cursor])=>c==='evaluationRecords'&&!cursor)).toHaveLength(1)})
 it('explains verified, error, unverified and stale dependency evidence without live checks',async()=>{expect(providerEvidence()).toMatchObject({genesysAutomation:{status:'unverified'},jev:{status:'unverified'}});expect(providerEvidence({...fixtureRun('r'),evaluationsFailed:0})).toMatchObject({genesysAutomation:{status:'verified'},jev:{status:'verified'}});expect(providerEvidence({...fixtureRun('r',overviewNow,'failed'),failures:[{conversationId:'*',reason:'genesys_auth: failed',code:'GENESYS_AUTH_FAILURE'}]})).toMatchObject({genesysAutomation:{status:'error'}});const store=new MemoryStore();await store.recordSchedulerHealth('2026-10-01T00:00:00Z',true);expect((await snapshot(store)).health).toMatchObject({complete:true,data:{scheduler:{status:'stale'}}})})
})
for(const role of ['ADMIN','AUTHOR','REVIEWER','VIEWER'] as Role[])it(`serves a safe overview to ${role} and invokes no Genesys/Jev execution providers`,async()=>{
 const store=new MemoryStore(),genesys={list:vi.fn(),load:vi.fn(),withQueueNames:vi.fn()},jev={evaluate:vi.fn()},identity=role==='ADMIN'?'admin':role.toLowerCase();if(role!=='ADMIN')await store.atomic([{collection:'roleAssignments',id:identity,expected:undefined,value:{id:identity,userId:identity,role}}]);const authenticate=vi.fn(async()=>new Response(JSON.stringify({id:identity}))),deps={store,genesys,jev,now:()=>new Date(overviewNow)} as RunnerDeps,server=createApi(deps,{origin:'https://example.test',region:'eu-west-1',allowedUserIds:overviewAuthority.allowedUserIds,bootstrapAdminId:'admin',schedulerEmail:'scheduler',schedulerAudience:'audience'},authenticate)
 await new Promise<void>(resolve=>server.listen(0,resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`
 try{expect((await fetch(`${base}/api/overview`)).status).toBe(401);for(const range of ['7','30']){const response=await fetch(`${base}/api/overview?range=${range}`,{headers:{Authorization:'Bearer fixture'}});expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toBe('no-store');expect((await response.json()).range.days).toBe(Number(range))}expect((await fetch(`${base}/api/overview?range=365`,{headers:{Authorization:'Bearer fixture'}})).status).toBe(400);expect(rolePermissions[role]).toContain('evaluations.read');for(const provider of [...Object.values(genesys),jev.evaluate])expect(provider).not.toHaveBeenCalled();expect(authenticate.mock.calls).toHaveLength(3)}finally{await new Promise<void>(resolve=>server.close(()=>resolve()))}
})
