import { afterEach, describe, expect, it } from 'vitest'
import type { Server } from 'node:http'
import type { AddressInfo } from 'node:net'
import type { Role, RoleAssignment, AuditEvent } from '../domain/governance'
import { buildReview, isReviewOverdue, matchesReviewQueue } from '../domain/reviews'
import { fixtureAnswers, reviewFixture, reviewInput } from '../fixtures/reviewFixture'
import { MemoryStore, StoreConflict } from './store'
import { assignReview, bulkAssignReviews, reviewerDirectory, reviewWorkload, scoreAssignedReview } from './reviewOperations'
import { auditContext } from './audit'
import { createApi } from './api'
import { requestSample } from './reviews'
import type { RunnerDeps } from './runner'
const now='2026-10-02T10:00:00.000Z',due='2026-10-01T09:00:00.000Z',admin={userId:'admin',displayName:'Owner'},a={userId:'a',displayName:'Alice'},b={userId:'b',displayName:'Bob'}
const authority={bootstrapId:'admin',allowedUserIds:new Set(['admin','a','b','author','viewer'])}
async function role(store:MemoryStore,userId:string,r:Role){const prior=await store.governanceRead<RoleAssignment>('roleAssignments',userId);await store.atomic([{collection:'roleAssignments',id:userId,expected:prior,value:{id:userId,userId,displayName:userId==='a'?'Alice':'Bob',role:r,createdAt:now,updatedAt:now,assignedBy:admin}}])}
async function fixture(store=new MemoryStore()) {for(const [id,r] of [['a','REVIEWER'],['b','REVIEWER'],['author','AUTHOR'],['viewer','VIEWER']] as [string,Role][])await role(store,id,r);const record=reviewFixture();await store.putEvaluation(record);return {store,record}}
const input=(expectedRevision=0,assigneeId='a',action:'assign'|'reassign'|'unassign'='assign')=>({action,expectedRevision,assigneeId,dueAt:due})
const assigned=(store:MemoryStore,id:string,v=input())=>assignReview(store,id,v,admin,now,authority)
const scored=(store:MemoryStore,id:string,action:'start'|'save'|'complete'|'claim',revision:number,actor=a)=>scoreAssignedReview(store,id,{...reviewInput(reviewFixture(id),action==='claim'?'start':action,revision),action},actor,now,authority)
describe('assignment authority and shared revision',()=>{
 it('assigns an unreviewed evaluation and creates exactly one request revision with safe assignment metadata',async()=>{const {store,record}=await fixture(),before=await store.evaluation(record.id);const r=await assigned(store,record.id);expect(r.status).toBe('REVIEW_REQUESTED');expect(r.revision).toBe(1);expect(r.reviewer).toBeUndefined();expect(r.assignment).toEqual({assignee:a,assignedAt:now,assignedBy:admin,dueAt:due});expect(r.events.map(e=>e.kind)).toEqual(['review_requested','review_assigned']);expect(await store.evaluation(record.id)).toEqual(before)})
 it('assigns requested, reassigns requested and unassigns while incrementing the shared revision',async()=>{const {store,record}=await fixture();await store.writeReviews([{review:buildReview(record,undefined,reviewInput(record,'request'),a,now),expectedRevision:0}]);await assigned(store,record.id,input(1));const r=await assigned(store,record.id,input(2,'b','reassign'));expect(r.assignment?.assignee).toEqual(b);expect(r.reviewer).toBeUndefined();const u=await assigned(store,record.id,input(3,'','unassign'));expect(u.revision).toBe(4);expect(u.assignment).toBeUndefined();expect(u.events.at(-1)?.assignee).toEqual(b)})
 it('requires explicit confirmation for in-progress takeover and preserves partial answers and notes',async()=>{const {store,record}=await fixture();await assigned(store,record.id);await scored(store,record.id,'start',1);const progress=await scoreAssignedReview(store,record.id,{...reviewInput(record,'save',2),answers:fixtureAnswers.slice(0,1),notes:'partial'},a,now,authority);await expect(assigned(store,record.id,input(3,'admin','reassign'))).rejects.toThrow('Partial answers');const takeover=await assignReview(store,record.id,{...input(3,'admin','reassign'),confirmInReview:true},admin,now,authority);expect(takeover.questions).toEqual(progress.questions);expect(takeover.notes).toBe('partial');expect(takeover.reviewer).toEqual(a);const saved=await scored(store,record.id,'save',4,admin);expect(saved.reviewer).toEqual(admin);expect(saved.assignment?.assignee).toEqual(admin)})
 it('blocks another reviewer and admin implicit takeover; allows the assigned reviewer',async()=>{const {store,record}=await fixture();await assigned(store,record.id);for(const actor of [b,admin])await expect(scored(store,record.id,'start',1,actor)).rejects.toThrow('explicit');expect((await scored(store,record.id,'start',1)).reviewer).toEqual(a)})
 it('freezes completed assignments and excludes completed from overdue and workload',async()=>{const {store,record}=await fixture();await assigned(store,record.id);const r=await scored(store,record.id,'complete',1);await expect(assigned(store,record.id,input(2,'b','reassign'))).rejects.toThrow('immutable');expect(isReviewOverdue(r,now)).toBe(false);expect((await reviewWorkload(store,now,authority)).items.find(r=>r.userId==='a')?.assignedOpen).toBe(0)})
 it('rejects stale assignment and scoring after an assignment change',async()=>{const {store,record}=await fixture();await assigned(store,record.id);await expect(assigned(store,record.id)).rejects.toThrow('Refresh');await assigned(store,record.id,input(1,'b','reassign'));await expect(scored(store,record.id,'save',1)).rejects.toThrow('Refresh')})
 it('double claim races produce one winner and one conflict',async()=>{const {store,record}=await fixture();await store.writeReviews([{review:buildReview(record,undefined,reviewInput(record,'request'),admin,now),expectedRevision:0}]);const results=await Promise.allSettled([scored(store,record.id,'claim',1,a),scored(store,record.id,'claim',1,b)]);expect(results.filter(v=>v.status==='fulfilled')).toHaveLength(1);expect(results.filter(v=>v.status==='rejected')).toHaveLength(1);const r=await store.review(record.id);expect(r?.revision).toBe(2);expect(r?.status).toBe('IN_REVIEW');expect(r?.events.map(e=>e.kind)).toEqual(['review_requested','review_claimed','review_started']);expect(r?.assignment?.assignee).toEqual(r?.reviewer)})
 it('preserves assignment when role is removed and rejects scoring; guards role changes at commit',async()=>{const {store,record}=await fixture();await assigned(store,record.id);await role(store,'a','VIEWER');await expect(scored(store,record.id,'start',1)).rejects.toThrow('reviewer access');expect((await store.review(record.id))?.assignment?.assignee).toEqual(a);expect((await reviewWorkload(store,now,authority)).items.find(r=>r.userId==='a')).toMatchObject({reviewerAccess:false,assignedOpen:1});class Race extends MemoryStore{race=false;async atomic(w:Parameters<MemoryStore['atomic']>[0],e?:AuditEvent[]){if(this.race){this.race=false;await role(this,'a','VIEWER')}return super.atomic(w,e)}}const racing=new Race();const f=await fixture(racing);racing.race=true;await expect(assigned(racing,f.record.id)).rejects.toBeInstanceOf(StoreConflict);expect(await racing.review(f.record.id)).toBeUndefined()})
 it('validates due timestamps; no due date is valid; overdue is derived',async()=>{const {store,record}=await fixture();await expect(assigned(store,record.id,{...input(),dueAt:'2026-10-05T10:00'})).rejects.toThrow('ISO');const r=await assigned(store,record.id,{...input(),dueAt:''});expect(r.assignment?.dueAt).toBeUndefined();expect(isReviewOverdue(r,now)).toBe(false);const overdue=await assigned(store,record.id,input(1,'a','reassign'));expect(isReviewOverdue(overdue,now)).toBe(true);expect('overdue' in overdue).toBe(false)})
 it('enforces existing event bounds without discarding history',async()=>{const {store,record}=await fixture();const r=buildReview(record,undefined,reviewInput(record,'request'),admin,now);r.events=Array.from({length:200},()=>r.events[0]);await store.writeReviews([{review:r,expectedRevision:0}]);await expect(assigned(store,record.id,input(1))).rejects.toThrow('audit limit')})
})
describe('bulk and calibration reuse',()=>{
 it('bulk requests and assigns all selected records atomically with identical due dates and safe audit',async()=>{const {store,record}=await fixture();await store.putEvaluation(reviewFixture('second'));const result=await auditContext.run({actor:admin,now,correlationId:'bulk-fixture'},()=>bulkAssignReviews(store,{items:[{evaluationId:record.id,expectedRevision:0},{evaluationId:'second',expectedRevision:0}],assigneeId:'a',dueAt:due},admin,now,authority));expect(result.count).toBe(2);expect(result.items.every(r=>r.revision===1&&r.status==='REVIEW_REQUESTED'&&r.assignment?.dueAt===due)).toBe(true);const audit=(await store.query<AuditEvent>('auditEvents',100)).items;expect(audit.find(e=>e.action==='review.bulk_assigned')?.metadata).toEqual({count:2,assigneeId:'a',dueAt:due});expect(audit.filter(e=>e.action==='review.assigned')).toHaveLength(2);expect(JSON.stringify(audit)).not.toMatch(/notes|answers|formSnapshot/)})
 it.each(['missing','in-progress','completed','duplicate','over-limit'])('rejects %s selection before any write',async kind=>{const {store,record}=await fixture();const second=reviewFixture('second');await store.putEvaluation(second);let items=[{evaluationId:record.id,expectedRevision:0},{evaluationId:second.id,expectedRevision:0}];if(kind==='missing')items[1].evaluationId='missing';if(kind==='in-progress'||kind==='completed'){await store.writeReviews([{review:buildReview(second,undefined,reviewInput(second,kind==='completed'?'complete':'save'),a,now),expectedRevision:0}]);items[1].expectedRevision=1}if(kind==='duplicate')items[1]=items[0];if(kind==='over-limit')items=Array.from({length:21},(_,i)=>({evaluationId:`item_${i}`,expectedRevision:0}));await expect(bulkAssignReviews(store,{items,assigneeId:'a'},admin,now,authority)).rejects.toThrow();expect(await store.review(record.id)).toBeUndefined()})
 it('concurrent change in one selection rolls back the other writes and bulk audit',async()=>{class Race extends MemoryStore {race=false;async atomic(w:Parameters<MemoryStore['atomic']>[0],e?:AuditEvent[]){if(this.race){this.race=false;const record=reviewFixture('second');await this.writeReviews([{review:buildReview(record,undefined,reviewInput(record,'request'),b,now),expectedRevision:0}])}return super.atomic(w,e)}}const store=new Race();const {record}=await fixture(store);await store.putEvaluation(reviewFixture('second'));store.race=true;await expect(bulkAssignReviews(store,{items:[{evaluationId:record.id,expectedRevision:0},{evaluationId:'second',expectedRevision:0}],assigneeId:'a'},admin,now,authority)).rejects.toBeInstanceOf(StoreConflict);expect(await store.review(record.id)).toBeUndefined();expect((await store.query('auditEvents',100)).items).toHaveLength(0)})
 it('sample integration uses the same assignment contract without changing quality metrics',async()=>{const {store,record}=await fixture();const before=await store.evaluation(record.id);const r=await requestSample(store,{count:1,strategy:'recent',assigneeId:'a',dueAt:due},admin,now,authority);expect(r.items[0].assignment?.assignee).toEqual(a);expect(r.items[0].events.at(-1)?.kind).toBe('review_assigned');expect(await store.evaluation(record.id)).toEqual(before);await expect(requestSample(store,{count:1,strategy:'recent',assigneeId:'b'},a,now,authority)).rejects.toThrow('reviewer access')})
})
describe('complete workload and safe directory',()=>{
 it('counts unassigned, requested, in-progress and overdue across reviewers, excluding completed',async()=>{const {store,record}=await fixture();await assigned(store,record.id);for(const id of ['unassigned','progress','completed'])await store.putEvaluation(reviewFixture(id));await store.writeReviews([{review:buildReview(reviewFixture('unassigned'),undefined,reviewInput(reviewFixture('unassigned'),'request'),admin,now),expectedRevision:0}]);await assigned(store,'progress',input(0,'b'));await scored(store,'progress','start',1,b);await assigned(store,'completed',input(0,'b'));await scored(store,'completed','complete',1,b);const data=await reviewWorkload(store,now,authority);expect(data.complete).toBe(true);expect(data.unassignedRequested).toBe(1);expect(data.items.find(r=>r.userId==='a')).toMatchObject({assignedOpen:1,requested:1,inReview:0,overdue:1});expect(data.items.find(r=>r.userId==='b')).toMatchObject({assignedOpen:1,requested:0,inReview:1,overdue:1})})
 it.each(['evaluationRecords','humanReviews'])('returns explicit incomplete state beyond 2000 %s',async collection=>{const {store,record}=await fixture();for(let i=0;i<2001;i++){const r=reviewFixture(`extra_${i}`);if(collection==='evaluationRecords')await store.putEvaluation({...record,id:r.id});else await store.writeReviews([{review:buildReview(r,undefined,reviewInput(r,'request'),admin,now),expectedRevision:0}])}expect(await reviewWorkload(store,now,authority)).toMatchObject({complete:false,needsIndexing:true,items:[]});expect((await reviewWorkload(store,now,authority)).unassignedRequested).toBeUndefined()})
 it('bounds and paginates directory, includes bootstrap owner and only safe review-capable identities',async()=>{const {store}=await fixture();const first=await reviewerDirectory(store,new URLSearchParams({limit:'1'}),authority,admin);expect(first.items).toEqual([{...admin,role:'ADMIN'}]);const second=await reviewerDirectory(store,new URLSearchParams({limit:'1',cursor:first.nextCursor!}),authority,admin);expect(second.items).toEqual([{...a,role:'REVIEWER'}]);const third=await reviewerDirectory(store,new URLSearchParams({limit:'1',cursor:second.nextCursor!}),authority,admin);expect(third.items).toEqual([{...b,role:'REVIEWER'}]);expect(JSON.stringify([first,second,third])).not.toMatch(/assignedBy|createdAt|updatedAt|secret/);await role(store,'a','VIEWER');expect((await reviewerDirectory(store,new URLSearchParams(),authority,b)).items.map(r=>r.userId)).toEqual(['admin','b'])})
 it('combines assignment, due, status, form and mine filters using verified actor',()=>{const record=reviewFixture(),r=buildReview(record,undefined,reviewInput(record,'request'),admin,now);r.assignment={assignee:a,assignedAt:now,assignedBy:admin,dueAt:due};const joined={...record,humanReview:r};expect(matchesReviewQueue(joined,new URLSearchParams({assignment:'mine',due:'overdue',reviewStatus:'REVIEW_REQUESTED',form:record.form.id}),a.userId,now)).toBe(true);expect(matchesReviewQueue(joined,new URLSearchParams({assignment:'mine',assigneeId:'a'}),b.userId,now)).toBe(false);expect(matchesReviewQueue(joined,new URLSearchParams({reviewQueue:'mine'}),undefined,now)).toBe(false);expect(matchesReviewQueue(joined,new URLSearchParams({assignment:'unassigned'}),a.userId,now)).toBe(false);r.assignment.dueAt=now;expect(matchesReviewQueue(joined,new URLSearchParams({due:'today'}),a.userId,now)).toBe(true);expect(matchesReviewQueue(joined,new URLSearchParams({due:'week'}),a.userId,now)).toBe(true)})
})
const servers:Server[]=[];afterEach(async()=>{await Promise.all(servers.splice(0).map(s=>new Promise<void>(resolve=>s.close(()=>resolve()))))})
it('enforces HTTP RBAC, safe directory, mine identity and conflict statuses without providers',async()=>{
 const {store,record}=await fixture(),deps:RunnerDeps={store,now:()=>new Date(now),genesys:{list:async()=>{throw Error('NO GENESYS')},load:async()=>{throw Error('NO GENESYS')},withQueueNames:async()=>{throw Error('NO GENESYS')}},jev:{evaluate:async()=>{throw Error('NO JEV')}}}
 const server=createApi(deps,{origin:'https://example.com',region:'eu-west-1',allowedUserIds:authority.allowedUserIds,bootstrapAdminId:'admin',schedulerEmail:'',schedulerAudience:''},async(_url,init)=>new Response(JSON.stringify({id:(init?.headers as Record<string,string>).Authorization.replace('Bearer ',''),name:'Verified'})))
 servers.push(server);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`
 const call=(actor:string,path:string,method='GET',value?:unknown)=>fetch(base+path,{method,headers:{Authorization:`Bearer ${actor}`,'Content-Type':'application/json'},...(value?{body:JSON.stringify(value)}:{})})
 for(const actor of ['a','author','viewer']){expect((await call(actor,`/api/reviews/${record.id}/assignment`,'PUT',input())).status).toBe(403);expect((await call(actor,'/api/reviewers')).status).toBe(200);expect((await call(actor,'/api/review-workload')).status).toBe(200)}
 expect((await call('admin',`/api/reviews/${record.id}/assignment`,'PUT',input())).status).toBe(200)
 expect((await call('b',`/api/reviews/${record.id}`,'PUT',reviewInput(record,'start',1))).status).toBe(403)
 expect((await call('admin',`/api/reviews/${record.id}`,'PUT',reviewInput(record,'start',1))).status).toBe(403)
 for(const actor of ['author','viewer'])expect((await call(actor,`/api/reviews/${record.id}`,'PUT',reviewInput(record,'start',1))).status).toBe(403)
 expect((await call('a',`/api/reviews/${record.id}`,'PUT',reviewInput(record,'start',1))).status).toBe(200)
 expect((await call('admin',`/api/reviews/${record.id}/assignment`,'PUT',{...input(1,'b','reassign'),confirmInReview:true})).status).toBe(409)
 expect((await (await call('b','/api/evaluations?assignment=mine&assigneeId=a')).json()).items).toHaveLength(0)
 expect((await (await call('a','/api/evaluations?reviewQueue=mine')).json()).items).toHaveLength(1)
 expect((await call('admin','/api/reviews/bulk-assign','POST',{items:[{evaluationId:record.id,expectedRevision:2}],assigneeId:'a'})).status).toBe(400)
 await store.putEvaluation(reviewFixture('claim'))
 await store.writeReviews([{review:buildReview(reviewFixture('claim'),undefined,reviewInput(reviewFixture('claim'),'request'),admin,now),expectedRevision:0}])
 const claims=await Promise.all(['a','b'].map(actor=>call(actor,'/api/reviews/claim','PUT',{...reviewInput(reviewFixture('claim'),'start',1),action:'claim'})))
 expect(claims.map(r=>r.status).sort()).toEqual([200,409])
})
