import { describe,it,expect,vi } from 'vitest'
import type { Firestore } from 'firebase-admin/firestore'
import { MemoryStore,FirestoreStore,StoreConflict } from './store'
import { sweepReviewSla,reconcileReviewSla,reviewSlaSummary,reviewMutationSla } from './reviewSla'
import { assignReview,scoreAssignedReview,reviewWorkload } from './reviewOperations'
import { bulkReviewDue } from './bulkReviewDue'
import { buildReview,type HumanReview } from '../domain/reviews'
import { reviewFixture,reviewInput } from '../fixtures/reviewFixture'
import { defaultGovernance } from '../domain/governance'
import { auditContext } from './audit'
import { notificationTick } from './notifications'
import { renderEmail } from './notificationProviders'
import { scanPurge } from './governance'
import { schedulerTick,type RunnerDeps } from './runner'
const now='2026-10-02T12:00:00.000Z',due='2026-10-03T00:00:00.000Z',admin={userId:'admin'},alice={userId:'a'},authority={bootstrapId:'admin',allowedUserIds:new Set(['admin','a','b'])}
async function fixture() {const store=new MemoryStore();for(const id of ['a','b'])await store.atomic([{collection:'roleAssignments',id,expected:undefined,value:{id,userId:id,role:'REVIEWER',createdAt:now,updatedAt:now,assignedBy:admin}}]);const record=reviewFixture('r');await store.putEvaluation(record);await store.writeReviews([{review:{...buildReview(record,undefined,reviewInput(record,'request'),admin,now),dueAt:due},expectedRevision:0}]);return {store,record}}
async function change(store:MemoryStore,value:Partial<HumanReview>) {const prior=(await store.review('r'))!;await store.atomic([{collection:'humanReviews',id:'r',expected:prior,value:{...prior,...value,revision:prior.revision+1}}])}
const active=(store:MemoryStore)=>store.alerts(true)
const at=(hours:number)=>new Date(Date.parse(due)+hours*3600000).toISOString()
describe('SLA alert lifecycle',()=>{
 it('opens one INFO due-soon alert and one routing event across repeated/concurrent sweeps',async()=>{const {store}=await fixture();await Promise.all(Array.from({length:5},()=>sweepReviewSla(store,now)));expect(await active(store)).toHaveLength(1);expect((await active(store))[0]).toMatchObject({type:'REVIEW_DUE_SOON',severity:'INFO',occurrences:1});expect((await store.query('notificationEvents',100)).items).toHaveLength(1)})
 it('resolves old stages while advancing overdue then escalated with fixed severities',async()=>{const {store}=await fixture();for(const time of [now,due,at(48)])await sweepReviewSla(store,time);expect((await active(store))[0]).toMatchObject({type:'REVIEW_ESCALATED',severity:'ERROR'});expect((await store.alerts()).map(a=>[a.type,a.status])).toEqual([['REVIEW_DUE_SOON','RESOLVED'],['REVIEW_OVERDUE','RESOLVED'],['REVIEW_ESCALATED','OPEN']]);expect((await store.query('notificationEvents',100)).items).toHaveLength(5)})
 it('reactivates an automatically resolved stage after disabling escalation without duplicating alert or delivery events',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const overdue=(await active(store))[0];await sweepReviewSla(store,at(48));await store.atomic([{collection:'governanceSettings',id:'governance',expected:undefined,value:{...defaultGovernance,reviewSla:{dueSoonHours:24,overdueEscalationHours:null}}}]);await sweepReviewSla(store,at(49));expect((await active(store))[0]).toMatchObject({id:overdue.id,type:'REVIEW_OVERDUE'});const eventCount=(await store.query('notificationEvents',100)).items.length;const prior=await store.governanceRead('governanceSettings','governance');await store.atomic([{collection:'governanceSettings',id:'governance',expected:prior,value:defaultGovernance}]);await sweepReviewSla(store,at(50));expect((await active(store))[0].type).toBe('REVIEW_ESCALATED');expect((await store.query('notificationEvents',100)).items).toHaveLength(eventCount)})
 it('acknowledgement does not prevent escalation',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const alert=(await active(store))[0];await store.transitionAlert(alert.id,'ACKNOWLEDGED',at(1),admin);await sweepReviewSla(store,at(48));expect((await store.alert(alert.id))?.status).toBe('RESOLVED');expect((await active(store))[0].type).toBe('REVIEW_ESCALATED')})
 it.each([{status:'REVIEWED' as const},{dueAt:undefined},{dueAt:'2027-01-01T00:00:00Z'}])('resolves when review is fixed %j',async value=>{const {store}=await fixture();await sweepReviewSla(store,due);await change(store,value);await sweepReviewSla(store,due);expect(await active(store)).toHaveLength(0);expect((await store.alerts())[0].events.at(-1)).toMatchObject({action:'RESOLVED',automatic:true});expect((await store.alerts())[0].resolutionReason).toContain('re-evaluated')})
 it('resolves deleted reviews through active alerts without scanning review history',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const prior=await store.review('r');await store.atomic([{collection:'humanReviews',id:'r',expected:prior}]);await sweepReviewSla(store,due);expect(await active(store)).toHaveLength(0)})
 it('opens an unassigned overdue alert with safe linkage',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);expect((await active(store))[0]).toMatchObject({type:'REVIEW_OVERDUE',message:'Review is overdue and has no assigned reviewer.',context:{evaluationId:'r',reviewId:'r',dueAt:due}});expect((await active(store))[0].context?.assigneeUserId).toBeUndefined()})
 it('reassignment opens a new alert without mutating prior histories; unassign preserves due date',async()=>{const {store}=await fixture();const first=await assignReview(store,'r',{action:'assign',expectedRevision:1,assigneeId:'a',dueAt:due},admin,at(1),authority);const old=(await active(store))[0];await assignReview(store,'r',{action:'reassign',expectedRevision:first.revision,assigneeId:'b',dueAt:due},admin,at(2),authority);expect((await store.alert(old.id))?.status).toBe('RESOLVED');expect((await active(store))[0].context?.assigneeUserId).toBe('b');expect((await active(store))[0].id).not.toBe(old.id);await assignReview(store,'r',{action:'unassign',expectedRevision:3},admin,at(3),authority);expect((await active(store))[0].message).toContain('no assigned reviewer');expect((await store.review('r'))?.dueAt).toBe(due)})
 it('completion immediately resolves alerts through the shared evaluator',async()=>{const {store,record}=await fixture();await assignReview(store,'r',{action:'assign',expectedRevision:1,assigneeId:'a',dueAt:due},admin,at(1),authority);const result=await scoreAssignedReview(store,'r',reviewInput(record,'complete',2),alice,at(2),authority);expect(result.status).toBe('REVIEWED');expect(await active(store)).toHaveLength(0);expect((await reviewSlaSummary(store,at(2))).open).toBe(0);expect((await store.review('r'))).toEqual(result)})
 it('manual resolution suppresses the same stage but permits escalation',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const alert=(await active(store))[0];await store.transitionAlert(alert.id,'RESOLVED',at(1),admin);await sweepReviewSla(store,at(2));expect(await active(store)).toHaveLength(0);await sweepReviewSla(store,at(48));expect((await active(store))[0].type).toBe('REVIEW_ESCALATED')})
 it('retention does not permit a purged resolved stage to notify again',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const alert=(await active(store))[0];await store.transitionAlert(alert.id,'RESOLVED',at(1),admin);await store.atomic([{collection:'operationalAlerts',id:alert.id,expected:await store.alert(alert.id)}]);await sweepReviewSla(store,at(2));expect(await active(store)).toHaveLength(0);expect((await store.query('notificationEvents',100)).items).toHaveLength(2)})
 it('guards against a completion between classification and alert commit',async()=>{const {store}=await fixture();const original=store.syncReviewSla.bind(store);store.syncReviewSla=async(...args)=>{await change(store,{status:'REVIEWED'});return original(...args)};await expect(reconcileReviewSla(store,'r',due)).rejects.toBeInstanceOf(StoreConflict);expect(await active(store)).toHaveLength(0);expect((await sweepReviewSla(store,due)).complete).toBe(true)})
 it('runs on the existing scheduler tick with zero provider calls and unchanged schedules',async()=>{const {store}=await fixture(),fail=vi.fn(async()=>{throw Error('NO PROVIDERS')}),deps:RunnerDeps={store,now:()=>new Date(due),genesys:{list:fail,load:fail,withQueueNames:fail},jev:{evaluate:fail}};expect(await schedulerTick(deps)).toEqual([]);expect(fail).not.toHaveBeenCalled();expect((await active(store))[0].type).toBe('REVIEW_OVERDUE');expect(await store.schedules()).toEqual([])})
 it('excludes completed history and explicitly reports a bounded scan ceiling',async()=>{const {store}=await fixture();for(const id of ['r2','r3','completed']){const record=reviewFixture(id);await store.putEvaluation(record);const review=buildReview(record,undefined,reviewInput(record,'request'),admin,now);await store.writeReviews([{review:{...review,status:id==='completed'?'REVIEWED':'REVIEW_REQUESTED',dueAt:due},expectedRevision:0}])}const health=await sweepReviewSla(store,due,2);expect(health).toMatchObject({complete:false,open:2,scanned:2});expect(health.message).toContain('incomplete');expect((await store.governanceRead('operationalHealth','reviewSla'))).toEqual(health)})
 it('counts mutually exclusive stages for reviewers and unassigned, with revoked access visible',async()=>{const {store}=await fixture();await assignReview(store,'r',{action:'assign',expectedRevision:1,assigneeId:'a',dueAt:due},admin,now,authority);for(const [id,hours] of [['overdue',-1],['escalated',-48],['completed',-48]] as [string,number][]){const record=reviewFixture(id);await store.putEvaluation(record);await store.writeReviews([{review:{...buildReview(record,undefined,reviewInput(record,'request'),admin,now),status:id==='completed'?'REVIEWED':'REVIEW_REQUESTED',dueAt:new Date(Date.parse(now)+hours*3600000).toISOString()},expectedRevision:0}])}const prior=await store.governanceRead('roleAssignments','a');await store.atomic([{collection:'roleAssignments',id:'a',expected:prior,value:{id:'a',userId:'a',role:'VIEWER'}}]);const health=await reviewWorkload(store,now,authority);expect(health.summary).toMatchObject({open:3,dueSoon:1,overdue:1,escalated:1});expect(health.items.find(r=>r.userId==='a')).toMatchObject({reviewerAccess:false,dueSoon:1,assignedOpen:1});expect(health.items.find(r=>r.userId==='unassigned')).toMatchObject({assignedOpen:2,overdue:1,escalated:1})})
 it('retries a concurrent post-write change and exposes an unavailable alert check without failing the review write',async()=>{const {store}=await fixture();const sync=store.syncReviewSla.bind(store);let first=true;store.syncReviewSla=async(...args)=>{if(first){first=false;throw new StoreConflict()}return sync(...args)};await reviewMutationSla(store,'r',due);expect(await active(store)).toHaveLength(1);store.syncReviewSla=async()=>{throw Error('UNAVAILABLE')};const log=vi.spyOn(console,'error').mockImplementation(()=>{});await reviewMutationSla(store,'r',due);expect(await store.governanceRead('operationalHealth','reviewSla')).toMatchObject({complete:false});log.mockRestore()})
 it('active alerts survive alert retention',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);expect((await scanPurge(store,{...defaultGovernance,alertRetentionDays:1},at(72))).counts.alerts).toBe(0)})
})
describe('existing provider-free notification pipeline',()=>{
 it('routes all stages exactly once and resolution per existing rule; reassignment creates a fresh delivery',async()=>{const {store}=await fixture();await store.atomic([{collection:'notificationDestinations',id:'d',expected:undefined,value:{id:'d',type:'EMAIL',name:'Operations',enabled:true,configuration:{},createdAt:now,updatedAt:now}},{collection:'notificationRules',id:'rule',expected:undefined,value:{id:'rule',name:'Reviews',enabled:true,severities:['INFO','WARNING','ERROR'],alertTypes:['REVIEW_DUE_SOON','REVIEW_OVERDUE','REVIEW_ESCALATED'],destinationIds:['d'],notifyOnResolution:true,createdAt:now,updatedAt:now}}]);const send=vi.fn(async()=>{}),providers={EMAIL:{send},WEBHOOK:{send}};for(const time of [now,now,due,due,at(48),at(48)]){await sweepReviewSla(store,time);await notificationTick(store,providers,()=>new Date(time))}expect(send).toHaveBeenCalledTimes(5);const before=await store.notificationHistory();await assignReview(store,'r',{action:'assign',expectedRevision:1,assigneeId:'a',dueAt:due},admin,at(49),authority);await notificationTick(store,providers,()=>new Date(at(49)));expect(send).toHaveBeenCalledTimes(7);for(const delivery of before.items)expect(await store.governanceRead('notificationDeliveries',delivery.id)).toEqual(delivery);expect(renderEmail((await store.notificationHistory()).items.find(d=>d.event==='OPEN')!).text).toContain('evaluationId=r')})
 it('keeps question answers, notes, transcripts and arbitrary context out of payloads',async()=>{const {store}=await fixture();await change(store,{notes:'PRIVATE NOTES',questions:[{...((await store.review('r'))!.questions[0]),human:{value:'PRIVATE ANSWER',outcome:'PRIVATE ANSWER',credit:1,note:'PRIVATE NOTE'}}]});await sweepReviewSla(store,due);const value=JSON.stringify({alerts:await store.alerts(),events:(await store.query('notificationEvents',100)).items});for(const marker of ['PRIVATE','questions','formSnapshot','conversationId'])expect(value).not.toContain(marker);expect(value).toContain('evaluationId')})
})
// This serial transaction fixture exercises the actual Firestore adapter, including retained keys.
it('Firestore SLA transaction deduplicates concurrent opens, guards reviews, resolves stages and retains tombstones',async()=>{
 const data=new Map<string,unknown>();let pending:Promise<unknown>=Promise.resolve();let writing=false
 const db={collection:(name:string)=>({doc:(id:string)=>({path:`${name}/${id}`})}),runTransaction:<T>(fn:(tx:any)=>Promise<T>)=>{const execute=async()=>{writing=false;return fn({get:async(ref:{path:string})=>{expect(writing).toBe(false);return{exists:data.has(ref.path),data:()=>structuredClone(data.get(ref.path))}},set:(ref:{path:string},v:unknown)=>{writing=true;data.set(ref.path,structuredClone(v))},create:(ref:{path:string},v:unknown)=>{writing=true;if(data.has(ref.path))throw Error('Already exists');data.set(ref.path,structuredClone(v))}})};const result=pending.then(execute);pending=result.catch(()=>{});return result}} as unknown as Firestore
 const store=new FirestoreStore(db),record=reviewFixture('r'),review={...buildReview(record,undefined,reviewInput(record,'request'),admin,now),dueAt:due};data.set('humanReviews/r',review)
 const input={dedupKey:'REVIEW:r:epoch:OVERDUE',type:'REVIEW_OVERDUE' as const,severity:'WARNING' as const,title:'Review overdue',message:'Review is overdue.',source:'review-sla' as const,metadata:{},context:{reviewId:'r',evaluationId:'r',formId:record.form.id,dueAt:due}}
 await Promise.all(Array.from({length:5},()=>store.syncReviewSla('r',review,input,due,'stage changed')));expect([...data.keys()].filter(k=>k.startsWith('operationalAlerts/'))).toHaveLength(1);expect([...data.keys()].filter(k=>k.startsWith('notificationEvents/'))).toHaveLength(1)
 await store.syncReviewSla('r',review,{...input,type:'REVIEW_ESCALATED',severity:'ERROR',dedupKey:'REVIEW:r:epoch:ESCALATED'},at(48),'stage changed');expect([...data.values()].filter((v:any)=>v.status==='RESOLVED')).toHaveLength(1);expect([...data.keys()].filter(k=>k.startsWith('notificationEvents/'))).toHaveLength(3)
 await store.syncReviewSla('r',review,input,at(49),'escalation disabled');expect([...data.values()].filter((v:any)=>v.status==='OPEN')).toHaveLength(1);expect([...data.keys()].filter(k=>k.startsWith('notificationEvents/'))).toHaveLength(4);await store.syncReviewSla('r',review,{...input,type:'REVIEW_ESCALATED',severity:'ERROR',dedupKey:'REVIEW:r:epoch:ESCALATED'},at(50),'escalation enabled');expect([...data.keys()].filter(k=>k.startsWith('notificationEvents/'))).toHaveLength(4)
 data.set('humanReviews/r',{...review,status:'REVIEWED',revision:2});await expect(store.syncReviewSla('r',review,input,due,'stale')).rejects.toBeInstanceOf(StoreConflict)
 await store.syncReviewSla('r',{...review,status:'REVIEWED',revision:2},undefined,at(49),'completed');expect([...data.values()].filter((v:any)=>v.status==='OPEN')).toHaveLength(0)
 for(const key of [...data.keys()])if(key.startsWith('operationalAlerts/'))data.delete(key)
 data.set('humanReviews/r',review);await store.syncReviewSla('r',review,input,due,'retained');expect([...data.keys()].filter(k=>k.startsWith('operationalAlerts/'))).toHaveLength(0)
})
describe('bulk due date',()=>{
 it('sets and clears mixed requested/in-progress dates without changing assignment, answers or reviewer',async()=>{const {store,record}=await fixture();await assignReview(store,'r',{action:'assign',expectedRevision:1,assigneeId:'a',dueAt:due},admin,now,authority);const progress=await scoreAssignedReview(store,'r',{...reviewInput(record,'save',2),answers:[],notes:'preserve'},alice,now,authority);const unassigned=reviewFixture('u');await store.putEvaluation(unassigned);await store.writeReviews([{review:buildReview(unassigned,undefined,reviewInput(unassigned,'request'),admin,now),expectedRevision:0}]);const result=await bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:3},{evaluationId:'u',expectedRevision:1}],dueAt:at(100)},admin,now,authority);expect(result.items[0].assignment?.assignee).toEqual(progress.assignment?.assignee);expect(result.items[0].assignment?.assignedAt).toEqual(progress.assignment?.assignedAt);expect(result.items[0].questions).toEqual(progress.questions);expect(result.items[0].notes).toBe('preserve');expect(result.items[1].assignment).toBeUndefined();expect(result.items[1].dueAt).toBe(at(100));const cleared=await bulkReviewDue(store,{items:result.items.map(r=>({evaluationId:r.id,expectedRevision:r.revision})),dueAt:null},admin,now,authority);expect(cleared.items.every(r=>!r.dueAt&&!r.assignment?.dueAt)).toBe(true);expect(cleared.items[0].events.at(-1)?.dueCleared).toBe(true)})
 it('validates every record before any writes, rejecting completed and stale revisions',async()=>{const {store}=await fixture();for(const selected of [{evaluationId:'missing',expectedRevision:0},{evaluationId:'r',expectedRevision:0}]){const before=await store.review('r');await expect(bulkReviewDue(store,{items:[selected],dueAt:due},admin,now,authority)).rejects.toThrow();expect(await store.review('r')).toEqual(before)}const completed=reviewFixture('z');await store.putEvaluation(completed);await store.writeReviews([{review:{...buildReview(completed,undefined,reviewInput(completed,'request'),admin,now),status:'REVIEWED'},expectedRevision:0}]);const before=await store.review('r');await expect(bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:1},{evaluationId:'z',expectedRevision:1}],dueAt:due},admin,now,authority)).rejects.toThrow('requested');expect(await store.review('r')).toEqual(before)})
 it('enforces max 20, uniqueness, explicit timestamp and assignment permissions',async()=>{const {store}=await fixture();for(const input of [{items:[],dueAt:due},{items:Array.from({length:21},(_,i)=>({evaluationId:`r${i}`,expectedRevision:1})),dueAt:due},{items:[{evaluationId:'r',expectedRevision:1},{evaluationId:'r',expectedRevision:1}],dueAt:due},{items:[{evaluationId:'r',expectedRevision:1}],dueAt:'invalid'},{items:[{evaluationId:'r',expectedRevision:1}],dueAt:undefined}])await expect(bulkReviewDue(store,input as any,admin,now,authority)).rejects.toThrow();await expect(bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:1}],dueAt:due},alice,now,authority)).rejects.toThrow('Forbidden')})
 it('audits old/new dates and clear operations with no answer leakage',async()=>{const {store}=await fixture();await auditContext.run({actor:admin,now,correlationId:'proof'},()=>bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:1}],dueAt:null},admin,now,authority));const audit=(await store.query<any>('auditEvents',100)).items;expect(audit.some(e=>e.action==='review.bulk_due_changed'&&e.metadata.previousDueAt===due&&e.metadata.dueCleared)).toBe(true);expect(audit.some(e=>e.action==='review.due_changed'&&e.metadata.dueCleared)).toBe(true);expect(JSON.stringify(audit)).not.toContain('questions')})
 it('keeps an unchanged due date in the same alert epoch',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);const alert=(await active(store))[0],prior=await store.review('r');await bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:1}],dueAt:due},admin,due,authority);await sweepReviewSla(store,due);expect(await store.review('r')).toEqual(prior);expect((await active(store))[0]).toEqual(alert);expect((await store.query('notificationEvents',100)).items).toHaveLength(1)})
 it('re-evaluates bulk due changes on next sweep with the same evaluator',async()=>{const {store}=await fixture();await sweepReviewSla(store,due);await bulkReviewDue(store,{items:[{evaluationId:'r',expectedRevision:1}],dueAt:null},admin,due,authority);expect(await active(store)).toHaveLength(1);await sweepReviewSla(store,due);expect(await active(store)).toHaveLength(0)})
})
