import { describe,it,expect,vi } from 'vitest'
import { MemoryStore } from './store'
import { executeServerRun, planServerRun, schedulerTick, scheduledRunId, executionClaimId, evaluationId, type RunnerDeps } from './runner'
import { seedForms } from '../domain/forms'
import type { Conversation, EvaluationResult, InteractionPolicy } from '../domain/types'
import type { Schedule } from './schedules'
const conversation:Conversation={conversationId:'12345678-1234-1234-1234-123456789abc',startedAt:'2026-09-28T12:00:00.000Z',channel:'voice',agent:{id:'a',name:'Agent'},customer:{id:'c',name:'Customer'},metadata:{source:'genesys-cloud',queue:'Service'},messages:[{id:'1',speaker:'customer',timestamp:'2026-09-28T12:00:01.000Z',text:'Sensitive transcript marker'}]}
const policy:InteractionPolicy={id:'policy',name:'Voice',description:'',enabled:true,version:2,criteria:{anyOf:[[{field:'channel',operator:'equals',value:'voice'}]]},evaluationFormIds:[seedForms[0].id],sampling:{strategy:'all'}}
const period={periodStart:'2026-09-28T00:00:00.000Z',periodEnd:'2026-09-29T00:00:00.000Z'}
function fixture(){const store=new MemoryStore();const evaluate=vi.fn(async()=>({conversationId:conversation.conversationId,scorecardId:seedForms[0].id,scorecardVersion:1,evaluatedAt:'2026-09-30T00:00:00.000Z',provider:'typesafe',model:'test',questions:[],overallScore:.8,countedWeight:1,rawResponse:{}} satisfies EvaluationResult));const deps:RunnerDeps={store,genesys:{list:async()=>({conversations:[conversation],page:1,pageSize:25,total:1,hasMore:false}),load:async()=>conversation,withQueueNames:async c=>c},jev:{evaluate},now:()=>new Date('2026-09-30T00:00:00.000Z')};return {store,evaluate,deps}}
describe('durable runner',()=>{
  it('executes recreated Customer Service through scheduled production without acknowledgement',async()=>{const {deps,store,evaluate}=fixture();const form={...seedForms.at(-1)!,sourceReview:{status:'REVIEW_REQUIRED' as const}};await store.putForm(form);const run=await executeServerRun(deps,{...policy,evaluationFormIds:[form.id]},period,'recreated_scheduled','scheduled');expect(run.status).toBe('completed');expect(evaluate).toHaveBeenCalledTimes(1);expect((await store.evaluations())[0]).toMatchObject({purpose:'PRODUCTION',executionMode:'scheduled',form})})

  it('uses deterministic identities, persists results and never retains transcript text',async()=>{const {store,evaluate,deps}=fixture();await store.putForm(seedForms[0]);const schedule:Schedule={id:'schedule',policyId:policy.id,enabled:true,frequency:'DAILY',timezone:'Europe/London',localTime:'02:00',nextDueAt:'2026-09-29T01:00:00.000Z',version:1};const id=scheduledRunId(policy,schedule,period);expect(id).toBe(scheduledRunId(policy,schedule,period));const run=await executeServerRun(deps,policy,period,id,'scheduled');expect(run.status).toBe('completed');expect(run.executionMode).toBe('scheduled');expect(evaluate).toHaveBeenCalledTimes(1);expect((await store.runs())[0].id).toBe(id);const records=await store.evaluations();expect(records).toHaveLength(1);expect(records[0].executionMode).toBe('scheduled');expect(records[0].id).toBe(evaluationId(executionClaimId(policy,period),conversation.conversationId,seedForms[0]));expect(JSON.stringify(records)).not.toContain('Sensitive transcript marker');await expect(executeServerRun(deps,policy,period,id,'scheduled')).rejects.toThrow('lease_conflict')})
  it('rejects competing leases and recovers expired ones',async()=>{const {store}=fixture();expect(await store.claim('x','a','2026-09-30T00:00:00Z','2026-09-30T01:00:00Z')).toBe(true);expect(await store.claim('x','b','2026-09-30T00:30:00Z','2026-09-30T01:30:00Z')).toBe(false);expect(await store.claim('x','b','2026-09-30T01:01:00Z','2026-09-30T02:00:00Z')).toBe(true)})
  it('ticks zero and multiple due schedules',async()=>{const {store,deps}=fixture();expect(await schedulerTick(deps)).toEqual([]);await store.putForm(seedForms[0]);await store.putPolicy(policy);for(const id of ['one','two'])await store.putSchedule({id,policyId:policy.id,enabled:true,frequency:'DAILY',timezone:'Europe/London',localTime:'02:00',nextDueAt:'2026-09-29T01:00:00.000Z',version:1});const outcomes=await schedulerTick(deps);expect(outcomes).toHaveLength(2);expect(outcomes[0].status).toBe('completed');expect(outcomes[1].status).toContain('lease_conflict')})
  it('does not retry an uncertain paid request',async()=>{const {store,deps,evaluate}=fixture();await store.putForm(seedForms[0]);evaluate.mockRejectedValueOnce(new Error('Jev network interrupted'));const id='r_partial';const first=await executeServerRun(deps,policy,period,id,'manual');expect(first.status).toBe('failed');const second=await executeServerRun(deps,policy,period,id,'manual');expect(second.failures[0].reason).toContain('evaluation_uncertain');expect(evaluate).toHaveBeenCalledTimes(1)})
  it('splits a 169-hour autumn monitoring week into provider-safe queries',async()=>{const {deps,store}=fixture();await store.putForm(seedForms[0]);const intervals:string[]=[];deps.now=()=>new Date('2026-10-27T00:00:00Z');deps.genesys.list=async query=>{intervals.push(`${query.from}/${query.to}`);return {conversations:[],page:1,pageSize:25,total:0,hasMore:false}};await planServerRun(deps,policy,{periodStart:'2026-10-18T23:00:00.000Z',periodEnd:'2026-10-26T00:00:00.000Z'});expect(intervals).toHaveLength(2);expect(intervals[0]).toBe('2026-10-18T23:00:00.000Z/2026-10-25T23:00:00.000Z');expect(intervals[1]).toBe('2026-10-25T23:00:00.000Z/2026-10-26T00:00:00.000Z')})
  it('plans legacy enabled recreated forms using ordinary readiness',async()=>{const {deps,store,evaluate}=fixture();const recreated={...seedForms[0],origin:'genesys-recreated' as const,status:undefined,enabled:true};await store.putForm(recreated);const list=vi.spyOn(deps.genesys,'list');await planServerRun(deps,{...policy,evaluationFormIds:[recreated.id]},period);expect(list).toHaveBeenCalled();expect(evaluate).not.toHaveBeenCalled()})
  it('persists an operational failure when Genesys authentication blocks planning',async()=>{const {deps,store}=fixture();await store.putForm(seedForms[0]);deps.genesys.list=async()=>{throw new Error('Genesys automation authentication failed (HTTP 401).')};await expect(executeServerRun(deps,policy,period,'r_auth','scheduled')).rejects.toThrow('authentication');const [run]=await store.runs();expect(run.status).toBe('failed');expect(run.failures[0].reason).toContain('genesys_auth')})
})

it('pushes only common AND predicates, preserves OR populations and samples at most three',async()=>{
 const {deps,store,evaluate}=fixture();await store.putForm(seedForms[0]);const list=vi.spyOn(deps.genesys,'list')
 const bounded={...policy,sampling:{strategy:'fixed_count' as const,count:3},criteria:{anyOf:[[{field:'channel' as const,operator:'equals' as const,value:'voice'},{field:'direction' as const,operator:'equals' as const,value:'inbound'}]]}}
 await planServerRun(deps,bounded,period);expect(list).toHaveBeenLastCalledWith(expect.objectContaining({channel:'voice',direction:'inbound',pageSize:25}));expect(evaluate).not.toHaveBeenCalled()
 const union={...bounded,criteria:{anyOf:[...bounded.criteria.anyOf,[{field:'channel' as const,operator:'equals' as const,value:'email'}]]}}
 await planServerRun(deps,union,period);expect(list.mock.calls.at(-1)![0]).not.toHaveProperty('channel');expect(list.mock.calls.at(-1)![0]).not.toHaveProperty('direction')
})
it('email uses ordinary sampling, evaluator, production records and coverage without persisting content',async()=>{
 const {deps,store,evaluate}=fixture();await store.putForm(seedForms[0]);const email={...conversation,channel:'email'};deps.genesys.list=async()=>({conversations:[email],page:1,pageSize:25,total:1,hasMore:false});deps.genesys.load=async()=>email
 const emailPolicy={...policy,criteria:{anyOf:[[{field:'channel' as const,operator:'equals' as const,value:'email'}]]},sampling:{strategy:'fixed_count' as const,count:3}}
 const planned=await planServerRun(deps,emailPolicy,period);expect(planned.plan.expectedEvaluations).toBe(1)
 const run=await executeServerRun(deps,emailPolicy,period,'email_run','manual',planned);expect(run.status).toBe('completed');expect(run.coverage?.successfulEvaluationCount).toBe(1);expect(evaluate).toHaveBeenCalledTimes(1);expect(JSON.stringify(await store.evaluations())).not.toContain('Sensitive transcript marker')
})
