import { describe,expect,it } from 'vitest'
import { applyAnswerSet, detachAnswerSet, updateAnswerSet, saveAnswerSet, validateAnswerSetAsset, transitionAnswerSet, nextAnswerSetVersion, assertAnswerSetWrite, answerSetDefinition, answerSetDirty, answerSetComparison, assertAttachedAnswers } from './answerSets'
import { seedAnswerSets } from './seedAnswerSets'
import { MemoryStore } from '../server/store'
import { exportDefinition, importDefinition } from './portability'
import { seedForms, toScorecard } from './forms'
import { reviewFixture, reviewInput } from '../fixtures/reviewFixture'
import { answerCredit, buildReview } from './reviews'
import { aggregateCalibration } from './calibration'
import { summarize, questionBreakdown } from './analytics'
import { fromJevResponse, toJevRequest } from '../provider/jev'
import { recordEvaluation } from './evaluations'
import { saveGroupAsset, insertGroupAsset, nextAssetVersion } from './groupAssets'
import type { AnswerSetAsset, EvaluationForm } from './types'
const now='2026-10-03T00:00:00.000Z',asset=()=>structuredClone(seedAnswerSets[1])
function form(type:'choice'|'score'='choice'):EvaluationForm {return {...structuredClone(seedForms[0]),status:'DRAFT',enabled:false,questions:[{id:'q',title:'Quality',instructions:'Assess the quality.',type,options:structuredClone(seedAnswerSets[type==='choice'?1:0].options),weight:1,enabled:true}]}}
const newer=(a=asset())=>transitionAnswerSet(nextAnswerSetVersion(a,[a],now),'PUBLISHED',now)
describe('reusable Answer Set definitions and snapshots',()=>{
 it('validates choice and ordered score starters with historical non-monotone source values',()=>{for(const a of seedAnswerSets)expect(validateAnswerSetAsset(a)).toEqual([]);const a={...asset(),type:'score' as const};a.options[0].sourceValue=99;a.options[1].sourceValue=-3;expect(validateAnswerSetAsset(a)).toEqual([])})
 it.each([{type:'noul'}, {id:'bad/id'},{familyId:''},{name:' '},{description:null},{version:0},{version:1.2},{status:'INVALID'},{options:[]},{options:null},{options:[{key:'a',label:'',description:'Missing label'},{key:'a',label:'A',description:'Duplicate'}]},{options:[{key:'a',label:'A',description:'A',credit:2},{key:'b',label:'B',description:'B',sourceValue:Infinity}]}])('rejects malformed definition %j',patch=>{expect(validateAnswerSetAsset({...asset(),...patch} as unknown as AnswerSetAsset).length).toBeGreaterThan(0)})
 it('bounds score/choice counts, keys, credits, source values, strings, request bytes and nesting',()=>{
  const a=asset();for(const [type,count] of [['score',11],['choice',256]] as const)expect(validateAnswerSetAsset({...a,type,options:Array.from({length:count},(_,i)=>({...a.options[0],key:`o_${i}`}))}).length).toBeGreaterThan(0)
  for(const patch of [{credit:-.1},{credit:NaN},{credit:Infinity},{sourceValue:NaN},{key:'Bad key'},{description:''}])expect(validateAnswerSetAsset({...a,options:[{...a.options[0],...patch},a.options[1]]}).length).toBeGreaterThan(0)
  expect(validateAnswerSetAsset({...a,name:'x'.repeat(10001)}).join(' ')).toContain('10,000');const nested:Record<string,unknown>={};let n=nested;for(let i=0;i<17;i++)n=n.child={};expect(validateAnswerSetAsset({...a,...{extra:nested}}).join(' ')).toContain('nesting')
 })
 it('tracks drafts and preserves immutable published/retired definitions and stable family type',()=>{
  const p=asset(),d={...p,status:'DRAFT' as const};expect(answerSetDirty({...d,name:'Changed'},d)).toBe(true);expect(answerSetDirty(d,d)).toBe(false);expect(answerSetDirty(p,p)).toBe(false)
  expect(()=>assertAnswerSetWrite(p,{...p,name:'Changed'})).toThrow('immutable');expect(()=>assertAnswerSetWrite(p,{...p,status:'DRAFT'})).toThrow('transition')
  expect(()=>transitionAnswerSet(p,'DRAFT',now)).toThrow('transition');const retired=transitionAnswerSet(p,'RETIRED',now);expect(retired.options).toEqual(p.options);expect(()=>assertAnswerSetWrite(retired,{...retired,options:[...p.options].reverse()})).toThrow('immutable')
  const v2=nextAnswerSetVersion(p,[p],now);expect(v2).toMatchObject({id:'resolution_clarity_v2',familyId:p.familyId,version:2,status:'DRAFT'});expect(nextAnswerSetVersion(p,[v2],now).version).toBe(3)
  expect(()=>assertAnswerSetWrite(undefined,{...v2,type:'score'},[p])).toThrow('base type');expect(()=>assertAnswerSetWrite(undefined,{...v2,id:'other'},[v2])).toThrow('already exists');expect(()=>assertAnswerSetWrite(undefined,p)).toThrow('DRAFT')
 })
 it('enforces durable uniqueness and isolation below the API',async()=>{const s=new MemoryStore(),a={...asset(),status:'DRAFT' as const};await s.putAnswerSet(a);await s.putAnswerSet(transitionAnswerSet(a,'PUBLISHED',now));await expect(s.putAnswerSet({...a,id:'conflict'})).rejects.toThrow('already exists');await expect(s.putAnswerSet({...nextAnswerSetVersion(a,[a],now),type:'score'})).rejects.toThrow('base type');const read=(await s.answerSet(a.id))!;read.options[0].label='Changed';expect((await s.answerSet(a.id))!.options[0].label).toBe('Clear')})
 it('applies a deep snapshot, detaches with exact options/type/scoring and saves as a new draft family',()=>{const a=asset(),f=form(),before=JSON.stringify(f),attached=applyAnswerSet(f,'q',a);expect(attached.questions[0].sourceAnswerSet).toEqual({familyId:a.familyId,answerSetId:a.id,answerSetVersion:1});expect(JSON.stringify(f)).toBe(before);a.options[0].label='Changed asset';expect(attached.questions[0].options[0].label).toBe('Clear');const detached=detachAnswerSet(attached,'q');expect(detached.questions[0].sourceAnswerSet).toBeUndefined();expect(detached.questions[0].options).toEqual(attached.questions[0].options);expect(detached.scoring).toEqual(attached.scoring);expect(detached.questions[0].type).toBe('choice');const saved=saveAnswerSet(detached,'q','fresh','Custom','Description',now);expect(saved).toMatchObject({familyId:'fresh',version:1,status:'DRAFT',type:'choice'});expect(saved.options).toEqual(detached.questions[0].options)})
 it('rejects missing question, type mismatch, Noul, retired/draft sets and published form mutation',()=>{expect(()=>applyAnswerSet(form(),'missing',asset())).toThrow('not found');expect(()=>applyAnswerSet(form('score'),'q',asset())).toThrow('type');const f=form();f.questions[0].type='noul';expect(()=>applyAnswerSet(f,'q',asset())).toThrow('Noul');expect(()=>saveAnswerSet(f,'q','fresh','N','',now)).toThrow('Noul');for(const status of ['DRAFT','RETIRED'] as const)expect(()=>applyAnswerSet(form(),'q',{...asset(),status})).toThrow('published');const f2={...applyAnswerSet(form(),'q',asset()),status:'PUBLISHED' as const};for(const action of [()=>applyAnswerSet(f2,'q',asset()),()=>detachAnswerSet(f2,'q'),()=>updateAnswerSet(f2,'q',newer())])expect(action).toThrow('draft/testing')})
 it('guards attached editing and requires explicit detach before type changes',()=>{const q=applyAnswerSet(form(),'q',asset()).questions[0];expect(()=>assertAttachedAnswers(q,{...q,options:[...q.options].reverse()})).toThrow('Detach');expect(()=>assertAttachedAnswers(q,{...q,type:'score'})).toThrow('Detach');expect(()=>assertAttachedAnswers(q,{...q,sourceAnswerSet:undefined,type:'score'})).not.toThrow();expect(()=>applyAnswerSet({...form(),questions:[q]},'q',asset())).toThrow('Detach')})
 it('previews all six difference categories and updates only explicitly',()=>{const a=asset(),f=applyAnswerSet(form(),'q',a),before=JSON.stringify(f),v2=newer(a);v2.options=v2.options.slice(0,3).reverse();v2.options[0]={...v2.options[0],label:'Different',description:'New',credit:.2,sourceValue:10};v2.options.push({key:'added',label:'Added',description:'Added',credit:1});const diff=answerSetComparison(f.questions[0].options,v2.options);expect(diff.map(d=>d.details.length>0)).toEqual([true,true,true,true,true,true]);expect(JSON.stringify(f)).toBe(before);const updated=updateAnswerSet(f,'q',v2);expect(updated.questions[0].options).toEqual(v2.options);expect(updated.questions[0].sourceAnswerSet?.answerSetVersion).toBe(2);expect(JSON.stringify(f)).toBe(before);expect(()=>updateAnswerSet(f,'q',{...v2,familyId:'other'})).toThrow('same');expect(()=>updateAnswerSet(f,'q',{...v2,type:'score'})).toThrow('type')})
 it('blocks removing referenced choice keys using full form composition, including disabled questions',()=>{const f=applyAnswerSet(form(),'q',asset());f.questions.push({...f.questions[0],id:'later',sourceAnswerSet:undefined,type:'noul',options:[],condition:{kind:'question_outcome',questionId:'q',outcomes:['partly_clear']}});const v2=newer();v2.options=v2.options.filter(o=>o.key!=='partly_clear');const before=JSON.stringify(f);expect(()=>updateAnswerSet(f,'q',v2)).toThrow('valid Choice option keys');f.questions[1].enabled=false;expect(()=>updateAnswerSet(f,'q',v2)).toThrow('valid Choice option keys');f.questions[1].enabled=true;expect(JSON.stringify(f)).toBe(before)})
 it('retains ordered score credits/source values and credit-threshold conditions',()=>{const a=structuredClone(seedAnswerSets[0]),f=applyAnswerSet(form('score'),'q',a);f.questions.push({...f.questions[0],id:'later',sourceAnswerSet:undefined,condition:{kind:'question_credit',questionId:'q',operator:'greater_than_or_equal',value:.7}});const v2=newer(a),updated=updateAnswerSet(f,'q',v2);expect(updated.questions[0].options).toEqual(a.options);expect(updated.questions[1].condition).toEqual(f.questions[1].condition)})
 it('round trips answer/form/group snapshots; missing external assets never block import',()=>{const a=asset(),imported=importDefinition('answer-set',exportDefinition('answer-set',a),'imported',now);expect(imported).toMatchObject({id:'imported',familyId:'imported',status:'DRAFT',version:1});expect(imported.options).toEqual(a.options);const f=applyAnswerSet(form(),'q',a),copy=importDefinition('form',exportDefinition('form',f),'copied',now);expect(copy.questions).toEqual(f.questions);f.groups=[{id:'g',name:'Group'}];f.questions[0].groupId='g';const group=saveGroupAsset(f,'g','group',now),round=importDefinition('group',exportDefinition('group',group),'copy_group',now);expect(round.questions).toEqual(group.questions);const inserted=insertGroupAsset({...form(),groups:[],questions:[]},{...round,status:'PUBLISHED'},'instance');expect(inserted.questions[0].sourceAnswerSet).toEqual(f.questions[0].sourceAnswerSet);expect(nextAssetVersion(round,[round],now).questions).toEqual(round.questions)})
 it('rejects malformed/unsupported portable definitions and provenance',()=>{const envelope=exportDefinition('answer-set',asset());for(const bad of [{...envelope,schemaVersion:2},{...envelope,schema:'wrong'},{...envelope,definition:{...asset(),options:[]}},{...envelope,definition:{...asset(),name:'x'.repeat(100001)}}])expect(()=>importDefinition('answer-set',bad,'copy',now)).toThrow();const f=applyAnswerSet(form(),'q',asset()),v=exportDefinition('form',f);v.definition.questions[0].sourceAnswerSet!.answerSetVersion=0;expect(()=>importDefinition('form',v,'f',now)).toThrow('provenance')})
 it('proves identical provider mapping, scoring, Human Review and Calibration with no source library',async()=>{
  const library:AnswerSetAsset[]=[],manual=reviewFixture(),sourced=structuredClone(manual),draft={...sourced.form,status:'DRAFT' as const,enabled:false}
  for(const q of draft.questions.filter(q=>q.type!=='noul')){const a=saveAnswerSet(draft,q.id,`set_${q.id}`,q.title,'',now);const published=transitionAnswerSet(a,'PUBLISHED',now);library.push(published);sourced.form=applyAnswerSet({...sourced.form,status:'DRAFT',enabled:false},q.id,published)}
  sourced.form={...sourced.form,status:'PUBLISHED',enabled:true}
  const conversation={conversationId:manual.conversationId,startedAt:now,channel:'voice',agent:manual.agent,customer:{id:'c',name:'C'},metadata:{},messages:[]}
  const request=(f:EvaluationForm)=>({conversation,scorecard:toScorecard(f),evaluatedAt:now,version:'v0' as const})
  expect(toJevRequest(request(sourced.form))).toEqual(toJevRequest(request(manual.form)))
  const payload={model:'fixture',answers:{greeting:{type:'noul',noul:.95},understanding:{type:'score',score:1,confidence:.75,probabilities:{'0':.1,'1':.8,'2':.1,'3':0}},resolution:{type:'choice',choice:'fully_resolved',confidence:.85,probabilities:{fully_resolved:.85,partially_resolved:.1,unresolved:.04,not_applicable:.01}}}}
  expect(fromJevResponse(request(sourced.form),payload)).toEqual(fromJevResponse(request(manual.form),payload))
  for(const q of sourced.form.questions){const value=q.type==='choice'?'fully_resolved':q.type==='score'?2:'No';expect(answerCredit(q,value)).toEqual(answerCredit(manual.form.questions.find(p=>p.id===q.id)!,value))}
  const actor={userId:'reviewer'},human=buildReview(manual,undefined,reviewInput(manual),actor,now),sourceHuman=buildReview(sourced,undefined,reviewInput(sourced),actor,now)
  expect(sourceHuman.humanOverallScore).toEqual(human.humanOverallScore);expect(sourceHuman.comparison).toEqual(human.comparison)
  expect(aggregateCalibration([{...manual,humanReview:human}])).toEqual(aggregateCalibration([{...sourced,humanReview:sourceHuman}]))
  expect(summarize([manual])).toEqual(summarize([sourced]));expect(questionBreakdown([manual])).toEqual(questionBreakdown([sourced]))
  const record=recordEvaluation(conversation,sourced.form,fromJevResponse(request(sourced.form),payload),[],'historical'),before=JSON.stringify(record),publishedForm=JSON.stringify(sourced.form)
  const store=new MemoryStore(),source=library.find(a=>a.type==='choice')!,v2=nextAnswerSetVersion(source,[source],now);await store.putEvaluation(record);await store.putAnswerSet({...source,status:'DRAFT'});await store.putAnswerSet(source);v2.options[0].credit=0;await store.putAnswerSet(v2);await store.putAnswerSet(transitionAnswerSet(v2,'PUBLISHED',now));await store.putAnswerSet(transitionAnswerSet(source,'RETIRED',now));v2.options[0].label='Later edit';library.length=0;expect(JSON.stringify(await store.evaluation(record.id))).toBe(before)
  expect(JSON.stringify(record)).toBe(before);expect(JSON.stringify(sourced.form)).toBe(publishedForm);expect(answerSetDefinition(source)).not.toBe(answerSetDefinition(v2))
 })
})
