import { describe,it,expect } from 'vitest'
import { bulkQuestions,deleteFormGroup,deleteQuestions,duplicateGroup,duplicateQuestion,filterLibrary } from './authoring'
import { cloneForm,exportDefinition,importDefinition,portableLimit } from './portability'
import { sameDefinition } from './formLifecycle'
import { seedForms } from './forms'
import { seedGroupAssets } from './seedGroupAssets'
import { updateGroupAsset } from './groupAssets'
import type { EvaluationForm } from './types'
const now='2026-10-02T10:00:00Z'
function fixture():EvaluationForm{
 const q=structuredClone(seedForms[0].questions[0]);return {id:'f',familyId:'family',name:'Form',description:'Example',version:3,status:'DRAFT',enabled:false,groups:[{id:'first',name:'First'},{id:'second',name:'Second',scoring:{weight:2,passScore:.8},sourceAsset:{assetId:'missing',familyId:'missing',assetVersion:1}}],questions:[{...q,id:'a',groupId:'first'},{...q,id:'b',groupId:'second',condition:{kind:'question_outcome',questionId:'a',outcomes:['yes']}},{...q,id:'c',groupId:'second',condition:{kind:'question_outcome',questionId:'b',outcomes:['yes']}}],scoring:{yesThreshold:.65,passScore:.7,criticalQuestionIds:['c']}}
}
describe('authoring operations',()=>{
 it('clones independently without operational state and keeps form-scoped references',()=>{const source={...fixture(),status:'PUBLISHED' as const,enabled:true,publishedAt:now};const copy=cloneForm(source,'copy',now);expect(copy).toMatchObject({id:'copy',familyId:'copy',version:1,status:'DRAFT',enabled:false});expect(copy.publishedAt).toBeUndefined();expect(copy.questions).toEqual(source.questions);expect(copy.scoring).toEqual(source.scoring);copy.groups![1].sourceAsset!.assetVersion=99;expect(source.groups![1].sourceAsset!.assetVersion).toBe(1)})
 it('duplicates groups with deterministic internal remapping, external references and critical scoring',()=>{const source=fixture(),copy=duplicateGroup(source,'second');expect(copy.groups!.map(g=>g.id)).toEqual(['first','second','second_copy_1']);expect(copy.questions.at(-2)?.condition).toMatchObject({questionId:'a'});expect(copy.questions.at(-1)?.condition).toMatchObject({questionId:'b_copy_1'});expect(copy.scoring.criticalQuestionIds).toEqual(['c','c_copy_1']);expect(copy.groups!.at(-1)?.scoring).toEqual(source.groups![1].scoring);copy.groups!.at(-1)!.sourceAsset!.assetVersion=8;expect(copy.groups![1].sourceAsset!.assetVersion).toBe(1)})
 it('updates only one asset-backed duplicate snapshot',()=>{const source=fixture();source.groups![1].sourceAsset={assetId:'asset',familyId:'asset',assetVersion:1};source.questions[1].sourceAssetQuestionId='b';source.questions[2].sourceAssetQuestionId='c';const copy=duplicateGroup(source,'second');const asset={...structuredClone(seedGroupAssets[0]),id:'asset_v2',familyId:'asset',version:2,questions:copy.questions.filter(q=>q.groupId==='second').map(q=>{const item={...q,id:q.sourceAssetQuestionId!,condition:q.id==='c'?{kind:'question_outcome' as const,questionId:'b',outcomes:['yes']}:undefined};delete item.groupId;delete item.sourceAssetQuestionId;return item})};const updated=updateGroupAsset(copy,'second_copy_1',asset);expect(updated.groups![1].sourceAsset!.assetVersion).toBe(1);expect(updated.groups![2].sourceAsset!.assetVersion).toBe(2)})
 it('duplicates questions adjacent, retaining condition and critical designation',()=>{const copy=duplicateQuestion(fixture(),'c');expect(copy.questions.map(q=>q.id)).toEqual(['a','b','c','c_copy_1']);expect(copy.questions.at(-1)?.condition).toEqual(copy.questions[2].condition);expect(copy.scoring.criticalQuestionIds).toContain('c_copy_1');expect(duplicateQuestion(fixture(),'b').questions[2].condition).toMatchObject({questionId:'a'})})
 it('identifies question and group dependencies, including critical designation',()=>{const f=fixture();f.groups![1].condition={kind:'question_outcome',questionId:'a',outcomes:['yes']};expect(()=>deleteQuestions(f,['a'])).toThrow('Group “Second”');expect(()=>deleteQuestions(f,['b'])).toThrow('Question “');expect(()=>deleteQuestions(f,['c'])).toThrow('critical');expect(()=>deleteFormGroup(f,'first',false)).toThrow('dependencies');f.scoring.criticalQuestionIds=[];expect(deleteFormGroup(f,'second',false).questions.map(q=>q.id)).toEqual(['a']);expect(deleteFormGroup(f,'second',true).questions.map(q=>q.id)).toEqual(['a','b','c'])})
 it('bulk disables without losing definitions and blocks unsafe enable/move',()=>{const f=fixture();expect(bulkQuestions(f,['b','c'],'disable').questions.filter(q=>!q.enabled).map(q=>q.id)).toEqual(['b','c']);expect(bulkQuestions(f,['b','c'],'disable').questions[1].condition).toEqual(f.questions[1].condition);expect(()=>bulkQuestions(f,['a'],'move','second')).toThrow('earlier');const disabled=bulkQuestions(f,['a'],'disable');expect(()=>bulkQuestions(disabled,['b'],'enable')).toThrow('disabled');const safe={...f,questions:f.questions.map(q=>({...q,condition:undefined})),scoring:{...f.scoring,criticalQuestionIds:[]}};expect(bulkQuestions(safe,['b','a'],'move','second').questions.map(q=>q.id)).toEqual(['c','a','b']);expect(bulkQuestions(safe,['b','c'],'delete').questions).toHaveLength(1)})
 it('forbids all in-place operations on published forms',()=>{const f={...fixture(),status:'PUBLISHED' as const};for(const operation of [()=>duplicateQuestion(f,'a'),()=>duplicateGroup(f,'first'),()=>deleteQuestions(f,['c']),()=>bulkQuestions(f,['a'],'disable')])expect(operation).toThrow('immutable')})
 it('combines status, latest family and usage filters conservatively',()=>{const a=fixture(),b={...a,id:'f2',version:4,status:'PUBLISHED' as const};expect(filterLibrary([a,b],'All',false,'All',f=>f.status!,()=>false)).toHaveLength(2);expect(filterLibrary([a,b],'PUBLISHED',true,'Used',f=>f.status!,f=>f.id==='f2')).toEqual([b]);expect(filterLibrary([a,b],'DRAFT',true,'All',f=>f.status!,()=>false)).toEqual([])})
 it('compares dirty definitions canonically, retaining array order',()=>{const a=fixture(),b=structuredClone(a);b.scoring={passScore:.7,criticalQuestionIds:['c'],yesThreshold:.65};expect(sameDefinition(a,b)).toBe(true);b.questions.reverse();expect(sameDefinition(a,b)).toBe(false)})
})
describe('portable definitions',()=>{
 it('round trips with missing source assets and strips operational fields at every level',()=>{const f=fixture();Object.assign(f,{evaluations:['private'],notificationConfiguration:{secret:'private'}});Object.assign(f.questions[0],{secret:'private'});const envelope=exportDefinition('form',f,now);expect(JSON.stringify(envelope)).not.toContain('private');const imported=importDefinition('form',envelope,'new',now);expect(imported).toMatchObject({id:'new',familyId:'new',version:1,status:'DRAFT',enabled:false,createdAt:now});expect(imported.groups).toEqual(f.groups);expect(imported.questions[0]).not.toHaveProperty('secret')})
 it('round trips reusable groups as new drafts',()=>{const a=seedGroupAssets[0],copy=importDefinition('group',exportDefinition('group',a),'new',now);expect(copy).toMatchObject({id:'new',familyId:'new',version:1,status:'DRAFT'});expect(copy.questions).toEqual(a.questions)})
 it('rejects unsupported schema/version, duplicate IDs, forward conditions and invalid scoring',()=>{const e=exportDefinition('form',fixture(),now);expect(()=>importDefinition('form',{...e,schema:'bad'},'new',now)).toThrow('schema');expect(()=>importDefinition('form',{...e,schemaVersion:2},'new',now)).toThrow('schemaVersion');for(const mutate of [(f:EvaluationForm)=>{f.questions[1].id='a'},(f:EvaluationForm)=>{f.questions[0].condition={kind:'question_outcome',questionId:'c',outcomes:['yes']}},(f:EvaluationForm)=>{f.scoring.passScore=2},(f:EvaluationForm)=>{f.groups![0].id='bad id'},(f:EvaluationForm)=>{f.questions[0].instructions='x'.repeat(10001)}]){const bad=structuredClone(e);mutate(bad.definition as EvaluationForm);expect(()=>importDefinition('form',bad,'new',now)).toThrow()}})
 it('rejects malformed structures and oversized payloads before mutation',()=>{for(const definition of [null,{}, {questions:[null]}, {...fixture(),questions:[{options:null}]}])expect(()=>importDefinition('form',{schema:'genesys-aqm/evaluation-form',schemaVersion:1,definition},'new',now)).toThrow();expect(()=>importDefinition('form',{...exportDefinition('form',fixture()),padding:'x'.repeat(portableLimit)},'new',now)).toThrow('limit')})
})
