import type { Conversation } from './types'
import billing from '../../public/samples/billing-conversation.json'
import delivery from '../../public/samples/delivery-conversation.json'
export interface SampleEntry { conversation: Conversation; title: string; quality: string; summary: string }
const agents = [{id:'agent-001',name:'Alex Morgan'},{id:'agent-002',name:'Priya Shah'},{id:'agent-003',name:'Jordan Lee'},{id:'agent-004',name:'Sam Rivera'},{id:'agent-005',name:'Casey Brown'},{id:'agent-006',name:'Taylor Quinn'}]
interface Scenario { id:string; title:string; quality:string; summary:string; queue:string; topic:string; channel:string; agent:number; customer:string; direction?:string; tag?:string; lines:string[] }
const scenarios: Scenario[] = [
{ id:'excellent-service',title:'Excellent general service',quality:'Excellent',summary:'An agent owns a damaged-item replacement from start to finish.',queue:'Customer Service',topic:'Delivery',channel:'messaging',agent:1,customer:'Noah Wilson',lines:[
'C:My new kettle arrived with a cracked handle and I need it for tomorrow.','A:Hi Noah, I’m Priya. I’m sorry it arrived damaged, especially with your plans tomorrow. I’ll sort out the quickest replacement.','A:Could you confirm the postcode and last four digits of the order number before I open the order?','C:SW6 2AB and 8142.','A:Thank you, that matches. I can see the delivery photo and the order. Would a replacement tomorrow before noon work?','C:Yes, that would be ideal. Do I need to post the broken one?','A:No. For safety, please do not use it. I’ve booked collection when the courier delivers the replacement, at no cost.','C:Perfect. Can you send me the details?','A:Yes. I’ve emailed confirmation and tracking reference EX-8142. If the courier misses the noon window, reply to that email and I’ll arrange another option. Anything else I can do?','C:No, that covers everything. Thank you.','A:You’re welcome, Noah. I’m glad we could get this resolved.' ]},
{ id:'mediocre-service',title:'Mediocre service',quality:'Mixed',summary:'Correct information, but little ownership or clarity.',queue:'Customer Service',topic:'Delivery',channel:'messaging',agent:2,customer:'Leah Evans',lines:[
'C:My parcel says delivered but I cannot find it.','A:Hello. Give me your order number.','C:It is 47620.','A:Please confirm your postcode first.','C:LS1 4DL.','A:The tracking shows it was left with a neighbour yesterday.','C:Which neighbour? I have asked next door and they do not have it.','A:The courier record does not say. You can wait 24 hours and check again.','C:Can you contact the courier?','A:I can log a query, but someone else will look at it.','C:When will I hear?','A:Usually a few days. Check your email. Goodbye.' ]},
{ id:'poor-service',title:'Clearly poor service',quality:'Poor',summary:'The agent dismisses an incorrect charge and ends the chat.',queue:'Customer Service',topic:'Billing',channel:'messaging',agent:4,customer:'Owen Miller',lines:[
'C:You charged me £46 after I cancelled my trial.','A:What is your account email?','C:owen@example.test.','A:It says you have a bill, so you must owe it.','C:I have a cancellation confirmation dated last week.','A:Our system is usually right. You probably cancelled late.','C:Can you check the date on the confirmation?','A:I cannot do that here. Try again later.','C:Please tell me who can help.','A:Look on the website. This chat is closed.' ]},
{ id:'billing-dispute',title:'Billing dispute',quality:'Mixed',summary:'A disputed fee receives a clear investigation path.',queue:'Billing',topic:'Billing',channel:'voice',agent:0,customer:'Amira Khan',lines:[
'C:I do not recognise the £18 service fee on my bill.','A:Good morning, Amira. I’m Alex. I can investigate that with you. First, please confirm your billing postcode and the last two digits of your account number.','C:E3 4JW and 29.','A:Thank you. The fee was applied after a plan change on the 12th. I can see the notice was sent two days later, which is a concern.','C:I never agreed to an extra fee.','A:I understand. I’m raising a dispute now and putting collection of that £18 on hold while we review the recording.','C:When will I get an answer?','A:Within three working days by email. Your reference is BD-729. If we charged it incorrectly, we’ll remove it.','C:All right.','A:Thank you for raising it. Is there anything else on the bill you’d like me to check?' ]},
{ id:'complaint',title:'Formal complaint',quality:'Good',summary:'The agent acknowledges impact and records a complaint.',queue:'Complaints',topic:'Complaint',channel:'voice',agent:3,customer:'Grace Roberts',lines:[
'C:This is the third time I have called about the same outage. I want to make a complaint.','A:I’m Sam. I’m sorry you’ve had to chase this repeatedly. I’ll register a formal complaint and look at what happened.','A:Before opening the account, could you verify the address and last four digits of your phone number?','C:17 Birch Road, 3018.','A:Thanks. I can see two earlier contacts and an engineer visit that was cancelled without notice.','C:I took a day off work for that.','A:That is understandably frustrating. I’ve recorded the missed appointment and your lost time. I can book a priority visit for Thursday and ask the complaints team to review compensation.','C:How do I know someone will call?','A:Your complaint reference is CP-413. You’ll get a text today and a case owner will call by Friday. I’ll include the earlier contact history.','C:Thank you for taking it seriously.','A:You’re welcome. I’m sorry again for the disruption.' ]},
{ id:'cancellation',title:'Respectful cancellation',quality:'Good',summary:'A clear cancellation without pressure.',queue:'Retention',topic:'Cancellation',channel:'messaging',agent:1,customer:'Ben Harris',lines:[
'C:I want to cancel my monthly plan.','A:Hi Ben, I can help. May I ask what prompted the decision, or would you prefer to go straight to cancellation?','C:I am moving abroad. Please cancel it.','A:Understood. Before changing the account, please confirm your postcode and the last four digits of the registered phone.','C:BN2 8RT and 6204.','A:Thank you. Your plan renews on 15 October. I can cancel now so it ends then, with no further renewal.','C:Yes, do that.','A:Done. Confirmation CA-6204 has been emailed. Your service stays active until 15 October and there is no cancellation fee.','C:Great, thanks.','A:You’re welcome. Safe travels.' ]},
{ id:'retention-attempt',title:'Retention attempt',quality:'Mixed',summary:'A relevant offer, but the agent pushes after refusal.',queue:'Retention',topic:'Cancellation',channel:'voice',agent:2,customer:'Iris Chen',lines:[
'C:I would like to cancel because the monthly price has gone up.','A:I’m Jordan. I can review your options. Could you verify your postcode and account suffix?','C:W2 5DA, 4419.','A:Thank you. I can offer a three-month £10 discount, after which the usual rate returns.','C:I appreciate that, but I still want to cancel.','A:Are you sure? This discount is excellent and you might regret it.','C:Yes. Please cancel.','A:All right. It will end on 30 October. I will send the confirmation today.','C:Can you give me a reference?','A:CN-4419. Goodbye.' ]},
{ id:'verification-success',title:'Verification success',quality:'Excellent',summary:'Secure checks precede account disclosure.',queue:'Customer Service',topic:'Security',channel:'messaging',agent:0,customer:'Dylan Foster',tag:'verification',lines:[
'C:I need to change the email address on my account.','A:Hi Dylan, Alex here. I can help protect and update your account.','A:Before I access your details, please confirm your postcode and the last four digits of the registered mobile. Please do not send a password.','C:SE10 9AF and 5076.','A:Thank you. Those match. I can see the current email ends in example.test. What new address would you like?','C:dylan.new@example.test.','A:I have started the change. For security, a confirmation link has been sent to your old address. The new address will take effect only after you approve it.','C:What if I no longer have the old address?','A:Use the secure account recovery link I’m sending now; our team can complete an additional identity check. Your case reference is SC-5076.','C:That is clear, thanks.','A:You’re welcome. Please let us know if you need help with the recovery step.' ]},
{ id:'verification-failure',title:'Verification failure',quality:'Poor',summary:'Account information is revealed after a failed check.',queue:'Customer Service',topic:'Security',channel:'messaging',agent:4,customer:'Avery Scott',tag:'verification',lines:[
'C:I cannot access my account. Can you tell me what address is on it?','A:What are the last four digits of the registered phone?','C:I think 9921.','A:That does not match. Maybe you changed it.','C:Can you at least tell me which email is registered?','A:It is avery.scott@example.test, and the billing address is 14 Park Street.','C:Yes, that sounds right. Can you reset the password?','A:I will send a reset link to that email.','C:Thank you.','A:Done. Goodbye.' ]},
{ id:'repeat-contact',title:'Repeat contact',quality:'Good',summary:'The agent uses prior case history to avoid repetition.',queue:'Customer Service',topic:'Delivery',channel:'voice',agent:3,customer:'Harper Green',tag:'repeat',lines:[
'C:I called twice about the missing package. I do not want to explain it all again.','A:I’m Sam. I’m sorry you have had to repeat yourself. Please verify your postcode and order suffix so I can look at the earlier notes.','C:M1 4PX and 3890.','A:Thank you. I can see the courier trace opened Monday and your call yesterday. The trace expired without an update, which should not have happened.','C:Exactly. I need the item for Saturday.','A:I’ll arrange a replacement on express delivery now and cancel the stalled trace. You will not be charged twice.','C:Will it arrive by Friday?','A:The available slot is Friday before 6 pm. I’ve booked it and sent tracking RP-3890. I’ll check the tracking tomorrow and contact you if it slips.','C:That helps a lot.','A:Thank you for your patience. I’m sorry we missed the first follow-up.' ]},
{ id:'transfer',title:'Transfer and escalation',quality:'Mixed',summary:'A warm handoff follows a technical diagnosis.',queue:'Technical Support',topic:'Technical',channel:'voice',agent:5,customer:'Elliot Moore',lines:[
'C:My router keeps disconnecting every hour.','A:Hi Elliot, I’m Taylor. I’ll check the line before we decide on next steps. Please confirm your postcode and account suffix.','C:NG1 6FG and 7731.','A:Verified. The line test shows intermittent signal loss, so restarting the router alone will not fix it.','C:I have already restarted it six times.','A:Understood. I need to transfer you to our network team for an engineer appointment. I’ll share the test result and your restart history so you do not repeat it.','C:How long is the wait?','A:About five minutes. Your reference is NT-7731. If the call drops, quote that number.','C:Okay, please transfer me.','A:I’m connecting you now. Thank you for your patience.' ]},
{ id:'vulnerable-customer',title:'Vulnerable customer',quality:'Excellent',summary:'The agent adapts pace and offers accessible follow-up.',queue:'Billing',topic:'Billing',channel:'voice',agent:1,customer:'Ruth Bennett',tag:'vulnerable',lines:[
'C:I am confused by this bill. I have trouble reading small print and I am worried the power will be cut off.','A:I’m Priya. I’m sorry this is worrying you. We can go slowly, and I can send a large-print copy if that helps.','A:First, please confirm your postcode and the last four digits of your account number so I can discuss the bill safely.','C:OX1 3PB and 2668.','A:Thank you. Your account is not scheduled for disconnection. The higher amount is from an estimated reading.','C:I cannot pay it all this week.','A:We can review the estimate and discuss an affordable payment plan. Would you like me to explain each option one at a time?','C:Yes, please.','A:I’ve requested a revised bill using the reading you gave and paused the overdue reminder for seven days. I’ll send a large-print summary and call you on Tuesday if you agree.','C:That would be very helpful.','A:Of course. Your reference is VB-2668. Please call us sooner if anything changes.' ]},
{ id:'incomplete-resolution',title:'Incomplete resolution',quality:'Mixed',summary:'Good investigation, but no concrete next step.',queue:'Technical Support',topic:'Technical',channel:'messaging',agent:2,customer:'Theo Martin',lines:[
'C:The app crashes when I try to download invoices.','A:Hi Theo, Jordan here. I can investigate. What phone and app version are you using?','C:Android 15, app version 8.4.','A:Thanks. Does it crash on every invoice or just one?','C:Every invoice since June.','A:I reproduced the issue on a test account. It appears to be a current bug.','C:Can you email the invoices meanwhile?','A:I cannot from this chat. Our product team is looking into it.','C:When should I expect a fix or workaround?','A:I do not have a date. Please keep checking the app.','C:All right.','A:Thanks for reporting it.' ]},
{ id:'empathy-process-gap',title:'Empathy, process gap',quality:'Mixed',summary:'Warm support with account disclosure before verification.',queue:'Customer Service',topic:'Billing',channel:'messaging',agent:3,customer:'Nina Ahmed',lines:[
'C:I lost my job and I am frightened by the overdue bill.','A:I’m Sam. I’m very sorry you are dealing with this. We will take it one step at a time.','C:Thank you. What do I owe?','A:Your account shows £142 overdue and your next payment is due Friday. We can discuss support options.','C:Can we set up smaller payments?','A:Absolutely. I want to help you find something manageable. Could you first confirm your postcode and account suffix?','C:EH3 7DW and 1150.','A:Thank you. I can arrange three payments of £48, but let me know if that is still too much.','C:That could work.','A:I’ll send the arrangement in writing and a link to our hardship support team. You can change it if your situation changes.','C:I appreciate your kindness.','A:You’re welcome, Nina. Please reach out any time.' ]},
{ id:'correct-poor-experience',title:'Correct but cold',quality:'Mixed',summary:'Technically correct answers delivered curtly.',queue:'Customer Service',topic:'Returns',channel:'messaging',agent:4,customer:'Milo Reed',lines:[
'C:Can I return shoes I bought last week? They hurt my feet.','A:Order number?','C:78931.','A:Postcode?','C:CF10 1EP.','A:Verified. Returns are allowed within 30 days if unworn outside.','C:I tried them on indoors. Is that okay?','A:Yes. Use the returns page and print the label.','C:I do not have a printer. Is there another way?','A:Choose the QR code option. It is on the page.','C:Which page?','A:The returns page. Goodbye.' ]},
{ id:'compliant-unresolved',title:'Compliant but unresolved',quality:'Mixed',summary:'Careful identity checks but no ownership of the issue.',queue:'Customer Service',topic:'Billing',channel:'voice',agent:5,customer:'Freya Lewis',lines:[
'C:There is a charge I do not recognise.','A:Hello, I’m Taylor. Before opening the account, please confirm your postcode and account suffix.','C:BS1 8QL and 9092.','A:Thank you. For security, please do not share card details. I can see a £24 fee from Monday.','C:What is the fee for?','A:The label says service adjustment. I do not have more detail.','C:Can you find out or raise a dispute?','A:Only the billing team can explain it. You would need to call them tomorrow.','C:Can you transfer me or give me a reference?','A:No, not from this queue. Their phone number is on the website.','C:That is frustrating.','A:I understand. Goodbye.' ]},
{ id:'sales-service',title:'Needs-led sales',quality:'Excellent',summary:'A recommendation linked to stated needs and clear terms.',queue:'Sales',topic:'Sales',channel:'voice',agent:0,customer:'Jules Parker',direction:'inbound',lines:[
'C:I need a mobile plan for my daughter, mostly messages and occasional video calls.','A:Hi Jules, I’m Alex. I can help compare options. What monthly budget are you aiming for?','C:Around £15. I do not want a long contract.','A:Understood. Is coverage or data allowance more important?','C:Coverage. She travels to school by train.','A:Our monthly rolling plan is £14 for 12 GB. It uses the same network as our larger plans, so coverage is identical. There is no fixed term, but the price can change with 30 days notice.','C:Can she use it abroad?','A:Roaming is not included. You can buy a travel add-on if needed. Would you like a coverage check for the train route before deciding?','C:Yes, please.','A:I’ll send the coverage map and full terms by email. No order has been placed. You can decide after reviewing them.','C:That sounds fair.','A:Thank you. Reply to the email if you have questions.' ]},
]
function make(s: Scenario, index: number): Conversation {
  const start = new Date(Date.UTC(2026,8,1+index,9+(index%5),0))
  return { conversationId:`syn-${s.id}`, startedAt:start.toISOString(), channel:s.channel, agent:agents[s.agent], customer:{id:`customer-${index+3}`,name:s.customer}, metadata:{queue:s.queue,topic:s.topic,status:'Closed',direction:s.direction ?? 'inbound',tags:s.tag ?? '',synthetic:'true'}, messages:s.lines.map((line,i) => ({id:`msg-${i+1}`,timestamp:new Date(start.getTime()+i*45000).toISOString(),speaker:line.startsWith('A:')?'agent':'customer',text:line.slice(2)})) }
}
export const sampleLibrary: SampleEntry[] = [
  {conversation:{...billing,metadata:{...billing.metadata,direction:'inbound',tags:'',synthetic:'true'}} as Conversation,title:'Duplicate payment',quality:'Good',summary:'A duplicate charge is refunded with a clear timeline.'},
  {conversation:{...delivery,metadata:{...delivery.metadata,direction:'inbound',tags:'',synthetic:'true'}} as Conversation,title:'Delayed delivery',quality:'Mixed',summary:'A delayed parcel needs follow-up.'},
  ...scenarios.map((s,i) => ({conversation:make(s,i),title:s.title,quality:s.quality,summary:s.summary}))
]
