import { afterEach, describe, expect, it, vi } from 'vitest'
import { ConversationCache, identityScope, MAX_SEARCHES, MAX_TRANSCRIPTS, MemoryCacheBackend, queryKey, SEARCH_TTL, TRANSCRIPT_TTL } from './conversationCache'
import { CachedGenesysSource, clearGenesysCache } from './cachedSource'
import { completeCallback, disconnect, getSession, type AuthSession } from './genesysAuth'
import { sampleLibrary } from './conversations'
import type { Conversation, ConversationSource } from './types'
const query={from:'2026-09-28T00:00:00Z',to:'2026-09-29T00:00:00Z',page:1,pageSize:10}
const conversation:Conversation={...structuredClone(sampleLibrary[0].conversation),conversationId:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',metadata:{source:'genesys-cloud',status:'Completed',queue:'Support',token:'DO-NOT-STORE',signedUrl:'https://signed.example'}}
const page={conversations:[conversation],page:1,pageSize:10,total:1,hasMore:false}
const session=():AuthSession=>({region:'eu-west-1',clientId:'public-client',userId:'user-a',organizationId:'org-a',accessToken:'DO-NOT-STORE',expiresAt:Date.now()+3600_000})
function fixture(){let now=Date.now();const backend=new MemoryCacheBackend(),cache=new ConversationCache(backend,()=>now);const current=session();const source:ConversationSource={id:'genesys-cloud',name:'Genesys',realData:true,capabilities:{pagination:true,filters:[]},status:async()=>({state:'connected',userId:'user-a'}),list:vi.fn(async()=>page),load:vi.fn(async()=>conversation)};const wrapper=new CachedGenesysSource(source,()=>current,cache);return {backend,cache,current,source,wrapper,advance:(n:number)=>{now+=n}}}
afterEach(()=>vi.unstubAllGlobals())
describe('scoped normalized conversation cache',()=>{
  it('has stable keys across property order, optional empty filters and equivalent dates',()=>{expect(queryKey(query)).toBe(queryKey({pageSize:10,page:1,to:'2026-09-29T00:00:00.000Z',from:'2026-09-28T01:00:00+01:00',queue:''}));expect(queryKey({...query,page:2})).not.toBe(queryKey(query))})
  it('separates user, region, client and organization without putting the token in scope',()=>{const a=session(),scope=identityScope(a)!;expect(scope).not.toContain(a.accessToken);for(const override of [{userId:'user-b'},{region:'us-east-1' as const},{clientId:'other-client'},{organizationId:'org-b'}])expect(identityScope({...a,...override})).not.toBe(scope);expect(identityScope({...a,userId:undefined})).toBeNull();expect(identityScope({...a,expiresAt:Date.now()})).toBeNull()})
  it('saves normalized metadata snapshots and reports TTL freshness/staleness',async()=>{const f=fixture();await f.cache.saveSearch('a',query,page);const hit=await f.cache.search('a',query);expect(hit?.value.total).toBe(1);expect(hit?.value.hasMore).toBe(false);expect(hit?.value.conversations[0].messages).toEqual([]);expect(hit?.stale).toBe(false);f.advance(SEARCH_TTL);expect((await f.cache.search('a',query))?.stale).toBe(true);expect(await f.cache.search('b',query)).toBeNull();expect(JSON.stringify(await f.backend.all())).not.toContain('DO-NOT-STORE');expect(JSON.stringify(await f.backend.all())).not.toContain('signed.example')})
  it('saves only normalized completed transcripts and isolates scopes',async()=>{const f=fixture();await f.cache.saveTranscript('a',conversation);expect((await f.cache.transcript('a',conversation.conversationId))?.value.messages).toEqual(conversation.messages);expect(await f.cache.transcript('b',conversation.conversationId)).toBeNull();f.advance(TRANSCRIPT_TTL);expect((await f.cache.transcript('a',conversation.conversationId))?.stale).toBe(true);await f.cache.saveTranscript('a',{...conversation,conversationId:'incomplete',metadata:{status:'In progress'}});expect(await f.cache.transcript('a','incomplete')).toBeNull()})
  it('bounds searches and transcripts by oldest-first eviction',async()=>{const f=fixture();for(let n=0;n<MAX_SEARCHES+2;n++){f.advance(1);await f.cache.saveSearch('a',{...query,page:n+1},page)}expect((await f.cache.stats('a')).searches).toBe(MAX_SEARCHES);expect(await f.cache.search('a',query)).toBeNull();for(let n=0;n<MAX_TRANSCRIPTS+2;n++){f.advance(1);await f.cache.saveTranscript('a',{...conversation,conversationId:`c${n}`})}expect((await f.cache.stats('a')).transcripts).toBe(MAX_TRANSCRIPTS);expect(await f.cache.transcript('a','c0')).toBeNull()})
  it('clears one identity without deleting another and supports explicit clear-all',async()=>{const f=fixture();await f.cache.saveSearch('a',query,page);await f.cache.saveTranscript('b',conversation);await f.cache.clear('a');expect((await f.cache.stats('a')).searches).toBe(0);expect((await f.cache.stats('b')).transcripts).toBe(1);await f.cache.clear();expect((await f.cache.stats()).transcripts).toBe(0)})
  it('falls back to memory when IndexedDB is unavailable',async()=>{const cache=new ConversationCache();await cache.saveSearch('a',query,page);await cache.saveTranscript('a',conversation);expect((await cache.search('a',query))?.value.total).toBe(1);expect((await cache.stats('a')).transcripts).toBe(1);await cache.clear();expect(await cache.search('a',query)).toBeNull()})
  it('cache hits avoid repeated provider calls and explicit refresh bypasses both caches',async()=>{const f=fixture();await f.wrapper.list(query);await f.wrapper.list(query);expect(f.source.list).toHaveBeenCalledTimes(1);await f.wrapper.list(query,true);expect(f.source.list).toHaveBeenCalledTimes(2);await f.wrapper.load(conversation.conversationId);await f.wrapper.load(conversation.conversationId);expect(f.wrapper.lastTranscript?.cached).toBe(true);expect(f.source.load).toHaveBeenCalledTimes(1);await f.wrapper.load(conversation.conversationId,true);expect(f.source.load).toHaveBeenCalledTimes(2)})
  it('serves stale search snapshots without silent refresh but reloads expired transcripts',async()=>{const f=fixture();await f.wrapper.list(query);await f.wrapper.load(conversation.conversationId);f.advance(TRANSCRIPT_TTL);await f.wrapper.list(query);expect(f.wrapper.lastSearch?.stale).toBe(true);expect(f.source.list).toHaveBeenCalledTimes(1);await f.wrapper.load(conversation.conversationId);expect(f.source.load).toHaveBeenCalledTimes(2)})
  it('requires an active session even when data is cached',async()=>{const f=fixture();await f.wrapper.load(conversation.conversationId);f.current.expiresAt=Date.now();await expect(f.wrapper.load(conversation.conversationId)).rejects.toThrow('Connect');expect(f.source.load).toHaveBeenCalledTimes(1)})
  it('rejects in-flight loads after a session change or explicit clear',async()=>{const f=fixture();let done!:(value:Conversation)=>void;vi.mocked(f.source.load).mockImplementation(()=>new Promise(resolve=>{done=resolve}));const pending=f.wrapper.load(conversation.conversationId);await vi.waitFor(()=>expect(done).toBeDefined());await clearGenesysCache();done(conversation);await expect(pending).rejects.toThrow('changed');expect((await f.cache.stats()).transcripts).toBe(0)})
  it('shares fresh bounded candidate metadata for Form Test sampling',async()=>{const f=fixture();await f.wrapper.list(query);expect((await f.wrapper.recentCandidates())?.query).toEqual(query);expect((await f.wrapper.recentCandidates())?.value.conversations[0].messages).toEqual([]);f.advance(SEARCH_TTL);expect(await f.wrapper.recentCandidates()).toBeNull()})
  it('disconnect drops the session and clears the identity cache',async()=>{const values=new Map<string,string>();const storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)};vi.stubGlobal('sessionStorage',storage);vi.stubGlobal('history',{replaceState:()=>{}});values.set('genesys-aqm-pkce-transaction',JSON.stringify({region:'eu-west-1',clientId:'public-client',verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'conversations'}));vi.stubGlobal('fetch',vi.fn(async(url)=>new Response(JSON.stringify(String(url).includes('/users/me')?{id:'user-a'}:{access_token:'DO-NOT-STORE',token_type:'Bearer',expires_in:3600}))));await completeCallback(new URL(`https://example.com/?code=abc&state=${'A'.repeat(43)}`));const {conversationCache}=await import('./conversationCache');const scope=identityScope(getSession())!;await conversationCache.saveTranscript(scope,conversation);disconnect();await vi.waitFor(async()=>expect((await conversationCache.stats(scope)).transcripts).toBe(0));expect(getSession()).toBeNull()})
})
