import { describe, expect, it } from 'vitest'
import { seedForms } from './forms'
import { formStatus, isOperationalForm, markSourceReviewed, nextFormVersion, productionReadinessErrors, sameDefinition, sourceReviewRequired, sourceReviewRequiredMessage, transitionForm, validatePolicyFormPins } from './formLifecycle'
import type { InteractionPolicy } from './types'
const now='2026-09-30T12:00:00.000Z'
describe('form lifecycle',()=>{
  it('compares Firestore map content independently of key order while preserving question order',()=>{const form=seedForms.at(-1)!;const reordered={...form,scoring:{criticalQuestionIds:form.scoring.criticalQuestionIds,passScore:form.scoring.passScore,yesThreshold:form.scoring.yesThreshold},questions:form.questions.map(q=>Object.fromEntries(Object.entries(q).reverse()) as unknown as typeof q)};expect(sameDefinition(form,reordered)).toBe(true);expect(sameDefinition(form,{...reordered,questions:[...reordered.questions].reverse()})).toBe(false)})

  it('native drafts need no source review and publish after ordinary validation',()=>{const native=nextFormVersion(seedForms[0],seedForms,now);expect(native.origin).toBeUndefined();expect(native.sourceReview).toBeUndefined();expect(native.enabled).toBe(false);expect(sourceReviewRequired(native)).toBe(false);expect(productionReadinessErrors(native)).toEqual([]);expect(isOperationalForm(native)).toBe(false);expect(isOperationalForm(transitionForm(native,'PUBLISHED',now))).toBe(true)})
  it('review acknowledges AQM use while preserving every source question and scoring value',()=>{const form=seedForms.at(-1)!;expect(sourceReviewRequired(form)).toBe(true);const reviewed=markSourceReviewed(form,now);expect(reviewed).toMatchObject({origin:form.origin,sourceFormId:form.sourceFormId,questions:form.questions,scoring:form.scoring,sourceReview:{status:'REVIEWED',reviewedAt:now}});const published=transitionForm(reviewed,'PUBLISHED',now);expect(isOperationalForm(published)).toBe(true);const policy:InteractionPolicy={id:'p',name:'P',description:'',enabled:true,criteria:{anyOf:[]},evaluationFormIds:[form.id]};expect(validatePolicyFormPins(policy,[published])).toEqual([]);expect(sourceReviewRequired(nextFormVersion(published,[published],now))).toBe(true)})
  it('enabled unsupported semantics and conditional execution block production after review',()=>{const form=markSourceReviewed(seedForms.at(-1)!,now);const conditional={...form,questions:form.questions.map((q,i)=>i===0?{...q,condition:{kind:'question_outcome' as const,questionId:'agent_name',outcomes:['yes']}}:q)};expect(()=>transitionForm(conditional,'PUBLISHED',now)).toThrow('Conditional');const unsupported={...form,questions:form.questions.map((q,i)=>i===0?{...q,type:'multi-select' as typeof q.type}:q)};expect(()=>transitionForm(unsupported,'PUBLISHED',now)).toThrow('unsupported')})

  it('locks legacy published definitions behind new version IDs',()=>{const published=seedForms[0];expect(formStatus(published)).toBe('PUBLISHED');const draft=nextFormVersion(published,[published],now);expect(draft.id).toBe(`${published.id}_v2`);expect(draft.version).toBe(2);expect(draft.status).toBe('DRAFT');expect(draft.enabled).toBe(false);const testing=transitionForm(draft,'TESTING',now);const version=transitionForm(testing,'PUBLISHED',now);expect(version.enabled).toBe(true);expect(()=>transitionForm(version,'DRAFT',now)).toThrow();expect(transitionForm(version,'RETIRED',now).enabled).toBe(false)})
  it('requires an explicit published version in policies',()=>{const draft=nextFormVersion(seedForms[0],[seedForms[0]],now);const policy:InteractionPolicy={id:'p',name:'P',description:'',enabled:true,criteria:{anyOf:[]},evaluationFormIds:[draft.id]};expect(validatePolicyFormPins(policy,[seedForms[0],draft])).toContain(`Assigned form ${draft.id} must be published and enabled.`)})
  it('requires explicit publication after reviewing a legacy enabled recreation',()=>{const legacy={...seedForms.at(-1)!,enabled:true};expect(formStatus(legacy)).toBe('DRAFT');const reviewed=markSourceReviewed(legacy,now);expect(reviewed.status).toBe('DRAFT');expect(reviewed.enabled).toBe(false);expect(isOperationalForm(reviewed)).toBe(false);expect(isOperationalForm(transitionForm(reviewed,'PUBLISHED',now))).toBe(true)})
  it('keeps a photographed recreation in review',()=>{const recreated={...seedForms[0],origin:'genesys-recreated' as const,status:'DRAFT' as const};expect(()=>transitionForm(recreated,'PUBLISHED',now)).toThrow('Review required')})
  it('blocks a legacy recreated form from policy assignment and treats their never-operational legacy state as draft',()=>{const recreated={...seedForms[0],origin:'genesys-recreated' as const,status:undefined,enabled:true};const policy:InteractionPolicy={id:'p',name:'P',description:'',enabled:true,criteria:{anyOf:[]},evaluationFormIds:[recreated.id]};expect(formStatus(recreated)).toBe('DRAFT');expect(validatePolicyFormPins(policy,[recreated])).toEqual([`Assigned form ${recreated.id}: ${sourceReviewRequiredMessage}`])})
})
