import { describe, expect, it, vi } from 'vitest'
import { conditionApplies, effectiveQuestions, evaluateForm, formGroups, materializeGroups, maximumEvaluationWaves, questionsInGroup, validateComposition } from './formComposition'
import { nextFormVersion, sameDefinition } from './formLifecycle'
import { genesysCustomerServiceForm } from './genesysForm'
import { sampleLibrary } from './conversations'
import { fixtureEvaluation } from '../fixtures/evaluationFixture'
import { recordEvaluation, parseHistory } from './evaluations'
import { buildReview } from './reviews'
import { aggregateCalibration } from './calibration'
import { groupBreakdown, questionBreakdown } from './analytics'
import type { EvaluationForm, EvaluationRequest, FormCondition, QuestionResult, ScorecardItem } from './types'
const now='2026-10-01T12:00:00Z',conversation={...sampleLibrary[0].conversation,channel:'email',metadata:{direction:'inbound',queue:'Customer Service',topic:'Billing'}}
const q=(id:string,condition?:FormCondition):ScorecardItem=>({id,title:id,instructions:`Evaluate ${id}`,type:'noul',options:[],weight:1,enabled:true,condition,groupId:'first'})
const form=(questions:ScorecardItem[]):EvaluationForm=>({id:'test_form',name:'Test form',description:'',version:1,status:'DRAFT',enabled:false,groups:[{id:'first',name:'First'},{id:'second',name:'Second'}],questions,scoring:{yesThreshold:.65,passScore:.7,criticalQuestionIds:[]}})
const when=(id:string):FormCondition=>({kind:'question_outcome',questionId:id,outcomes:['Yes']})
const evaluate=async(f:EvaluationForm)=>{const provider=vi.fn(async (request:EvaluationRequest)=>fixtureEvaluation(request));return {result:await evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:provider}),provider}}
describe('compatible ordered groups',()=>{
  it('derives virtual sections and General without modifying a legacy snapshot',()=>{const legacy=form([q('a'),{...q('b'),section:'Opening'},{...q('c'),section:'Opening'}]);delete legacy.groups;legacy.questions.forEach(q=>delete q.groupId);const original=JSON.stringify(legacy);expect(formGroups(legacy).map(g=>g.name)).toEqual(['General','Opening']);expect(questionsInGroup(legacy,formGroups(legacy)[1]).map(q=>q.id)).toEqual(['b','c']);expect(JSON.stringify(legacy)).toBe(original)})
  it('creates explicit groups only in a new draft version and preserves disabled questions',()=>{const old={...structuredClone(genesysCustomerServiceForm),version:17},copy=JSON.stringify(old);const next=nextFormVersion(old,[old],now);expect(next.version).toBe(18);expect(next.groups!.map(g=>g.name)).toEqual(['Opening','Assisting The Customer','Call Handling Skills','Compliance & Closure']);expect(next.questions.filter(q=>!q.enabled).map(q=>q.id)).toEqual(old.questions.filter(q=>!q.enabled).map(q=>q.id));expect(JSON.stringify(old)).toBe(copy);expect(old.groups).toBeUndefined()})
  it('uses group order then within-group flat question order',()=>{const f=form([{...q('a'),groupId:'second'},q('b'),{...q('c'),groupId:'second'}]);expect(effectiveQuestions(f).map(q=>q.id)).toEqual(['b','a','c']);f.groups!.reverse();expect(effectiveQuestions(f).map(q=>q.id)).toEqual(['a','c','b'])})
  it('materializes ungrouped questions into a sensible explicit General',()=>{const f=form([{...q('a'),groupId:undefined}]);const next=materializeGroups(f);expect(next.groups!.at(-1)!.name).toBe('General');expect(next.questions[0].groupId).toBe(next.groups!.at(-1)!.id);expect(f.questions[0].groupId).toBeUndefined()})
  it('definition equality includes group order, conditions, provenance and membership',()=>{const f=form([q('a')]);for(const next of [{...f,groups:[...f.groups!].reverse()},{...f,groups:[{...f.groups![0],condition:{kind:'interaction_metadata' as const,field:'channel' as const,equals:'email'}},f.groups![1]]},{...f,questions:[{...f.questions[0],groupId:'second'}]},{...f,groups:[{...f.groups![0],sourceAsset:{familyId:'asset',assetId:'asset',assetVersion:1}},f.groups![1]]}])expect(sameDefinition(f,next)).toBe(false)})
  it('rejects missing membership and duplicate group/question IDs',()=>{const f=form([q('a'),q('a')]);f.questions[0].groupId='missing';f.groups!.push(f.groups![0]);expect(validateComposition(f).join(' ')).toMatch(/unique.*unique.*does not exist/)})
})
describe('conditions and deterministic waves',()=>{
  it.each(['channel','queue','direction','topic'] as const)('evaluates static %s equals/in conditions',async field=>{const value=field==='channel'?conversation.channel:conversation.metadata[field];for(const operator of ['equals','in'] as const){const f=form([q('a',{kind:'interaction_metadata',field,operator,values:operator==='in'?[value,'other']:[value]})]);expect((await evaluate(f)).provider).toHaveBeenCalledTimes(1);f.questions[0].condition={kind:'interaction_metadata',field,equals:'no-match'};const skipped=await evaluate(f);expect(skipped.provider).not.toHaveBeenCalled();expect(skipped.result.questions[0]).toMatchObject({status:'SKIPPED',skipReason:'question_condition_false'});expect(skipped.result.providerRequestCount).toBe(0)}})
  it('keeps unconditional evaluation in one batched request',async()=>{const f=form([q('a'),q('b'),{...q('c'),enabled:false}]);const {result,provider}=await evaluate(f);expect(provider).toHaveBeenCalledTimes(1);expect(provider.mock.calls[0][0].scorecard.items.map((q:ScorecardItem)=>q.id)).toEqual(['a','b']);expect(result.questions[2]).toMatchObject({status:'SKIPPED',skipReason:'disabled'});expect(maximumEvaluationWaves(f)).toBe(1)})
  it('batches multiple ready dependents and executes three levels',async()=>{const f=form([q('a'),q('b',when('a')),q('c',when('a')),q('d',when('b'))]);const {result,provider}=await evaluate(f);expect(provider.mock.calls.map(([request])=>request.scorecard.items.map((q:ScorecardItem)=>q.id))).toEqual([['a'],['b','c'],['d']]);expect(result.providerRequestCount).toBe(3);expect(maximumEvaluationWaves(f)).toBe(3)})
  it('uses normalized Noul No outcomes and skips descendants without sending them',async()=>{const f=form([q('a'),q('b',{kind:'question_outcome',questionId:'a',operator:'equals',outcomes:['No']}),q('c',when('b'))]);const {result,provider}=await evaluate(f);expect(provider).toHaveBeenCalledTimes(1);expect(result.questions.slice(1).every(q=>q.status==='SKIPPED')).toBe(true);expect(maximumEvaluationWaves(f)).toBe(3)})
  it('matches Choice option keys, not labels',async()=>{const f=form([{...q('a'),type:'choice',options:[{key:'billing',label:'Billing question',description:'Bill',credit:1},{key:'other',label:'Other',description:'Other',credit:0}]},q('b',{kind:'question_outcome',questionId:'a',outcomes:['billing']})]);expect((await evaluate(f)).provider).toHaveBeenCalledTimes(2);f.questions[1].condition={kind:'question_outcome',questionId:'a',outcomes:['Billing question']};expect(validateComposition(f).join(' ')).toContain('option keys')})
  it.each([{operator:'less_than' as const,value:.67,expected:false},{operator:'greater_than_or_equal' as const,value:1,expected:true}])('uses prior normalized credit $operator',async({operator,value,expected})=>{const f=form([q('a'),q('b',{kind:'question_credit',questionId:'a',operator,value})]);const {result,provider}=await evaluate(f);expect(provider).toHaveBeenCalledTimes(expected?2:1);expect(result.questions[1].status).toBe(expected?'ANSWERED':'SKIPPED')})
  it('makes a condition on an unscored prior result false',()=>{const results=new Map<string,QuestionResult>([['a',{id:'a',title:'a',type:'choice',rawValue:'na',outcome:'N/A',credit:null,weight:1,weightedContribution:null}]]);expect(conditionApplies({kind:'question_credit',questionId:'a',operator:'less_than',value:.67},conversation,results)).toBe(false)})
  it('ANDs group and question conditions and skips all children of false groups',async()=>{const f=form([q('a'),{...q('b',when('a')),groupId:'second'},{...q('c'),groupId:'second'}]);f.groups![1].condition={kind:'question_outcome',questionId:'a',outcomes:['No']};f.scoring.criticalQuestionIds=['b'];f.questions[1].weight=100;const {result,provider}=await evaluate(f);expect(provider).toHaveBeenCalledTimes(1);expect(result.questions.slice(1).every(q=>q.skipReason==='group_condition_false')).toBe(true);expect(result.countedWeight).toBe(1);expect(result.overallScore).toBe(1);expect(result.groups![1]).toMatchObject({status:'SKIPPED',overallScore:null,countedWeight:0});expect(recordEvaluation(conversation,f,result,[]).criticalFailures).toEqual([])})
  it('enables a dependent group in the next wave with individual filtering',async()=>{const f=form([q('a'),{...q('b'),groupId:'second'},{...q('c'),groupId:'second',condition:{kind:'interaction_metadata',field:'channel',equals:'voice'}}]);f.groups![1].condition=when('a');const {result,provider}=await evaluate(f);expect(provider.mock.calls.map(([r])=>r.scorecard.items.map((q:ScorecardItem)=>q.id))).toEqual([['a'],['b']]);expect(result.groups![1]).toMatchObject({status:'APPLICABLE',answered:1,skipped:1,overallScore:1})})
  it.each([{id:'a',ref:'a',error:'earlier'},{id:'a',ref:'b',error:'earlier'},{id:'b',ref:'missing',error:'does not exist'}])('rejects self/forward/missing dependency $id -> $ref before calling a provider',async({id,ref,error})=>{const f=form([q('a'),q('b')]);f.questions.find(q=>q.id===id)!.condition=when(ref);const provider=vi.fn();await expect(evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:provider})).rejects.toThrow(error);expect(provider).not.toHaveBeenCalled()})
  it('rejects cycles and same-group references in group conditions',()=>{const f=form([q('a',when('b')),q('b',when('a'))]);expect(validateComposition(f).join(' ')).toContain('cyclic');const same=form([q('a'),{...q('b'),groupId:'second'}]);same.groups![0].condition=when('a');expect(validateComposition(same).join(' ')).toContain('earlier')})
  it('rejects score/outcome mismatches and invalid credit/operators',()=>{const f=form([{...q('a'),type:'score',options:[{key:'poor',label:'Poor',description:'Poor',credit:0},{key:'good',label:'Good',description:'Good',credit:1}]},q('b',when('a'))]);expect(validateComposition(f).join(' ')).toContain('Score requires');f.questions[1].condition={kind:'question_credit',questionId:'a',operator:'less_than',value:2};expect(validateComposition(f).join(' ')).toContain('between 0 and 1')})
  it('reports actual attempted provider count on wave failure and never retries',async()=>{const f=form([q('a'),q('b',when('a'))]),provider=vi.fn(async (request:EvaluationRequest)=>fixtureEvaluation(request));provider.mockRejectedValueOnce(Error('uncertain'));await expect(evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:provider})).rejects.toMatchObject({providerRequestCount:1});expect(provider).toHaveBeenCalledTimes(1)})
  it('refuses incomplete results from a provider wave',async()=>{const f=form([q('a')]);await expect(evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:async request=>({...fixtureEvaluation(request),questions:[]})})).rejects.toThrow('incomplete')})
})
describe('historical review, analytics and scoring compatibility',()=>{
  it('keeps historical results with no status interpretable',async()=>{const f=form([q('a')]),result=fixtureEvaluation({conversation,scorecard:{id:f.id,version:f.version,title:f.name,threshold:.65,items:f.questions},evaluatedAt:now,version:'v0'}),record=recordEvaluation(conversation,f,result,[]);expect(parseHistory(JSON.stringify([record]))).toHaveLength(1);expect(buildReview(record,undefined,{expectedRevision:0,action:'complete',formId:f.id,formVersion:1,answers:[{questionId:'a',value:'Yes'}]},{userId:'reviewer'},now).comparison.total).toBe(1)})
  it('does not ask for skipped answers or count them in calibration/pass rates',async()=>{const f=form([q('a'),q('b',{kind:'interaction_metadata',field:'channel',equals:'voice'}),{...q('c'),enabled:false}]);const {result}=await evaluate(f),record={...recordEvaluation(conversation,f,result,[]),conversationSource:'genesys-cloud' as const};const review=buildReview(record,undefined,{expectedRevision:0,action:'complete',formId:f.id,formVersion:1,answers:[{questionId:'a',value:'Yes'}]},{userId:'reviewer'},now);expect(review.questions.find(q=>q.questionId==='b')!.human).toBeNull();expect(review.comparison).toMatchObject({total:1,answered:1,agreements:1});expect(aggregateCalibration([{...record,humanReview:review}]).metrics.questionsReviewed).toBe(1);expect(()=>buildReview(record,undefined,{expectedRevision:0,action:'save',formId:f.id,formVersion:1,answers:[{questionId:'b',value:'No'}]},{userId:'reviewer'},now)).toThrow('Invalid');expect(questionBreakdown([record]).find(q=>q.questionId==='b')).toMatchObject({count:0,skippedCount:1,passRate:null});expect(groupBreakdown([record])[0]).toMatchObject({count:1,applicableCount:1,averageScore:1})})
  it('uses only question weights for overall and group scores',async()=>{const f=form([{...q('a'),weight:2,sourceGroupWeight:999},{...q('b'),weight:1}]);const provider=async(request:import('./types').EvaluationRequest)=>{const output=fixtureEvaluation(request);output.questions[1].credit=0;return output};const result=await evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:provider});expect(result.overallScore).toBeCloseTo(2/3);expect(result.groups![0].overallScore).toBeCloseTo(2/3);expect(result.countedWeight).toBe(3)})
})
