import { describe, expect, it } from 'vitest'
import { seedForms } from './forms'
import { formStatus, isOperationalForm, nextFormVersion, productionReadinessErrors, sameDefinition, transitionForm, validatePolicyFormPins } from './formLifecycle'
import type { InteractionPolicy } from './types'
const now='2026-09-30T12:00:00.000Z'
const policy=(id:string):InteractionPolicy=>({id:'p',name:'P',description:'',enabled:true,criteria:{anyOf:[]},evaluationFormIds:[id]})
describe('form lifecycle',()=>{
  it('compares Firestore map content independently of key order while preserving question order',()=>{const form=seedForms.at(-1)!;const reordered={...form,scoring:{criticalQuestionIds:form.scoring.criticalQuestionIds,passScore:form.scoring.passScore,yesThreshold:form.scoring.yesThreshold},questions:form.questions.map(q=>Object.fromEntries(Object.entries(q).reverse()) as unknown as typeof q)};expect(sameDefinition(form,reordered)).toBe(true);expect(sameDefinition(form,{...reordered,questions:[...reordered.questions].reverse()})).toBe(false)})
  it('native drafts publish after ordinary validation',()=>{const native=nextFormVersion(seedForms[0],seedForms,now);expect(native.origin).toBeUndefined();expect(native.enabled).toBe(false);expect(productionReadinessErrors(native)).toEqual([]);expect(isOperationalForm(native)).toBe(false);expect(isOperationalForm(transitionForm(native,'PUBLISHED',now))).toBe(true)})
  it.each([undefined,{status:'REVIEW_REQUIRED' as const},{status:'REVIEWED' as const,reviewedAt:now}])('publishes recreated forms and pins them with inert legacy metadata %j',sourceReview=>{const form={...seedForms.at(-1)!,status:'DRAFT' as const,enabled:false,sourceReview};const published=transitionForm(form,'PUBLISHED',now);expect(productionReadinessErrors(published)).toEqual([]);expect(isOperationalForm(published)).toBe(true);expect(validatePolicyFormPins(policy(form.id),[published])).toEqual([]);expect(published).toMatchObject({version:1,questions:form.questions,scoring:form.scoring,origin:form.origin,sourceFormId:form.sourceFormId});expect(nextFormVersion(published,[published],now).status).toBe('DRAFT')})
  it('enabled unsupported semantics and conditional execution still block production',()=>{const form={...seedForms.at(-1)!,status:'DRAFT' as const};const conditional={...form,questions:form.questions.map((q,i)=>i===0?{...q,condition:{kind:'question_outcome' as const,questionId:'agent_name',outcomes:['yes']}}:q)};expect(()=>transitionForm(conditional,'PUBLISHED',now)).toThrow('Conditional');const unsupported={...form,questions:form.questions.map((q,i)=>i===0?{...q,type:'multi-select' as typeof q.type}:q)};expect(()=>transitionForm(unsupported,'PUBLISHED',now)).toThrow('unsupported')})
  it('locks legacy published definitions behind new version IDs',()=>{const published=seedForms[0];expect(formStatus(published)).toBe('PUBLISHED');const draft=nextFormVersion(published,[published],now);expect(draft.id).toBe(`${published.id}_v2`);expect(draft.version).toBe(2);expect(draft.status).toBe('DRAFT');expect(draft.enabled).toBe(false);const testing=transitionForm(draft,'TESTING',now);const version=transitionForm(testing,'PUBLISHED',now);expect(version.enabled).toBe(true);expect(()=>transitionForm(version,'DRAFT',now)).toThrow();expect(transitionForm(version,'RETIRED',now).enabled).toBe(false)})
  it('requires an explicit published version in policies',()=>{const draft=nextFormVersion(seedForms[0],[seedForms[0]],now);expect(validatePolicyFormPins(policy(draft.id),[seedForms[0],draft])).toContain(`Assigned form ${draft.id} must be published and enabled.`)})
  it('applies the same legacy enabled lifecycle regardless of provenance',()=>{const recreated={...seedForms[0],origin:'genesys-recreated' as const,status:undefined,enabled:true};expect(formStatus(recreated)).toBe('PUBLISHED');expect(isOperationalForm(recreated)).toBe(true);expect(validatePolicyFormPins(policy(recreated.id),[recreated])).toEqual([])})
})
