import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { beginLogin, authorizationUrl, challenge, cleanCallbackUrl, completeCallback, disconnect, generateState, generateVerifier, getSession, parseCallback, randomUrlSafe, REGIONS } from './genesysAuth'
import { GenesysCloudConversationSource } from './sources'

const values = new Map<string,string>()
const storage = { getItem: (key:string) => values.get(key) ?? null, setItem: (key:string,value:string) => { values.set(key,value) }, removeItem: (key:string) => { values.delete(key) } }
const config = { region: 'eu-west-1' as const, clientId: 'public-client-id' }
const fakeSession = { ...config, accessToken: 'test-token', expiresAt: Date.now()+60_000 }
beforeEach(() => { values.clear(); vi.stubGlobal('sessionStorage', storage); vi.stubGlobal('localStorage', storage); vi.stubGlobal('history', { replaceState: vi.fn() }) })
afterEach(() => { vi.unstubAllGlobals(); disconnect() })
describe('Genesys browser PKCE', () => {
  it('generates valid random verifier and state without Math.random', () => { const math = vi.spyOn(Math,'random').mockImplementation(()=>{throw Error('Math.random used')}); expect(generateVerifier()).toMatch(/^[A-Za-z0-9_-]{86}$/); expect(generateState()).toMatch(/^[A-Za-z0-9_-]{43}$/); expect(randomUrlSafe(32)).not.toBe(randomUrlSafe(32)); math.mockRestore() })
  it('computes the RFC 7636 S256 challenge', async () => { expect(await challenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk')).toBe('E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM') })
  it('uses an allowlisted paired login/API region and authorization parameters', () => { const url = new URL(authorizationUrl(config,'A'.repeat(43),'B'.repeat(43))); expect(url.origin).toBe(REGIONS['eu-west-1'].login); expect(REGIONS['eu-west-1'].api).toBe('https://api.mypurecloud.ie'); expect(url.pathname).toBe('/oauth/authorize'); expect(url.searchParams.get('code_challenge_method')).toBe('S256'); expect(url.searchParams.get('response_type')).toBe('code'); expect(url.searchParams.get('redirect_uri')).toBe('https://simonridd.github.io/Genesys-aqm/'); expect(() => authorizationUrl({region:'evil.com' as never,clientId:'public-client-id'},'A'.repeat(43),'B'.repeat(43))).toThrow() })
  it('parses callbacks, rejects missing or duplicate state, and strips OAuth parameters', () => { const url = new URL('https://simonridd.github.io/Genesys-aqm/?code=abc&state=def&x=1'); expect(parseCallback(url)).toEqual({code:'abc',state:'def'}); expect(cleanCallbackUrl(url)).toBe('/Genesys-aqm/?x=1'); expect(() => parseCallback(new URL('https://example.test/?code=abc'))).toThrow(); expect(() => parseCallback(new URL('https://example.test/?code=a&code=b&state=c'))).toThrow(); expect(() => parseCallback(new URL('https://example.test/?state=c'))).toThrow() })
  it('rejects mismatched state before exchange and clears transaction', async () => { storage.setItem('genesys-aqm-pkce-transaction', JSON.stringify({...config,verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'conversations'})); const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher); await expect(completeCallback(new URL(`https://simonridd.github.io/Genesys-aqm/?code=abc&state=${'B'.repeat(43)}`))).rejects.toThrow('invalid or expired'); expect(fetcher).not.toHaveBeenCalled(); expect(storage.getItem('genesys-aqm-pkce-transaction')).toBeNull(); expect(history.replaceState).toHaveBeenCalled() })
  it('exchanges code without secret, keeps token in memory, and disconnects', async () => { storage.setItem('genesys-aqm-pkce-transaction', JSON.stringify({...config,verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'conversations'})); const fetcher=vi.fn(async()=>new Response(JSON.stringify({access_token:'secret-test-token',token_type:'Bearer',expires_in:3600}),{status:200}));vi.stubGlobal('fetch',fetcher); expect(await completeCallback(new URL(`https://simonridd.github.io/Genesys-aqm/?code=abc&state=${'A'.repeat(43)}`))).toBe('conversations'); expect(getSession()?.accessToken).toBe('secret-test-token'); expect(JSON.stringify([...values])).not.toContain('secret-test-token'); const body=(fetcher.mock.calls as unknown as Array<[unknown, RequestInit]>)[0]![1].body as URLSearchParams;expect(body.get('client_secret')).toBeNull();expect(body.get('code_verifier')).toBe('a'.repeat(43)); disconnect();expect(getSession()).toBeNull() })
  it('expires a short-lived token before API use', async () => { storage.setItem('genesys-aqm-pkce-transaction', JSON.stringify({...config,verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'settings'})); vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({access_token:'test-token',token_type:'Bearer',expires_in:31}),{status:200}))); await completeCallback(new URL(`https://simonridd.github.io/Genesys-aqm/?code=abc&state=${'A'.repeat(43)}`)); const now=Date.now(); const clock=vi.spyOn(Date,'now').mockReturnValue(now+2_000); expect(getSession()).toBeNull(); clock.mockRestore() })
  it('preserves a safe review link through the fixed OAuth redirect',async()=>{const assign=vi.fn();vi.stubGlobal('window',{location:{href:'https://simonridd.github.io/Genesys-aqm/?page=evaluations&evaluationId=review_123',assign}});await beginLogin(config,'settings');expect(assign).toHaveBeenCalled();const t=JSON.parse(storage.getItem('genesys-aqm-pkce-transaction')!);expect(t.evaluationId).toBe('review_123');vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({access_token:'fixture',token_type:'Bearer',expires_in:3600}))));expect(await completeCallback(new URL(`https://simonridd.github.io/Genesys-aqm/?code=abc&state=${t.state}`))).toBe('evaluations');expect(history.replaceState).toHaveBeenLastCalledWith(null,'','/Genesys-aqm/?page=evaluations&evaluationSource=server&evaluationId=review_123')})
  it('rejects an unsafe review reference without changing login navigation',async()=>{storage.setItem('genesys-aqm-pkce-transaction',JSON.stringify({...config,verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'settings',evaluationId:'https://evil.example/'}));vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({access_token:'fixture',token_type:'Bearer',expires_in:3600}))));expect(await completeCallback(new URL(`https://simonridd.github.io/Genesys-aqm/?code=abc&state=${'A'.repeat(43)}`))).toBe('settings')})
  it('rejects missing transaction', async () => { await expect(completeCallback(new URL('https://simonridd.github.io/Genesys-aqm/?code=abc&state=xyz'))).rejects.toThrow('missing') })
})
describe('browser API source', () => {
  it('guides disconnected users without network calls', async () => { const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher); const source=new GenesysCloudConversationSource(()=>null);expect((await source.status()).state).toBe('not-configured');await expect(source.list({from:'2026-09-28T00:00:00Z',to:'2026-09-29T00:00:00Z',page:1,pageSize:10})).rejects.toThrow('Connect');expect(fetcher).not.toHaveBeenCalled() })
  it('injects bearer token and handles 401 without leaking it', async () => { const fetcher=vi.fn(async()=>new Response('',{status:401}));vi.stubGlobal('fetch',fetcher);const source=new GenesysCloudConversationSource(()=>fakeSession);await expect(source.status()).resolves.toMatchObject({state:'error'});expect(new Headers((fetcher.mock.calls as unknown as Array<[unknown, RequestInit]>)[0]![1].headers).get('Authorization')).toBe('Bearer test-token');expect(JSON.stringify(await source.status())).not.toContain('test-token') })
  it('rejects expired sessions', async () => { const source=new GenesysCloudConversationSource(()=>null);await expect(source.load('00000000-0000-0000-0000-000000000000')).rejects.toThrow('Connect') })
})
