import { describe,it,expect } from 'vitest'
import { scoreFormResults,validateComposition,evaluateForm } from './formComposition'
import { recordEvaluation,parseHistory,serializeHistory } from './evaluations'
import { buildReview } from './reviews'
import { aggregateCalibration } from './calibration'
import { groupBreakdown } from './analytics'
import { saveGroupAsset,transitionAsset,insertGroupAsset,updateGroupAsset,nextAssetVersion,assertAssetWrite } from './groupAssets'
import { transitionForm } from './formLifecycle'
import { sampleLibrary } from './conversations'
import type { EvaluationForm,QuestionResult } from './types'
const now='2026-10-01T12:00:00Z',conversation=sampleLibrary[0].conversation
const form=():EvaluationForm=>({id:'f',name:'Form',description:'',version:1,status:'DRAFT',enabled:false,groups:[{id:'opening',name:'Opening',scoring:{weight:10}},{id:'compliance',name:'Compliance',scoring:{weight:40,passScore:.9,critical:true}}],questions:[{id:'a',groupId:'opening',title:'A',instructions:'A?',type:'noul',options:[],weight:9,enabled:true},{id:'b',groupId:'compliance',title:'B',instructions:'B?',type:'noul',options:[],weight:1,enabled:true}],scoring:{mode:'GROUP_WEIGHTED',yesThreshold:.65,passScore:.7,criticalQuestionIds:[]}})
const answers=(a=1,b=.8):QuestionResult[]=>[{id:'a',title:'A',type:'noul',outcome:'Yes',credit:a,weight:9,weightedContribution:a*9,status:'ANSWERED'},{id:'b',title:'B',type:'noul',outcome:'Yes',credit:b,weight:1,weightedContribution:b,status:'ANSWERED'}]
const record=(f=form(),qs=answers())=>{const s=scoreFormResults(f,qs);return recordEvaluation(conversation,f,{...s,questions:qs,conversationId:conversation.conversationId,scorecardId:f.id,scorecardVersion:1,evaluatedAt:now,provider:'fixture',model:'fixture',rawResponse:{}},[],'record')}
describe('advanced group scoring',()=>{
 it('keeps legacy question weighting even with group/source metadata',()=>{const f=form();delete f.scoring.mode;f.questions[0].sourceGroupWeight=999;expect(scoreFormResults(f,answers()).overallScore).toBeCloseTo(.98);expect(scoreFormResults(f,answers()).scoringMode).toBe('QUESTION_WEIGHTED')})
 it('normalizes unequal weights rather than requiring a total of 100',()=>{const s=scoreFormResults(form(),answers());expect(s.overallScore).toBeCloseTo(.84);expect(s.groups.map(g=>g.normalizedWeight)).toEqual([.2,.8]);expect(s.countedWeight).toBe(50)})
 it('supports equal weights independently of question weights',()=>{const f=form();f.groups![1].scoring!.weight=10;expect(scoreFormResults(f,answers()).overallScore).toBeCloseTo(.9)})
 it('excludes null and skipped questions and groups from denominators',()=>{const qs=answers();qs[1].credit=null;qs[1].status='SKIPPED';qs[1].skipReason='group_condition_false';const s=scoreFormResults(form(),qs);expect(s.overallScore).toBe(1);expect(s.groups[1]).toMatchObject({overallScore:null,applicable:false,passed:null,normalizedWeight:0});expect(s.passed).toBe(true)})
 it('marks applicable unscored critical groups as anomalies and fails closed',()=>{const qs=answers();qs[1].credit=null;const s=scoreFormResults(form(),qs);expect(s.scoringAnomalies).toEqual(['compliance']);expect(s.groups[1].overallScore).toBeNull();expect(s.passed).toBe(false)})
 it('keeps an ordinary group threshold failure separate from overall pass',()=>{const f=form();f.groups![1].scoring!.critical=false;const s=scoreFormResults(f,answers());expect(s.groups[1].passed).toBe(false);expect(s.passed).toBe(true)})
 it('passes a critical group at its threshold',()=>{const s=scoreFormResults(form(),answers(1,.9));expect(s.groups[1].passed).toBe(true);expect(s.passed).toBe(true)})
 it('fails critical groups despite high overall score',()=>{const s=scoreFormResults(form(),answers());expect(s.overallScore).toBeGreaterThan(.7);expect(s.criticalGroupFailures).toEqual(['compliance']);expect(s.passed).toBe(false)})
 it('preserves critical question failures alongside critical group failures',()=>{const f=form();f.scoring.criticalQuestionIds=['a'];const s=scoreFormResults(f,answers(0,.8));expect(s.criticalFailures).toEqual(['a']);expect(s.criticalGroupFailures).toEqual(['compliance']);expect(s.passed).toBe(false)})
 it('returns null for entirely unscored noncritical evaluations',()=>{const f=form();f.groups![1].scoring!.critical=false;const qs=answers();qs.forEach(q=>q.credit=null);const s=scoreFormResults(f,qs);expect(s.overallScore).toBeNull();expect(s.passed).toBeNull()})
 it.each([0,-1,NaN,Infinity])('rejects invalid group weight %s before publication',weight=>{const f=form();f.groups![0].scoring!.weight=weight;expect(validateComposition(f).join(' ')).toContain('positive');expect(()=>transitionForm(f,'PUBLISHED',now)).toThrow()})
 it.each([-1,1.01,NaN,Infinity])('rejects invalid group passScore %s',passScore=>{const f=form();f.groups![1].scoring!.passScore=passScore;expect(validateComposition(f).join(' ')).toContain('between 0 and 1')})
 it('rejects missing weights, critical thresholds, and non-scoring weighted definitions',()=>{const f=form();delete f.groups![1].scoring!.passScore;delete f.groups![0].scoring!.weight;expect(validateComposition(f).join(' ')).toMatch(/positive weight.*requires/);f.questions.forEach(q=>q.enabled=false);expect(validateComposition(f).join(' ')).toContain('at least one weighted')})
 it('persists scoring mode, critical failures, question IDs and form snapshot in JSON',()=>{const r=record(),restored=parseHistory(serializeHistory([r]))[0];expect(restored).toEqual(JSON.parse(JSON.stringify(r)));expect(restored.scoringMode).toBe('GROUP_WEIGHTED');expect(restored.groupResults![1].questionIds).toEqual(['b']);expect(restored.criticalGroupFailures).toEqual(['compliance']);expect(restored.form.groups![1].scoring!.weight).toBe(40)})
 it('uses identical human semantics and preserves AI scoring',()=>{const r={...record(form(),answers(1,0)),conversationSource:'genesys-cloud' as const},before=structuredClone(r);const review=buildReview(r,undefined,{formId:'f',formVersion:1,expectedRevision:0,action:'complete',answers:[{questionId:'a',value:'No'},{questionId:'b',value:'Yes'}]},{userId:'operator'},now);expect(review.humanOverallScore).toBe(.8);expect(review.humanGroupResults![1].passed).toBe(true);expect(review.groupComparison![1].difference).toBe(1);expect(r).toEqual(before);const analytics=aggregateCalibration([{...r,humanReview:review}]);expect(analytics.byGroup.find(g=>g.groupId==='compliance')).toMatchObject({reviewed:1,aiAverageCredit:0,humanAverageCredit:1,meanScoreDifference:1});expect(groupBreakdown([r],new Map([[r.id,review]]))[1]).toMatchObject({criticalGroupFailures:1,passRate:0,humanAverageScore:1,meanScoreDifference:1})})
 it('does not mix group results across form versions',()=>{const r=record(),r2={...r,id:'second',form:{...r.form,version:2}};expect(groupBreakdown([r,r2])).toHaveLength(4)})
 it('snapshots reusable scoring and applies updates only on request',()=>{const f=form(),draft=saveGroupAsset(f,'compliance','asset',now),asset=transitionAsset(draft,'PUBLISHED',now),consumer=insertGroupAsset({...f,id:'consumer'},asset,'inserted'),before=structuredClone(consumer),v2=nextAssetVersion(asset,[asset],now);v2.scoring={weight:20,passScore:.8,critical:false};const published=transitionAsset(v2,'PUBLISHED',now);expect(consumer).toEqual(before);expect(()=>assertAssetWrite(asset,{...asset,scoring:v2.scoring})).toThrow('immutable');const updated=updateGroupAsset(consumer,'inserted',published);expect(updated.groups!.find(g=>g.id==='inserted')!.scoring).toEqual(v2.scoring);expect(consumer.groups!.find(g=>g.id==='inserted')!.scoring).toEqual(asset.scoring)})
 it('skips conditional critical groups in provider execution',async()=>{const f=form();f.groups![1].condition={kind:'interaction_metadata',field:'channel',equals:'impossible'};const result=await evaluateForm({form:f,conversation,evaluatedAt:now,evaluateQuestions:async request=>({conversationId:conversation.conversationId,scorecardId:'f',scorecardVersion:1,evaluatedAt:now,provider:'fixture',model:'fixture',questions:answers().filter(q=>request.scorecard.items.some(i=>i.id===q.id)),overallScore:1,countedWeight:9,rawResponse:{}})});expect(result.groups![1].status).toBe('SKIPPED');expect(recordEvaluation(conversation,f,result,[]).passed).toBe(true)})
})
