import { describe, expect, it } from 'vitest'
import { detachGroupAsset, insertGroupAsset, nextAssetVersion, saveGroupAsset, transitionAsset, updateGroupAsset, validateGroupAsset } from './groupAssets'
import { effectiveQuestions } from './formComposition'
import { seedGroupAssets } from './seedGroupAssets'
import { MemoryStore } from '../server/store'
import type { EvaluationForm, QuestionGroupAsset, ScorecardItem } from './types'
const now='2026-10-01T00:00:00Z'
const question=(id:string):ScorecardItem=>({id,title:id,instructions:`Evaluate ${id}`,type:'noul',options:[],weight:1,enabled:true})
const asset=():QuestionGroupAsset=>({id:'asset',familyId:'asset',name:'Identity',description:'Verification',version:1,status:'PUBLISHED',questions:[question('a'),{...question('b'),condition:{kind:'question_outcome',questionId:'a',outcomes:['Yes']}}],createdAt:now,updatedAt:now,publishedAt:now})
const form=():EvaluationForm=>({id:'form',name:'Form',description:'',version:1,status:'DRAFT',enabled:false,groups:[],questions:[],scoring:{yesThreshold:.65,passScore:.7,criticalQuestionIds:[]}})
describe('versioned reusable group snapshots',()=>{
  it('has a small useful starter library derived without mutating original forms',()=>{expect(seedGroupAssets).toHaveLength(4);for(const a of seedGroupAssets)expect(validateGroupAsset(a)).toEqual([])})
  it('creates draft, publishes, versions and retires with immutable published content',async()=>{const store=new MemoryStore(),draft={...asset(),status:'DRAFT' as const};await store.putGroupAsset(draft);expect(await store.groupAsset(draft.id)).toEqual(draft);const published=transitionAsset(draft,'PUBLISHED',now);await store.putGroupAsset(published);await expect(store.putGroupAsset({...published,name:'Changed'})).rejects.toThrow('immutable');await expect(store.putGroupAsset({...published,status:'DRAFT'})).rejects.toThrow('cannot return');const v2=nextAssetVersion(published,[published],now);expect(v2).toMatchObject({id:'asset_v2',version:2,status:'DRAFT'});await store.putGroupAsset(v2);await store.putGroupAsset(transitionAsset(published,'RETIRED',now));expect((await store.groupAsset('asset'))!.status).toBe('RETIRED')})
  it('bounds library reads and paginates without fetching during evaluation',async()=>{const store=new MemoryStore();await store.putGroupAsset(asset());await store.putGroupAsset(nextAssetVersion(asset(),[asset()],now));const first=await store.query<QuestionGroupAsset>('questionGroupAssets',1);expect(first.items).toHaveLength(1);expect(first.nextCursor).toBe('asset');expect((await store.query<QuestionGroupAsset>('questionGroupAssets',1,first.nextCursor)).items[0].id).toBe('asset_v2')})
  it('copies content, namespaces IDs and remaps internal conditions for two instances',()=>{const first=insertGroupAsset(form(),asset(),'one'),second=insertGroupAsset(first,asset(),'two');expect(second.questions.map(q=>q.id)).toEqual(['one__a','one__b','two__a','two__b']);expect(second.questions[3].condition).toMatchObject({questionId:'two__a'});expect(second.groups![0].sourceAsset).toMatchObject({assetVersion:1,familyId:'asset'});const a=asset();const other=insertGroupAsset(form(),a,'other');a.questions[0].instructions='Changed';expect(first.questions[0].instructions).toBe('Evaluate a');expect(other.questions[0].instructions).toBe('Evaluate a')})
  it('rejects collisions and unpublished/retired assets',()=>{const first=insertGroupAsset(form(),asset(),'one');expect(()=>insertGroupAsset(first,asset(),'one')).toThrow('unique');const colliding={...form(),questions:[question('one__a')]};expect(()=>insertGroupAsset(colliding,asset(),'one')).toThrow('collision');for(const status of ['DRAFT','RETIRED'] as const)expect(()=>insertGroupAsset(form(),{...asset(),status},'one')).toThrow('published')})
  it('a new asset version never changes existing consumers, and explicit update keeps matching IDs',()=>{const v1=asset(),f=insertGroupAsset(form(),v1,'instance'),before=JSON.stringify(f),v2={...nextAssetVersion(v1,[v1],now),status:'PUBLISHED' as const,name:'Updated identity',questions:[{...question('a'),instructions:'New verification'},{...question('b'),condition:{kind:'question_outcome' as const,questionId:'a',outcomes:['Yes']}},question('c')]};expect(JSON.stringify(f)).toBe(before);const next=updateGroupAsset(f,'instance',v2);expect(next.groups![0]).toMatchObject({id:'instance',name:'Updated identity',sourceAsset:{assetVersion:2}});expect(next.questions.map(q=>q.id)).toEqual(['instance__a','instance__b','instance__c']);expect(next.questions[1].condition).toMatchObject({questionId:'instance__a'});expect(f.questions).toHaveLength(2);expect(effectiveQuestions(next).map(q=>q.id)).toEqual(['instance__a','instance__b','instance__c'])})
  it('blocks deleting externally referenced questions and incompatible outcome changes',()=>{const f=insertGroupAsset(form(),asset(),'instance');f.groups!.push({id:'later',name:'Later',condition:{kind:'question_outcome',questionId:'instance__a',outcomes:['Yes']}});f.questions.push({...question('external'),groupId:'later'});const v2={...nextAssetVersion(asset(),[asset()],now),status:'PUBLISHED' as const,questions:[question('b')]};expect(()=>updateGroupAsset(f,'instance',v2)).toThrow('disappear');v2.questions=[{...question('a'),type:'choice',options:[{key:'yes',label:'Yes',description:'Yes',credit:1},{key:'no',label:'No',description:'No',credit:0}]}];expect(()=>updateGroupAsset(f,'instance',v2)).toThrow('option keys');expect(f.questions[0].type).toBe('noul')})
  it('removes unused questions safely but protects critical designations',()=>{const f=insertGroupAsset(form(),asset(),'instance'),v2={...nextAssetVersion(asset(),[asset()],now),status:'PUBLISHED' as const,questions:[question('a')]};expect(updateGroupAsset(f,'instance',v2).questions.map(q=>q.id)).toEqual(['instance__a']);f.scoring.criticalQuestionIds=['instance__b'];expect(()=>updateGroupAsset(f,'instance',v2)).toThrow('critical')})
  it('protects dormant external dependencies during asset updates',()=>{const f=insertGroupAsset(form(),asset(),'instance');f.groups!.push({id:'later',name:'Later'});f.questions.push({...question('external'),enabled:false,groupId:'later',condition:{kind:'question_outcome',questionId:'instance__a',outcomes:['Yes']}});const v2={...nextAssetVersion(asset(),[asset()],now),status:'PUBLISHED' as const,questions:[question('b')]};expect(()=>updateGroupAsset(f,'instance',v2)).toThrow('disappear')})
  it('detach preserves the current definition and removes reusable provenance',()=>{const f=insertGroupAsset(form(),asset(),'instance'),next=detachGroupAsset(f,'instance');expect(next.groups![0].sourceAsset).toBeUndefined();expect(next.questions.map(q=>q.id)).toEqual(f.questions.map(q=>q.id));expect(next.questions.every(q=>q.sourceAssetQuestionId===undefined)).toBe(true);expect(next.questions[1].condition).toEqual(f.questions[1].condition);expect(f.groups![0].sourceAsset).toBeDefined()})
  it('saves a new group as draft and customized snapshots as a new asset version',()=>{const f=insertGroupAsset(form(),asset(),'instance');f.questions[0].instructions='Custom';const next=saveGroupAsset(f,'instance','ignored',now,[asset()]);expect(next).toMatchObject({id:'asset_v2',familyId:'asset',version:2,status:'DRAFT'});expect(next.questions[0]).toMatchObject({id:'a',instructions:'Custom'});expect(next.questions[1].condition).toMatchObject({questionId:'a'});expect(next.questions[0].groupId).toBeUndefined();const detached=detachGroupAsset(f,'instance');expect(saveGroupAsset(detached,'instance','fresh',now).status).toBe('DRAFT')})
  it('rejects non-self-contained asset dependencies',()=>{const a=asset();a.questions[1].condition={kind:'question_outcome',questionId:'external',outcomes:['Yes']};expect(validateGroupAsset(a).join(' ')).toContain('does not exist');const f=insertGroupAsset(form(),asset(),'instance');f.questions[1].condition={kind:'question_outcome',questionId:'external',outcomes:['Yes']};expect(()=>saveGroupAsset(f,'instance','new',now)).toThrow('outside')})
  it('preserves interaction group conditions in saved/inserted assets',()=>{const f=insertGroupAsset(form(),asset(),'instance');f.groups![0].condition={kind:'interaction_metadata',field:'channel',equals:'email'};const saved=saveGroupAsset(f,'instance','new',now,[asset()]),published=transitionAsset(saved,'PUBLISHED',now);expect(insertGroupAsset(form(),published,'another').groups![0].condition).toEqual(f.groups![0].condition)})
  it('never permits published form insertion, update or detach',()=>{const f={...insertGroupAsset(form(),asset(),'instance'),status:'PUBLISHED' as const,enabled:true};for(const operation of [()=>insertGroupAsset(f,asset(),'two'),()=>updateGroupAsset(f,'instance',asset()),()=>detachGroupAsset(f,'instance')])expect(operation).toThrow('draft/testing')})
})
