import { describe,it,expect,vi } from 'vitest'
import { manualEvaluation } from './manualClient'
import { seedForms } from './forms'
const session={region:'eu-west-1' as const,clientId:'public-client',accessToken:'browser-token',expiresAt:Date.now()+3600_000}
describe('trusted manual evaluation client',()=>{
  it('uses the Cloud Run API without a browser Jev key or proxy and sends only source identities',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({status:'created',record:{id:'saved'}})));const outcome=await manualEvaluation(session,'synthetic','c1',seedForms[0],fetcher,'https://aqm.example');expect(outcome.record.id).toBe('saved');const [url,init]=fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(url).toBe('https://aqm.example/api/evaluations/manual');expect(JSON.parse(init.body as string)).toEqual({source:'synthetic',conversationId:'c1',formId:seedForms[0].id,formVersion:seedForms[0].version});expect(init.body).not.toMatch(/questions|transcript|apiKey/);expect(new Headers(init.headers).get('Authorization')).toBe('Bearer browser-token')})
  it('shows duplicate results and uncertain status without making another request',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({status:'duplicate',record:{id:'prior'}})));expect((await manualEvaluation(session,'synthetic','c1',seedForms[0],fetcher,'https://aqm.example')).duplicate).toBe(true);const uncertain=vi.fn(async()=>new Response(JSON.stringify({status:'uncertain',message:'Reconcile before retry.'}),{status:409}));await expect(manualEvaluation(session,'synthetic','c1',seedForms[0],uncertain,'https://aqm.example')).rejects.toThrow('Reconcile')})
  it('guides disconnected users to the service without calling a proxy',async()=>{const fetcher=vi.fn();await expect(manualEvaluation(null,'synthetic','c1',seedForms[0],fetcher,'https://aqm.example')).rejects.toThrow('automation service');expect(fetcher).not.toHaveBeenCalled()})
})
