import { describe,it,expect } from 'vitest'
import { landingPage,overviewEvaluationLink } from './navigation'
import { matchesReviewQueue } from './reviews'
import { reviewFixture,reviewInput } from '../fixtures/reviewFixture'
import { buildReview } from './reviews'
describe('Overview landing and drill-through state',()=>{
 it('defaults an existing valid connected session to Overview and disconnected to synthetic conversation review',()=>{expect(landingPage(new URLSearchParams(),true)).toBe('automation');expect(landingPage(new URLSearchParams(),false)).toBe('evaluate')})
 it('preserves evaluation/review deep links, explicit pages, policy links and run links',()=>{expect(landingPage(new URLSearchParams('page=automation&evaluationId=review'),true)).toBe('evaluations');for(const page of ['settings','policies','analytics','groups','evaluate'])expect(landingPage(new URLSearchParams({page}),true)).toBe(page);expect(landingPage(new URLSearchParams('policyId=p'),true)).toBe('policies');expect(landingPage(new URLSearchParams('runId=r'),true)).toBe('automation')})
 it('sets clean server evaluation filters for critical, late and my queue links',()=>{for(const filters of ([{critical:'yes'},{due:'overdue',dueState:'OVERDUE'},{dueState:'ESCALATED'},{reviewQueue:'mine',assignment:'mine'}] as Record<string,string>[])){const link=overviewEvaluationLink(new URL('https://app.test/?evaluationId=old&critical=no&form=stale&runId=r'),filters);expect(link.searchParams.get('page')).toBe('evaluations');expect(link.searchParams.get('evaluationSource')).toBe('server');expect(link.searchParams.has('evaluationId')).toBe(false);expect(link.searchParams.has('form')).toBe(false);expect(link.searchParams.has('runId')).toBe(false);for(const [key,value] of Object.entries(filters))expect(link.searchParams.get(key)).toBe(value)}})
 it('filters exact SLA stages with configured thresholds, excluding completed reviews',()=>{const record=reviewFixture(),review=buildReview(record,undefined,reviewInput(record,'request'),{userId:'admin'},'2026-10-02T12:00:00Z');review.dueAt='2026-10-01T00:00:00Z';const row={...record,humanReview:review},now='2026-10-02T12:00:00Z';expect(matchesReviewQueue(row,new URLSearchParams('dueState=ESCALATED'),undefined,now,{dueSoonHours:24,overdueEscalationHours:24})).toBe(true);expect(matchesReviewQueue(row,new URLSearchParams('dueState=OVERDUE'),undefined,now,{dueSoonHours:24,overdueEscalationHours:24})).toBe(false);expect(matchesReviewQueue(row,new URLSearchParams('dueState=OVERDUE'),undefined,now,{dueSoonHours:24,overdueEscalationHours:null})).toBe(true);review.status='REVIEWED';expect(matchesReviewQueue(row,new URLSearchParams('dueState=ESCALATED'),undefined,now)).toBe(false)})
})
