import { test,expect,type Page } from '@playwright/test'
import { mkdirSync,writeFileSync } from 'node:fs'
import type { AddressInfo } from 'node:net'
import { buildSync } from 'esbuild'
import { fileURLToPath } from 'node:url'
const generated=new URL('./.generated/answerSetsApi.mjs',import.meta.url)
buildSync({entryPoints:[fileURLToPath(new URL('./answerSetsApi.ts',import.meta.url))],outfile:fileURLToPath(generated),bundle:true,platform:'node',format:'esm',packages:'external'})
const { createApi, MemoryStore }=await import(generated.href) as typeof import('./answerSetsApi')
import { seedForms } from '../src/domain/forms'
import { seedAnswerSets } from '../src/domain/seedAnswerSets'
import { nextAnswerSetVersion,transitionAnswerSet,applyAnswerSet } from '../src/domain/answerSets'
import { type Role } from '../src/domain/governance'
import type { AnswerSetAsset,EvaluationForm } from '../src/domain/types'
const app=process.env.AQM_BROWSER_URL??'http://127.0.0.1:4174/Genesys-aqm/',api='https://aqm-api-bd54ukouga-nw.a.run.app',now='2026-10-03T10:00:00.000Z',evidence=process.env.AQM_ANSWER_EVIDENCE??'docs/v019-evidence'
mkdirSync(evidence,{recursive:true})
const nav=(page:Page,name:string)=>page.getByRole('navigation').getByRole('button',{name,exact:true})
function draft(type:'choice'|'score'='choice'):EvaluationForm{return {...structuredClone(seedForms[0]),id:`fixture_${type}`,familyId:`fixture_${type}`,name:`Fixture ${type} form`,status:'DRAFT',enabled:false,groups:[{id:'general',name:'General'}],questions:[{id:'q',title:'Quality',instructions:'Assess the quality.',groupId:'general',type,options:structuredClone(seedAnswerSets[type==='choice'?1:0].options),weight:1,enabled:true}]}}
async function fixture(page:Page,role:Role='ADMIN',sets:AnswerSetAsset[]=[],forms:EvaluationForm[]=[draft(),draft('score')]){
 const store=new MemoryStore(),errors:string[]=[],requests:{path:string;method:string}[]=[],user=role==='ADMIN'?'owner':role.toLowerCase()
 for(const f of forms)await store.putForm(f)
 for(const a of sets){const d={...a,status:'DRAFT' as const};await store.putAnswerSet(d);if(a.status!=='DRAFT')await store.putAnswerSet(transitionAnswerSet(d,'PUBLISHED',now))}
 for(const r of ['AUTHOR','REVIEWER','VIEWER'] as const)await store.atomic([{collection:'roleAssignments',id:r.toLowerCase(),expected:undefined,value:{id:r.toLowerCase(),role:r}}])
 const server=createApi({store,now:()=>new Date(now),genesys:{list:async()=>{throw Error('Provider forbidden')},load:async()=>{throw Error('Provider forbidden')},withQueueNames:async c=>c},jev:{evaluate:async()=>{throw Error('Provider forbidden')}}},{origin:'https://simonridd.github.io',region:'eu-west-1',allowedUserIds:new Set(['owner','author','reviewer','viewer']),bootstrapAdminId:'owner',schedulerEmail:'fixture',schedulerAudience:'https://fixture'},async()=>new Response(JSON.stringify({id:user,name:user})))
 await new Promise<void>(r=>server.listen(0,r));const local=`http://127.0.0.1:${(server.address() as AddressInfo).port}`
 page.on('pageerror',e=>errors.push(e.message))
 await page.addInitScript(()=>{sessionStorage.setItem('genesys-aqm-pkce-transaction',JSON.stringify({region:'eu-west-1',clientId:'fixture-client',verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'answerSets'}));localStorage.setItem('genesys-aqm-auth-config',JSON.stringify({region:'eu-west-1',clientId:'fixture-client'}))})
 await page.route('**/*',async route=>{
  const u=new URL(route.request().url())
  if(u.origin===new URL(app).origin)return route.continue()
  if(u.origin==='https://login.mypurecloud.ie'&&u.pathname==='/oauth/token')return route.fulfill({json:{access_token:'fixture',token_type:'Bearer',expires_in:3600}})
  if(u.origin==='https://api.mypurecloud.ie'&&u.pathname==='/api/v2/users/me')return route.fulfill({json:{id:user,name:user,organization:{id:'fixture'}}})
  if(u.origin!==api)return route.abort()
  requests.push({path:u.pathname,method:route.request().method()})
  const response=await fetch(local+u.pathname+u.search,{method:route.request().method(),headers:{Authorization:'Bearer fixture','Content-Type':'application/json'},body:route.request().postData()??undefined})
  return route.fulfill({status:response.status,body:await response.text(),contentType:'application/json'})
 })
 await page.goto(`${app}?page=answerSets&code=fixture&state=${'A'.repeat(43)}`);await expect(page.getByLabel('Current role')).toHaveText(role)
 return {store,errors,requests,close:()=>new Promise<void>(r=>server.close(()=>r()))}
}
async function bounds(page:Page,control:ReturnType<Page['getByRole']>){await control.scrollIntoViewIfNeeded();const b=await control.boundingBox(),m=await page.locator('main').boundingBox();expect(b).not.toBeNull();expect(b!.x).toBeGreaterThanOrEqual(Math.max(0,m!.x)-1);expect(b!.x+b!.width).toBeLessThanOrEqual(Math.min(page.viewportSize()!.width,m!.x+m!.width)+1);return {name:await control.innerText(),box:b}}
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]){
 test(`connected lifecycle, local separation, audit and focus ${viewport.width}`,async({page})=>{
  await page.setViewportSize(viewport);const state=await fixture(page)
  try{
   await expect(page.getByRole('heading',{name:'SAVED IN AQM · 0 saved Answer Sets'})).toBeVisible();await expect(page.getByRole('button',{name:/Open Answer Set/})).toHaveCount(0)
   await page.locator('.local-library>summary').click();await expect(page.locator('.local-library')).toContainText('Service quality');expect(state.requests.filter(r=>r.method!=='GET')).toEqual([])
   await page.getByRole('button',{name:'New Answer Set',exact:true}).click();const detail=page.locator('.answer-set-detail')
   await expect(detail.locator('h2')).toBeFocused();await detail.getByLabel('Answer Set name',{exact:true}).fill('Fixture reusable clarity');await detail.getByLabel('Answer Set description',{exact:true}).fill('Fixture common answers')
   await detail.getByLabel('Option 1 label',{exact:true}).fill('Clear');await detail.getByLabel('Option 2 label',{exact:true}).fill('Unclear');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await expect(detail.getByText('Unsaved changes',{exact:true})).toHaveCount(0)
   await detail.getByRole('button',{name:'Publish Answer Set',exact:true}).click();await expect(detail).toContainText('Published version is locked');await expect(detail.getByLabel('Option 1 label')).toHaveCount(0)
   await detail.getByRole('button',{name:'Edit as new version',exact:true}).click();await detail.getByLabel('Option 1 credit').fill('90');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await detail.getByRole('button',{name:'Publish Answer Set',exact:true}).click();await expect(detail).toContainText('v2 · PUBLISHED')
   const original=page.getByRole('button',{name:'Open Answer Set Fixture reusable clarity v1',exact:true});await original.focus();await page.keyboard.press('Enter');await detail.getByRole('button',{name:'Retire Answer Set',exact:true}).click();await expect(detail).toContainText('Retired version is locked')
   await detail.getByRole('button',{name:'View history',exact:true}).click();await expect(detail).toContainText('answer_set retire');const boxes=[];for(const label of ['Close details','Export JSON','Edit as new version'])boxes.push(await bounds(page,detail.getByRole('button',{name:label,exact:true})))
   writeFileSync(`${evidence}/bounds-library-${viewport.width}.json`,JSON.stringify(boxes,null,2));await detail.locator('h2').scrollIntoViewIfNeeded();await page.screenshot({path:`${evidence}/library-detail-${viewport.width}.png`});await detail.getByRole('button',{name:'Close details'}).click();await expect(original).toBeFocused()
   expect((await state.store.query('answerSetAssets',100)).items).toHaveLength(2);expect(state.errors).toEqual([])
  }finally{await state.close()}
 })
 test(`choice attach detach save-as update and blocked condition ${viewport.width}`,async({page})=>{
  await page.setViewportSize(viewport);const a=structuredClone(seedAnswerSets[1]),v2=transitionAnswerSet(nextAnswerSetVersion(a,[a],now),'PUBLISHED',now);v2.options[0].label='Completely clear'
  const state=await fixture(page,'AUTHOR',[a,v2])
  try{
   await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click()
   await detail.getByRole('button',{name:'Use reusable Answer Set'}).click();const picker=detail.getByRole('dialog',{name:'Use reusable Answer Set'});await expect(picker.locator('h4')).toBeFocused();await expect(picker).not.toContainText('Service quality');await expect(picker).toContainText('4 answers')
   await bounds(page,picker.getByRole('button',{name:'Use Resolution clarity v1'}));await page.screenshot({path:`${evidence}/picker-${viewport.width}.png`});await picker.getByRole('button',{name:'Use Resolution clarity v1'}).click();await expect(detail.locator('.answer-tools h3')).toBeFocused();await expect(detail.getByLabel('Option 1 label')).toHaveCount(0);await expect(detail.getByLabel('Answer format')).toBeDisabled();await expect(detail.getByText('Unsaved changes',{exact:true})).toBeVisible()
   await detail.getByRole('button',{name:'Newer version available: v2'}).click();await expect(detail.getByRole('dialog',{name:'Update Answer Set'})).toContainText('RENAMED');await bounds(page,detail.getByRole('button',{name:'Update this question to v2'}));await page.screenshot({path:`${evidence}/comparison-${viewport.width}.png`});await detail.getByRole('button',{name:'Update this question to v2'}).click();await expect(detail.locator('.inline-answers>summary')).toContainText('Completely clear')
   await detail.getByRole('button',{name:'Detach and customize',exact:true}).click();await detail.locator('.inline-answers>summary').click();await expect(detail.getByLabel('Option 1 label')).toBeEditable();await detail.getByLabel('Option 1 label').fill('Customized');await detail.getByRole('button',{name:'Save as Answer Set'}).click();await detail.getByLabel('Answer Set name').fill('Customized answers');await detail.getByLabel('Answer Set description').fill('Customized snapshot');await detail.getByRole('button',{name:'Create draft Answer Set'}).click();await expect(detail.getByText('Customized answers was created as a draft Answer Set. Publish it from Answer Sets before using it elsewhere.')).toBeVisible()
   const saved=(await state.store.query<AnswerSetAsset>('answerSetAssets',100)).items.find(a=>a.name==='Customized answers')!;expect(saved.status).toBe('DRAFT');expect(saved.options[0].label).toBe('Customized');expect(saved.familyId).not.toBe(a.familyId)
   await detail.getByRole('button',{name:'Use reusable Answer Set'}).click();await detail.getByRole('button',{name:'Use Resolution clarity v1'}).click();await detail.getByRole('button',{name:'Save changes',exact:true}).click()
   const current=(await state.store.form('fixture_choice'))!;current.questions.push({...current.questions[0],id:'later',title:'Follow-up',type:'noul',options:[],sourceAnswerSet:undefined,condition:{kind:'question_outcome',questionId:'q',outcomes:['partly_clear']}});await state.store.putForm(current)
   const v3=nextAnswerSetVersion(v2,[a,v2],now);v3.options=v3.options.filter(o=>o.key!=='partly_clear');await state.store.putAnswerSet(v3);await state.store.putAnswerSet(transitionAnswerSet(v3,'PUBLISHED',now))
   await nav(page,'Answer Sets').click();await page.getByRole('button',{name:'Refresh saved Answer Sets'}).click();await expect(page.getByRole('heading',{name:'SAVED IN AQM · 4 saved Answer Sets'})).toBeVisible();await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Refresh saved forms'}).click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();await detail.locator('.question-card').first().getByRole('button',{name:'Edit',exact:true}).click()
   await detail.getByRole('button',{name:'Newer version available: v3'}).click();await expect(detail.getByRole('alert')).toContainText('Change or remove that condition first');await expect(detail.getByRole('button',{name:'Update this question to v3'})).toBeDisabled();await expect(detail.locator('.inline-answers>summary')).toContainText('Partly clear');await page.screenshot({path:`${evidence}/blocked-update-${viewport.width}.png`})
   await detail.getByRole('button',{name:'Cancel',exact:true}).click();await detail.getByRole('button',{name:'Detach and customize',exact:true}).click();await expect(detail.getByLabel('Answer format')).toBeEnabled();await detail.getByLabel('Answer format').selectOption('score');await expect(detail.getByRole('button',{name:'Use reusable Answer Set'})).toBeVisible()
   expect(state.errors).toEqual([])
  }finally{await state.close()}
 })
 test(`ordered score snapshot and option order ${viewport.width}`,async({page})=>{
  await page.setViewportSize(viewport);const a=structuredClone(seedAnswerSets[0]),state=await fixture(page,'AUTHOR',[a])
  try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture score form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Use reusable Answer Set'}).click();await detail.getByRole('button',{name:'Use Service quality v1'}).click();await expect(detail.locator('.inline-answers>summary')).toContainText('Excellent');await expect(detail.getByRole('button',{name:'Move option 1 down'})).toHaveCount(0);await detail.getByRole('button',{name:'Detach and customize',exact:true}).click();await detail.locator('.inline-answers>summary').click();await expect(detail.getByLabel('Option 2 credit')).toHaveValue('67');await detail.locator('.option-advanced').nth(3).locator('summary').click();await expect(detail.getByLabel('Option 4 external/source value')).toHaveValue('3');await detail.getByRole('button',{name:'Move option 1 down'}).click();await expect(detail.getByLabel('Option 1 label')).toHaveValue('Good');await detail.locator('.option-advanced').first().locator('summary').click();await expect(detail.getByLabel('Option 1 external/source value')).toHaveValue('1');await bounds(page,detail.getByRole('button',{name:'Move option 1 down'}));await page.screenshot({path:`${evidence}/score-${viewport.width}.png`});await detail.getByRole('button',{name:'Save changes',exact:true}).click();expect((await state.store.form('fixture_score'))!.questions[0].options[0]).toEqual(a.options[1]);expect(state.errors).toEqual([])}finally{await state.close()}
 })
}
for(const role of ['ADMIN','AUTHOR','REVIEWER','VIEWER'] as const)test(`Answer Sets role ${role}`,async({page})=>{const state=await fixture(page,role,[seedAnswerSets[1]]);try{await page.getByRole('button',{name:'Open Answer Set Resolution clarity v1'}).click();const detail=page.locator('.answer-set-detail');await expect(detail.getByLabel('Answer Set name')).not.toBeEditable();if(role==='ADMIN'||role==='AUTHOR'){await expect(page.getByRole('button',{name:'New Answer Set',exact:true})).toBeVisible();await expect(detail).toContainText('Published version is locked');await expect(detail.getByRole('button',{name:'Edit as new version'})).toBeVisible()}else{await expect(page.getByRole('button',{name:'New Answer Set',exact:true})).toHaveCount(0);await expect(detail).toContainText('Your role can view this definition but cannot change it');await expect(detail.getByRole('button',{name:'Edit as new version'})).toHaveCount(0)}expect(state.errors).toEqual([]);expect(state.requests.every(r=>r.method==='GET')).toBe(true)}finally{await state.close()}})
test('dirty guards keep Answer Set edits across refresh, cancelled switch/close/navigation and unload',async({page})=>{const state=await fixture(page,'AUTHOR');try{await page.getByRole('button',{name:'New Answer Set',exact:true}).click();const detail=page.locator('.answer-set-detail');await detail.getByLabel('Answer Set name').fill('Keep unsaved');await page.getByRole('button',{name:'Refresh saved Answer Sets'}).click();await expect(detail.getByLabel('Answer Set name')).toHaveValue('Keep unsaved');page.on('dialog',d=>d.dismiss());await detail.getByRole('button',{name:'Close details'}).click();await expect(detail).toBeVisible();await nav(page,'Evaluation Forms').click();await expect(detail).toBeVisible();await page.getByRole('button',{name:'New Answer Set',exact:true}).click();await expect(detail.getByLabel('Answer Set name')).toHaveValue('Keep unsaved');expect(await page.evaluate(()=>{const e=new Event('beforeunload',{cancelable:true});window.dispatchEvent(e);return e.defaultPrevented})).toBe(true);await detail.getByLabel('Option 1 credit').fill('200');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('alert')).toContainText('credit must be between');await expect(detail.getByLabel('Answer Set name')).toHaveValue('Keep unsaved');await detail.getByLabel('Option 1 credit').fill('100');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await detail.getByRole('button',{name:'Close details'}).click();await expect(detail).toHaveCount(0);expect(state.errors).toEqual([])}finally{await state.close()}})
test('disconnected starters/custom snapshot and reconnect never upload browser state',async({page})=>{
 await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(app).origin?r.continue():r.abort());await page.goto(`${app}?page=answerSets`)
 await expect(page.getByRole('button',{name:'Open Answer Set Resolution clarity v1'})).toBeVisible();await page.getByRole('button',{name:'New Answer Set',exact:true}).click();const detail=page.locator('.answer-set-detail');await detail.getByLabel('Answer Set name').fill('Browser custom');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await detail.getByRole('button',{name:'Publish Answer Set',exact:true}).click();await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'＋ New form'}).click();const form=page.locator('.form-detail');await form.getByRole('button',{name:'Add question',exact:true}).click();await form.getByLabel('Answer format').selectOption('choice');await form.getByRole('button',{name:'Use reusable Answer Set'}).click();await form.getByRole('button',{name:'Use Browser custom v1'}).click();await expect(form.getByLabel('Option 1 label')).toHaveCount(0);const before=await page.evaluate(()=>localStorage.getItem('genesys-aqm-v019-answer-sets'))
 await page.unroute('**/*');const state=await fixture(page,'AUTHOR');try{await expect(page.getByRole('heading',{name:'SAVED IN AQM · 0 saved Answer Sets'})).toBeVisible();await page.locator('.local-library>summary').click();await expect(page.locator('.local-library')).toContainText('Browser custom');expect(await page.evaluate(()=>localStorage.getItem('genesys-aqm-v019-answer-sets'))).toBe(before);expect(state.requests.filter(r=>r.method!=='GET')).toEqual([]);expect((await state.store.query('answerSetAssets',100)).items).toHaveLength(0)}finally{await state.close()}
})

test('Answer Set import creates a new draft with exact options and safe history',async({page})=>{const state=await fixture(page,'AUTHOR');try{const a=seedAnswerSets[0],value={schema:'genesys-aqm/answer-set',schemaVersion:1,exportedAt:now,definition:a};await page.getByLabel('Import Answer Set',{exact:true}).setInputFiles({name:'answers.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});const detail=page.locator('.answer-set-detail');await expect(detail).toContainText('Service quality · v1 · DRAFT');await detail.locator('.option-advanced').nth(3).locator('summary').click();await expect(detail.getByLabel('Option 4 external/source value')).toHaveValue('3');const rows=(await state.store.query<AnswerSetAsset>('answerSetAssets',100)).items;expect(rows).toHaveLength(1);expect(rows[0].status).toBe('DRAFT');expect(rows[0].options).toEqual(a.options);expect(rows[0].familyId).toBe(rows[0].id);await detail.getByRole('button',{name:'View history'}).click();await expect(detail).toContainText('answer_set imported');expect(state.errors).toEqual([])}finally{await state.close()}})
test('connected failed library reads never substitute local starters in the picker',async({page})=>{const state=await fixture(page,'AUTHOR');try{await page.route(`${api}/api/answer-sets?**`,r=>r.fulfill({status:503,json:{error:'Fixture unavailable'}}));await page.getByRole('button',{name:'Refresh saved Answer Sets'}).click();await expect(page.getByRole('alert')).toContainText('Saved Answer Sets unavailable');await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Use reusable Answer Set'}).click();await expect(detail.getByRole('dialog')).toContainText('Publish a compatible Answer Set');await expect(detail.getByRole('dialog')).not.toContainText('Resolution clarity');expect(state.requests.filter(r=>r.method!=='GET')).toEqual([])}finally{await state.close()}})
test('stale incompatible family update is blocked without changing the snapshot',async({page})=>{const a=seedAnswerSets[1],f=applyAnswerSet(draft(),'q',a),state=await fixture(page,'AUTHOR',[a],[f]);try{const bad={...nextAnswerSetVersion(a,[a],now),status:'PUBLISHED',type:'score'};await page.route(`${api}/api/answer-sets?**`,r=>r.fulfill({json:{items:[a,bad]}}));await page.getByRole('button',{name:'Refresh saved Answer Sets'}).click();await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Newer version available: v2'}).click();await expect(detail.getByRole('alert')).toContainText('answer format does not match');await expect(detail.getByRole('button',{name:'Update this question to v2'})).toBeDisabled();await expect(detail.locator('.inline-answers>summary')).toContainText('Clear');expect((await state.store.form(f.id))!.questions[0].sourceAnswerSet?.answerSetVersion).toBe(1)}finally{await state.close()}})
test('Answer Set changes inside a group affect only the form snapshot',async({page})=>{const a=seedAnswerSets[1],f=applyAnswerSet(draft(),'q',a);f.groups![0].sourceAsset={familyId:'group',assetId:'group',assetVersion:1};const state=await fixture(page,'AUTHOR',[a],[f]);try{const source={id:'group',familyId:'group',name:'Source group',description:'',version:1,status:'PUBLISHED' as const,questions:[{...f.questions[0],groupId:undefined}],createdAt:now,updatedAt:now};await state.store.putGroupAsset(source);const before=JSON.stringify(await state.store.groupAsset('group'));await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Detach and customize',exact:true}).click();await detail.locator('.inline-answers>summary').click();await detail.getByLabel('Option 1 label').fill('Form customization');await detail.getByRole('button',{name:'Save changes',exact:true}).click();expect(JSON.stringify(await state.store.groupAsset('group'))).toBe(before);expect((await state.store.form(f.id))!.questions[0].sourceAnswerSet).toBeUndefined()}finally{await state.close()}})
