import { test,expect,type Page,type Locator } from '@playwright/test'
import { mkdirSync,writeFileSync,readFileSync } from 'node:fs'
import { fixture,draft,app } from './authoringSimplificationFixture'
import { seedAnswerSets } from '../src/domain/seedAnswerSets'
import { seedGroupAssets } from '../src/domain/seedGroupAssets'
import { applyAnswerSet,nextAnswerSetVersion } from '../src/domain/answerSets'
import type { AnswerSetAsset,EvaluationForm } from '../src/domain/types'
const evidence=process.env.AQM_AUTHORING_EVIDENCE??'docs/v019b-evidence';mkdirSync(evidence,{recursive:true})
const nav=(p:Page,n:string)=>p.getByRole('navigation').getByRole('button',{name:n,exact:true})
const a=seedAnswerSets[1],now='2026-10-03T10:00:00Z',group={...structuredClone(seedGroupAssets[2]),name:'Resolution & Next Steps',status:'PUBLISHED' as const}
function version():AnswerSetAsset {const next=nextAnswerSetVersion(a,[a],now);return {...next,status:'PUBLISHED',options:[{...a.options[1],label:'Mostly resolved',credit:.8},{...a.options[0]},{...a.options[3]},{key:'not_stated',label:'Not stated',description:'No clarity statement.',credit:0}]}}
async function screenshot(page:Page,name:string,scope?:Locator){if(scope)await scope.screenshot({path:`${evidence}/${name}-${page.viewportSize()!.width}.png`});else await page.screenshot({path:`${evidence}/${name}-${page.viewportSize()!.width}.png`,fullPage:true})}
async function visibleText(root:Locator){return root.evaluate(el=>(el as HTMLElement).innerText)}
async function bounds(page:Page,root:Locator){const boxes=await root.locator('input:visible,textarea:visible,select:visible,button:visible,summary:visible').evaluateAll(els=>els.map(el=>({name:el.getAttribute('aria-label')??el.textContent??'',x:el.getBoundingClientRect().x,right:el.getBoundingClientRect().right})));expect(boxes.filter(b=>b.x<0||b.right>page.viewportSize()!.width+1)).toEqual([])}
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]){
 test(`question density, connected authority, attach/detach, advanced mapping ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);const state=await fixture(page,'AUTHOR',[a]);try{
 await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail'),card=detail.locator('.question-card');
 await expect(detail.getByRole('status')).toContainText('Saved in AQM');expect(await visibleText(card)).not.toMatch(/partly_clear|sourceValue|\bID\b|Provides a clear/);await expect(card.locator('.condition-fields')).toHaveCount(0);await expect(card.getByText('Weight 1',{exact:false})).toBeVisible();
 const collapsed=await page.evaluate(()=>({pageHeight:document.documentElement.scrollHeight,questionHeight:document.querySelector('.question-card')!.getBoundingClientRect().height}));await screenshot(page,'form-collapsed',detail);if(viewport.width===390)await screenshot(page,'form-after-full');
 if(viewport.width===390){const before=JSON.parse(readFileSync('docs/v019b-evidence/mobile-before.json','utf8'));expect(collapsed.pageHeight).toBeLessThan(before.pageHeight*.65);writeFileSync(`${evidence}/mobile-after.json`,JSON.stringify({before,after:collapsed,reduction:1-collapsed.pageHeight/before.pageHeight},null,2))}
 const edit=card.getByRole('button',{name:'Edit',exact:true});await edit.focus();await page.keyboard.press('Enter');await expect(card.locator('.editor-focus-heading')).toBeFocused();await expect(card.getByLabel('Stable question ID')).toBeHidden();await expect(card.getByLabel('Option 1 key')).toBeHidden();await expect(card.getByLabel('Option 1 external/source value')).toBeHidden();await expect(card.getByLabel('Option 1 credit (%)')).toBeHidden();await bounds(page,card);await screenshot(page,'form-expanded',detail);if(viewport.width===390)await screenshot(page,'form-expanded-after-full');
 const expanded=await page.evaluate(()=>({pageHeight:document.documentElement.scrollHeight,questionHeight:document.querySelector('.question-card')!.getBoundingClientRect().height}));if(viewport.width===390){const before=JSON.parse(readFileSync('docs/v019b-evidence/mobile-expanded-before.json','utf8'));writeFileSync(`${evidence}/mobile-expanded-after.json`,JSON.stringify({before,after:expanded,reduction:1-expanded.pageHeight/before.pageHeight},null,2));expect(expanded.pageHeight).toBeLessThan(before.pageHeight*.65)}
 await card.locator('.inline-answers>summary').click();await bounds(page,card);await screenshot(page,'inline-option-editor',card);await card.getByLabel('Title',{exact:true}).fill('Resolution quality');await expect(detail.getByRole('status')).toContainText('Unsaved changes');await card.getByRole('button',{name:'Use reusable Answer Set',exact:true}).focus();await page.keyboard.press('Enter');const picker=card.getByRole('dialog');await expect(picker.locator('h4')).toBeFocused();await screenshot(page,'answer-picker',picker);await picker.getByRole('button',{name:'Use Resolution clarity v1'}).focus();await page.keyboard.press('Enter');await expect(card.getByRole('heading',{name:'Answers',exact:true})).toBeFocused();await expect(card).toContainText('Using Resolution clarity v1');await expect(card.getByLabel('Option 1 label')).toHaveCount(0);await screenshot(page,'answer-attached',detail);
 await card.getByRole('button',{name:'Detach and customize',exact:true}).click();await expect(card.getByRole('status')).toContainText('Current answers kept');await card.getByLabel('Option 1 label').fill('Clearly resolved');await card.locator('.option-advanced').first().locator('summary').focus();await page.keyboard.press('Enter');await expect(card.getByLabel('Option 1 key')).toHaveValue('clear');await card.getByLabel('Option 1 external/source value').fill('17.125');await card.getByLabel('Option 1 credit (%)').fill('75');await card.locator('.advanced-details').filter({has:page.getByLabel('Stable question ID')}).locator('summary').click();await expect(card.getByLabel('Stable question ID')).toHaveValue('q');await card.getByRole('button',{name:'Done',exact:true}).last().click();await expect(edit).toBeFocused();await detail.getByRole('button',{name:'Save changes',exact:true}).click();await expect(detail.getByRole('status')).toContainText('Saved in AQM');expect(await visibleText(detail)).not.toMatch(/save locally|saved locally|to server|familyId|sourceValue/);
 const saved=(await state.store.form('fixture_choice'))!;expect(saved.questions[0]).toMatchObject({id:'q',title:'Resolution quality'});expect(saved.questions[0].options[0]).toEqual({...a.options[0],label:'Clearly resolved',credit:.75,sourceValue:17.125});expect(saved.questions[0].options.slice(1)).toEqual(a.options.slice(1));expect(state.errors).toEqual([])
 }finally{await state.close()}
 })
 test(`new empty form and exact three-question reusable group ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);const state=await fixture(page,'AUTHOR',[a],[],[group]);try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'＋ New form'}).click();const detail=page.locator('.form-detail');await expect(detail.locator('.question-card')).toHaveCount(0);await expect(detail).toContainText('No questions yet.');await screenshot(page,'form-empty',detail);await detail.getByRole('button',{name:'Publish version'}).click();await expect(detail.getByRole('alert')).toContainText('Enable at least one question');await expect(detail).toContainText('DRAFT · VERSION 1');await detail.getByRole('button',{name:'Add reusable group',exact:true}).last().focus();await page.keyboard.press('Enter');await detail.getByRole('button',{name:'Add Resolution & Next Steps',exact:true}).focus();await page.keyboard.press('Enter');await expect(detail.locator('.question-card')).toHaveCount(3);await expect(detail.locator('.question-card')).not.toContainText(['Untitled question','Untitled question','Untitled question']);await expect(detail).toContainText('Using Resolution & Next Steps v1');await expect(detail.getByRole('status')).toContainText('Unsaved changes');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await expect(detail.getByRole('status')).toContainText('Saved in AQM');const forms=(await state.store.forms());expect(forms).toHaveLength(1);expect(forms[0].questions).toHaveLength(3);expect(forms[0].groups?.find(g=>g.sourceAsset)?.sourceAsset?.assetId).toBe(group.id);expect(await state.store.groupAsset(group.id)).toEqual(group);await screenshot(page,'group-reused',detail);await nav(page,'Question Groups').click();await screenshot(page,'groups-library');expect(state.errors).toEqual([])}finally{await state.close()}
 })
 test(`human version comparison and blocked question/group repair ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);const f=applyAnswerSet(draft(),'q',a),v2=version(),state=await fixture(page,'AUTHOR',[a,v2],[f]);try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Newer version available: v2'}).click();const dialog=detail.getByRole('dialog');for(const label of ['ADDED','REMOVED','RENAMED','CREDIT CHANGED','ORDER CHANGED'])expect(await visibleText(dialog)).toContain(label);expect(await visibleText(dialog)).not.toMatch(/mostly_clear|partly_clear|not_stated|family/);await expect(dialog).toContainText('80%');await expect(dialog).toContainText('No dependent condition will break');expect((await state.store.form(f.id))!.questions[0].options).toEqual(a.options);await screenshot(page,'answer-diff',dialog);await dialog.getByRole('button',{name:'Update this question to v2'}).click();await detail.getByRole('button',{name:'Save changes',exact:true}).click();expect((await state.store.form(f.id))!.questions[0].options).toEqual(v2.options);
 const blocked=applyAnswerSet(draft(),'q',a);blocked.questions.push({id:'escalation',groupId:'general',title:'Escalation required',instructions:'Is escalation required?',type:'noul',options:[],weight:1,enabled:true,condition:{kind:'question_outcome',questionId:'q',outcomes:['partly_clear']}});blocked.groups!.push({id:'followup',name:'Follow-up questions',condition:{kind:'question_outcome',questionId:'q',outcomes:['partly_clear']}});await state.store.putForm(blocked);await detail.getByRole('button',{name:'Done',exact:true}).last().click();await detail.getByRole('button',{name:'Close details'}).click();await page.getByRole('button',{name:'Refresh saved forms'}).click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();await detail.locator('.question-card').first().getByRole('button',{name:'Edit',exact:true}).click();const snapshot=JSON.stringify(await state.store.form(f.id)),mutations=state.requests.filter(r=>r.method!=='GET').length;await detail.getByRole('button',{name:'Newer version available: v2'}).click();await expect(dialog.getByRole('alert')).toContainText('Partly clear');await expect(dialog.getByRole('alert')).toContainText('Escalation required');await expect(dialog.getByRole('alert')).toContainText('Follow-up questions');await expect(dialog.getByRole('alert')).toContainText('Change or remove that condition first');await expect(dialog.getByRole('button',{name:'Update this question to v2'})).toBeDisabled();expect(await visibleText(dialog.getByRole('alert'))).not.toMatch(/partly_clear|question_outcome|valid Choice|Noul/);await screenshot(page,'blocked-update',dialog);expect(JSON.stringify(await state.store.form(f.id))).toBe(snapshot);expect(state.requests.filter(r=>r.method!=='GET')).toHaveLength(mutations);await dialog.getByRole('button',{name:'Cancel'}).click();expect(state.errors).toEqual([])
 }finally{await state.close()}
 })
 test(`Customer effort creation, lifecycle and mobile labels ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);const state=await fixture(page,'AUTHOR');try{await screenshot(page,'answers-library');await page.getByRole('button',{name:'New Answer Set',exact:true}).click();const detail=page.locator('.answer-set-detail');await expect(detail.locator('h2')).toBeFocused();await detail.getByLabel('Answer Set name',{exact:true}).fill('Customer effort');await detail.getByLabel('Answer Set description').fill('Less effort earns more credit.');await detail.getByLabel('Answer format',{exact:true}).selectOption('score');for(let i=0;i<3;i++)await detail.getByRole('button',{name:'＋ Add level'}).click();const labels=['Very low','Low','Moderate','High','Very high'];for(const [i,label] of labels.entries()){await detail.getByLabel(`Option ${i+1} label`,{exact:true}).fill(label);await detail.getByLabel(`Option ${i+1} description`,{exact:true}).fill(`${label} customer effort.`);await detail.getByLabel(`Option ${i+1} credit (%)`,{exact:true}).fill(String(100-i*25))};expect(await visibleText(detail)).not.toMatch(/Base type|family|Source value|Stable key/);await bounds(page,detail);await screenshot(page,'answers-editor',detail);await detail.getByRole('button',{name:'Save changes',exact:true}).click();await detail.getByRole('button',{name:'Publish Answer Set'}).click();await expect(detail).toContainText('Published version is locked');const saved=(await state.store.query<AnswerSetAsset>('answerSetAssets',100)).items[0];expect(saved.options.map(o=>o.credit)).toEqual([1,.75,.5,.25,0]);expect(saved.options.map(o=>o.key)).toEqual(['yes','no','option_3','option_4','option_5']);await detail.getByRole('button',{name:'Edit as new version'}).focus();await page.keyboard.press('Enter');await detail.getByLabel('Option 2 label').fill('Little effort');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await detail.getByRole('button',{name:'Publish Answer Set'}).click();expect((await state.store.query<AnswerSetAsset>('answerSetAssets',100)).items.find(s=>s.version===2)!.options[1].key).toBe('no');expect(state.errors).toEqual([])}finally{await state.close()}
 })
}
test('imported form, group and Answer Set preserve keys, external mappings and export after unrelated edits',async({page})=>{
 const importedSet={...structuredClone(seedAnswerSets[0]),name:'Imported score',status:'DRAFT' as const},f=draft('score');f.name='Imported form';f.questions[0].options=structuredClone(importedSet.options);const g={...structuredClone(group),name:'Imported group',questions:[{...f.questions[0],groupId:undefined}]};const state=await fixture(page,'AUTHOR');try{
 for(const [kind,definition,importLabel,scope,nameLabel,name] of [
 ['answer-set',importedSet,'Import Answer Set','.answer-set-detail','Answer Set name','Imported scale edited'],
 ['group',g,'Import reusable group','.asset-detail','Reusable question group name','Imported group edited'],
 ['form',f,'Import form','.form-detail','Form name','Imported form edited']
 ] as const){await nav(page,kind==='form'?'Evaluation Forms':kind==='group'?'Question Groups':'Answer Sets').click();await page.getByLabel(importLabel,{exact:true}).setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schema:`genesys-aqm/${kind==='form'?'evaluation-form':kind==='group'?'question-group':'answer-set'}`,schemaVersion:1,exportedAt:now,definition}))});const detail=page.locator(scope);await detail.getByLabel(nameLabel,{exact:true}).fill(name);await detail.getByRole('button',{name:'Save changes',exact:true}).click();if(kind==='form')await detail.locator('.more-actions>summary').click();const pending=page.waitForEvent('download');await detail.getByRole('button',{name:'Export JSON',exact:true}).click();const result=JSON.parse(readFileSync((await(await pending).path())!,'utf8'));expect(kind==='answer-set'?result.definition.options:result.definition.questions[0].options).toEqual(importedSet.options);await detail.getByRole('button',{name:'Close details'}).click()}
 expect(state.errors).toEqual([])
 }finally{await state.close()}
})
test('save inline answers as reusable keeps current question until explicit attach',async({page})=>{const state=await fixture(page,'AUTHOR');try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Edit',exact:true}).click();await detail.getByRole('button',{name:'Save as Answer Set',exact:true}).click();const dialog=detail.getByRole('dialog');await expect(dialog).toContainText('keeps its current answers');await expect(dialog).toContainText('Answer format: Multiple choice');await dialog.getByLabel('Answer Set name').fill('Reusable clarity');await dialog.getByRole('button',{name:'Create draft Answer Set'}).click();await expect(detail.getByRole('status').filter({hasText:'was created'})).toContainText('Publish it from Answer Sets');expect((await state.store.form('fixture_choice'))!.questions[0].sourceAnswerSet).toBeUndefined();const sets=(await state.store.query<AnswerSetAsset>('answerSetAssets',100)).items;expect(sets[0].status).toBe('DRAFT');expect(sets[0].options).toEqual(a.options)}finally{await state.close()}})
test('published and role-read-only questions expand without disabled editing controls',async({page})=>{const f={...draft(),status:'PUBLISHED' as const,enabled:true};const state=await fixture(page,'VIEWER',[a],[f]);try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await expect(detail).toContainText('Your role can view this definition but cannot change it');await expect(detail.locator('.question-card input')).toHaveCount(0);await detail.getByRole('button',{name:'View details'}).click();await expect(detail.locator('.question-card input:disabled')).toHaveCount(0);await detail.locator('.inline-answers>summary').click();await expect(detail).toContainText('Clear resolution clarity.');expect(state.requests.every(r=>r.method==='GET')).toBe(true)}finally{await state.close()}})
test('advanced key used by a condition fails closed with no silent migration',async({page})=>{const f=draft();f.questions.push({id:'followup',groupId:'general',title:'Escalation required',instructions:'Should we escalate?',type:'noul',options:[],weight:1,enabled:true,condition:{kind:'question_outcome',questionId:'q',outcomes:['partly_clear']}});const state=await fixture(page,'AUTHOR',[],[f]);try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail'),card=detail.locator('.question-card').first();await card.getByRole('button',{name:'Edit',exact:true}).click();await card.locator('.inline-answers>summary').click();await card.locator('.option-advanced').nth(2).locator('summary').click();await card.getByLabel('Option 3 key').fill('different_key');await detail.getByRole('button',{name:'Save changes',exact:true}).click();await expect(detail.getByRole('alert')).toContainText('Escalation required');expect((await state.store.form(f.id))!.questions[0].options[2].key).toBe('partly_clear');expect((await state.store.form(f.id))!.questions[1].condition).toEqual(f.questions[1].condition)}finally{await state.close()}})
test('disconnected question copy remains neutral; reconnect never uploads definitions',async({page})=>{await page.route('**/*',r=>new URL(r.request().url()).origin===new URL(app).origin?r.continue():r.abort());await page.goto(`${app}?page=forms`);await page.getByRole('button',{name:'＋ New form'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Add question',exact:true}).click();await detail.getByLabel('Title',{exact:true}).fill('Browser-only question');await detail.getByLabel('Instructions / question').fill('Was the resolution clear?');await expect(detail.getByRole('status')).toContainText('Saved in this browser');expect(await visibleText(detail.locator('.question-editor'))).not.toMatch(/browser|locally|server/);const before=await page.evaluate(()=>localStorage.getItem('genesys-aqm-v02-forms'));await page.unroute('**/*');const state=await fixture(page,'AUTHOR',[],[]);try{await nav(page,'Evaluation Forms').click();await expect(page.getByRole('heading',{name:'Saved in AQM · 0 saved forms'})).toBeVisible();expect(state.requests.every(r=>r.method==='GET')).toBe(true);expect(await page.evaluate(()=>localStorage.getItem('genesys-aqm-v02-forms'))).toBe(before);expect(await state.store.forms()).toEqual([])}finally{await state.close()}})
async function keyboardTo(page:Page,target:Locator){for(let i=0;i<180;i++){if(await target.evaluate(el=>el===document.activeElement))return;await page.keyboard.press('Tab')}throw Error(`Keyboard could not reach ${await target.textContent()}`)}
test('author tasks replay and keyboard reachability from navigation through reusable choices',async({page})=>{const state=await fixture(page,'AUTHOR',[a],[],[group],'conversations'),actions:{action:string;page:string}[]=[];const act=async(label:string,target:Locator)=>{await keyboardTo(page,target);await page.keyboard.press('Enter');actions.push({action:label,page:await page.getByRole('heading',{level:1}).innerText()})};try{
 await act('Evaluation Forms',nav(page,'Evaluation Forms'));await act('New form',page.getByRole('button',{name:'＋ New form'}));const detail=page.locator('.form-detail');await detail.getByLabel('Form name',{exact:true}).fill('Resolution clarity evaluation');await act('Add question',detail.getByRole('button',{name:'Add question',exact:true}));await detail.getByLabel('Title',{exact:true}).fill('Resolution clarity');await detail.getByLabel('Instructions / question').fill('Was the resolution clear?');await keyboardTo(page,detail.getByLabel('Answer format'));await page.keyboard.press('m');await page.keyboard.press('Tab');await expect(detail.getByLabel('Answer format')).toHaveValue('choice');actions.push({action:'Multiple choice',page:'Evaluation Forms'});await act('Use reusable Answer Set',detail.getByRole('button',{name:'Use reusable Answer Set'}));await act('Use Resolution clarity v1',detail.getByRole('button',{name:'Use Resolution clarity v1'}));await act('Advanced details',detail.locator('.question-editor>.advanced-details>summary'));await expect(detail.getByLabel('Stable question ID')).toBeVisible();await act('Done',detail.locator('.question-done').getByRole('button',{name:'Done'}));await act('Save changes',detail.getByRole('button',{name:'Save changes',exact:true}));await expect(detail.getByRole('status')).toContainText('Saved in AQM');
 const first=(await state.store.forms())[0];expect(first.questions[0].options).toEqual(a.options);expect(first.questions[0].sourceAnswerSet?.answerSetId).toBe(a.id);
 await act('Question Groups',nav(page,'Question Groups'));await act('Open Resolution & Next Steps',page.getByRole('button',{name:'Open reusable question group Resolution & Next Steps v1'}));await expect(page.locator('.asset-detail')).toContainText('3 questions');await act('Close details',page.locator('.asset-detail').getByRole('button',{name:'Close details'}));await act('Evaluation Forms',nav(page,'Evaluation Forms'));await act('New form',page.getByRole('button',{name:'＋ New form'}));await act('Add reusable group',detail.getByRole('button',{name:'Add reusable group',exact:true}).last());await expect(detail.locator('.reusable-picker h3')).toBeFocused();await act('Add Resolution & Next Steps',detail.getByRole('button',{name:'Add Resolution & Next Steps'}));await act('Save changes',detail.getByRole('button',{name:'Save changes',exact:true}));expect((await state.store.forms()).find(f=>f.id!==first.id)!.questions).toHaveLength(3);
 writeFileSync(`${evidence}/author-task-replay.json`,JSON.stringify({goals:['Create a quality form that asks whether the resolution was clear, using the reusable four-level Resolution clarity scale.','Reuse three related questions across another evaluation form.'],actions,completion:[true,true],wrongTurns:0,confusedAnswerSetsWithGroups:false,limitations:'Scripted keyboard replay by the implementing agent; not an independent blind or recruited human test. Field fills are additional actions, recorded in the spec.',errors:state.errors,requests:state.requests},null,2))
 }finally{await state.close()}
})
test('group version update and detach preserve copied questions and source definitions',async({page})=>{const v2={...structuredClone(group),id:`${group.familyId}_v2`,version:2,questions:group.questions.map(q=>({...q,instructions:'Updated reusable instructions.'}))};const state=await fixture(page,'AUTHOR',[a],[draft()],[group,v2]);try{await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Fixture choice form v1'}).click();const detail=page.locator('.form-detail');await detail.getByRole('button',{name:'Add reusable group',exact:true}).click();await detail.getByRole('button',{name:'Add Resolution & Next Steps',exact:true}).first().click();await detail.getByRole('button',{name:'Save changes',exact:true}).click();const before=(await state.store.form('fixture_choice'))!,g=detail.getByRole('region',{name:'Group: Resolution & Next Steps',exact:true});await g.locator('.group-details>summary').click();await g.getByRole('button',{name:'Update group to v2'}).click();await expect(g).toContainText('Using Resolution & Next Steps v2');await detail.getByRole('button',{name:'Save changes',exact:true}).click();const updated=(await state.store.form('fixture_choice'))!;expect(updated.questions.map(q=>q.id)).toEqual(before.questions.map(q=>q.id));expect(updated.questions.filter(q=>q.sourceAssetQuestionId).every(q=>q.instructions==='Updated reusable instructions.')).toBe(true);const answers=JSON.stringify(updated.questions);await g.getByRole('button',{name:'Detach and customize group'}).click();await detail.getByRole('button',{name:'Save changes',exact:true}).click();const detached=(await state.store.form('fixture_choice'))!;expect(detached.groups?.find(g=>g.name===group.name)?.sourceAsset).toBeUndefined();expect(detached.questions.map(q=>q.options)).toEqual(updated.questions.map(q=>q.options));expect(JSON.stringify(await state.store.groupAsset(group.id))).toBe(JSON.stringify(group));expect(JSON.stringify(await state.store.groupAsset(v2.id))).toBe(JSON.stringify(v2));expect(answers).toContain('Updated reusable instructions.');expect(state.errors).toEqual([])}finally{await state.close()}})
