import { installOwnerGovernanceFixture } from './governanceFixture'
import { test,expect } from '@playwright/test'
import detail from '../src/fixtures/genesys-detail.json' with {type:'json'}
import transcript from '../src/fixtures/genesys-transcript.json' with {type:'json'}
import { seedForms } from '../src/domain/forms'
import { normalizeGenesys } from '../src/domain/genesys'
import { recordEvaluation } from '../src/domain/evaluations'
const origin='https://aqm-api-bd54ukouga-nw.a.run.app'
const conversationId=detail.conversationId
for(const viewport of [{width:1440,height:900},{width:390,height:844}]){
 test(`provider-free navigation, IndexedDB cache and trusted evaluation at ${viewport.width}`,async({browser})=>{
  const context=await browser.newContext({viewport});const page=await context.newPage();let searches=0,downloads=0,manual=0;let lastInput:Record<string,unknown>|null=null
  await page.addInitScript(()=>{sessionStorage.setItem('genesys-aqm-pkce-transaction',JSON.stringify({region:'eu-west-1',clientId:'e05784c9-2421-4c2b-a3af-79fafb25aea8',verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'conversations'}));localStorage.setItem('genesys-aqm-v03-source',JSON.stringify('genesys-cloud'))})
  await page.route('https://login.mypurecloud.ie/oauth/token',route=>route.fulfill({json:{access_token:'fixture-token',token_type:'Bearer',expires_in:3600}}))
  await page.route('https://api.mypurecloud.ie/**',async route=>{const url=route.request().url();if(url.includes('/users/me'))await route.fulfill({json:{id:'fixture-user',name:'Fixture User',organization:{id:'fixture-org'}}});else if(url.includes('/details/query')){searches++;const number=route.request().postDataJSON().paging.pageNumber;await route.fulfill({json:{conversations:number===1?Array.from({length:10},(_,index)=>({...detail,conversationId:`22222222-2222-4222-8222-${String(index).padStart(12,'0')}`})):[detail],totalHits:20}})}else if(url.includes('/transcripturl'))await route.fulfill({json:{url:'https://api-downloads.mypurecloud.ie/transcriptsCache/fixture'}});else if(url.includes('/routing/queues'))await route.fulfill({json:{name:'Fixture Queue'}});else await route.fulfill({json:detail})})
  await page.route('https://api-downloads.mypurecloud.ie/**',route=>{downloads++;return route.fulfill({json:transcript})})
  const normalized=normalizeGenesys(detail,transcript);const form=seedForms[0];const record=recordEvaluation(normalized,form,{conversationId,scorecardId:form.id,scorecardVersion:form.version,evaluatedAt:new Date().toISOString(),provider:'typesafe',model:'fixture',questions:[],overallScore:.8,countedWeight:1,rawResponse:{}},[],'fixture-record',{conversationSource:'genesys-cloud',executionMode:'manual'})
  await page.route(`${origin}/**`,async route=>{const url=route.request().url();if(url.endsWith('/manual')){manual++;lastInput=route.request().postDataJSON() as Record<string,unknown>;await route.fulfill({json:{status:manual>1?'duplicate':'created',record}})}else if(url.includes('/forms'))await route.fulfill({json:{items:seedForms}});else if(url.includes('/form-tests'))await route.fulfill({json:{items:[]}});else if(url.includes('/analytics'))await route.fulfill({json:{metrics:{evaluations:manual}}});else await route.fulfill({json:{items:manual?[record]:[]}})})
  await installOwnerGovernanceFixture(page);await page.goto(`http://127.0.0.1:4174/Genesys-aqm/?code=fixture-code&state=${'A'.repeat(43)}`)
  await expect(page.getByRole('heading',{name:'Completed interactions'})).toBeVisible()
  await page.getByLabel('From',{exact:true}).fill('2026-09-28T00:00');await page.getByLabel('To',{exact:true}).fill('2026-09-29T00:00');await page.getByLabel('Queue ID').fill('55555555-5555-4555-8555-555555555555');await page.getByRole('combobox',{name:'Channel',exact:true}).selectOption('voice');await page.getByRole('combobox',{name:'Direction',exact:true}).selectOption('inbound')
  await page.getByRole('button',{name:'Search completed interactions',exact:true}).click();await expect(page.getByText(/10 shown · page 1 · 20 reported/)).toBeVisible();await page.getByRole('button',{name:'Next →',exact:true}).click();await expect(page.getByText(/1 shown · page 2 · 20 reported/)).toBeVisible();expect(searches).toBe(2)
  await page.getByRole('group',{name:'View'}).getByRole('button',{name:'Cards'}).click();await page.getByRole('button',{name:/Open transcript/}).click();await expect(page.getByText('I need help with my bill.',{exact:true})).toBeVisible();expect(downloads).toBe(1)
  await page.getByRole('button',{name:'← Back to conversations',exact:true}).click();await expect(page.getByText(/1 shown · page 2 · 20 reported/)).toBeVisible();await expect(page.getByLabel('Queue ID')).toHaveValue('55555555-5555-4555-8555-555555555555');await expect(page.getByRole('combobox',{name:'Channel',exact:true})).toHaveValue('voice');await expect(page.getByRole('button',{name:/Open transcript/})).toBeVisible();expect(searches).toBe(2)
  await page.getByRole('button',{name:/Open transcript/}).click();await expect(page.getByText(/Loaded from local browser cache/)).toBeVisible();expect(downloads).toBe(1)
  await page.getByRole('button',{name:'Refresh from Genesys',exact:true}).click();await expect(page.getByText(/Retrieved from Genesys/)).toBeVisible();expect(downloads).toBe(2)
  await page.getByRole('button',{name:'✦ Evaluate selected form →',exact:true}).click();await expect(page.getByText(/Production evaluation saved to the automation service/)).toBeVisible();expect(manual).toBe(1);expect(lastInput).toEqual({source:'genesys-cloud',conversationId,formId:form.id,formVersion:form.version});await expect(page.getByText(/proxy.*deployed/)).toHaveCount(0)
  const nav=page.getByRole('navigation',{name:'Primary navigation'});await nav.getByRole('button',{name:'Evaluations',exact:true}).click();await page.getByRole('row').filter({hasText:conversationId}).click();await page.getByRole('button',{name:/Open conversation/}).click();await expect(page.getByText('I need help with my bill.',{exact:true})).toBeVisible();expect(downloads).toBe(2)
  await nav.getByRole('button',{name:'Evaluation Forms',exact:true}).click();await page.getByRole('button',{name:'＋ New form'}).click();await expect(page.getByLabel('Execution')).toHaveValue('server');await page.getByRole('combobox',{name:'Source',exact:true}).selectOption('genesys-cloud');await page.getByRole('button',{name:'Load recent',exact:true}).click();await expect(page.getByText(/recent interactions available/)).toBeVisible();expect(searches).toBe(2)
  await nav.getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByLabel('OAuth Client ID')).toHaveValue('e05784c9-2421-4c2b-a3af-79fafb25aea8');await expect(page.getByText(/2 cached searches · 1 cached transcripts/)).toBeVisible()
  const stored=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('genesys-aqm-conversations-v1',1);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return new Promise<string>((resolve,reject)=>{const request=db.transaction('entries').objectStore('entries').getAll();request.onsuccess=()=>resolve(JSON.stringify(request.result));request.onerror=()=>reject(request.error)})});expect(stored).toContain('I need help with my bill.');expect(stored).not.toContain('fixture-token');expect(stored).not.toContain('transcriptsCache');expect(stored).not.toContain('fixture-code')
  await page.getByRole('button',{name:'Disconnect',exact:true}).click();await expect(page.getByText('Disconnected',{exact:true})).toBeVisible();await expect.poll(async()=>page.evaluate(async()=>{const request=indexedDB.open('genesys-aqm-conversations-v1',1);const db=await new Promise<IDBDatabase>(resolve=>{request.onsuccess=()=>resolve(request.result)});return new Promise<number>(resolve=>{const count=db.transaction('entries').objectStore('entries').count();count.onsuccess=()=>resolve(count.result)})})).toBe(0)
  await nav.getByRole('button',{name:'Conversation review',exact:true}).click();await expect(page.getByText('I need help with my bill.',{exact:true})).toHaveCount(0)
  await context.close()
 })
}
