import { installOwnerGovernanceFixture } from './governanceFixture'
import { test, expect } from '@playwright/test'
import { seedForms } from '../src/domain/forms'
import { readFileSync } from 'node:fs'
const sampleLibrary=['billing','delivery'].map(name=>({conversation:JSON.parse(readFileSync(new URL(`../src/samples/${name}-conversation.json`,import.meta.url),'utf8'))}))
import { evaluateForm, maximumEvaluationWaves } from '../src/domain/formComposition'
import { fixtureEvaluation } from '../src/fixtures/evaluationFixture'
import { recordEvaluation } from '../src/domain/evaluations'
import type { EvaluationForm, QuestionGroupAsset } from '../src/domain/types'
const origin='https://aqm-api-bd54ukouga-nw.a.run.app',appUrl=process.env.AQM_BROWSER_URL??'http://127.0.0.1:4174/Genesys-aqm/'
const draft=(id:string,name:string):EvaluationForm=>({...structuredClone(seedForms[0]),id,familyId:id,name,enabled:false,status:'DRAFT',groups:[{id:'general',name:'General'}],questions:seedForms[0].questions.filter(q=>['greeting','ownership','closing'].includes(q.id)).map(q=>({...structuredClone(q),groupId:'general'}))})
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]){
 test(`provider-free group composition and reusable snapshots at ${viewport.width}`,async({browser})=>{
  test.setTimeout(90_000)
  const context=await browser.newContext({viewport}),page=await context.newPage(),errors:string[]=[]
  page.on('dialog',dialog=>{if(dialog.message().startsWith('Unsaved changes'))void dialog.accept()})
  page.on('pageerror',e=>errors.push(e.message))
  let forms=[draft('alpha','Alpha form'),draft('beta','Beta form'),{...structuredClone(seedForms.at(-1)!),version:17}],assets:QuestionGroupAsset[]=[],providerCalls=0
  await page.addInitScript(()=>sessionStorage.setItem('genesys-aqm-pkce-transaction',JSON.stringify({region:'eu-west-1',clientId:'e05784c9-2421-4c2b-a3af-79fafb25aea8',verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'forms'})))
  await page.route('https://login.mypurecloud.ie/oauth/token',route=>route.fulfill({json:{access_token:'fixture-token',token_type:'Bearer',expires_in:3600}}))
  await page.route('https://api.mypurecloud.ie/**',route=>route.fulfill({json:{id:'fixture-user',name:'Fixture User',organization:{id:'fixture-org'}}}))
  await page.route('https://api.typesafe.ai/**',()=>{throw Error('No live Jev request authorized')})
  await page.route(`${origin}/**`,async route=>{
   const url=new URL(route.request().url()),method=route.request().method()
   if(url.pathname.startsWith('/api/forms/')&&method==='PUT'){const item=route.request().postDataJSON() as EvaluationForm;forms=forms.map(f=>f.id===item.id?item:f);await route.fulfill({json:{item}})}
   else if(url.pathname==='/api/forms')await route.fulfill({json:{items:forms}})
   else if(url.pathname.startsWith('/api/question-groups/')&&method==='PUT'){const item=route.request().postDataJSON() as QuestionGroupAsset;assets=[...assets.filter(a=>a.id!==item.id),item];await route.fulfill({json:{item}})}
   else if(url.pathname==='/api/question-groups')await route.fulfill({json:{items:assets}})
   else if(url.pathname.startsWith('/api/form-tests/')&&method==='POST'){
    const input=route.request().postDataJSON(),conversation=sampleLibrary.find(s=>s.conversation.conversationId===input.selectedConversationIds[0])!.conversation
    const result=await evaluateForm({conversation,form:input.form,evaluatedAt:'2026-10-01T12:00:00Z',evaluateQuestions:async request=>{providerCalls++;return fixtureEvaluation(request)}})
    const record={...recordEvaluation(conversation,input.form,result,[],'test_record'),purpose:'FORM_TEST'}
    await route.fulfill({json:{run:{id:input.id,formId:input.form.id,formSnapshot:input.form,createdAt:'2026-10-01T12:00:00Z',status:'completed',sampleSource:input.source,selectedConversationIds:input.selectedConversationIds,sampleConfiguration:input.sampleConfiguration,provider:result.provider,model:result.model,expectedRequests:maximumEvaluationWaves(input.form),actualProviderRequests:result.providerRequestCount,results:[record],failures:[]}}})
   }else if(url.pathname==='/api/analytics')await route.fulfill({json:{byForm:[],metrics:{evaluations:0}}})
   else await route.fulfill({json:{items:[]}})
  })
  await installOwnerGovernanceFixture(page);await page.goto(`${appUrl}?code=fixture-code&state=${'A'.repeat(43)}`)
  const nav=page.getByRole('navigation',{name:'Primary navigation'}),detail=page.locator('.form-detail')
  await expect(page.getByRole('heading',{name:'Evaluation Forms',exact:true})).toBeVisible()
  await page.getByRole('row').filter({hasText:'Alpha form'}).click()
  await detail.getByRole('button',{name:'Add group',exact:true}).click()
  await page.getByRole('region',{name:'Group: New group',exact:true}).getByLabel('Group name',{exact:true}).fill('Branch')
  const branch=page.getByRole('region',{name:'Group: Branch',exact:true})
  await branch.getByLabel('Group description').fill('Conditional resolution checks')
  await branch.getByRole('button',{name:'Move group Branch up',exact:true}).click()
  await expect(detail.locator('.form-group').first().getByLabel('Group name')).toHaveValue('Branch')
  await branch.getByRole('button',{name:'Move group Branch down',exact:true}).click()
  await expect(detail.locator('.form-group').first().getByLabel('Group name')).toHaveValue('General')
  await detail.getByRole('button',{name:'Add group',exact:true}).click()
  await page.getByRole('region',{name:'Group: New group',exact:true}).getByLabel('Group name').fill('Scratch')
  const scratch=page.getByRole('region',{name:'Group: Scratch',exact:true})
  await scratch.getByRole('button',{name:'Add question',exact:true}).click()
  await scratch.getByLabel('Title',{exact:true}).fill('Temporary criterion')
  await scratch.getByLabel('Instructions / question').fill('Temporary draft criterion for deletion proof.')
  await scratch.getByRole('button',{name:'Delete group',exact:true}).click()
  const deletion=page.getByRole('dialog',{name:'Delete group',exact:true})
  await expect(deletion.getByRole('button',{name:'Keep questions in General',exact:true})).toBeVisible()
  await deletion.getByRole('button',{name:'Delete contained questions',exact:true}).click()
  await expect(scratch).toHaveCount(0)
  await expect(detail.getByText('Temporary criterion',{exact:true})).toHaveCount(0)
  const branchId=await branch.getByLabel('Group name').evaluate(el=>el.closest('section')!.getAttribute('aria-label'))
  expect(branchId).toBe('Group: Branch')
  await detail.getByLabel('Group for Ownership',{exact:true}).selectOption({label:'Branch'})
  await expect(branch.getByText('Ownership',{exact:true})).toBeVisible()
  const general=page.getByRole('region',{name:'Group: General',exact:true})
  await general.getByRole('button',{name:'Move Appropriate close up',exact:true}).click()
  await expect(general.locator('.question-titles').first()).toContainText('Appropriate close')
  await general.getByRole('button',{name:'Move Appropriate close down',exact:true}).click()
  await expect(general.locator('.question-titles').first()).toContainText('Warm opening')
  await branch.getByRole('button',{name:'Add group condition',exact:true}).click()
  await branch.getByLabel('Condition value').fill('email')
  await expect(branch.getByText(/email/, {exact:false}).first()).toBeVisible()
  await branch.getByLabel('Condition value').fill('messaging')
  await expect(branch.getByText(/messaging/, {exact:false}).first()).toBeVisible()
  await branch.getByLabel('Condition value').fill('voice')
  const closing=detail.locator('.question-card').filter({has:page.getByText('Appropriate close',{exact:true})})
  await closing.getByRole('button',{name:'Add question condition',exact:true}).click()
  await closing.getByLabel('Condition source').selectOption('question_outcome')
  await closing.getByRole('combobox',{name:'Previous question',exact:true}).selectOption({label:'Warm opening'})
  await expect(closing.getByRole('combobox',{name:'Previous question',exact:true}).locator('option').filter({hasText:'Ownership'})).toHaveCount(0)
  await expect(closing.getByText(/Ask when Warm opening.*Yes/)).toBeVisible()
  await closing.locator('.condition-builder').screenshot({path:`/private/tmp/aqm-v08-condition-${viewport.width}.png`})
  await branch.getByRole('button',{name:'Save group as reusable group',exact:true}).click()
  await expect(page.getByText(/Branch saved as v1 DRAFT/)).toBeVisible()
  const alphaBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('genesys-aqm-v02-forms')!).find((f:EvaluationForm)=>f.id==='alpha'))
  await nav.getByRole('button',{name:'Question Groups',exact:true}).click()
  await page.getByRole('row').filter({hasText:'Branch'}).click()
  await page.locator('.asset-detail').screenshot({path:`/private/tmp/aqm-v08-library-${viewport.width}.png`})
  await page.getByRole('button',{name:'Publish reusable question group',exact:true}).click()
  await expect(page.locator('.asset-detail').getByRole('heading',{name:'Branch · v1 · PUBLISHED'})).toBeVisible()
  await nav.getByRole('button',{name:'Evaluation Forms',exact:true}).click()
  await page.getByRole('row').filter({hasText:'Beta form'}).click()
  await detail.getByRole('button',{name:'Add reusable group',exact:true}).click()
  await detail.getByRole('button',{name:'Add Branch',exact:true}).click()
  await expect(detail.getByText('Reusable snapshot v1 ·', {exact:false})).toBeVisible()
  const betaBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('genesys-aqm-v02-forms')!).find((f:EvaluationForm)=>f.id==='beta'))
  await nav.getByRole('button',{name:'Question Groups',exact:true}).click()
  await page.getByRole('row').filter({hasText:'Branch'}).click()
  await page.getByRole('button',{name:'Edit as new version',exact:true}).click()
  await page.locator('.asset-detail').getByRole('button',{name:'Edit',exact:true}).click()
  await page.getByLabel('Instructions / question').fill('Updated reusable ownership instructions.')
  await page.getByRole('button',{name:'Publish reusable question group',exact:true}).click()
  await expect(page.locator('.asset-detail').getByRole('heading',{name:'Branch · v2 · PUBLISHED'})).toBeVisible()
  await nav.getByRole('button',{name:'Evaluation Forms',exact:true}).click()
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('genesys-aqm-v02-forms')!) as EvaluationForm[])
  expect(stored.find(f=>f.id==='alpha')).toEqual(alphaBefore);expect(stored.find(f=>f.id==='beta')).toEqual(betaBefore)
  await page.getByRole('row').filter({hasText:'Beta form'}).click()
  await detail.getByRole('button',{name:'Update group to v2',exact:true}).click()
  await expect(detail.getByText('Updated reusable ownership instructions.',{exact:true})).toBeVisible()
  const betaAfter=await page.evaluate(()=>JSON.parse(localStorage.getItem('genesys-aqm-v02-forms')!).find((f:EvaluationForm)=>f.id==='beta'))
  expect(betaAfter.questions.map((q:EvaluationForm['questions'][number])=>q.id)).toEqual(betaBefore.questions.map((q:EvaluationForm['questions'][number])=>q.id))
  await detail.getByRole('button',{name:'Detach from reusable group',exact:true}).click()
  await expect(detail.getByText(/Reusable snapshot/)).toHaveCount(0)
  await page.getByRole('row').filter({hasText:'Alpha form'}).click()
  await detail.getByRole('button',{name:'Publish version',exact:true}).click()
  await expect(detail.getByText('PUBLISHED · VERSION 1')).toBeVisible()
  await expect(branch.getByLabel('Group name')).toHaveAttribute('readonly','')
  await expect(branch.getByRole('button',{name:'Delete group',exact:true})).toBeDisabled()
  await expect(detail.getByRole('button',{name:'Add group',exact:true})).toBeDisabled()
  await expect(closing.getByText(/Ask when Warm opening.*Yes/)).toBeVisible()
  await detail.getByRole('button',{name:'TEST FORM',exact:true}).click()
  await page.getByLabel('Conversations',{exact:true}).fill('1')
  await page.locator('#form-test').getByRole('button',{name:'Test form',exact:true}).click()
  await expect(page.getByText('1 completed · 0 failed',{exact:true})).toBeVisible()
  await page.locator('.test-results').getByText(/test results/i).count()
  await page.locator('.test-results details summary').click()
  await expect(page.locator('.test-results').getByText(/Skipped group/)).toBeVisible()
  await expect(page.locator('.test-results').getByText(/Ownership: Skipped \/ Not applicable/)).toBeVisible()
  await expect(page.locator('.test-results').getByText('Actual Jev requests: 2',{exact:true})).toBeVisible()
  expect(providerCalls).toBe(2)
  await page.locator('.test-results').screenshot({path:`/private/tmp/aqm-v08-test-${viewport.width}.png`})
  await branch.scrollIntoViewIfNeeded()
  await branch.screenshot({path:`/private/tmp/aqm-v08-group-${viewport.width}.png`})
  expect((await branch.boundingBox())!.width).toBeLessThanOrEqual(viewport.width)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width)
  // Real compatibility proof: virtual published v17 and materialized v18 draft, disabled states preserved.
  await page.getByRole('row').filter({hasText:'Customer Service - AI Scoring'}).click()
  await expect(detail.getByText('PUBLISHED · VERSION 17')).toBeVisible()
  await expect(page.getByRole('region',{name:'Group: Compliance & Closure',exact:true})).toBeVisible()
  const v17=JSON.stringify(forms.find(f=>f.version===17))
  await detail.getByRole('button',{name:'Edit as new version',exact:true}).click()
  await expect(detail.getByText('DRAFT · VERSION 18')).toBeVisible()
  expect(JSON.stringify(forms.find(f=>f.version===17))).toBe(v17)
  const v18=await page.evaluate(()=>JSON.parse(localStorage.getItem('genesys-aqm-v02-forms')!).find((f:EvaluationForm)=>f.version===18))
  expect(v18.groups.map((g:{name:string})=>g.name)).toEqual(['Opening','Assisting The Customer','Call Handling Skills','Compliance & Closure'])
  expect(v18.questions.filter((q:EvaluationForm['questions'][number])=>!q.enabled).map((q:EvaluationForm['questions'][number])=>q.id)).toEqual(forms.find(f=>f.version===17)!.questions.filter(q=>!q.enabled).map(q=>q.id))
  expect(errors).toEqual([])
  await context.close()
 })
}
