import {test,expect} from '@playwright/test'
import {normalizeGenesys} from '../src/domain/genesys'
const origin='https://aqm-api-bd54ukouga-nw.a.run.app',id='22222222-2222-4222-8222-222222222222'
const detail={conversationId:id,conversationStart:'2026-09-30T12:00:00Z',conversationEnd:'2026-09-30T12:10:00Z',participants:[{purpose:'customer',participantName:'Messaging Customer',sessions:[{sessionId:'33333333-3333-4333-8333-333333333333',mediaType:'message',direction:'inbound',segments:[{queueId:'55555555-5555-4555-8555-555555555555'}]}]},{purpose:'agent',participantName:'Messaging Agent',userId:'agent'}]}
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}])test(`messaging search, normalized relay, content cache and refresh at ${viewport.width}`,async({browser})=>{
 const context=await browser.newContext({viewport}),page=await context.newPage();let retrievals=0,searches=0
 await page.addInitScript(()=>{sessionStorage.setItem('genesys-aqm-pkce-transaction',JSON.stringify({region:'eu-west-1',clientId:'e05784c9-2421-4c2b-a3af-79fafb25aea8',verifier:'a'.repeat(43),state:'A'.repeat(43),createdAt:Date.now(),page:'conversations'}));localStorage.setItem('genesys-aqm-v03-source',JSON.stringify('genesys-cloud'))})
 await page.route('https://login.mypurecloud.ie/oauth/token',route=>route.fulfill({json:{access_token:'fixture-token',token_type:'Bearer',expires_in:3600}}))
 await page.route('https://api.mypurecloud.ie/**',async route=>{const url=route.request().url();if(url.includes('/users/me'))await route.fulfill({json:{id:'fixture-user',name:'Fixture User'}});else if(url.includes('/details/query')){searches++;expect(route.request().postDataJSON().segmentFilters[0].predicates).toContainEqual({dimension:'mediaType',value:'message'});await route.fulfill({json:{conversations:[detail],totalHits:1}})}else if(url.includes('/routing/queues'))await route.fulfill({json:{name:'Messaging Queue'}});else {expect(url).not.toContain('speechandtextanalytics');await route.fulfill({json:detail})}})
 const normalized={...normalizeGenesys(detail),metadata:{...normalizeGenesys(detail).metadata,queue:'Messaging Queue',transcriptStatus:'Available'},messages:[{id:'c',speaker:'customer' as const,timestamp:'2026-09-30T12:01:00Z',senderName:'Messaging Customer',text:'Please help with my bill.'},{id:'b',speaker:'bot' as const,timestamp:'2026-09-30T12:01:10Z',senderName:'Service Assistant',text:'I will connect you.'},{id:'s',speaker:'system' as const,timestamp:'2026-09-30T12:01:20Z',text:'Connected to service team.'},{id:'a',speaker:'agent' as const,timestamp:'2026-09-30T12:02:00Z',senderName:'Messaging Agent',text:'I can help.'}]}
 await page.route(`${origin}/**`,async route=>{if(route.request().url().endsWith(`/conversations/${id}/digital`)){retrievals++;expect(route.request().headers().authorization).toBe('Bearer fixture-token');await route.fulfill({json:normalized})}else await route.fulfill({json:{items:[]}})})
 await page.goto(`http://127.0.0.1:4174/Genesys-aqm/?code=fixture-code&state=${'A'.repeat(43)}`)
 await page.getByLabel('From',{exact:true}).fill('2026-09-30T00:00');await page.getByLabel('To',{exact:true}).fill('2026-10-01T00:00');await page.getByRole('combobox',{name:'Channel',exact:true}).selectOption('messaging');await page.getByRole('button',{name:'Search completed interactions',exact:true}).click()
 await expect(page.getByRole('row').filter({hasText:id})).toContainText('Messaging Agent');await page.getByRole('group',{name:'View'}).getByRole('button',{name:'Cards'}).click();await page.getByRole('button',{name:/Open transcript/}).click()
 await expect(page.locator('.message-row.customer .bubble')).toContainText('Please help with my bill.');await expect(page.locator('.message-row.bot')).toContainText('Service Assistant');await expect(page.locator('.message-row.bot .pill')).toHaveText('Bot');await expect(page.locator('.message-row.system .pill')).toHaveText('System');await expect(page.locator('.message-row.agent .bubble')).toContainText('I can help.');expect(retrievals).toBe(1)
 await page.getByRole('button',{name:'← Back to conversations',exact:true}).click();await page.getByRole('button',{name:/Open transcript/}).click();await expect(page.getByText(/Loaded from local browser cache/)).toBeVisible();expect(retrievals).toBe(1);expect(searches).toBe(1)
 await page.getByRole('button',{name:'Refresh from Genesys',exact:true}).click();await expect(page.getByText(/Retrieved from Genesys/)).toBeVisible();expect(retrievals).toBe(2)
 const entries=await page.evaluate(async()=>new Promise<unknown[]>((resolve,reject)=>{const req=indexedDB.open('genesys-aqm-conversations-v1',1);req.onsuccess=()=>{const read=req.result.transaction('entries').objectStore('entries').getAll();read.onsuccess=()=>resolve(read.result)};req.onerror=()=>reject(req.error)}))
 expect(JSON.stringify(entries)).toContain('I will connect you.');expect(JSON.stringify(entries)).not.toMatch(/fixture-token|mediaUri|signed|EML|MIME-Version|attachments/)
 await page.locator('.transcript').screenshot({path:`/private/tmp/aqm-v09-messaging-${viewport.width}.png`});expect((await page.locator('.message-row.bot .bubble').boundingBox())!.width).toBeLessThan(viewport.width);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(viewport.width)
 await page.getByRole('navigation',{name:'Primary navigation'}).getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Disconnect',exact:true}).click();await expect(page.getByText(/0 cached searches · 0 cached transcripts/)).toBeVisible()
 await context.close()
})
