import {test,expect,type Page} from '@playwright/test'
import {writeFileSync,mkdirSync} from 'node:fs'
import {continuityFixture} from './reviewer-continuity-fixture'
import {fixture,draft} from './authoringSimplificationFixture'
import {qualityFixture} from './qualityActionabilityFixture'
import {seedAnswerSets} from '../src/domain/seedAnswerSets'
import {navigateWorkspace,chooseView} from './workspace-navigation'
const evidence=process.env.AQM_NAV_EVIDENCE??'docs/v019d-evidence';mkdirSync(evidence,{recursive:true})
const goals={REVIEWER:'Complete the review that needs my attention.',AUTHOR:'Edit an evaluation form and reuse an Answer Set.',VIEWER:'Find the lowest-average quality question.',ADMIN:'Check whether anything needs attention, then open Policies.'}
for(const width of [1440,390])for(const role of ['REVIEWER','AUTHOR','VIEWER','ADMIN'] as const)test(`goal-only ${role} ${width}`,async({page})=>{
 await page.setViewportSize({width,height:width===390?844:900});const actions:string[]=[],expansions:string[]=[]
 const go=async(name:string)=>{const group=page.getByRole('navigation',{name:'Primary navigation'}).locator('details:not([open])').filter({has:page.getByText(name,{exact:true})});if(await group.count())expansions.push(await group.locator('summary').innerText());await navigateWorkspace(page,name);actions.push(name)}
 const click=async(name:string,scope:ReturnType<Page['getByRole']>=page.locator('body'))=>{await scope.getByRole('button',{name,exact:true}).click();actions.push(name)}
 let conclusion=''
 if(role==='REVIEWER'){
  const state=await continuityFixture(page,'page=evaluations', {start:false});await expect(page.getByRole('button',{name:'My reviews',exact:true})).toHaveAttribute('aria-pressed','true');await click('Open evaluation review-a');const panel=page.getByRole('region',{name:'Human review',exact:true});await click('Start review',panel);await panel.getByLabel('Human answer: Warm opening',{exact:true}).selectOption('No');actions.push('Answer Warm opening');await click('Open conversation');await expect(page.getByRole('heading',{level:1})).toHaveText('Conversation review');await click('← Back to review');await expect(panel.getByLabel('Human answer: Warm opening',{exact:true})).toHaveValue('No');await panel.getByLabel('Human answer: Understanding the issue',{exact:true}).selectOption('2');await panel.getByLabel('Human answer: Resolution',{exact:true}).selectOption('fully_resolved');actions.push('Answer remaining questions');await click('Complete review',panel);await expect(panel.getByRole('status')).toContainText('removed from My Reviews');expect(state.errors).toEqual([]);expect(state.forbidden).toEqual([]);conclusion='Review completed; evidence detour preserved draft and selected review.'
 }else if(role==='AUTHOR'){
  const state=await fixture(page,'AUTHOR',[seedAnswerSets[1]],[draft()],[],'forms');try{await click('Open form Fixture choice form v1');const detail=page.locator('.form-detail');await click('Edit',detail);await detail.getByLabel('Title',{exact:true}).fill('Resolution quality');actions.push('Edit question title');await click('Use reusable Answer Set',detail);await click('Use Resolution clarity v1',detail.getByRole('dialog'));await click('Save changes',detail);await expect(detail.getByRole('status')).toContainText('Saved in AQM');expect((await state.store.form('fixture_choice'))!.questions[0].sourceAnswerSet?.answerSetId).toBe(seedAnswerSets[1].id);expect(state.errors).toEqual([]);conclusion='Edited question and reused published Resolution clarity v1; saved exact snapshot.'}finally{await state.close()}
 }else{
  const state=await qualityFixture(page,role==='VIEWER'?'analytics':'automation',role)
  if(role==='VIEWER'){
   const insight=page.getByRole('region',{name:'What stands out'}).locator('article').filter({hasText:'Lowest average question'});await expect(insight).toContainText('Customer Service v17 · Clear next step');await expect(insight).toContainText('33.3% average · 8 applicable answers');await chooseView(page,'Questions');actions.push('View: Questions');const row=page.locator('.operational-table tbody tr').filter({hasText:'Clear next step'}).filter({hasText:'Customer Service v17'});await click('Inspect evaluations →',row);await expect(page.getByRole('button',{name:/^Open evaluation /})).toHaveCount(8);await click('Back to Analytics');if(width===390)await expect(page.getByRole('combobox',{name:'View',exact:true})).toHaveValue('questions');else await expect(page.locator('.analytics-tabs button[aria-pressed=true]')).toHaveText('Questions');conclusion='Lowest-average question: Clear next step, Customer Service v17, 33.3%, 8 applicable answers; exact cohort returned to Questions.'
  }else{await page.getByLabel('Dashboard range').selectOption('30');actions.push('Dashboard range: 30 days');const attention=page.getByRole('region',{name:'Attention required'});await expect(attention).toContainText('2 critical failure occurrences');actions.push('Inspect attention summary');await go('Policies');await expect(page.getByRole('heading',{level:1})).toHaveText('Policies');conclusion='Quality requires attention: two critical failure occurrences; Policies reached from visible Configuration disclosure.'}
  expect(state.errors).toEqual([]);expect(state.writes).toEqual([]);expect(state.blocked).toEqual([])
 }
 writeFileSync(`${evidence}/task-${role.toLowerCase()}-${width}.json`,JSON.stringify({goal:goals[role],role,viewport:page.viewportSize(),actions,actionCount:actions.length,wrongTurns:0,groupExpansions:expansions,completed:true,conclusion,route:page.url(),kind:'Scripted agent replay of goal-only fictional tasks; no independent human research or action-count usability threshold.'},null,2));await page.screenshot({path:`${evidence}/task-${role.toLowerCase()}-${width}.png`})
})
