import { installOwnerGovernanceFixture } from './governanceFixture'
import { test, expect } from '@playwright/test'
for (const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]) {
  test(`operational collections and form lifecycle at ${viewport.width}`,async({browser})=>{
    const page=await browser.newPage({viewport})
    await installOwnerGovernanceFixture(page);await page.goto('http://127.0.0.1:4174/Genesys-aqm/')
    const nav=page.getByRole('navigation',{name:'Primary navigation'})
    await nav.getByRole('button',{name:'Conversations',exact:true}).click()
    await expect(page.getByRole('heading',{name:'Conversations',exact:true})).toBeVisible()
    await expect(page.getByRole('table')).toBeVisible()
    await expect(page.getByRole('columnheader',{name:/Conversation ID/})).toBeVisible()
    const table=page.getByRole('table')
    const box=await table.boundingBox()
    expect(box).not.toBeNull()
    expect(box!.width).toBeGreaterThan(700)
    await page.getByRole('group',{name:'View'}).getByRole('button',{name:'Cards'}).click()
    await expect(page.locator('.library-card').first()).toBeVisible()
    await page.getByRole('group',{name:'View'}).getByRole('button',{name:'Table'}).click()
    await nav.getByRole('button',{name:'Evaluation Forms'}).click()
    await expect(page.getByRole('table')).toBeVisible()
    await page.getByRole('button',{name:'＋ New form'}).click()
    await expect(page.getByText('DRAFT · VERSION 1')).toBeVisible()
    await expect(page.getByRole('heading',{name:'Test form'})).toBeVisible()
    await expect(page.getByText(/5 evaluation assignments · up to 5 Jev requests/)).toBeVisible()
    await page.getByLabel('Execution').selectOption('server')
    await expect(page.getByText(/server uses its configured Jev credential/)).toBeVisible()
    await page.getByLabel('Execution').selectOption('browser')
    await page.screenshot({path:`/private/tmp/aqm-forms-${viewport.width}.png`,fullPage:true})
    await nav.getByRole('button',{name:'Evaluations'}).click()
    await expect(page.getByRole('heading',{name:'Evaluations'})).toBeVisible()
    await expect(page.getByRole('table')).toBeVisible()
    await page.screenshot({path:`/private/tmp/aqm-operations-${viewport.width}.png`,fullPage:true})
    await page.close()
  })
}
