import { test,expect,type Page } from '@playwright/test'
import { mkdirSync,writeFileSync } from 'node:fs'
import { qualityFixture } from './qualityActionabilityFixture'
const evidence=process.env.AQM_QUALITY_EVIDENCE??'docs/v019c-evidence';mkdirSync(evidence,{recursive:true})
const nav=(page:Page,name:string)=>page.getByRole('navigation',{name:'Primary navigation'}).getByRole('button',{name,exact:true}).click()
const evaluations=(page:Page)=>page.getByRole('button',{name:/^Open evaluation /})
async function capture(page:Page,name:string){if(name==='analytics-overview'||name==='overview-attention')await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`${evidence}/${name}-viewport-${page.viewportSize()!.width}.png`});await page.screenshot({path:`${evidence}/${name}-${page.viewportSize()!.width}.png`,fullPage:true});const visible=await page.locator('body').innerText();writeFileSync(`${evidence}/${name}-${page.viewportSize()!.width}.txt`,visible);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
async function filters(page:Page){await page.getByRole('button',{name:'Change filters',exact:true}).click();await page.locator('.analytics-filter-bar').getByLabel('From',{exact:true}).fill('2026-09-01');await page.locator('.analytics-filter-bar').getByLabel('To',{exact:true}).fill('2026-09-30');await page.locator('.analytics-filter-bar').getByLabel('Source',{exact:true}).selectOption('genesys-cloud')}
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]){
 test(`quality-leader task and exact insights ${viewport.width}`,async({page})=>{
  await page.setViewportSize(viewport);const state=await qualityFixture(page)
  await page.getByLabel('Dashboard range').selectOption('30')
  const attention=page.getByRole('region',{name:'Attention required'}),quality=page.getByRole('region',{name:'Quality and coverage'}),work=page.getByRole('region',{name:'Review workload health'})
  await expect(attention).toContainText('2 critical failure occurrences');await capture(page,'overview-attention');await quality.scrollIntoViewIfNeeded();await capture(page,'overview-quality-coverage');await work.scrollIntoViewIfNeeded();await capture(page,'overview-review-workload');const health=page.getByRole('region',{name:'Health summary'});await health.scrollIntoViewIfNeeded();await capture(page,'overview-health');expect(await health.locator('details').getAttribute('open')).toBeNull()
  const order=await page.locator('.overview-page>section').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label')));expect(order).toEqual(['Attention required','Quality and coverage','Review workload health','Health summary','Upcoming automation','Recent runs'])
  await attention.getByRole('button',{name:'Inspect critical evaluations →'}).focus();await page.keyboard.press('Enter');await expect(evaluations(page)).toHaveCount(2);expect(Object.fromEntries(new URL(page.url()).searchParams)).toMatchObject({source:'genesys-cloud',critical:'yes',from:'2026-09-02',to:'2026-10-02'});await capture(page,'overview-critical-drill')
  await nav(page,'Analytics');await filters(page);await page.getByRole('button',{name:'Change filters',exact:true}).click();await expect(page.getByRole('region',{name:'Selected quality cohort'})).toContainText('12 evaluations');await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible();await capture(page,'analytics-overview')
  const insights=page.getByRole('region',{name:'What stands out'}),question=insights.locator('article').filter({hasText:'Lowest average question'})
  await expect(question).toContainText('Customer Service v17 · Clear next step');await expect(question).toContainText('33.3% average · 8 applicable answers');await capture(page,'what-stands-out');await question.getByRole('button',{name:'Inspect evaluations →'}).focus();await page.keyboard.press('Enter');await expect(evaluations(page)).toHaveCount(8)
  expect(Object.fromEntries(new URL(page.url()).searchParams)).toMatchObject({form:'general_service@17',question:'understanding',from:'2026-09-01',to:'2026-09-30',source:'genesys-cloud',origin:'analytics'});await capture(page,'exact-evaluation-drill')
  await evaluations(page).first().focus();await page.keyboard.press('Enter');await expect(page.getByRole('region',{name:'Human review',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to Analytics',exact:true}).focus();await page.keyboard.press('Enter');await expect(insights).toBeVisible();expect(new URL(page.url()).searchParams.get('analyticsTab')).toBe('overview')
  const queue=insights.locator('article').filter({hasText:'Lowest average queue'});await expect(queue).toContainText('Claims');await expect(queue).toContainText('50% average · 6 evaluations');await queue.getByRole('button',{name:'Inspect evaluations →'}).click();await expect(evaluations(page)).toHaveCount(6);expect(new URL(page.url()).searchParams.get('queue')).toBe('Claims');expect(new URL(page.url()).searchParams.has('form')).toBe(false);await capture(page,'queue-evaluation-drill');await page.getByRole('button',{name:'Back to Analytics',exact:true}).click();expect(new URL(page.url()).searchParams.has('queue')).toBe(false)
  await page.locator('.analytics-tabs').getByRole('button',{name:'Questions',exact:true}).click();await expect(page.locator('.operational-table tbody tr').filter({hasText:'Clear next step'})).toHaveCount(2);await capture(page,'question-analytics');await page.locator('.analytics-tabs').getByRole('button',{name:'Queues',exact:true}).click();await capture(page,'queue-analytics');await page.locator('.analytics-tabs').getByRole('button',{name:'Groups',exact:true}).click();await capture(page,'group-analytics');await page.locator('.analytics-tabs').getByRole('button',{name:'Forms',exact:true}).click();await capture(page,'form-analytics')
  const text=await page.locator('body').innerText();expect(text).not.toMatch(/general_service@|Cloud Run|endpoint|records scanned|questionId|formRef/)
  writeFileSync(`${evidence}/quality-task-${viewport.width}.json`,JSON.stringify({route:['Overview','Inspect critical evaluations','Analytics','What stands out','Inspect question evaluations','Evaluation detail','Back to Analytics','Inspect queue evaluations'],qualityInvestigationActions:3,wrongTurns:0,conclusion:'Customer Service v17 · Clear next step, lowest average question, 33.3%, 8 applicable answers; Claims lowest queue average 50%, 6 evaluations',exactQuestionCohort:{from:'2026-09-01',to:'2026-09-30',source:'genesys-cloud',form:'general_service@17',question:'understanding'},queueCohort:{from:'2026-09-01',to:'2026-09-30',source:'genesys-cloud',queue:'Claims'},kind:'Scripted agent task replay; no recruited human tester'},null,2))
  expect(state.errors).toEqual([]);expect(state.writes).toEqual([]);expect(state.blocked).toEqual([])
 })
 test(`coverage interpretation, scope and consistency ${viewport.width}`,async({page})=>{
  await page.setViewportSize(viewport);const state=await qualityFixture(page);await page.getByLabel('Dashboard range').selectOption('30');const overview=page.getByRole('region',{name:'Quality and coverage'});await expect(overview.locator('.coverage-funnel')).toContainText('1000');const expected=await overview.locator('.coverage-funnel').innerText()
  await overview.getByRole('button',{name:'Explore coverage →'}).click();const funnel=page.locator('.coverage-funnel');expect((await funnel.innerText()).startsWith(expected)).toBe(true);await expect(funnel).toContainText('50%');await expect(funnel).toContainText('92%');await expect(funnel).toContainText('97.8%');await expect(funnel).toContainText('Evaluation coverage: 45%');await capture(page,'coverage-funnel');await expect(funnel).toContainText('500 eligible interactions were not selected');await expect(funnel).toContainText('40 sampled interactions');await expect(funnel).toContainText('10 interactions had content');await expect(funnel).toContainText('Failed evaluation attempts: 10');await capture(page,'coverage-by-queue')
  const claims=page.locator('.coverage-breakdown').filter({hasText:'Claims'});await expect(claims).toContainText('600 Eligible · 300 Sampled · 270 Evaluated');await claims.getByRole('button',{name:'View evaluated quality →'}).focus();await page.keyboard.press('Enter');await expect(page.locator('.analytics-tabs').getByRole('button',{name:'Queues',exact:true})).toHaveAttribute('aria-pressed','true');expect(new URL(page.url()).searchParams.get('queue')).toBe('Claims');await page.locator('.operational-table tbody tr').filter({hasText:'Claims'}).getByRole('button',{name:'Inspect evaluations →'}).click();await expect(evaluations(page)).toHaveCount(6);await page.getByRole('button',{name:'Back to Analytics',exact:true}).click();await page.locator('.analytics-tabs').getByRole('button',{name:'Coverage',exact:true}).click();await expect(funnel.locator('li').nth(0)).toContainText('1000')
  await nav(page,'Overview');await page.getByLabel('Dashboard range').selectOption('30');await page.getByRole('region',{name:'Recent runs'}).getByRole('button').first().click();const detail=page.locator('#overview-run-detail');await expect(detail).toContainText('Content available');await expect(detail).toContainText('97.8%');await expect(detail).toContainText('Evaluation coverage: 45%');await expect(detail).toContainText('Failed evaluation attempts: 5');await capture(page,'run-detail');expect(await detail.locator('details').getAttribute('open')).toBeNull()
  writeFileSync(`${evidence}/coverage-interpretation-${viewport.width}.json`,JSON.stringify({eligible:1000,sampled:500,contentAvailable:460,evaluated:450,samplingCoverage:'500 / 1000 = 50%',evaluationCoverage:'450 / 1000 = 45%',contentAvailability:'460 / 500 = 92%',sampleCompletion:'450 / 460 = 97.8%',failedAttempts:10,scope:'2 run observations; run detail shows one run with half the counts and same rates',interpretation:'Sampling intentional; content unavailable 40; content available but not evaluated 10',kind:'Scripted comprehension assertions'},null,2));expect(state.errors).toEqual([]);expect(state.writes).toEqual([]);expect(state.blocked).toEqual([])
 })
}
test('safe errors, retry, empty scope, unavailable names and sparse history',async({page})=>{
 const state=await qualityFixture(page,'analytics');await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible();state.failAnalytics();await page.getByRole('button',{name:'Change filters',exact:true}).click();await page.locator('.analytics-filter-bar').getByLabel('From',{exact:true}).fill('2026-09-10');await expect(page.getByRole('alert')).toContainText('Quality analytics could not be loaded.');expect(await page.locator('body').innerText()).not.toContain('Fictional HTTP');state.failAnalytics(false);await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible();await page.locator('.analytics-filter-bar').getByLabel('From',{exact:true}).fill('2027-01-01');await expect(page.getByRole('heading',{name:'No evaluations match this scope.'})).toBeVisible();await expect(page.getByRole('region',{name:'What stands out'})).toHaveCount(0);await expect(page.getByText('Limited history in this period.')).toBeVisible();await page.locator('.analytics-tabs').getByRole('button',{name:'Coverage',exact:true}).click();await expect(page.getByText('Coverage will appear after a monitoring policy run.')).toBeVisible();state.failNames();await nav(page,'Overview');await nav(page,'Analytics');await page.getByRole('button',{name:'Change filters',exact:true}).click();await page.getByText('Advanced filters',{exact:true}).click();await expect(page.getByLabel('Policy identifier')).toBeVisible();await expect(page.getByText('Policy names unavailable.',{exact:false})).toBeVisible();expect(state.writes).toEqual([]);expect(state.errors).toEqual([])
})
test('goal-only route from Overview uses visible quality evidence',async({page})=>{
 const state=await qualityFixture(page),goal='Find the quality area most worth investigating and inspect the supporting evaluations.'
 await page.getByLabel('Dashboard range').selectOption('30')
 // Follow the visible quality metric and the stated lowest-average evidence; no Analytics tab is prescribed.
 const quality=page.getByRole('region',{name:'Quality and coverage'});await expect(quality).toContainText('65%');await quality.locator('.overview-metric').filter({has:page.getByText('Average quality',{exact:true})}).getByRole('button').click()
 await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible();const candidate=page.getByRole('region',{name:'What stands out'}).locator('article').filter({hasText:'Lowest average question'});const conclusion=await candidate.innerText();await candidate.getByRole('button',{name:'Inspect evaluations →'}).click();await expect(evaluations(page)).toHaveCount(8);const filters=Object.fromEntries(new URL(page.url()).searchParams);await evaluations(page).first().click();await expect(page.getByRole('region',{name:'Human review',exact:true})).toBeVisible();await page.getByRole('button',{name:'Back to Analytics',exact:true}).click();await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible()
 writeFileSync(`${evidence}/goal-only-task.json`,JSON.stringify({goal,route:['Overview: Average quality','What stands out: lowest-average question','Inspect evaluations','Evaluation detail','Back to Analytics'],actionsToSupportingEvaluations:2,actionsToDetail:3,wrongTurns:0,conclusion,filters,tester:'Scripted agent replay from visible labels, not an independent human usability study'},null,2));expect(state.writes).toEqual([]);expect(state.errors).toEqual([])
})
test('Overview Analytics entry replaces stale quality filters',async({page})=>{
 const state=await qualityFixture(page);await page.getByLabel('Dashboard range').selectOption('30');await page.evaluate(()=>{const url=new URL(location.href);for(const [key,value] of Object.entries({form:'old@9',policy:'old',agent:'Old',queue:'Old',channel:'email',mode:'manual',from:'2000-01-01',to:'2000-01-02'}))url.searchParams.set(key,value);history.replaceState(null,'',url)})
 await page.getByRole('region',{name:'Quality and coverage'}).getByRole('button',{name:'Explore coverage →'}).click();await expect(page.locator('.coverage-funnel')).toContainText('1000');const q=new URL(page.url()).searchParams;for(const key of ['form','policy','agent','queue','channel','mode'])expect(q.has(key)).toBe(false);expect(q.get('from')).toBe('2026-09-02');expect(q.get('to')).toBe('2026-10-02');expect(q.get('source')).toBe('genesys-cloud');expect(state.writes).toEqual([])
})
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}])test(`Tab-only quality, filters, table and return ${viewport.width}`,async({page})=>{
 await page.setViewportSize(viewport);const state=await qualityFixture(page,'analytics'),trace:string[]=[]
 async function reach(locator:ReturnType<Page['getByRole']>,label:string){for(let i=0;i<180;i++){if(await locator.evaluate(node=>node===document.activeElement)){trace.push(label);return}await page.keyboard.press('Tab')}throw Error(`Not reachable by Tab: ${label}`)}
 const change=page.getByRole('button',{name:'Change filters',exact:true});await reach(change,'Change filters');await page.keyboard.press('Enter');const form=page.locator('.analytics-filter-bar').getByLabel('Form',{exact:true});await reach(form,'Form');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.keyboard.press('Tab');await reach(change,'Close filters');await page.keyboard.press('Enter');await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible()
 const action=page.getByRole('region',{name:'What stands out'}).locator('article').filter({hasText:'Lowest average question'}).getByRole('button',{name:'Inspect evaluations →'});await reach(action,'Question insight');await page.keyboard.press('Enter');await expect(evaluations(page)).toHaveCount(8);await reach(evaluations(page).first(),'Evaluation row');await page.keyboard.press('Enter');await reach(page.getByRole('button',{name:'Back to Analytics',exact:true}),'Back to Analytics');await page.keyboard.press('Enter');await expect(page.getByRole('region',{name:'What stands out'})).toBeVisible()
 const questions=page.locator('.analytics-tabs').getByRole('button',{name:'Questions',exact:true});await reach(questions,'Questions view');await page.keyboard.press('Enter');const row=page.locator('.operational-table tbody tr').filter({hasText:'Clear next step'}).filter({hasText:'Customer Service v17'}).getByRole('button',{name:'Inspect evaluations →'});await reach(row,'Question table action');await page.keyboard.press('Enter');await expect(evaluations(page)).toHaveCount(8);await reach(page.getByRole('button',{name:'Back to Analytics',exact:true}),'Back to question context');await page.keyboard.press('Enter');expect(new URL(page.url()).searchParams.get('analyticsTab')).toBe('questions');writeFileSync(`${evidence}/keyboard-${viewport.width}.json`,JSON.stringify({trace,method:'Tab traversal, native-select ArrowDown and Enter; no mouse clicks'},null,2));expect(state.errors).toEqual([]);expect(state.writes).toEqual([])
})
