import { test,expect,type Page } from '@playwright/test'
import { mkdirSync } from 'node:fs'
import { writeFileSync } from 'node:fs'
import { continuityFixture } from './reviewer-continuity-fixture'
import { keyboardTo } from './usability-fixture'
const evidence=process.env.AQM_REVIEW_EVIDENCE??'docs/v019a-evidence';mkdirSync(evidence,{recursive:true})
const panel=(page:Page)=>page.getByRole('region',{name:'Human review',exact:true})
const open=(page:Page,id='review-a')=>page.getByRole('button',{name:`Open evaluation ${id}`,exact:true}).click()
const nav=(page:Page,name:string)=>page.getByRole('navigation',{name:'Primary navigation'}).getByRole('button',{name,exact:true}).click()
const guard=(page:Page)=>page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return {prevented:event.defaultPrevented,guards:(window as any).__reviewTrace.guards}})
const puts=(state:Awaited<ReturnType<typeof continuityFixture>>)=>state.requests.filter(r=>r.method==='PUT')
async function edit(page:Page,all=false) {
  const review=panel(page)
  await review.getByLabel('Human answer: Warm opening',{exact:true}).selectOption('No')
  await review.getByLabel('Question note: Warm opening',{exact:true}).fill('UNSAVED question note: fictional review')
  await review.getByLabel('Human answer: Understanding the issue',{exact:true}).selectOption('2')
  await review.getByLabel('Overall review note',{exact:true}).fill('UNSAVED overall note: fictional review')
  if(all)await review.getByLabel('Human answer: Resolution',{exact:true}).selectOption('fully_resolved')
}
async function restored(page:Page) {
  const review=panel(page)
  await expect(review.getByLabel('Human answer: Warm opening',{exact:true})).toHaveValue('No')
  await expect(review.getByLabel('Question note: Warm opening',{exact:true})).toHaveValue('UNSAVED question note: fictional review')
  await expect(review.getByLabel('Human answer: Understanding the issue',{exact:true})).toHaveValue('2')
  await expect(review.getByLabel('Overall review note',{exact:true})).toHaveValue('UNSAVED overall note: fictional review')
}
async function evidenceRoundTrip(page:Page,after?:()=>Promise<unknown>) {
  const exact=page.url()
  await page.getByRole('button',{name:'Open conversation',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Conversation review',exact:true})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Conversation review',exact:true})).toBeFocused()
  await expect(page.getByText('I need help with my bill.',{exact:true})).toBeVisible()
  if(after)await after()
  await page.getByRole('button',{name:'← Back to review',exact:true}).click()
  await expect(page).toHaveURL(exact)
  await expect(panel(page).getByRole('heading',{level:2})).toBeFocused()
}
async function reachable(page:Page,name:string) {
  const control=page.getByRole('button',{name,exact:true})
  await control.scrollIntoViewIfNeeded()
  const box=(await control.boundingBox())!,viewport=page.viewportSize()!
  expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(viewport.width+1)
  expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(viewport.height+1)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  return {name,box}
}
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}]){
  test(`reviewer safely inspects evidence and completes My Reviews at ${viewport.width}`,async({browser})=>{
    const context=await browser.newContext({viewport}),page=await context.newPage(),state=await continuityFixture(page,undefined,{start:false})
    await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toBeVisible()
    await page.screenshot({path:`${evidence}/my-reviews-${viewport.width}.png`,fullPage:true})
    await open(page)
    await expect(page.locator('.evaluation-detail> .panel-heading h2')).toBeFocused()
    expect(await guard(page)).toEqual({prevented:false,guards:0})
    await panel(page).getByRole('button',{name:'Start review',exact:true}).click()
    await expect(panel(page).getByLabel('Human answer: Warm opening',{exact:true})).toBeVisible()
    expect(await guard(page)).toEqual({prevented:false,guards:0})
    await edit(page)
    await expect(panel(page).getByRole('status')).toContainText(['Unsaved review changes','Review started.'])
    expect(await guard(page)).toEqual({prevented:true,guards:1})
    const count=puts(state).length
    await page.screenshot({path:`${evidence}/unsaved-${viewport.width}.png`,fullPage:true})
    const bounds=[await reachable(page,'Open conversation')]
    await evidenceRoundTrip(page,async()=>{bounds.push(await reachable(page,'← Back to review'));await page.screenshot({path:`${evidence}/evidence-${viewport.width}.png`,fullPage:true});await page.screenshot({path:`${evidence}/evidence-viewport-${viewport.width}.png`})})
    expect(new URL(page.url()).searchParams.get('evaluationId')).toBe('review-a')
    await restored(page)
    await panel(page).getByRole('heading',{name:'Review this evaluation',exact:true}).scrollIntoViewIfNeeded()
    await page.screenshot({path:`${evidence}/restored-viewport-${viewport.width}.png`})
    await expect(panel(page).getByRole('status')).toContainText('Unsaved review changes')
    expect(puts(state)).toHaveLength(count)
    const writes=await page.evaluate(()=>(window as any).__reviewTrace.writes as {store:string;value:string}[])
    expect(writes.filter(w=>/UNSAVED|baseRevision|reviewDraft|"questionId"/.test(w.value))).toEqual([])
    for(const store of ['localStorage','sessionStorage','IndexedDB'])expect(writes.filter(w=>w.store===store&&/UNSAVED|reviewDraft/.test(w.value))).toHaveLength(0)
    await panel(page).getByLabel('Human answer: Resolution',{exact:true}).selectOption('fully_resolved')
    const workloadBefore=state.requests.filter(r=>r.url.pathname==='/api/review-workload').length
    bounds.push(await reachable(page,'Complete review'))
    await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
    await expect(panel(page).getByRole('status')).toContainText('Review completed. It has been removed from My Reviews.')
    await expect(panel(page).getByRole('status')).toBeFocused()
    await expect(panel(page).getByRole('heading',{name:'Completed calibration',exact:true})).toBeVisible()
    await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(0)
    await expect.poll(()=>state.requests.filter(r=>r.url.pathname==='/api/review-workload').length).toBeGreaterThan(workloadBefore)
    await expect(page.getByLabel('My review summary').locator('.health-grid>div').first()).toContainText('1')
    expect(puts(state).filter(r=>r.body.action==='complete')).toHaveLength(1)
    expect(JSON.stringify(await state.store.evaluations())).toBe(state.before)
    expect(await guard(page)).toEqual({prevented:false,guards:0})
    await page.screenshot({path:`${evidence}/completed-${viewport.width}.png`,fullPage:true})
    bounds.push(await reachable(page,'Close and continue My Reviews'))
    await page.screenshot({path:`${evidence}/completed-viewport-${viewport.width}.png`})
    writeFileSync(`${evidence}/bounds-${viewport.width}.json`,JSON.stringify(bounds,null,2)+'\n')
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    expect(state.errors).toEqual([]);expect(state.forbidden).toEqual([])
    await panel(page).getByRole('button',{name:'Close and continue My Reviews',exact:true}).click()
    await expect(page.locator('.evaluation-detail')).toHaveCount(0)
    await expect(page.getByRole('heading',{name:'Evaluations',exact:true})).toBeFocused()
    await context.close()
  })
}
test('exact My Reviews filter context survives evidence navigation',async({page})=>{
  const query='page=evaluations&reviewQueue=mine&assignment=mine&dueState=DUE_SOON&form=general_service%4017&queue=Fixture+Queue&evaluationSource=server&due=today&agent=Test+Agent&channel=voice&source=genesys-cloud&mode=scheduled&policy=fictional-policy'
  const state=await continuityFixture(page,query);await open(page);await edit(page)
  const url=page.url();await evidenceRoundTrip(page);await restored(page)
  expect(page.url()).toBe(url)
  expect(puts(state)).toHaveLength(0)
  await expect(page.getByRole('button',{name:'My reviews',exact:true})).toHaveAttribute('aria-pressed','true')
})
test('Analytics question investigation retains exact cohort, selected evaluation and return tab',async({page})=>{
  const query='page=analytics&from=2026-09-01&to=2026-09-30&source=genesys-cloud&form=general_service%4017&agent=Test+Agent&queue=Fixture+Queue&channel=voice&mode=scheduled&policy=fictional-policy&analyticsTab=questions'
  await continuityFixture(page,query)
  await page.locator('.operational-table tbody tr').filter({hasText:'Warm opening'}).click()
  await expect(page.getByRole('heading',{name:'Evaluations',exact:true})).toBeVisible()
  await open(page);await edit(page);const investigation=page.url()
  await evidenceRoundTrip(page);await restored(page);expect(page.url()).toBe(investigation)
  await page.getByRole('button',{name:'Back to Analytics',exact:true}).click()
  const returned=new URL(page.url()).searchParams,original=new URLSearchParams(query)
  for(const key of original.keys())expect(returned.get(key)).toBe(original.get(key))
  await expect(page.locator('.analytics-tabs').getByRole('button',{name:'Questions',exact:true})).toHaveClass(/active/)
})
test('save progress adopts returned revision and clears unload guard, then restores authoritative answers',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page)
  await panel(page).getByRole('button',{name:'Save progress',exact:true}).click()
  await expect(panel(page).getByRole('status')).toHaveText('Review progress saved.')
  expect(puts(state)).toHaveLength(1);expect(puts(state)[0].body.expectedRevision).toBe(2)
  expect((await state.store.review('review-a'))!.revision).toBe(3)
  expect(await guard(page)).toEqual({prevented:false,guards:0})
  await evidenceRoundTrip(page);await restored(page)
  await expect(panel(page).getByText(/Unsaved review changes/)).toHaveCount(0)
  await panel(page).getByLabel('Overall review note',{exact:true}).fill('UNSAVED second revision')
  await panel(page).getByRole('button',{name:'Save progress',exact:true}).click()
  await expect(panel(page).getByRole('status')).toHaveText('Review progress saved.')
  expect(puts(state).at(-1)!.body.expectedRevision).toBe(3)
})
for(const [name,query,remains] of [
  ['All Evaluations','page=evaluations&evaluationSource=server',true],
  ['active cohort','page=evaluations&reviewQueue=active',false],
  ['review status','page=evaluations&reviewStatus=IN_REVIEW',false],
  ['due cohort','page=evaluations&dueState=DUE_SOON',false],
] as const)test(`completion reconciles ${name} without Refresh`,async({page})=>{
  const state=await continuityFixture(page,query);await open(page);await edit(page,true)
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('status')).toHaveText('Review completed. The original AI result is preserved.')
  await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(remains?1:0)
  if(remains){const row=page.locator('tr').filter({has:page.getByRole('button',{name:'Open evaluation review-a',exact:true})});await expect(row).toContainText('REVIEWED');await expect(row).toContainText('Fictional Reviewer');await expect(row.getByRole('cell',{name:'62%',exact:true})).toBeVisible()}
  expect(new URL(page.url()).searchParams.get('evaluationId')).toBe('review-a')
  expect(puts(state).filter(r=>r.body.action==='complete')).toHaveLength(1)
  expect(JSON.stringify(await state.store.evaluations())).toBe(state.before)
})
test('revision conflict retains inputs, blocks submit and requires explicit discard',async({page})=>{
  const state=await continuityFixture(page)
  await state.advance();await open(page)
  await expect(panel(page)).toContainText('revision 3')
  await edit(page,true)
  expect((await state.store.review('review-a'))!.revision).toBe(3)
  await evidenceRoundTrip(page,()=>state.advance())
  await restored(page)
  await expect(panel(page).getByRole('alert')).toContainText('This review changed while you were inspecting evidence.')
  await expect(panel(page).getByRole('button',{name:'Save progress',exact:true})).toBeDisabled()
  await expect(panel(page).getByRole('button',{name:'Complete review',exact:true})).toBeDisabled()
  await panel(page).getByRole('button',{name:'Refresh server review',exact:true}).click();await restored(page)
  expect(puts(state)).toHaveLength(0)
  await panel(page).getByRole('button',{name:'Discard my unsaved answers',exact:true}).click()
  await expect(panel(page).getByLabel('Overall review note',{exact:true})).toHaveValue('New authoritative note')
  await expect(panel(page).getByRole('alert')).toHaveCount(0)
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
test('reassignment retains unsaved notes but removes editing and submission authority',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true)
  await evidenceRoundTrip(page,()=>state.advance('review-a',true))
  await expect(panel(page)).toContainText('Assigned to another reviewer')
  await expect(panel(page)).toContainText('UNSAVED question note: fictional review')
  await expect(panel(page)).toContainText('UNSAVED overall note: fictional review')
  await expect(panel(page).getByLabel('Human answer: Warm opening',{exact:true})).toHaveCount(0)
  await expect(panel(page).getByRole('button',{name:'Complete review',exact:true})).toHaveCount(0)
  expect(puts(state)).toHaveLength(0)
  expect(await guard(page)).toEqual({prevented:true,guards:1})
})
test('409 refresh retains draft without silently replacing its base',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true);await state.advance()
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('alert')).toContainText('changed')
  await restored(page);expect(puts(state)).toHaveLength(1)
  expect(puts(state)[0].body.expectedRevision).toBe(2)
  await panel(page).getByRole('button',{name:'Refresh review',exact:true}).click()
  await expect(panel(page).getByRole('alert')).toContainText('Your unsaved answers are still held')
  await restored(page);expect(puts(state)).toHaveLength(1)
})
test('two drafts survive unrelated SPA pages; guard remains until both are resolved',async({page})=>{
  await continuityFixture(page);await open(page);await edit(page)
  await nav(page,'Conversations');await nav(page,'Evaluations');await open(page,'review-b');await edit(page)
  await panel(page).getByRole('button',{name:'Save progress',exact:true}).click()
  await expect(panel(page).getByRole('status')).toHaveText('Review progress saved.')
  expect(await guard(page)).toEqual({prevented:true,guards:1})
  await open(page);await restored(page)
  await panel(page).getByRole('button',{name:'Discard my unsaved answers',exact:true}).click()
  expect(await guard(page)).toEqual({prevented:false,guards:0})
  await open(page,'review-b');await restored(page)
})
test('later server page survives evidence return and completion background reload',async({page})=>{
  const state=await continuityFixture(page,undefined,{pagination:true})
  await page.getByRole('button',{name:'Next server page →',exact:true}).click()
  await open(page,'review-b');await edit(page,true);await evidenceRoundTrip(page);await restored(page)
  await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(0)
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('status')).toContainText('Review completed.')
  await expect.poll(()=>state.requests.filter(r=>r.url.pathname==='/api/evaluations').at(-1)!.url.searchParams.get('cursor')).toBe('page-two')
  await expect(page.getByRole('button',{name:'Open evaluation review-b',exact:true})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(0)
})
test('keyboard-only evidence detour returns to review heading, then reviewer completes',async({page})=>{
  await continuityFixture(page)
  await keyboardTo(page,page.getByRole('button',{name:'Open evaluation review-a',exact:true}));await page.keyboard.press('Enter')
  await expect(page.locator('.evaluation-detail> .panel-heading h2')).toBeFocused()
  const first=panel(page).getByLabel('Human answer: Warm opening',{exact:true})
  await keyboardTo(page,first);await page.keyboard.press('n');await page.keyboard.press('Tab')
  await keyboardTo(page,panel(page).getByLabel('Question note: Warm opening',{exact:true}));await page.keyboard.type('UNSAVED keyboard note')
  await keyboardTo(page,page.getByRole('button',{name:'Open conversation',exact:true}));await page.keyboard.press('Enter')
  await keyboardTo(page,page.getByRole('button',{name:'← Back to review',exact:true}));await page.keyboard.press('Enter')
  await expect(panel(page).getByRole('heading',{name:'Review this evaluation',exact:true})).toBeFocused()
  await expect(first).toHaveValue('No')
  for(const [label,keys] of [['Understanding the issue',['g']],['Resolution',['f']]] as const){await keyboardTo(page,panel(page).getByLabel(`Human answer: ${label}`,{exact:true}));for(const key of keys)await page.keyboard.press(key);await page.keyboard.press('Tab')}
  await keyboardTo(page,panel(page).getByRole('button',{name:'Complete review',exact:true}));await page.keyboard.press('Enter')
  await expect(panel(page).getByRole('status')).toContainText('Review completed.')
})
test('unstarted review returns to selected evaluation heading',async({page})=>{
  await continuityFixture(page,undefined,{start:false});await open(page);const url=page.url()
  await page.getByRole('button',{name:'Open conversation',exact:true}).click()
  await page.getByRole('button',{name:'← Back to evaluation',exact:true}).click()
  await expect(page).toHaveURL(url);await expect(page.locator('.evaluation-detail> .panel-heading h2')).toBeFocused()
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
test('completion removes the row before a failed background list reload, preserving confirmation',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true)
  await page.route('**/api/evaluations?**',route=>route.fulfill({status:503,json:{error:'Fictional list refresh unavailable'}}))
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('status')).toContainText('Review completed.')
  await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(0)
  await expect(page.getByRole('alert')).toContainText('Fictional list refresh unavailable')
  await expect(panel(page).getByRole('heading',{name:'Completed calibration',exact:true})).toBeVisible()
  expect(puts(state).filter(r=>r.body.action==='complete')).toHaveLength(1)
})
test('failed completion retains all changes and explicit retry completes exactly once',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true)
  let failures=0
  await page.route('**/api/reviews/review-a',route=>{
    if(route.request().method()==='PUT'&&failures++===0)return route.fulfill({status:503,json:{error:'Fictional temporary failure'}})
    return route.fallback()
  })
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('alert')).toContainText('Fictional temporary failure')
  await restored(page);expect(await guard(page)).toEqual({prevented:true,guards:1})
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click()
  await expect(panel(page).getByRole('status')).toContainText('Review completed.')
  expect(failures).toBe(2);expect(puts(state).filter(r=>r.body.action==='complete')).toHaveLength(1)
})
test('reload starts a new session without unsubmitted answers or notes',async({page})=>{
  await continuityFixture(page);await open(page);await edit(page)
  expect(await guard(page)).toEqual({prevented:true,guards:1})
  await page.evaluate(()=>{const url=new URL(location.href);url.searchParams.set('code','fixture');url.searchParams.set('state','A'.repeat(43));history.replaceState(null,'',url)})
  page.on('dialog',dialog=>dialog.accept())
  await page.reload()
  await expect(page.getByLabel('Current role')).toHaveText('REVIEWER')
  await expect(panel(page).getByLabel('Human answer: Warm opening',{exact:true})).toHaveValue('')
  await expect(panel(page).getByLabel('Overall review note',{exact:true})).toHaveValue('')
  await expect(panel(page).getByText(/Unsaved review changes/)).toHaveCount(0)
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
test('About and workspace handoff retain human work and unload protection in this SPA',async({page})=>{
  await continuityFixture(page);await open(page);await edit(page)
  await page.getByRole('button',{name:'About / product tour',exact:true}).click()
  await expect(page.getByRole('heading',{name:/More conversations understood/})).toBeVisible()
  expect(await guard(page)).toEqual({prevented:true,guards:1})
  await page.getByRole('button',{name:'Open AQM',exact:true}).first().click()
  await nav(page,'Evaluations');await open(page);await restored(page)
  await expect(panel(page).getByRole('status')).toContainText('Unsaved review changes')
  await panel(page).getByRole('button',{name:'Discard my unsaved answers',exact:true}).click()
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
test('a pending completion reconciles the current filters rather than the scope at click time',async({page})=>{
  const state=await continuityFixture(page,'page=evaluations&reviewStatus=IN_REVIEW')
  await open(page);await edit(page,true)
  let release!:()=>void,started!:()=>void
  const waiting=new Promise<void>(resolve=>{release=resolve}),received=new Promise<void>(resolve=>{started=resolve})
  await page.route('**/api/reviews/review-a',async route=>{
    if(route.request().method()==='PUT'){started();await waiting}
    await route.fallback()
  })
  await panel(page).getByRole('button',{name:'Complete review',exact:true}).click();await received
  await page.getByRole('combobox',{name:'Review status',exact:true}).selectOption('REVIEWED')
  release()
  await expect(panel(page).getByRole('status')).toContainText('Review completed.')
  await expect(page.getByRole('button',{name:'Open evaluation review-a',exact:true})).toHaveCount(1)
  await expect.poll(()=>state.requests.filter(r=>r.url.pathname==='/api/evaluations').at(-1)!.url.searchParams.get('reviewStatus')).toBe('REVIEWED')
})
test('completion in another session keeps unfinished answers separate from completed authority',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true)
  await evidenceRoundTrip(page,()=>state.completeElsewhere())
  await expect(panel(page).getByRole('alert')).toContainText('This review has already been completed.')
  await expect(panel(page)).toContainText('UNSAVED overall note: fictional review')
  await expect(panel(page)).toContainText('HUMAN PROGRESS PREVIEW')
  await expect(panel(page).getByRole('button',{name:'Complete review',exact:true})).toHaveCount(0)
  expect(puts(state)).toHaveLength(0)
  await panel(page).getByRole('button',{name:'Discard my unsaved answers',exact:true}).click()
  await expect(panel(page).getByRole('heading',{name:'Completed calibration',exact:true})).toBeVisible()
  await expect(panel(page)).toContainText('Completed in another session')
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
test('a clean saved draft yields to newer completed authority after evidence inspection',async({page})=>{
  const state=await continuityFixture(page);await open(page);await edit(page,true)
  await panel(page).getByRole('button',{name:'Save progress',exact:true}).click()
  await expect(panel(page).getByRole('status')).toHaveText('Review progress saved.')
  await evidenceRoundTrip(page,()=>state.completeElsewhere())
  await expect(panel(page).getByRole('heading',{name:'Completed calibration',exact:true})).toBeVisible()
  await expect(panel(page)).toContainText('Completed in another session')
  await expect(panel(page)).toContainText('The opening was abrupt.')
  await expect(panel(page)).not.toContainText('UNSAVED')
  await expect(panel(page).getByRole('alert')).toHaveCount(0)
  expect(puts(state)).toHaveLength(1)
  expect(await guard(page)).toEqual({prevented:false,guards:0})
})
