import {test,expect} from '@playwright/test'
import {fixture,capture} from './whole-product-review-fixture'
import {appendFileSync} from 'node:fs'
const out='docs/v019-whole-product-review-evidence',api='https://aqm-api-bd54ukouga-nw.a.run.app'
const nav=(page:any,name:string)=>page.getByRole('navigation',{name:'Primary navigation'}).getByRole('button',{name,exact:true})
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}])test(`whole product actual API fixture inspection ${viewport.width}`,async({page})=>{
 test.setTimeout(180000);await page.setViewportSize(viewport);const f=await fixture(page);const w=viewport.width
 try{
  for(const name of ['Overview','Evaluations','Analytics','Calibration','Evaluation Forms','Question Groups','Answer Sets','Policies','Settings','Conversations','Conversation review']){await nav(page,name).click();await capture(page,'connected-'+name.toLowerCase().replaceAll(' ','-')+'-'+w)}
  await nav(page,'Settings').click();for(const section of ['Access','Reviews','Privacy & retention','Notifications','Audit']){await page.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:section,exact:true}).click();if(section==='Audit')await page.getByRole('button',{name:'Load audit history'}).click();await capture(page,'settings-'+section.toLowerCase().replace(/[^a-z]+/g,'-')+'-'+w)}
  await nav(page,'Answer Sets').click();await page.getByRole('button',{name:'Open Answer Set Resolution clarity v1',exact:true}).click();await capture(page,'answer-set-published-'+w);await page.locator('.answer-set-detail').getByRole('button',{name:'Edit as new version'}).click();await capture(page,'answer-set-draft-'+w);await page.locator('.answer-set-detail').getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('.answer-set-detail').getByRole('button',{name:'Close details'}).click();await page.getByRole('button',{name:'Open Answer Set Service quality v1'}).click();await capture(page,'answer-set-score-'+w)
  await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Resolution clarity form v1'}).click();const form=page.locator('.form-detail');await form.getByRole('button',{name:'Edit',exact:true}).click();await capture(page,'form-editor-'+w);await form.getByRole('button',{name:'Use reusable answer set'}).click();await capture(page,'answer-set-picker-'+w);await form.getByRole('button',{name:'Use Resolution clarity v1'}).click();await capture(page,'answer-set-attached-'+w);await form.getByRole('button',{name:'Newer version available: v2'}).click();await capture(page,'answer-set-comparison-'+w);await form.getByRole('button',{name:'Apply update to v2'}).click();await form.getByRole('button',{name:'Detach',exact:true}).click();await capture(page,'answer-set-detached-'+w);await form.getByLabel('Option 1 label').fill('Customized clarity');await form.getByRole('button',{name:'Save as reusable answer set'}).click();await capture(page,'answer-set-save-as-'+w);await form.getByRole('button',{name:'Cancel',exact:true}).click();await form.getByRole('button',{name:'Save changes',exact:true}).click()
  await nav(page,'Question Groups').click();await page.getByRole('button',{name:/^Open reusable question group /}).first().click();await capture(page,'question-group-detail-'+w)
  await nav(page,'Policies').click();await page.locator('.operational-table .text-link').first().click();await capture(page,'policy-detail-'+w)
  await nav(page,'Evaluations').click();await page.getByRole('button',{name:/^Open evaluation /}).first().click();await capture(page,'evaluation-detail-'+w)
  for(const name of ['Overview','Answer Sets','Analytics']){await nav(page,name).click();const resize=[];for(const width of [1440,390,1440]){await page.setViewportSize({width,height:width===390?844:900});resize.push(await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,main:document.querySelector('main')!.getBoundingClientRect().toJSON()})))}appendFileSync(out+'/resize.ndjson',JSON.stringify({name,resize})+'\n')}
  expect(f.errors).toEqual([]);expect(f.blocked).toEqual([])
 }finally{await f.close()}
})
for(const state of ['empty','healthy'])test(`overview ${state} and connected answer sets empty`,async({page})=>{const f=await fixture(page,'ADMIN',state);try{await capture(page,'overview-'+state);if(state==='empty'){await nav(page,'Answer Sets').click();await capture(page,'answer-sets-empty-connected')}}finally{await f.close()}})
for(const role of ['AUTHOR','REVIEWER','VIEWER'])test(`role ${role} actual API fixture`,async({page})=>{test.setTimeout(90000);const f=await fixture(page,role);try{await capture(page,'role-'+role+'-home');await nav(page,'Evaluations').click();await capture(page,'role-'+role+'-evaluations');if(role==='REVIEWER'){await page.getByRole('button',{name:'Open evaluation escalated',exact:true}).click();await capture(page,'reviewer-priority-detail')}await nav(page,'Settings').click();for(const section of ['Connection','Access','Reviews','Privacy & retention','Notifications','Audit']){const dest=page.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:section,exact:true});if(!await dest.count()){appendFileSync(out+'/role-hidden-sections.ndjson',JSON.stringify({role,section,hidden:true})+'\n');continue}await dest.click();await capture(page,'role-'+role+'-settings-'+section.toLowerCase().replace(/[^a-z]+/g,'-'))}expect(f.errors).toEqual([])}finally{await f.close()}})
test('failure UX using intercepted failures over real local API',async({page})=>{test.setTimeout(90000);const f=await fixture(page,'AUTHOR');try{
 for(const [name,path,refresh] of [['Evaluation Forms','/api/forms','Refresh saved forms'],['Question Groups','/api/question-groups','Refresh saved groups'],['Answer Sets','/api/answer-sets','Refresh saved Answer Sets'],['Policies','/api/policies','Refresh durable policies']]){await nav(page,name).click();f.failures.set('GET '+path,{status:503,error:'Temporarily unavailable'});await page.getByRole('button',{name:refresh,exact:true}).click();await expect(page.getByRole('alert').first()).toBeVisible();await capture(page,'failure-'+name.toLowerCase().replaceAll(' ','-'));f.failures.delete('GET '+path);await page.getByRole('button',{name:refresh,exact:true}).click()}
 await nav(page,'Answer Sets').click();await page.getByRole('button',{name:'New Answer Set',exact:true}).click();await page.getByLabel('Answer Set name',{exact:true}).fill('Conflict clarity scale');await page.route(api+'/api/answer-sets/*',r=>r.request().method()==='PUT'?r.fulfill({status:409,json:{error:'Answer Set changed in another session. Refresh before saving.'}}):r.fallback());await page.getByRole('button',{name:'Save changes',exact:true}).click();await capture(page,'failure-answer-set-conflict');page.on('dialog',d=>d.accept());await nav(page,'Evaluation Forms').click();
 await page.getByLabel('Import form',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await capture(page,'failure-invalid-import')
 await nav(page,'Evaluations').click();f.failures.set('GET /api/evaluations',{status:503,error:'Temporarily unavailable'});await page.getByRole('button',{name:/Refresh evaluations|Refresh$/}).first().click();await capture(page,'failure-evaluation-list');
 }finally{await f.close()}})
