import {test,expect} from '@playwright/test'
import {fixture,capture} from './whole-product-review-fixture'
import {appendFileSync} from 'node:fs'
const out='docs/v019-whole-product-review-evidence',api='https://aqm-api-bd54ukouga-nw.a.run.app'
const nav=(page:any,name:string)=>page.getByRole('navigation',{name:'Primary navigation'}).getByRole('button',{name,exact:true})
for(const viewport of [{width:1440,height:900},{width:1920,height:1080},{width:390,height:844}])test(`priority reviewer completion and conversation evidence ${viewport.width}`,async({page})=>{
 test.setTimeout(90000);await page.setViewportSize(viewport);const f=await fixture(page,'REVIEWER','attention','evaluations');const actions:any[]=[]
 const action=async(label:string,kind:string,fn:()=>Promise<any>)=>{const before=await page.evaluate(()=>scrollY);await fn();await page.clock.runFor(400);await page.waitForLoadState('networkidle');actions.push({label,kind,beforeY:before,afterY:await page.evaluate(()=>scrollY)})}
 try{
  await capture(page,'reviewer-queue-'+viewport.width);await expect(page.locator('.operational-table tbody tr')).toHaveCount(5);const original=JSON.stringify(await f.store.evaluations())
  await action('Open highest priority escalated review','click',()=>page.getByRole('button',{name:'Open evaluation escalated',exact:true}).click());await capture(page,'reviewer-detail-'+viewport.width)
  await action('Open original conversation evidence','click',()=>page.locator('.evaluation-detail').getByRole('button',{name:'Open conversation',exact:true}).click());await expect(page.getByText('I need help with my bill.',{exact:true})).toBeVisible();await capture(page,'connected-original-conversation-'+viewport.width)
  await action('Return to evaluation','click',()=>page.getByRole('button',{name:'← Back to evaluations',exact:true}).click());await capture(page,'reviewer-return-'+viewport.width);await action('Reopen evaluation after evidence detour','click',()=>page.getByRole('button',{name:'Open evaluation escalated',exact:true}).click())
  const panel=page.getByRole('region',{name:'Human review',exact:true});await action('Start independent human review','click',()=>panel.getByRole('button',{name:'Start review',exact:true}).click());
  for(const [name,value]of [['Warm opening','No'],['Understanding the issue','2'],['Resolution','fully_resolved']])await action('Judge '+name,'select',()=>panel.getByLabel('Human answer: '+name,{exact:true}).selectOption(value))
  await action('Explain independent judgment','input',()=>panel.getByLabel('Overall review note',{exact:true}).fill('Opening did not acknowledge the impact. Resolution evidence is clear.'))
  await action('Complete review','click',()=>panel.getByRole('button',{name:'Complete review',exact:true}).click());await expect(panel.getByRole('heading',{name:'Completed calibration'})).toBeVisible();await capture(page,'reviewer-completed-'+viewport.width)
  await action('Return to assigned queue','click',()=>page.locator('.evaluation-detail').getByRole('button',{name:'Close details',exact:true}).click());await capture(page,'reviewer-completed-stale-queue-'+viewport.width);await action('Refresh queue to remove completed review','click',()=>page.getByRole('button',{name:'Refresh',exact:true}).click());await expect(page.getByRole('button',{name:'Open evaluation escalated',exact:true})).toHaveCount(0);expect(JSON.stringify(await f.store.evaluations())).toBe(original)
  appendFileSync(out+'/task-actions.ndjson',JSON.stringify({task:'Reviewer complete',viewport:viewport.width,actions,clicks:actions.filter(a=>a.kind==='click').length,inputs:actions.filter(a=>a.kind!=='click').length,scrollDistance:actions.reduce((s,a)=>s+Math.abs(a.afterY-a.beforeY),0),unnecessaryDetours:2})+'\n')
  expect(f.errors).toEqual([]);expect(f.blocked).toEqual([])
 }finally{await f.close()}
})
test('quality leader finds weak question, exact version and supporting evaluations',async({page})=>{
 const f=await fixture(page);const actions:string[]=[];try{
  await nav(page,'Analytics').click();actions.push('Analytics');await capture(page,'analytics-task-start');await page.getByRole('button',{name:'Queues',exact:true}).click();actions.push('Queues');await page.getByRole('button',{name:'Investigate queues: Customer care',exact:true}).click();actions.push('Customer care queue');await capture(page,'analytics-affected-queue');await page.getByRole('button',{name:'Forms',exact:true}).click();actions.push('Forms');
  await page.getByRole('button',{name:/Investigate forms: general_service@17/}).click();actions.push('General Customer Service v17');await capture(page,'analytics-questions');await page.getByRole('columnheader',{name:'Average score',exact:true}).getByRole('button').click();actions.push('Sort average score ascending');await capture(page,'analytics-worst-question');
  const row=page.locator('.operational-table tbody tr').first();const question=await row.innerText();await row.getByRole('button').first().click();actions.push('Open worst question supporting evaluations');await capture(page,'analytics-supporting-evaluations');expect(new URL(page.url()).searchParams.get('form')).toBe('general_service@17');expect(new URL(page.url()).searchParams.get('cohort')).toBe('analytics');expect(new URL(page.url()).searchParams.get('queue')).toBe('Customer care');
  appendFileSync(out+'/task-actions.ndjson',JSON.stringify({task:'Quality leader weak question to evidence',actions,clicks:actions.length,question,url:page.url(),unnecessaryDetours:0})+'\n')
 }finally{await f.close()}
})
test('admin review SLA dirty state and save failure preserves input',async({page})=>{
 const f=await fixture(page);try{await nav(page,'Settings').click();await page.getByRole('navigation',{name:'Settings sections'}).getByRole('button',{name:'Reviews',exact:true}).click();await page.getByLabel('Due soon hours',{exact:true}).fill('12');await expect(page.getByText(/Unsaved/).first()).toBeVisible();f.failures.set('PUT /api/governance',{status:503,error:'Settings could not be saved. Try again.'});await page.getByRole('button',{name:'Save all settings',exact:true}).click();await expect(page.getByRole('alert').first()).toBeVisible();await capture(page,'failure-settings-save');await expect(page.getByLabel('Due soon hours',{exact:true})).toHaveValue('12');f.failures.delete('PUT /api/governance');await page.getByRole('button',{name:'Save all settings',exact:true}).click();await capture(page,'settings-reviews-saved');appendFileSync(out+'/task-actions.ndjson',JSON.stringify({task:'Admin configure review SLA',clicks:3,inputs:1,actions:['Settings','Reviews','Due soon hours = 12','Save all settings'],failureRetryClicks:1})+'\n')}finally{await f.close()}
})
test('Question Group containing Answer Set is used as independent form copy',async({page})=>{
 test.setTimeout(90000);const f=await fixture(page,'AUTHOR');try{
  await nav(page,'Question Groups').click();await page.getByRole('button',{name:'New reusable question group',exact:true}).click();const group=page.locator('.asset-detail');await group.getByLabel('Reusable question group name',{exact:true}).fill('Resolution standards');await group.getByRole('button',{name:'Edit',exact:true}).click();await group.getByLabel('Title',{exact:true}).fill('Was the resolution clear?');await group.getByLabel('Instructions / question',{exact:true}).fill('Assess whether the resolution was explained clearly.');await group.getByRole('combobox',{name:'Question type',exact:true}).selectOption('choice');await capture(page,'group-composition-editor');await group.getByRole('button',{name:'Use reusable answer set'}).click();await group.getByRole('button',{name:'Use Resolution clarity v1'}).click();await group.getByRole('button',{name:'Save changes',exact:true}).click();await group.getByRole('button',{name:'Publish reusable question group'}).click();await capture(page,'group-with-answer-set')
  await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'＋ New form',exact:true}).click();const form=page.locator('.form-detail');await form.getByRole('button',{name:'Add reusable group'}).click();await capture(page,'group-picker-composition');await form.getByRole('button',{name:/Add Resolution standards/}).click();await form.getByRole('button',{name:'Save changes',exact:true}).click();await capture(page,'form-group-answer-set-composition');await expect(form).toContainText('Reusable snapshot v1');
 }finally{await f.close()}
})
test('mobile analytics/calibration tabs and inline Answer Set dialog semantics',async({page})=>{
 await page.setViewportSize({width:390,height:844});const f=await fixture(page,'AUTHOR');try{
  const probes=[];for(const name of ['Analytics','Calibration']){await nav(page,name).click();await capture(page,'mobile-tabs-'+name.toLowerCase());const selector='.analytics-tabs';probes.push({page:name,regions:await page.locator(selector).evaluateAll(es=>es.map(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,overflow:getComputedStyle(e).overflowX,tabindex:e.getAttribute('tabindex'),role:e.getAttribute('role')})))});const button=page.getByRole('button',{name:name==='Analytics'?'Coverage':'Confidence vs disagreement',exact:true});await button.focus();await page.keyboard.press('Enter');await capture(page,'mobile-tab-activated-'+name.toLowerCase())}
  await nav(page,'Evaluation Forms').click();await page.getByRole('button',{name:'Open form Resolution clarity form v1'}).click();const form=page.locator('.form-detail');await form.getByRole('button',{name:'Edit',exact:true}).click();await form.getByRole('button',{name:'Use reusable answer set'}).focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Use reusable answer set'});await expect(dialog.locator('h4')).toBeFocused();const tabs=[];for(let i=0;i<10;i++){await page.keyboard.press('Tab');tabs.push(await page.evaluate(()=>({text:(document.activeElement as HTMLElement).innerText||document.activeElement?.getAttribute('aria-label'),inside:!!document.activeElement?.closest('[role="dialog"]')})))}probes.push({page:'Answer Set picker',ariaModal:await dialog.getAttribute('aria-modal'),tabs});await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(form.getByRole('button',{name:'Use reusable answer set'})).toBeFocused();appendFileSync(out+'/accessibility-probes.ndjson',JSON.stringify(probes)+'\n')
 }finally{await f.close()}
})
