import {fixture,capture} from './whole-product-review-fixture';
import {test,expect} from '@playwright/test';
test('first-time author exploration',async({page})=>{
 const f=await fixture(page,'AUTHOR','attention','automation');
 try {
 const replayStart=Date.now();
 console.log('ROUTE',page.url());
 console.log('UI INITIAL',await page.locator('body').innerText());
 await capture(page,'first-author-01-initial');
 await page.getByText('Evaluation Forms',{exact:true}).click();
 console.log('UI FORMS',await page.locator('body').innerText());
 await capture(page,'first-author-02-forms');
 await page.getByRole('button',{name:'＋ New form',exact:true}).click();
 console.log('UI NEW',await page.locator('body').innerText());
 console.log('ARIA NEW',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-03-new-form');
 await page.getByRole('textbox',{name:'Form name',exact:true}).fill('First author resolution review');
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 console.log('ARIA EDIT',await page.locator('body').ariaSnapshot());
 await capture(page,'first-author-04-question-editor');
 await page.getByRole('textbox',{name:'Title',exact:true}).fill('Was the resolution clear?');
 await page.getByRole('textbox',{name:'Instructions / question',exact:true}).fill('Assess whether the customer understood the resolution.');
 await page.getByRole('combobox',{name:'Question type',exact:true}).selectOption({label:'Multiple choice · Choice'});
 console.log('ARIA MULTIPLE',await page.locator('article').ariaSnapshot());
 await capture(page,'first-author-05-multiple-choice');
 await page.getByRole('button',{name:'Use reusable answer set',exact:true}).click();
 console.log('ARIA ANSWER PICKER',await page.locator('body').ariaSnapshot());
 await capture(page,'first-author-06-answer-picker');
 await page.getByRole('button',{name:'Use Resolution clarity v1',exact:true}).click();
 console.log('ARIA APPLIED',await page.locator('article').ariaSnapshot());
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:/^Saved/})).toBeVisible();
 console.log('GOAL ONE REPLAY ELAPSED MS',Date.now()-replayStart);
 console.log('GOAL ONE SAVED',await page.locator('main').innerText());
 await capture(page,'first-author-07-form-saved');
 await page.getByRole('button',{name:'Question Groups',exact:true}).click();
 console.log('ARIA GROUP LIBRARY',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-08-group-library');
 await page.getByRole('button',{name:'Open reusable question group Resolution & Next Steps v1',exact:true}).click();
 console.log('ARIA GROUP DETAILS',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-09-group-details');
 await page.getByRole('button',{name:'Evaluation Forms',exact:true}).click();
 await page.getByRole('button',{name:'＋ New form',exact:true}).click();
 await page.getByRole('textbox',{name:'Form name',exact:true}).fill('First author next steps review');
 await page.getByRole('button',{name:'Add reusable group',exact:true}).click();
 console.log('ARIA GROUP PICKER',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-10-group-picker');
 await page.getByRole('button',{name:'Add Resolution & Next Steps',exact:true}).click();
 console.log('ARIA GROUP ADDED',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-11-group-added');
 await page.getByRole('region',{name:'Group: General',exact:true}).getByRole('button',{name:'Delete group',exact:true}).click();
 console.log('ARIA STARTER REMOVED',await page.locator('main').ariaSnapshot());
 await capture(page,'first-author-12-delete-starter-confirmation');
 await page.getByRole('button',{name:'Delete contained questions',exact:true}).click();
 await expect(page.locator('article')).toHaveCount(3);
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:/^Saved/})).toBeVisible();
 await page.getByRole('button',{name:'Close details',exact:true}).click();
 await page.getByRole('button',{name:'Open form First author next steps review v1',exact:true}).click();
 await expect(page.locator('article')).toHaveCount(3);
 await expect(page.getByRole('region',{name:'Group: Resolution & Next Steps',exact:true})).toBeVisible();
 console.log('GOAL TWO SAVED',await page.locator('main').innerText());
 console.log('BOTH GOALS REPLAY ELAPSED MS',Date.now()-replayStart);
 await capture(page,'first-author-13-second-form-saved');
 } finally {await f.close();}
});
