import { useDetailFocus } from './useDetailFocus'
import { usePermission } from './GovernancePanel'
import { useEffect, useRef, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { OperationalAlert } from './domain/operationalAlerts'
import { alertSummary } from './domain/operationalAlerts'
import { apiOrigin } from './domain/manualClient'
import { OperationalTable } from './OperationalTable'
export function AlertsPanel({session,onRun,onReview,selectedAlertId,selectedAlertRequest}:{session:AuthSession|null;onRun:(id:string)=>void;onReview:(id:string)=>void;selectedAlertId?:string|null;selectedAlertRequest?:number}){
  const [items,setItems]=useState<OperationalAlert[]>([]),[selected,setSelected]=useState<OperationalAlert|null>(null),[status,setStatus]=useState('ACTIVE'),[severity,setSeverity]=useState(''),[next,setNext]=useState<string|undefined>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[summary,setSummary]=useState({openAlertCount:0,errorAlertCount:0,warningAlertCount:0})
  const [deliveries,setDeliveries]=useState<Array<{id:string;destinationName:string;state:string;event:string;attemptCount:number}>>([]),[deliveryNext,setDeliveryNext]=useState<string|undefined>()
  useEffect(()=>{setDeliveries([]);setDeliveryNext(undefined);let active=true;if(selected&&session)void call(`/api/alerts/${selected.id}/notifications`).then(v=>{if(active){setDeliveries(v.items);setDeliveryNext(v.nextCursor)}}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[selected?.id,session?.accessToken])
  const acknowledge=usePermission('alerts.acknowledge'),resolve=usePermission('alerts.resolve')
  const sequence=useRef(0)
  const call=async(path:string,method='GET')=>{
    const response=await fetch(`${apiOrigin}${path}`,{method,headers:{Authorization:`Bearer ${session!.accessToken}`}}),body=await response.json()
    if(!response.ok)throw Error(body.error??'Operational alerts unavailable.')
    return body
  }
  const load=async(cursor?:string)=>{if(!session)return;const seq=++sequence.current;setBusy(true);setError('');try{const q=new URLSearchParams({limit:'50',status,severity});if(cursor)q.set('cursor',cursor);const [page,health]=await Promise.all([call(`/api/alerts?${q}`),call('/api/monitoring-health')]);if(seq===sequence.current){setItems(page.items);setNext(page.nextCursor);setSummary({openAlertCount:health.openAlertCount??alertSummary(page.items).openAlertCount,errorAlertCount:health.errorAlertCount??alertSummary(page.items).errorAlertCount,warningAlertCount:health.warningAlertCount??alertSummary(page.items).warningAlertCount})}}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'Alerts unavailable.')}finally{if(seq===sequence.current)setBusy(false)}}
  useEffect(()=>{setSelected(null);void load();return()=>{sequence.current++}},[session?.accessToken,status,severity])
  useEffect(()=>{let active=true;if(selectedAlertId&&session)void call(`/api/alerts/${selectedAlertId}`).then(v=>{if(active)setSelected(v.item??v)}).catch(e=>{if(active)setError(String(e))});return()=>{active=false}},[selectedAlertId,selectedAlertRequest,session?.accessToken])
  const focus=useDetailFocus(selected?.id)
  const act=async(alert:OperationalAlert,action:'acknowledge'|'resolve')=>{setBusy(true);try{const reply=await call(`/api/alerts/${alert.id}/${action}`,'POST');setSelected(reply.item);await load()}catch(e){setError(e instanceof Error?e.message:'Could not update alert.');setBusy(false)}}
  return <section className="panel operational-alerts" aria-label="Operational alerts"><div className="panel-heading"><h3 ref={focus.fallbackRef} tabIndex={-1}>Operational alerts <span className="pill">{summary.openAlertCount}</span></h3><button className="outline-button" disabled={busy} onClick={()=>void load()}>Refresh alerts</button></div><div className="health-grid"><div><small>Open alerts (including acknowledged)</small><strong>{summary.openAlertCount}</strong></div><div><small>Errors</small><strong>{summary.errorAlertCount}</strong></div><div><small>Warnings</small><strong>{summary.warningAlertCount}</strong></div></div><div className="browser-filters"><label>Alert status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Active</option><option value="OPEN">Open</option><option value="ACKNOWLEDGED">Acknowledged</option><option value="RESOLVED">Resolved</option><option value="">All</option></select></label><label>Alert severity<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All</option>{['INFO','WARNING','ERROR'].map(s=><option key={s}>{s}</option>)}</select></label></div>{error&&<p className="inline-error" role="alert">{error}</p>}
    <OperationalTable tableLabel="Operational alerts table" bounded selectionControl={{columnKey:'type',label:a=>`Open alert ${a.title}`}} rows={items} keyOf={a=>a.id} stateKey="operational-alerts" loading={busy} onSelect={a=>{focus.capture();setSelected(a)}} empty="No alerts match these filters." columns={[{key:'severity',label:'Severity',value:a=>a.severity},{key:'type',label:'Type',value:a=>a.title},{key:'policy',label:'Policy',value:a=>a.policyId??(a.source==='review-sla'?'Review workload':'Scheduler')},{key:'run',label:'Run',value:a=>a.runId??'—'},{key:'opened',label:'Opened',value:a=>a.createdAt},{key:'status',label:'Status',value:a=>a.status},{key:'action',label:'Action',value:a=>a.status,render:a=><div className="heading-actions">{acknowledge&&a.status==='OPEN'&&<button className="outline-button" disabled={busy} onClick={e=>{e.stopPropagation();void act(a,'acknowledge')}}>Acknowledge</button>}{resolve&&a.status!=='RESOLVED'&&<button className="outline-button" disabled={busy} onClick={e=>{e.stopPropagation();void act(a,'resolve')}}>Resolve</button>}</div>}]}/>
    {next&&<button className="outline-button" disabled={busy} onClick={()=>void load(next)}>Next alerts page →</button>}
    {selected&&<section className="panel alert-detail" aria-label="Alert detail"><div className="panel-heading"><h3 ref={focus.headingRef} tabIndex={-1}>{selected.title} · {selected.severity}</h3><button className="outline-button" onClick={()=>{setSelected(null);focus.restore()}}>Close alert</button></div><p>{selected.message}</p><p>{selected.type} · {selected.status} · Occurrences {selected.occurrences}</p>{selected.context&&<p>Due {new Date(selected.context.dueAt).toLocaleString()} · Assignee {selected.context.assigneeUserId??'Unassigned'}</p>}<p>Opened {selected.createdAt} · Last observed {selected.lastOccurredAt}</p>{selected.context?.evaluationId&&<button className="outline-button" onClick={()=>onReview(selected.context!.evaluationId)}>Open review</button>}{selected.runId&&<button className="outline-button" onClick={()=>onRun(selected.runId!)}>Inspect related run</button>}<dl>{Object.entries(selected.metadata).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl><h4>Notifications</h4>{deliveries.length?deliveries.map(d=><p key={d.id}>{d.destinationName} — {d.state} · {d.event} · {d.attemptCount} attempts</p>):<p>No notification deliveries recorded.</p>}{deliveryNext&&<button className="outline-button" onClick={()=>void call(`/api/alerts/${selected.id}/notifications?cursor=${deliveryNext}`).then(v=>{setDeliveries([...deliveries,...v.items]);setDeliveryNext(v.nextCursor)}).catch(e=>setError(String(e)))}>More alert notifications</button>}<h4>Alert history</h4>{selected.events.map((e,i)=><p key={i}>{e.action} · {e.at} · {e.reason??''} · {e.automatic?'Automatic recovery':e.actor?.displayName??e.actor?.userId??(selected.source==='review-sla'?'Review SLA':'Scheduler')}</p>)}</section>}
  </section>
}
