import { describe,it,expect } from 'vitest'
import { lowestApplicable,formLabels,formLabel,questionTitle,sampleLabel,coverageSteps,coverageInterpretation,qualityPercent,cohortDateLabel } from './analyticsPresentation'
import type { Breakdown } from './domain/analytics'
const row=(changes:Partial<Breakdown>={}):Breakdown=>({key:'Service v17 · Clear next step',formRef:'service@17',questionId:'next_step',count:24,applicableCount:24,averageScore:.58,passRate:null,criticalFailures:2,...changes})
describe('evidence-based presentation',()=>{
 it('summarizes dates for humans without changing UTC query boundaries',()=>{expect(cohortDateLabel('2026-09-01','2026-09-30')).toBe('1–30 September 2026');expect(cohortDateLabel('','')).toBe('All available dates');expect(cohortDateLabel('invalid','')).toBe('Selected dates')})
 it('withholds rankings without applicable records, scores or exact versions',()=>{expect(lowestApplicable([])).toBeUndefined();expect(lowestApplicable([row({applicableCount:0}),row({averageScore:null}),row({averageScore:NaN})])).toBeUndefined();expect(lowestApplicable([row({formRef:undefined})],true)).toBeUndefined()})
 it('does not treat null as zero; real zero is eligible',()=>{expect(lowestApplicable([row({averageScore:null}),row()])?.averageScore).toBe(.58);expect(lowestApplicable([row(),row({averageScore:0})])?.averageScore).toBe(0)})
 it('keeps exact versions distinct and resolves ties deterministically',()=>{const a=row(),b=row({formRef:'service@18',key:'Service v18 · Clear next step'});expect(lowestApplicable([b,a],true)).toBe(a);expect(lowestApplicable([a,b],true)).toBe(a);expect(lowestApplicable([a,{...b,averageScore:.5}],true)?.formRef).toBe('service@18');const c=row({questionId:'aaa'});expect(lowestApplicable([a,c],true)).toBe(c)})
 it('shows human identities, exact versions and sample counts',()=>{const names=formLabels([row({key:'service@17 · Service v17'})]);expect(formLabel('service@17',names)).toBe('Service v17');expect(formLabel('missing@18',names)).toBe('Unavailable form name · v18');expect(questionTitle(row())).toBe('Clear next step');expect(sampleLabel(row(),'question')).toBe('24 applicable answers');expect(sampleLabel(row(),'group')).toBe('24 applicable evaluations');expect(sampleLabel(row(),'queue')).toBe('24 evaluations');expect(qualityPercent(null)).toBe('—')})
 it('uses the existing denominators and canonical labels',()=>{const counts={candidate:1250,eligible:1000,sampled:500,evaluable:460,evaluated:450,failed:10};expect(coverageSteps(counts).map(s=>[s.label,s.count,s.rate])).toEqual([['Eligible',1000,null],['Sampled',500,.5],['Content available',460,.92],['Evaluated',450,450/460]]);expect(coverageInterpretation(counts).afterSelection).toEqual(['40 sampled interactions had no usable conversation content.','10 interactions had content available but did not reach a completed evaluation.']);expect(coverageSteps({...counts,eligible:0,sampled:0,evaluable:0,evaluated:0}).every(s=>s.rate===null)).toBe(true)})
 it('makes no causal, threshold or statistical-significance claim',()=>{const text=[sampleLabel(row(),'question'),...coverageInterpretation({candidate:1250,eligible:1000,sampled:500,evaluable:460,evaluated:450,failed:10}).afterSelection].join(' ');expect(text).not.toMatch(/bad|poor-performing|model problem|significan|cause|missed/i)})
})
