import { useEffect, useState } from 'react'
import { useDetailFocus } from './useDetailFocus'
import { OperationalTable } from './OperationalTable'
import { answerFormat } from './authoringPresentation'
import { OptionEditor } from './OptionEditor'
import { ResourceHistory, usePermission } from './GovernancePanel'
import { apiOrigin } from './domain/manualClient'
import { policyCall } from './domain/policyClient'
import { answerSetDirty, assertAnswerSetWrite, nextAnswerSetVersion, transitionAnswerSet } from './domain/answerSets'
import { seedAnswerSets } from './domain/seedAnswerSets'
import { downloadDefinition, exportDefinition, importDefinition, readImport } from './domain/portability'
import type { AuthSession } from './domain/genesysAuth'
import type { AnswerSetAsset, EvaluationForm } from './domain/types'
import type { SavedCollection } from './useSavedConfiguration'
const storage='genesys-aqm-v019-answer-sets'
export function useAnswerSets(session:AuthSession|null,saved:SavedCollection<AnswerSetAsset>) {
 const [localAnswerSets,setLocal]=useState<AnswerSetAsset[]>(()=>{try{const value=JSON.parse(localStorage.getItem(storage)??'null');return Array.isArray(value)?value:structuredClone(seedAnswerSets)}catch{return structuredClone(seedAnswerSets)}})
 const connected=!!session&&!!apiOrigin,assets=connected?saved.items:localAnswerSets
 const accept=(a:AnswerSetAsset)=>{if(connected)saved.accept(a);else{const next=[...localAnswerSets.filter(v=>v.id!==a.id),a];localStorage.setItem(storage,JSON.stringify(next));setLocal(next)}}
 const save=async(a:AnswerSetAsset)=>{
  assertAnswerSetWrite(assets.find(v=>v.id===a.id),a,assets)
  if(connected){const reply=await policyCall<{item:AnswerSetAsset}>(apiOrigin,session!,`/api/answer-sets/${a.id}`,'PUT',a);saved.accept(reply.item)}else accept(a)
 }
 return {assets,localAnswerSets,save,accept}
}
export function AnswerSetsPage({session,savedState,assets,localAnswerSets,forms,formsReady,onSave,onImported,onDirty}:{session:AuthSession|null;savedState:SavedCollection<AnswerSetAsset>;assets:AnswerSetAsset[];localAnswerSets:AnswerSetAsset[];forms:EvaluationForm[];formsReady:boolean;onSave:(a:AnswerSetAsset)=>Promise<void>;onImported:(a:AnswerSetAsset)=>void;onDirty:(name:string|null)=>void}) {
 const connected=!!session&&!!apiOrigin,canWrite=usePermission('forms.write')
 const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<AnswerSetAsset>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const asset=draft??assets.find(a=>a.id===selected),dirty=answerSetDirty(asset,assets.find(a=>a.id===asset?.id)),editable=canWrite&&asset?.status==='DRAFT',focus=useDetailFocus(asset?.id)
 useEffect(()=>{onDirty(dirty?asset!.name:null);return()=>onDirty(null)},[dirty,asset?.name,onDirty])
 const leave=()=>!dirty||window.confirm(`You have unsaved changes to ${asset!.name}. Leave this Answer Set and discard them?`)
 const select=(a:AnswerSetAsset)=>{if(busy||!leave())return;focus.capture();setSelected(a.id);setDraft(undefined);setError('');setNotice('')}
 const perform=async(a:AnswerSetAsset)=>{setBusy(true);setError('');try{const next={...a,updatedAt:new Date().toISOString()};await onSave(next);setSelected(next.id);setDraft(undefined);setNotice(`${next.name} v${next.version} saved as ${next.status}${connected?' in AQM':' in this browser'}.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const newDraft=()=>{if(!leave())return;focus.capture();const id=`answers_${crypto.randomUUID().replaceAll('-','')}`,now=new Date().toISOString();setDraft({id,familyId:id,name:'New Answer Set',description:'',type:'choice',options:[{key:'yes',label:'Yes',description:'Meets the standard.',credit:1},{key:'no',label:'No',description:'Does not meet the standard.',credit:0}],version:1,status:'DRAFT',createdAt:now,updatedAt:now});setSelected(id);setNotice('');setError('')}
 const importValue=async(value:unknown)=>{if(connected){const reply=await policyCall<{item:AnswerSetAsset}>(apiOrigin,session!,'/api/answer-sets/import','POST',value);onImported(reply.item);setSelected(reply.item.id);setDraft(undefined);setNotice('Answer Set imported as a new DRAFT.')}else await perform(importDefinition('answer-set',value,`answers_${crypto.randomUUID().replaceAll('-','')}`,new Date().toISOString()))}
 const lifecycle=(status:AnswerSetAsset['status'])=>{try{void perform(transitionAnswerSet(asset!,status,new Date().toISOString()))}catch(e){setError((e as Error).message)}}
 return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION</div><h1 ref={focus.fallbackRef} tabIndex={-1}>Answer Sets</h1><p>Reuse the same choices or rating scale across multiple questions.</p><p className="field-note">Published forms keep their own versioned copy.</p></div>{canWrite&&<div className="heading-actions"><label className="outline-button">Import Answer Set<input className="sr-only" aria-label="Import Answer Set" type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||!leave())return;setBusy(true);setError('');try{await importValue(await readImport(file))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label><button className="primary-button" disabled={busy} onClick={newDraft}>New Answer Set</button></div>}</div>
 {connected?<section aria-label="Saved Answer Sets"><h2>SAVED IN AQM · {assets.length} saved Answer Sets</h2><button className="outline-button" disabled={busy||savedState.loading} onClick={()=>void savedState.refresh()}>Refresh saved Answer Sets</button>{savedState.loading&&<p role="status">Loading saved Answer Sets…</p>}{savedState.error&&<p role="alert">Saved Answer Sets unavailable: {savedState.error}</p>}</section>:<p className="field-note">Saved in this browser. Connect to use saved AQM configuration.</p>}
 {!formsReady&&<p role="status">Saved form usage unavailable until saved forms load.</p>}
 <OperationalTable tableLabel="Answer Sets table" rows={assets} keyOf={a=>a.id} onSelect={select} selectionControl={{columnKey:'name',label:a=>`Open Answer Set ${a.name} v${a.version}`}} columns={[{key:'name',label:'Name',value:a=>a.name},{key:'type',label:'Answer format',value:a=>answerFormat(a.type)},{key:'version',label:'Version',value:a=>a.version,render:a=>`v${a.version}`},{key:'status',label:'Status',value:a=>a.status},{key:'options',label:'Answers',value:a=>a.options.length},{key:'used',label:'Used by forms',value:a=>formsReady?forms.filter(f=>f.questions.some(q=>q.sourceAnswerSet?.answerSetId===a.id&&q.sourceAnswerSet.familyId===a.familyId&&q.sourceAnswerSet.answerSetVersion===a.version)).length:'Unavailable'},{key:'updated',label:'Last modified',value:a=>a.updatedAt,render:a=>new Date(a.updatedAt).toLocaleDateString()}]}/>
 {connected&&<details className="panel local-library"><summary>LOCAL STARTERS &amp; DRAFTS · {localAnswerSets.length} Answer Sets</summary><p>Preserved in this browser. Not saved in AQM. Connected forms offer only published saved Answer Sets.</p>{localAnswerSets.map(a=><div key={a.id} className="panel"><strong>{a.name} · {answerFormat(a.type)} · v{a.version} · {a.status}</strong><p>{a.options.map(o=>o.label).join(' · ')}</p><div className="heading-actions"><button className="outline-button" onClick={()=>downloadDefinition('answer-set',a)}>Export local JSON</button>{canWrite&&<button className="outline-button" disabled={busy} onClick={()=>{if(!leave())return;void perform(importDefinition('answer-set',exportDefinition('answer-set',a),`answers_${crypto.randomUUID().replaceAll('-','')}`,new Date().toISOString()))}}>Save as AQM draft</button>}</div></div>)}</details>}
 {error&&<p role="alert" className="inline-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {asset&&<section className="answer-set-detail"><div className="panel"><div className="panel-heading"><h2 ref={focus.headingRef} tabIndex={-1}>{asset.name} · v{asset.version} · {asset.status}</h2><div className="heading-actions"><button className="outline-button" disabled={busy} onClick={()=>{if(!leave())return;setSelected(null);setDraft(undefined);focus.restore()}}>Close details</button><button className="outline-button" onClick={()=>downloadDefinition('answer-set',asset)}>Export JSON</button>{editable?<><button className="outline-button" disabled={busy} onClick={()=>void perform(asset)}>Save changes</button><button className="primary-button" disabled={busy} onClick={()=>lifecycle('PUBLISHED')}>Publish Answer Set</button></>:canWrite?<><button className="outline-button" disabled={busy} onClick={()=>{setDraft(nextAnswerSetVersion(asset,assets,new Date().toISOString()));setSelected(null);setNotice('')}}>Edit as new version</button>{asset.status==='PUBLISHED'&&<button className="outline-button" disabled={busy} onClick={()=>lifecycle('RETIRED')}>Retire Answer Set</button>}</>:null}</div></div>
 {!canWrite?<p className="field-note">You have read-only access. Your role can view this definition but cannot change it.</p>:!editable?<p className="field-note">{asset.status==='PUBLISHED'?'Published':'Retired'} version is locked. Create a new version to edit.</p>:<p role="status">{dirty?'Unsaved changes':'Saved'+(connected?' in AQM':' in this browser')}</p>}
 <div className="editor-grid"><label>Answer Set name<input readOnly={!editable||busy} value={asset.name} onChange={e=>setDraft({...asset,name:e.target.value})}/></label><label>Answer Set description<textarea readOnly={!editable||busy} value={asset.description} onChange={e=>setDraft({...asset,description:e.target.value})}/></label><label>Answer format<select aria-label="Answer format" disabled={!editable||busy||assets.some(a=>a.familyId===asset.familyId)} value={asset.type} onChange={e=>setDraft({...asset,type:e.target.value as AnswerSetAsset['type']})}><option value="choice">Multiple choice</option><option value="score">Ordered scale</option></select><small>Answer format cannot change after the first version is saved.</small></label></div>
 <OptionEditor type={asset.type} options={asset.options} readOnly={!editable||busy} onChange={options=>setDraft({...asset,options})}/></div><ResourceHistory session={session} type="answer_set" id={asset.id}/></section>}
 </div>
}
