import { useState } from 'react'
import { useDetailFocus } from './useDetailFocus'
import { answerSetComparison, applyAnswerSet, detachAnswerSet, saveAnswerSet, updateAnswerSet } from './domain/answerSets'
import type { AnswerSetAsset, EvaluationForm, ScorecardItem } from './domain/types'
export function AnswerSetQuestionTools({form,item,assets,onChange,onSave}:{form:EvaluationForm;item:ScorecardItem;assets:AnswerSetAsset[];onChange:(form:EvaluationForm)=>void;onSave?:(a:AnswerSetAsset)=>Promise<void>}) {
 const [mode,setMode]=useState<'picker'|'update'|'save'|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState('')
 const focus=useDetailFocus(mode?`${item.id}_${mode}`:undefined)
 if(item.type==='noul')return null
 const source=item.sourceAnswerSet,current=assets.find(a=>a.id===source?.answerSetId),latest=source?assets.filter(a=>a.familyId===source.familyId&&a.status==='PUBLISHED'&&a.version>source.answerSetVersion).sort((a,b)=>b.version-a.version)[0]:undefined
 const compatible=assets.filter(a=>a.type===item.type&&a.status==='PUBLISHED'&&a.name.toLowerCase().includes(search.toLowerCase()))
 const open=(next:typeof mode)=>{focus.capture();setError('');setNotice('');setMode(next);setPage(0);setSearch('');setName(item.title||'Reusable answers');setDescription('')}
 const close=()=>{setMode(null);focus.restore()}
 const run=(fn:()=>EvaluationForm)=>{try{setError('');onChange(fn());close();requestAnimationFrame(()=>focus.fallbackRef.current?.focus())}catch(e){setError((e as Error).message)}}
 let blocked='';if(mode==='update'&&latest)try{updateAnswerSet(form,item.id,latest)}catch(e){blocked=(e as Error).message}
 return <section className="answer-tools" aria-label="Answers"><h3 ref={focus.fallbackRef} tabIndex={-1}>ANSWERS</h3>{source?<><p>{current?.name??source.familyId} · v{source.answerSetVersion} · copied snapshot</p><p className="field-note">Options and type are read-only while attached. Detach to customize the copied answers.</p><div className="heading-actions">{latest&&<button className="outline-button" onClick={()=>open('update')}>Newer version available: v{latest.version}</button>}<button className="outline-button" onClick={()=>run(()=>detachAnswerSet(form,item.id))}>Detach</button></div></>:<div className="heading-actions"><button className="outline-button" onClick={()=>open('picker')}>Use reusable answer set</button>{onSave&&<button className="outline-button" onClick={()=>open('save')}>Save as reusable answer set</button>}</div>}
 {error&&<p role="alert" className="inline-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {mode&&<div className="panel answer-dialog" role="dialog" aria-label={mode==='picker'?'Use reusable answer set':mode==='update'?'Update Answer Set snapshot':'Save current answers'}><div className="panel-heading"><h4 ref={focus.headingRef} tabIndex={-1}>{mode==='picker'?'Published Answer Sets':mode==='update'?`Update to v${latest?.version}`:'Save current answers as a new family'}</h4><button className="outline-button" disabled={busy} onClick={close}>Cancel</button></div>
 {mode==='picker'&&<><label>Find Answer Set<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/></label><p>{compatible.length} published {item.type} sets. Each selection copies its options.</p>{compatible.slice(page*100,(page+1)*100).map(a=><div key={a.id} className="answer-picker-item"><strong>{a.name} · v{a.version}</strong><p>{a.options.length} options · {a.options.map(o=>o.label).join(' · ')}</p><button className="outline-button" onClick={()=>run(()=>applyAnswerSet(form,item.id,a))}>Use {a.name} v{a.version}</button></div>)}{!compatible.length&&<p>Publish a compatible Answer Set in Answer Sets first.</p>}<div className="heading-actions">{page>0&&<button onClick={()=>setPage(page-1)}>Previous sets</button>}{(page+1)*100<compatible.length&&<button onClick={()=>setPage(page+1)}>Next sets</button>}</div></>}
 {mode==='update'&&latest&&<><p>Current snapshot v{source!.answerSetVersion} → {latest.name} v{latest.version}. Apply explicitly to replace this question’s answers.</p><dl className="answer-comparison">{answerSetComparison(item.options,latest.options).map(d=><div key={d.label}><dt>{d.label}</dt><dd>{d.details.join(', ')||'None'}</dd></div>)}</dl><p>New option order: {latest.options.map(o=>`${o.label} (${o.key}, credit ${o.credit??'unscored'}${o.sourceValue===undefined?'':`, source ${o.sourceValue}`})`).join(' → ')}</p>{blocked&&<p role="alert" className="inline-error">{blocked}</p>}<button className="primary-button" disabled={!!blocked} onClick={()=>run(()=>updateAnswerSet(form,item.id,latest))}>Apply update to v{latest.version}</button></>}
 {mode==='save'&&<><div className="editor-grid"><label>Answer Set name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Answer Set description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Base type<input readOnly value={item.type}/></label></div><p>A new DRAFT family will be saved. Publish it separately from Answer Sets.</p><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{const a=saveAnswerSet(form,item.id,`answers_${crypto.randomUUID().replaceAll('-','')}`,name,description,new Date().toISOString());await onSave!(a);close();setNotice(`${a.name} saved as a new DRAFT Answer Set.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Create draft Answer Set</button></>}
 </div>}
 </section>
}
