import { useState } from 'react'
import { useDetailFocus } from './useDetailFocus'
import { applyAnswerSet, applyAnswerSetWithFormatChange, detachAnswerSet, saveAnswerSet, updateAnswerSet } from './domain/answerSets'
import { answerFormat, answerSetUpdateImpact, answerSetFormatChangeDependencies, discoverAnswerSets, creditLabel } from './authoringPresentation'
import type { AnswerSetAsset, EvaluationForm, ScorecardItem } from './domain/types'
export function AnswerSetQuestionTools({form,item,assets,onChange,onSave}:{form:EvaluationForm;item:ScorecardItem;assets:AnswerSetAsset[];onChange:(form:EvaluationForm)=>void;onSave?:(a:AnswerSetAsset)=>Promise<void>}) {
 const [selectedId,setSelectedId]=useState<string>(),[mode,setMode]=useState<'picker'|'update'|'save'|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState('')
 const focus=useDetailFocus(mode?`${item.id}_${mode}`:undefined)
 const previewFocus=useDetailFocus(mode==='picker'?selectedId:undefined)
 const source=item.sourceAnswerSet,current=assets.find(a=>a.id===source?.answerSetId),latest=source?assets.filter(a=>a.familyId===source.familyId&&a.status==='PUBLISHED'&&a.version>source.answerSetVersion).sort((a,b)=>b.version-a.version)[0]:undefined
 const discovered=discoverAnswerSets(assets,item.type,search),selected=discovered.find(a=>a.id===selectedId&&a.type!==item.type)
 const dependencies=selected?answerSetFormatChangeDependencies(form,item,selected):[]
 let formatBlocked='';if(mode==='picker'&&selected)try{applyAnswerSetWithFormatChange(form,item.id,selected)}catch(e){formatBlocked=(e as Error).message}
 const open=(next:typeof mode)=>{focus.capture();setError('');setNotice('');setMode(next);setSelectedId(undefined);setPage(0);setSearch('');setName(item.title||'Reusable answers');setDescription('')}
 const close=()=>{setMode(null);setSelectedId(undefined);focus.restore()}
 const run=(fn:()=>EvaluationForm)=>{try{setError('');onChange(fn());close();requestAnimationFrame(()=>{if(document.activeElement===document.body)focus.fallbackRef.current?.focus()})}catch(e){setError((e as Error).message)}}
 const impact=latest?answerSetUpdateImpact(form,item,latest):undefined
 let blocked='';if(mode==='update'&&latest)try{updateAnswerSet(form,item.id,latest)}catch(e){blocked=(e as Error).message}
 return <section className="answer-tools" aria-label="Answers"><h3 ref={focus.fallbackRef} tabIndex={-1}>Answers</h3>{source?<><p>Using {current?.name??'Answer Set'} v{source.answerSetVersion}</p><p className="field-note">This question keeps its own copy of the published answers. Detach if you want to customize them here.</p><div className="heading-actions">{latest&&<button className="outline-button" onClick={()=>open('update')}>Newer version available: v{latest.version}</button>}<button className="text-link" onClick={()=>{run(()=>detachAnswerSet(form,item.id));setNotice('Current answers kept. The reusable link is removed; future Answer Set versions will no longer be offered automatically.')}}>Detach and customize</button></div></>:<div className="heading-actions"><button className="primary-button" onClick={()=>open('picker')}>Use reusable Answer Set</button>{onSave&&item.type!=='noul'&&<button className="text-link" onClick={()=>open('save')}>Save as Answer Set</button>}</div>}
 {error&&<div role="alert" className="inline-error"><p>Could not change these answers. Check the answers and dependent conditions, then try again.</p><details><summary>Advanced details</summary>{error}</details></div>}{notice&&<p role="status">{notice}</p>}
 {mode&&<div className="panel answer-dialog" role="dialog" aria-label={mode==='picker'?'Use reusable Answer Set':mode==='update'?'Update Answer Set':'Save current answers'}><div className="panel-heading"><h4 ref={focus.headingRef} tabIndex={-1}>{mode==='picker'?'Published Answer Sets':mode==='update'?`${latest?.name} · update to v${latest?.version}`:'Save as Answer Set'}</h4><button className="outline-button" disabled={busy} onClick={close}>Cancel</button></div>
 {mode==='picker'&&<><label>Find Answer Set<input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);setSelectedId(undefined)}}/></label><p>{discovered.length} published Answer {discovered.length===1?'Set':'Sets'}.</p>{discovered.slice(page*100,(page+1)*100).map(a=><div key={a.id} className="answer-picker-item"><strong>{a.name} · v{a.version}</strong><p>{answerFormat(a.type)} · {a.options.length} {a.type==='score'?'levels':'answers'}</p><p>{a.options.map(o=>o.label).join(' · ')}</p>{a.type===item.type?<button className="primary-button" onClick={()=>run(()=>applyAnswerSet(form,item.id,a))}>Use {a.name} v{a.version}</button>:<><p>{a.name} uses {answerFormat(a.type)}. Your question currently uses {answerFormat(item.type)}.</p><button className="outline-button" onClick={()=>{previewFocus.capture();setSelectedId(a.id);setError('')}}>Preview {a.name} v{a.version} format change</button>
 {selected?.id===a.id&&<section className="answer-format-preview" aria-label={`${a.name} format change preview`}><h5 ref={previewFocus.headingRef} tabIndex={-1}>Change answer format</h5><p>This changes the answer format from {answerFormat(item.type)} to {answerFormat(a.type)} and replaces this question’s current answers with {a.name} v{a.version}.</p><p>The question wording, instructions, weight and position are kept.</p><p>Current answers: {item.type==='noul'?'Yes · No':item.options.map(o=>o.label).join(' · ')||'No answers yet'}</p><p>New answers, in order:</p><ol>{a.options.map(o=><li key={o.key}><strong>{o.label}</strong> · {creditLabel(o.credit)}<p>{o.description}</p></li>)}</ol>
 {formatBlocked&&<div role="alert" className="inline-error"><strong>CAN’T CHANGE ANSWER FORMAT YET</strong>{dependencies.length?dependencies.map((d,i)=><p key={i}>{d.dependentKind==='group'?'Group ':''}“{d.dependentTitle}” depends on {d.affectedAnswerLabel==='scored answers'?'scored answers':`the “${d.affectedAnswerLabel}” answer`} from this question. The new format {d.affectedAnswerLabel==='scored answers'?'has no scored answers':'cannot keep that answer dependency'}. Change or remove that condition first, then use {a.name}.</p>):<p>This form has unfinished or invalid questions or conditions. Repair them before changing these answers.</p>}<details><summary>Advanced details</summary>{formatBlocked}</details></div>}
 <div className="heading-actions"><button className="primary-button" disabled={!!formatBlocked} onClick={()=>run(()=>applyAnswerSetWithFormatChange(form,item.id,a))}>Change to {answerFormat(a.type)} and use {a.name} v{a.version}</button><button className="text-link" onClick={()=>{setSelectedId(undefined);previewFocus.restore()}}>Cancel format change</button></div></section>}
 </>}</div>)}{!discovered.length&&<p>{search.trim()?'No published Answer Sets match this search.':'No published Answer Sets are available in this library.'}</p>}<div className="heading-actions">{page>0&&<button onClick={()=>{setPage(page-1);setSelectedId(undefined)}}>Previous sets</button>}{(page+1)*100<discovered.length&&<button onClick={()=>{setPage(page+1);setSelectedId(undefined)}}>Next sets</button>}</div></>}
 {mode==='update'&&latest&&impact&&<><p>Review the answers below. Nothing changes until you update this question.</p>
 <div className="answer-diff" role="table" aria-label="Answer comparison"><div role="row" className="diff-heading"><strong role="columnheader">CURRENT · v{source!.answerSetVersion}</strong><strong role="columnheader">NEW · v{latest.version}</strong><strong role="columnheader">Changes</strong></div>{impact.changes.map(d=><div role="row" key={d.key}><div role="cell">{d.before?<><strong>{d.before.label}</strong><span>{creditLabel(d.before.credit)}</span><small>Position {item.options.findIndex(o=>o.key===d.key)+1}</small>{d.marks.includes('DESCRIPTION CHANGED')&&<p>{d.before.description}</p>}</>:'—'}</div><div role="cell">{d.after?<><strong>{d.after.label}</strong><span>{creditLabel(d.after.credit)}</span><small>Position {latest.options.findIndex(o=>o.key===d.key)+1}</small>{d.marks.includes('DESCRIPTION CHANGED')&&<p>{d.after.description}</p>}</>:'—'}</div><div role="cell" className="diff-marks">{d.marks.join(' · ')||'Unchanged'}</div></div>)}</div>
 <p>Resulting order: {latest.options.map(o=>o.label).join(' → ')}</p>
 {(blocked||impact.blockingDependencies.length>0)?<div role="alert" className="inline-error"><strong>CAN’T UPDATE YET</strong>{impact.blockingDependencies.length?impact.blockingDependencies.map((d,i)=><p key={i}>{latest.name} v{latest.version} {d.reason.includes('credit')?'removes credit from the answers':`removes “${d.affectedAnswerLabel}”`}. The condition on {d.dependentKind==='group'?'group ':''}“{d.dependentTitle}” {d.reason}. Change or remove that condition first, then try the update again.</p>):<p>{latest.type!==item.type?'The answer format does not match this question. Choose a published Answer Set with the same answer format.':'This form has unfinished or invalid questions or conditions. Repair them before updating these answers.'}</p>}</div>:<p>No dependent condition will break.</p>}
 <details className="advanced-details"><summary>Advanced details</summary>{impact.changes.map(d=><p key={d.key}>Key {d.key} · External/source value {d.before?.sourceValue??'Not supplied'} → {d.after?.sourceValue??'Not supplied'}</p>)}{blocked&&<p>{blocked}</p>}</details>
 <button className="primary-button" disabled={!!blocked||impact.blockingDependencies.length>0} onClick={()=>run(()=>updateAnswerSet(form,item.id,latest))}>Update this question to v{latest.version}</button></>}
 {mode==='save'&&<><p>Create a reusable copy of these answers. This question keeps its current answers until you choose to attach the new Answer Set.</p><div className="editor-grid"><label>Answer Set name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Answer Set description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label></div><p>Answer format: {answerFormat(item.type)}</p><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{const a=saveAnswerSet(form,item.id,`answers_${crypto.randomUUID().replaceAll('-','')}`,name,description,new Date().toISOString());await onSave!(a);close();setNotice(`${a.name} was created as a draft Answer Set. Publish it from Answer Sets before using it elsewhere.`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Create draft Answer Set</button></>}
 </div>}
 </section>
}
