import { useEffect, useRef, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { EvaluationForm, EvaluationRecord, InteractionPolicy, PolicyRun } from './domain/types'
import { summarize, summarizeCoverage } from './domain/analytics'
import { nextDueAfter, type Schedule } from './server/schedules'
import { OperationalTable, type Column } from './OperationalTable'

const origin=(import.meta.env.VITE_AQM_API_ORIGIN??'').trim().replace(/\/$/,'')
interface Snapshot {policies:InteractionPolicy[];forms:EvaluationForm[];schedules:Schedule[];runs:PolicyRun[];evaluations:EvaluationRecord[]}
const empty:Snapshot={policies:[],forms:[],schedules:[],runs:[],evaluations:[]}
function localInput(date:Date){return new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,16)}
export function AutomationPanel({session,localPolicies,localForms}:{session:AuthSession|null;localPolicies:InteractionPolicy[];localForms:EvaluationForm[]}){
  const refreshSequence=useRef(0)
  const [data,setData]=useState<Snapshot>(empty),[state,setState]=useState<'not-configured'|'disconnected'|'connected'|'error'>(origin?'disconnected':'not-configured')
  const [message,setMessage]=useState(''),[selected,setSelected]=useState(''),[frequency,setFrequency]=useState<Schedule['frequency']>('MANUAL'),[localTime,setLocalTime]=useState('02:00'),[weekday,setWeekday]=useState(1)
  const [from,setFrom]=useState(()=>localInput(new Date(Date.now()-86400_000))),[to,setTo]=useState(()=>localInput(new Date()))
  const [preview,setPreview]=useState<{fingerprint:string;expectedEvaluations:number;candidateCount:number;eligibleCount:number;sampledCount:number;selected:Array<{conversationId:string;pendingFormIds:string[]}>}|null>(null)
  const [busy,setBusy]=useState(false),[selectedRun,setSelectedRun]=useState<string|null>(null)
  const call=async(path:string,method='GET',payload?:unknown)=>{
    if(!session)throw new Error('Connect to Genesys Cloud in Settings first.')
    const response=await fetch(`${origin}${path}`,{method,headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:payload===undefined?undefined:JSON.stringify(payload)})
    const result=await response.json() as Record<string,unknown>
    if(!response.ok)throw new Error(typeof result.error==='string'?result.error:`Automation service returned HTTP ${response.status}.`)
    return result
  }
  const refresh=async()=>{
    if(!origin||!session)return
    const request=++refreshSequence.current
    try{const [policies,forms,schedules,runs,evaluations]=await Promise.all(['/api/policies?limit=100','/api/forms?limit=100','/api/schedules','/api/runs?limit=100','/api/evaluations?limit=100'].map(path=>call(path)))
      if(request!==refreshSequence.current)return
      setData({policies:policies.items as InteractionPolicy[],forms:forms.items as EvaluationForm[],schedules:schedules.items as Schedule[],runs:runs.items as PolicyRun[],evaluations:evaluations.items as EvaluationRecord[]});setState('connected')
    }catch(error){if(request===refreshSequence.current){setState('error');setMessage(error instanceof Error?error.message:'Automation service could not be reached.')}}
  }
  useEffect(()=>{void refresh();return()=>{refreshSequence.current++}},[session?.accessToken])
  const action=async(work:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await work();await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Action failed.')}finally{setBusy(false)}}
  const publish=()=>action(async()=>{for(const form of localForms.filter(f=>f.enabled))await call(`/api/forms/${encodeURIComponent(form.id)}`,'PUT',form)
    for(const policy of localPolicies)await call(`/api/policies/${encodeURIComponent(policy.id)}`,'PUT',policy)
    setMessage('Local forms and policies published to the automation service. Browser history remains local.')})
  const saveSchedule=()=>action(async()=>{if(!selected)throw new Error('Select a server policy.')
    const schedule:Schedule={id:`schedule_${selected}`,policyId:selected,enabled:frequency!=='MANUAL',frequency,timezone:'Europe/London',localTime,weekday,version:1}
    schedule.nextDueAt=nextDueAfter(schedule,new Date().toISOString())
    await call(`/api/schedules/${schedule.id}`,'PUT',schedule)
    setMessage('Schedule saved.')})
  const period=()=>({periodStart:new Date(from).toISOString(),periodEnd:new Date(to).toISOString()})
  const plan=()=>action(async()=>{if(!selected)throw new Error('Select a server policy.');const result=await call(`/api/policies/${selected}/plan`,'POST',{period:period()});setPreview(result as unknown as typeof preview)})
  const run=()=>action(async()=>{if(!selected||!preview)throw new Error('Preview a plan first.');const result=await call(`/api/policies/${selected}/run`,'POST',{period:period(),fingerprint:preview.fingerprint});setPreview(null);setMessage(`Run ${(result.run as PolicyRun).status}.`)})
  const schedule=data.schedules.find(s=>s.policyId===selected)
  const quality=summarize(data.evaluations.filter(r=>r.conversationSource==='genesys-cloud'&&r.purpose!=='FORM_TEST'))
  const coverage=summarizeCoverage(data.runs.filter(r=>r.source==='genesys-cloud'))
  return <div className="page-content"><div className="panel run-panel"><div className="panel-heading"><div><span className="mini-label">V0.5 DURABLE AUTOMATION</span><h2>Automation service</h2></div><span className="pill">{state==='connected'?'Connected':state==='not-configured'?'Not configured':state==='disconnected'?'Connect to Genesys':'Unavailable'}</span></div>
    <p>Server policies, schedules, runs, and evaluations are stored separately from this browser's V0.4 local data. Only real Genesys conversations are processed by automation. Server runs use the Jev key in Secret Manager; no browser Jev key is needed here.</p>
    {state==='connected'&&<><p>{data.policies.length} loaded server policies · {data.schedules.length} schedules · {data.runs.length} loaded runs · {data.evaluations.length} loaded evaluations</p><button className="outline-button" disabled={busy} onClick={publish}>Publish local forms and policies to server</button><button className="outline-button" disabled={busy} onClick={()=>void refresh()}>Refresh durable data</button>
      <div className="browser-filters"><label>Server policy<select value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null);const s=data.schedules.find(x=>x.policyId===e.target.value);setFrequency(s?.frequency??'MANUAL');setLocalTime(s?.localTime??'02:00');setWeekday(s?.weekday??1)}}><option value="">Select policy</option>{data.policies.map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version??1}</option>)}</select></label></div>
      {selected&&<><h3>Run frequency</h3><div className="monitoring-options">{(['MANUAL','DAILY','WEEKLY'] as const).map(f=><label key={f}><input type="radio" name="server-frequency" checked={frequency===f} onChange={()=>setFrequency(f)}/>{f==='MANUAL'?'Manual':f==='DAILY'?'Daily · previous day':'Weekly · previous Monday–Sunday'}</label>)}</div>
        {frequency!=='MANUAL'&&<div className="browser-filters">{frequency==='WEEKLY'&&<label>Run on<select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((day,i)=><option key={day} value={i+1}>{day}</option>)}</select></label>}<label>Local time<input type="time" value={localTime} onChange={e=>setLocalTime(e.target.value)}/></label><label>Timezone<input value="Europe/London" readOnly/></label></div>}
        <p>Next run: {schedule?.nextDueAt?new Date(schedule.nextDueAt).toLocaleString('en-GB',{timeZone:'Europe/London'}):'—'} · Last attempted: {schedule?.lastAttemptedAt??'—'} · Last successful: {schedule?.lastSuccessfulAt??'—'}</p><button className="outline-button" disabled={busy} onClick={saveSchedule}>Save server schedule</button>
        <h3>Manual server run</h3><p>Plan → preview → confirm → execute. A fresh plan is required if the selected population changes.</p><div className="browser-filters"><label>From<input type="datetime-local" value={from} onChange={e=>{setFrom(e.target.value);setPreview(null)}}/></label><label>To<input type="datetime-local" value={to} onChange={e=>{setTo(e.target.value);setPreview(null)}}/></label></div><button className="primary-button" disabled={busy} onClick={plan}>Build server plan</button>
        {preview&&<div className="confirmation panel"><strong>Confirm real Genesys evaluation</strong><p>{preview.candidateCount} candidates · {preview.eligibleCount} eligible · {preview.sampledCount} sampled · {preview.expectedEvaluations} Jev evaluations</p><ul>{preview.selected.map(item=><li key={item.conversationId}>{item.conversationId}: {item.pendingFormIds.join(', ')||'No pending forms'}</li>)}</ul><button className="primary-button" disabled={busy||!preview.expectedEvaluations} onClick={run}>Confirm and execute on server</button><button className="outline-button" onClick={()=>setPreview(null)}>Cancel</button></div>}</>}
      <div className="panel health-panel"><h3>Operational health</h3><div className="health-grid"><div><small>Automation service</small><strong>{state==='connected'?'Connected':'Unavailable'}</strong></div><div><small>Genesys automation</small><strong>{data.runs.some(item=>item.failures.some(failure=>failure.reason.includes('genesys_auth')))?'Recent authentication error':'Configured · live access unverified'}</strong></div><div><small>Jev</small><strong>{data.runs.some(item=>item.evaluationsSucceeded>0)?'Recent successful evaluation':'Configured · execution unverified'}</strong></div><div><small>Policies</small><strong>{data.policies.filter(item=>item.enabled).length} enabled · {data.policies.filter(item=>!item.enabled).length} disabled</strong></div><div><small>Runs</small><strong>{data.runs.filter(item=>item.status==='completed').length} successful · {data.runs.filter(item=>item.status==='partial-failure').length} partial · {data.runs.filter(item=>item.status==='failed').length} failed</strong></div><div><small>Last successful run</small><strong>{[...data.runs].filter(item=>item.status==='completed').sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0]?.completedAt??'—'}</strong></div><div><small>Next scheduled run</small><strong>{[...data.schedules].filter(item=>item.enabled&&item.nextDueAt).sort((a,b)=>a.nextDueAt!.localeCompare(b.nextDueAt!))[0]?.nextDueAt??'—'}</strong></div><div><small>Last scheduler attempt</small><strong>{[...data.schedules].filter(item=>item.lastAttemptedAt).sort((a,b)=>b.lastAttemptedAt!.localeCompare(a.lastAttemptedAt!))[0]?.lastAttemptedAt??'—'}</strong></div></div><p className="field-note">Counts reflect the loaded server page. Configuration status is inferred from available runtime observations; no secret values are exposed.</p></div>
      <h3>Durable operational results</h3><p>Quality (loaded page): {quality.evaluations} real evaluations · average {quality.averageScore===null?'—':`${Math.round(quality.averageScore*100)}%`} · pass rate {quality.passRate===null?'—':`${Math.round(quality.passRate*100)}%`}</p><p>Coverage (loaded runs): {coverage.eligible} eligible / {coverage.sampled} sampled / {coverage.evaluated} evaluated · {coverage.failed} failed evaluations</p><p>{data.runs.filter(r=>r.executionMode==='scheduled').length} scheduled runs · {data.runs.filter(r=>r.executionMode==='manual').length} manual server runs · {data.evaluations.filter(r=>r.executionMode==='scheduled').length} automatic evaluations</p><p>{data.runs.filter(r=>r.status==='completed').length} completed · {data.runs.filter(r=>r.status==='partial-failure').length} partial · {data.runs.filter(r=>r.status==='failed').length} failed</p>
      <div className="panel analytics-panel"><h3>Automation by policy</h3><div className="coverage-table"><div className="coverage-row heading"><span>Policy</span><span>Frequency</span><span>Next due</span><span>Last run</span><span>Last success</span></div>{data.policies.map(policy=>{const s=data.schedules.find(item=>item.policyId===policy.id);const last=[...data.runs].filter(r=>r.policyId===policy.id).sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];return <div className="coverage-row" key={policy.id}><strong>{policy.name}</strong><span>{s?.enabled?s.frequency:'Manual'}</span><span>{s?.nextDueAt?new Date(s.nextDueAt).toLocaleString('en-GB',{timeZone:'Europe/London'}):'—'}</span><span>{last?`${last.status} · ${new Date(last.startedAt).toLocaleDateString('en-GB')}`:'—'}</span><span>{s?.lastSuccessfulAt?new Date(s.lastSuccessfulAt).toLocaleDateString('en-GB'):'—'}</span></div>})}</div></div>
      <h3>Monitoring runs</h3><OperationalTable rows={data.runs} stateKey="runs" columns={[{key:'started',label:'Started',value:(item:PolicyRun)=>item.startedAt},{key:'policy',label:'Policy',value:(item:PolicyRun)=>item.policySnapshot.name},{key:'source',label:'Source',value:(item:PolicyRun)=>item.source},{key:'period',label:'Period',value:(item:PolicyRun)=>item.period?`${item.period.periodStart} – ${item.period.periodEnd}`:'—'},{key:'trigger',label:'Trigger',value:(item:PolicyRun)=>item.executionMode??'manual'},{key:'eligible',label:'Eligible',value:(item:PolicyRun)=>item.coverage?.eligibleCount??item.matchedConversationCount},{key:'sampled',label:'Sampled',value:(item:PolicyRun)=>item.coverage?.sampledCount??0},{key:'success',label:'Succeeded',value:(item:PolicyRun)=>item.evaluationsSucceeded},{key:'failed',label:'Failed',value:(item:PolicyRun)=>item.evaluationsFailed},{key:'status',label:'Status',value:(item:PolicyRun)=>item.status}] satisfies Column<PolicyRun>[]} keyOf={item=>item.id} onSelect={item=>setSelectedRun(item.id)}/>{data.runs.filter(item=>item.id===selectedRun).map(item=><div className="panel run-detail" key={item.id}><h3>{item.policySnapshot.name} · {item.status}</h3><p>Run {item.id} · Policy v{item.policySnapshot.version??1} · {item.executionMode??'manual'} · {item.startedAt} to {item.completedAt??'in progress'}</p><p>Candidate {item.coverage?.candidateCount??item.candidateConversationCount} → eligible {item.coverage?.eligibleCount??item.matchedConversationCount} → sampled {item.coverage?.sampledCount??item.sampledConversationIds?.length??0} → transcript available {item.coverage?.evaluableCount??item.evaluableCount??0} → evaluated {item.coverage?.evaluatedConversationCount??0}</p><p>Selected interactions: {item.sampledConversationIds?.join(', ')||'Not recorded'}</p><p>Resulting evaluations: {data.evaluations.filter(record=>record.policyRunId===item.id).map(record=>record.id).join(', ')||'None on loaded page'}</p>{item.failures.map((failure,index)=><p className="inline-error" key={index}>{failure.conversationId} {failure.formId}: {failure.reason}</p>)}</div>)}</>}
    {message&&<p role="status">{message}</p>}{state==='not-configured'&&<p>Set VITE_AQM_API_ORIGIN when the trusted API is deployed. Synthetic and browser local features remain available.</p>}{state==='disconnected'&&<p>Connect with Genesys PKCE in Settings to access the server.</p>}
  </div></div>
}
