import { useEffect, useRef, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { CalibrationAnalytics, CalibrationGroup } from './domain/calibration'
import { apiOrigin } from './domain/manualClient'
import { OperationalTable, type Column } from './OperationalTable'
import { reviewPercent } from './ReviewPanel'
const gap=(value:number|null)=>value===null?'—':`${(value*100).toFixed(1)} pp`
export function CalibrationPage({session,onExplore}:{session:AuthSession|null;onExplore:(filters:Record<string,string>)=>void}){
  const [data,setData]=useState<CalibrationAnalytics|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const [source,setSource]=useState('genesys-cloud'),[form,setForm]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[agent,setAgent]=useState(''),[queue,setQueue]=useState('')
  const [tab,setTab]=useState<'forms'|'groups'|'questions'|'types'|'confidence'>('forms'),[selected,setSelected]=useState<CalibrationGroup|null>(null)
  const sequence=useRef(0)
  useEffect(()=>{const current=++sequence.current;setData(null);setSelected(null);if(!session||!apiOrigin)return;const timer=setTimeout(async()=>{setLoading(true);setError('');try{const url=new URL(`${apiOrigin}/api/calibration`);for(const [key,value] of Object.entries({source,form,from:from?`${from}T00:00:00.000Z`:'',to:to?`${to}T23:59:59.999Z`:'',agent,queue}))if(value)url.searchParams.set(key,value);const reply=await fetch(url,{headers:{Authorization:`Bearer ${session.accessToken}`}});const body=await reply.json() as CalibrationAnalytics&{error?:string};if(!reply.ok)throw Error(body.error??'Calibration unavailable.');if(sequence.current===current)setData(body)}catch(reason){if(sequence.current===current)setError(reason instanceof Error?reason.message:'Calibration unavailable.')}finally{if(sequence.current===current)setLoading(false)}},200);return()=>{clearTimeout(timer);sequence.current++}},[session?.accessToken,source,form,from,to,agent,queue])
  const rows=data?.[tab==='forms'?'byForm':tab==='groups'?'byGroup':tab==='questions'?'byQuestion':tab==='types'?'byType':'confidenceBands']??[]
  const columns:Column<CalibrationGroup>[]=[{key:'name',label:tab==='confidence'?'Confidence band':tab==='questions'?'Question':'Dimension',value:item=>item.label,width:'240px'},...(tab==='groups'?[{key:'aiScore',label:'AI group score',value:(item:CalibrationGroup)=>item.aiAverageCredit??-1,render:(item:CalibrationGroup)=>reviewPercent(item.aiAverageCredit)},{key:'humanScore',label:'Human group score',value:(item:CalibrationGroup)=>item.humanAverageCredit??-1,render:(item:CalibrationGroup)=>reviewPercent(item.humanAverageCredit)}]:[]),...(tab==='confidence'?[]:[{key:'reviewed',label:'Reviews',value:(item:CalibrationGroup)=>item.reviewed}]),{key:'questions',label:'Questions',value:item=>item.questions},{key:'rate',label:'Exact agreement',value:item=>item.agreementRate??-1,render:item=>reviewPercent(item.agreementRate)},{key:'disagreed',label:'Disagreements',value:item=>item.disagreements},...((tab==='forms'||tab==='groups')?[{key:'gap',label:'Mean score gap',value:(item:CalibrationGroup)=>item.meanScoreDifference??-1,render:(item:CalibrationGroup)=>gap(item.meanScoreDifference)}]:tab==='questions'?[{key:'ai',label:'AI credit',value:(item:CalibrationGroup)=>item.aiAverageCredit??-1,render:(item:CalibrationGroup)=>reviewPercent(item.aiAverageCredit)},{key:'human',label:'Human credit',value:(item:CalibrationGroup)=>item.humanAverageCredit??-1,render:(item:CalibrationGroup)=>reviewPercent(item.humanAverageCredit)},{key:'difference',label:'Mean credit gap',value:(item:CalibrationGroup)=>item.averageAbsoluteCreditDifference??-1,render:(item:CalibrationGroup)=>gap(item.averageAbsoluteCreditDifference)},{key:'agreeConfidence',label:'Confidence: agree',value:(item:CalibrationGroup)=>item.confidenceOnAgreements??-1,render:(item:CalibrationGroup)=>reviewPercent(item.confidenceOnAgreements)},{key:'disagreeConfidence',label:'Confidence: disagree',value:(item:CalibrationGroup)=>item.confidenceOnDisagreements??-1,render:(item:CalibrationGroup)=>reviewPercent(item.confidenceOnDisagreements)}]:[])]
  const explore=(item:CalibrationGroup,comparison='',evaluationId='')=>onExplore({source:source==='all'?'':source,form:item.formRef??form,reviewQuestion:item.questionId??'',reviewStatus:'REVIEWED',comparison,evaluationId,agent,queue,from,to,evaluationSource:'server'})
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">HUMAN + AI</div><h1>Calibration</h1><p>Compare completed human reviews with the original AI evaluations.</p></div></div>
    <div className="panel browser-filters"><label>Calibration source<select value={source} onChange={event=>setSource(event.target.value)}><option value="genesys-cloud">Real Genesys only</option><option value="synthetic">Synthetic only</option><option value="all">All sources</option><option value="uploaded">Uploaded only</option><option value="unknown">Unknown provenance</option></select></label><label>Calibration form @ version<input value={form} placeholder="form_id@17" onChange={event=>setForm(event.target.value)}/></label><label>Calibration agent<input value={agent} onChange={event=>setAgent(event.target.value)}/></label><label>Calibration queue<input value={queue} onChange={event=>setQueue(event.target.value)}/></label><label>Calibration from<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Calibration to<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></div>
    <p className="field-note">Diagnostic evidence from completed reviews. Exact agreement is descriptive; sample size does not establish statistical confidence or causality. Human scores do not replace Quality KPIs.</p>
    {!session&&<div className="panel empty-state"><h2>Connect to view calibration</h2><p>Use Settings to sign in with your authorized Genesys identity.</p></div>}{loading&&<p role="status">Loading calibration…</p>}{error&&<p className="inline-error" role="alert">{error}</p>}
    {data&&<><div className="metrics-grid calibration-metrics"><div className="metric panel"><small>Evaluations reviewed</small><strong>{data.metrics.evaluationsReviewed}</strong></div><div className="metric panel"><small>Questions reviewed</small><strong>{data.metrics.questionsReviewed}</strong></div><div className="metric panel"><small>Exact agreement</small><strong>{reviewPercent(data.metrics.exactAgreementRate)}</strong></div><div className="metric panel"><small>Mean absolute score gap</small><strong>{gap(data.metrics.averageAbsoluteScoreDifference)}</strong></div><div className="metric panel"><small>Unresolved reviews</small><strong>{data.metrics.unresolved}</strong><small>{data.metrics.inReview} in progress</small></div></div>
    <div className="analytics-tabs" role="group" aria-label="Calibration breakdown">{(['forms','groups','questions','types','confidence'] as const).map(value=><button key={value} className={tab===value?'active':''} onClick={()=>{setTab(value);setSelected(null)}}>{value==='forms'?'Form / version':value==='groups'?'Groups':value==='questions'?'Questions':value==='types'?'Question types':'Confidence vs disagreement'}</button>)}</div>
    {tab==='confidence'&&<div className="panel calibration-explanation"><h2>Confidence vs disagreement</h2><p>Noul uses the probability of the AI’s selected Yes/No answer. Choice and Score use provider confidence when supplied. Missing confidence has its own band. These counts describe this reviewed sample.</p></div>}
    {tab==='questions'&&!form?<p className="panel">Select a form/version to inspect its questions.</p>:<OperationalTable rows={rows} columns={columns} keyOf={item=>item.key} stateKey={`calibration.${tab}`} onSelect={tab==='forms'?item=>{setForm(item.formRef!);setTab('questions')}:tab==='questions'?setSelected:undefined} empty="No completed reviews match these filters."/>}
    {selected&&<section className="panel calibration-drill" aria-label="Question calibration drill-down"><div className="panel-heading"><div><span className="mini-label">{selected.formRef}</span><h2>{selected.label}</h2><p>{selected.reviewed} reviewed · {selected.agreements} agree / {selected.disagreements} disagree</p></div><button className="outline-button" onClick={()=>setSelected(null)}>Close question</button></div><div className="review-actions"><button className="outline-button" onClick={()=>explore(selected)}>Open reviewed evaluations</button><button className="outline-button" onClick={()=>explore(selected,'disagreements')}>Open disagreements</button></div><div className="reviewed-evaluation-links">{selected.evaluationIds.map(id=><button className="coverage-drill" key={id} onClick={()=>explore(selected,'',id)}>Evaluation {id} →</button>)}</div></section>}
    </>}
  </div>
}
