import type { FormCondition, ScorecardItem } from './domain/types'
export function conditionSummary(condition:FormCondition,questions:ScorecardItem[]):string {
  if(condition.kind==='interaction_metadata')return `${condition.field} ${condition.operator??'equals'} ${(condition.equals===undefined?condition.values:[condition.equals]).join(', ')}`
  const question=questions.find(q=>q.id===condition.questionId),title=question?.title||'Unavailable question'
  return condition.kind==='question_credit'?`${title} credit ${condition.operator==='less_than'?'<':'≥'} ${Number((condition.value*100).toFixed(6))}%`:`${title} ${condition.operator??'in'} ${condition.outcomes.map(key=>question?.type==='noul'?key:question?.options.find(o=>o.key===key)?.label??'Unavailable answer').join(', ')}`
}
export function ConditionBuilder({condition,earlier,onChange,readOnly=false,label='Run when'}:{condition?:FormCondition;earlier:ScorecardItem[];onChange:(condition?:FormCondition)=>void;readOnly?:boolean;label?:string}){
  const available=earlier.filter(q=>q.enabled),source=condition?.kind??'interaction_metadata'
  const chooseQuestion=(id:string,kind:'question_outcome'|'question_credit')=>{const q=available.find(q=>q.id===id);if(kind==='question_credit')onChange({kind,questionId:id,operator:'less_than',value:.67});else onChange({kind,questionId:id,operator:'equals',outcomes:[q?.type==='noul'?'Yes':q?.options[0]?.key??'']})}
  if(!condition)return readOnly?null:<button className="outline-button" onClick={()=>onChange({kind:'interaction_metadata',field:'channel',operator:'equals',values:['email']})}>{label==='Run this group when'?'Add group condition':'Add question condition'}</button>
  const ref=condition.kind!=='interaction_metadata'?available.find(q=>q.id===condition.questionId):undefined
  return <div className="condition-builder"><p className="field-note"><strong>{label} {conditionSummary(condition,earlier)}</strong></p>{!readOnly&&<><div className="condition-fields"><label>Condition source<select value={source} onChange={e=>{if(e.target.value==='interaction_metadata')onChange({kind:'interaction_metadata',field:'channel',operator:'equals',values:['email']});else chooseQuestion(available.filter(q=>e.target.value==='question_credit'||q.type!=='score')[0]?.id??'',e.target.value as 'question_outcome'|'question_credit')}}><option value="interaction_metadata">Interaction field</option><option value="question_outcome" disabled={!available.some(q=>q.type!=='score')}>Previous question outcome</option><option value="question_credit" disabled={!available.length}>Previous question credit</option></select></label>
    {condition.kind==='interaction_metadata'?<><label>Interaction field<select value={condition.field} onChange={e=>onChange({...condition,field:e.target.value as typeof condition.field})}>{['channel','queue','direction','topic'].map(field=><option key={field}>{field}</option>)}</select></label><label>Operator<select value={condition.operator??'equals'} onChange={e=>onChange({kind:condition.kind,field:condition.field,operator:e.target.value as 'equals'|'in',values:condition.equals===undefined?condition.values:[condition.equals]})}><option value="equals">equals</option><option value="in">in</option></select></label><label>Condition value<input value={(condition.equals===undefined?condition.values:[condition.equals]).join(', ')} onChange={e=>onChange({kind:condition.kind,field:condition.field,operator:condition.operator??'equals',values:e.target.value.split(',').map(v=>v.trim())})}/><small>Separate multiple values with commas for “in”.</small></label></>:<><label>Previous question<select value={condition.questionId} onChange={e=>chooseQuestion(e.target.value,condition.kind)}><option value="" disabled>Select earlier question</option>{available.filter(q=>condition.kind==='question_credit'||q.type!=='score').map(q=><option key={q.id} value={q.id}>{q.title}</option>)}</select></label>
    {condition.kind==='question_credit'?<><label>Operator<select value={condition.operator} onChange={e=>onChange({...condition,operator:e.target.value as typeof condition.operator})}><option value="less_than">less than</option><option value="greater_than_or_equal">greater than or equal</option></select></label><label>Credit threshold (%)<input type="number" min="0" max="100" step="any" value={Number((condition.value*100).toFixed(6))} onChange={e=>onChange({...condition,value:Number(e.target.value)/100})}/></label></>:<><label>Operator<select value={condition.operator??'in'} onChange={e=>onChange({...condition,operator:e.target.value as 'equals'|'in'})}><option value="equals">equals</option><option value="in">in</option></select></label><label>Outcome<select multiple={condition.operator==='in'} value={condition.operator==='in'?condition.outcomes:condition.outcomes[0]??''} onChange={e=>onChange({...condition,outcomes:Array.from(e.target.selectedOptions).map(o=>o.value)})}>{ref?.type==='noul'?['Yes','No'].map(value=><option key={value}>{value}</option>):ref?.options.map(o=><option value={o.key} key={o.key}>{o.label}</option>)}</select></label></>}
    </>}</div><button className="text-link" onClick={()=>onChange(undefined)}>Remove condition</button></>}</div>
}
