import { useState } from 'react'
import type { Conversation, ConversationSource, EvaluationForm, FormTestRun } from './domain/types'
import { sampleLibrary } from './domain/conversations'
import { toScorecard, validateForm } from './domain/forms'
import { recordEvaluation } from './domain/evaluations'
import { validateScorecard } from './domain/validation'
import { JevProxyProvider } from './provider/jev'

const storageKey='genesys-aqm-v06-form-tests'
const provider=new JevProxyProvider((import.meta.env.VITE_JEV_PROXY_URL??'').trim())
function read():FormTestRun[]{try{const value=JSON.parse(localStorage.getItem(storageKey)??'[]') as unknown;return Array.isArray(value)?value as FormTestRun[]:[]}catch{return []}}
const hash=(value:string)=>{let n=2166136261;for(const char of value)n=Math.imul(n^char.charCodeAt(0),16777619);return n>>>0}
export function FormTestPanel({form,source,keyValue,onSettings}:{form:EvaluationForm;source:ConversationSource;keyValue:string;onSettings:()=>void}){
  const [sampleSource,setSampleSource]=useState<'synthetic'|'genesys-cloud'>('synthetic'),[strategy,setStrategy]=useState<'manual'|'recent'|'deterministic-random'>('recent'),[count,setCount]=useState(5),[seed,setSeed]=useState('form-test'),[selected,setSelected]=useState<string[]>([])
  const [runs,setRuns]=useState<FormTestRun[]>(read),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[active,setActive]=useState<string|null>(null)
  const [candidates,setCandidates]=useState<Conversation[]>(sampleLibrary.map(item=>item.conversation))
  const chooseSource=(value:'synthetic'|'genesys-cloud')=>{setSampleSource(value);setCandidates(value==='synthetic'?sampleLibrary.map(item=>item.conversation):[]);setSelected([])}
  const loadRecent=async()=>{setBusy(true);setMessage('');try{const to=new Date(),from=new Date(to.getTime()-7*86400_000);const page=await source.list({from:from.toISOString(),to:to.toISOString(),page:1,pageSize:20});setCandidates(page.conversations);setMessage(`${page.conversations.length} recent interactions available for selection. Transcripts load only during the test.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not list interactions.')}finally{setBusy(false)}}
  const ordered=strategy==='deterministic-random'?[...candidates].sort((a,b)=>hash(`${seed}|${a.conversationId}`)-hash(`${seed}|${b.conversationId}`)): [...candidates].sort((a,b)=>b.startedAt.localeCompare(a.startedAt))
  const sample=(strategy==='manual'?candidates.filter(item=>selected.includes(item.conversationId)):ordered.slice(0,count)).slice(0,20)
  const run=async()=>{
    if(!keyValue){onSettings();return}
    if([...validateForm(form),...validateScorecard(toScorecard(form))].length){setMessage('Fix form validation before testing.');return}
    if(!sample.length){setMessage('Select at least one conversation.');return}
    setBusy(true);setMessage('');const snapshot=structuredClone(form)
    const output:FormTestRun={id:crypto.randomUUID(),formId:form.id,formSnapshot:snapshot,createdAt:new Date().toISOString(),sampleSource,selectedConversationIds:sample.map(item=>item.conversationId),sampleConfiguration:{strategy,count:sample.length,seed:strategy==='deterministic-random'?seed:undefined},expectedRequests:sample.length,results:[],failures:[]}
    for(const candidate of sample){try{const conversation=sampleSource==='genesys-cloud'?await source.load(candidate.conversationId):candidate;if(!conversation.messages.length)throw new Error('Transcript unavailable.');const result=await provider.evaluate({conversation,scorecard:toScorecard(snapshot),evaluatedAt:new Date().toISOString(),version:'v0'},keyValue);const record=recordEvaluation(conversation,snapshot,result,[]);record.purpose='FORM_TEST';output.results.push(record);output.provider=result.provider;output.model=result.model}catch(error){output.failures.push({conversationId:candidate.conversationId,reason:error instanceof Error?error.message:'Test failed.'})}setMessage(`${output.results.length+output.failures.length} / ${sample.length} conversations processed`)}
    const next=[output,...runs].slice(0,20);setRuns(next);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{setMessage('Test completed, but browser storage is full. Results are available until this page is closed.')}setActive(output.id);setBusy(false)
  }
  const family=(item:FormTestRun)=>(item.formSnapshot.familyId??item.formSnapshot.id)===(form.familyId??form.id)
  const current=runs.find(item=>item.id===active&&family(item))??runs.find(family)
  return <section className="panel form-test"><div className="panel-heading"><div><span className="mini-label">ISOLATED SANDBOX</span><h2>Test form</h2></div></div><p>Try this exact form draft on a small sample. Results stay in this browser's test history and do not count toward production quality, coverage, or monitoring.</p><div className="browser-filters"><label>Source<select value={sampleSource} onChange={event=>chooseSource(event.target.value as typeof sampleSource)}><option value="synthetic">Synthetic</option><option value="genesys-cloud">Genesys Cloud</option></select></label><label>Selection<select value={strategy} onChange={event=>setStrategy(event.target.value as typeof strategy)}><option value="recent">Most recent</option><option value="deterministic-random">Deterministic random</option><option value="manual">Manual selection</option></select></label><label>Conversations<input type="number" min="1" max="20" value={count} onChange={event=>setCount(Math.max(1,Math.min(20,Number(event.target.value)||1)))}/></label>{strategy==='deterministic-random'&&<label>Seed<input value={seed} onChange={event=>setSeed(event.target.value)}/></label>}{sampleSource==='genesys-cloud'&&<button className="outline-button" disabled={busy} onClick={()=>void loadRecent()}>Load recent</button>}</div>{strategy==='manual'&&<div className="test-candidates">{candidates.map(item=><label key={item.conversationId}><input type="checkbox" checked={selected.includes(item.conversationId)} onChange={event=>setSelected(event.target.checked?[...selected,item.conversationId]:selected.filter(id=>id!==item.conversationId))}/>{item.conversationId} · {item.agent.name}</label>)}</div>}<p><strong>{sample.length} conversations · {form.questions.filter(item=>item.enabled).length} questions · {sample.length} expected Jev requests</strong></p><p className="field-note">Jev receives all enabled questions in one request per conversation. Maximum sample size: 20.</p><button className="primary-button" disabled={busy||!sample.length} onClick={()=>void run()}>{busy?'Testing…':'Test form'}</button>{message&&<p role="status">{message}</p>}
    {runs.some(family)&&<><div className="panel-heading"><h3>Recent test runs</h3><button className="outline-button" onClick={()=>{const next=runs.filter(item=>!family(item));setRuns(next);setActive(null);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{setMessage('Browser storage could not be updated.')}}}>Clear this form's test history</button></div><div className="test-history">{runs.filter(family).map(item=><button key={item.id} className={current?.id===item.id?'active':''} onClick={()=>setActive(item.id)}>{new Date(item.createdAt).toLocaleString()} · v{item.formSnapshot.version} · {item.results.length}/{item.selectedConversationIds.length} completed</button>)}</div></>}
    {current&&<div className="test-results"><h3>Test results</h3><p>{current.selectedConversationIds.length} selected · {current.formSnapshot.questions.filter(item=>item.enabled).length} questions · {current.expectedRequests} expected Jev requests · {current.results.length} completed · {current.failures.length} failed · {current.provider??'Provider unavailable'} {current.model??''}</p>{current.failures.map(item=><p className="inline-error" key={item.conversationId}>{item.conversationId}: {item.reason}</p>)}<h4>Per conversation</h4>{current.results.map(item=><details key={item.id}><summary>{item.conversationId} · {item.overallScore===null?'Unscored':Math.round(item.overallScore*100)+'%'} · {item.criticalFailures.length} critical failures</summary>{item.questions.map(question=><p key={question.id}>{question.title}: {question.outcome} · {question.credit===null?'Unscored':Math.round(question.credit*100)+'%'} credit {question.confidence===undefined?'':`· ${Math.round(question.confidence*100)}% confidence`}</p>)}</details>)}<h4>Per question</h4>{current.formSnapshot.questions.filter(item=>item.enabled).map(question=>{const values=current.results.flatMap(item=>item.questions.filter(result=>result.id===question.id));const passing=values.filter(item=>item.credit!==null&&item.credit>=.67).length;const lowConfidence=values.filter(item=>(item.confidence??item.probability??1)<.6).length;const scored=values.filter(item=>item.credit!==null);const average=scored.length?Math.round(scored.reduce((total,item)=>total+item.credit!,0)/scored.length*100):null;const distribution=[...new Set(values.map(item=>item.outcome))].map(outcome=>`${outcome}: ${values.filter(item=>item.outcome===outcome).length}`).join(', ');const critical=current.results.filter(item=>item.criticalFailures.includes(question.id)).length;return <p key={question.id}><strong>{question.title}</strong> · {values.length} answers · {passing} pass · average {average===null?'—':`${average}%`} · {critical} critical failures · {lowConfidence} low confidence · {distribution||'No answers'} {values.length>=3&&(passing===0||passing===values.length||lowConfidence>values.length/2)?'· Potentially worth reviewing.':''}</p>})}</div>}
  </section>
}
