import { createContext, useContext, useEffect, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import { defaultGovernance, pendingGovernanceSections, roles, rolePermissions, type Permission, type SessionAccess, type GovernanceSettings, type RoleAssignment, type AuditEvent } from './domain/governance'
import { apiOrigin } from './domain/manualClient'
import { clearGenesysContentCache } from './domain/cachedSource'
import { conversationCache } from './domain/conversationCache'
import { OperationalTable } from './OperationalTable'
export const AccessContext=createContext<readonly Permission[]>(rolePermissions.ADMIN)
export const usePermission=(p:Permission)=>useContext(AccessContext).includes(p)
export async function governanceCall(session:AuthSession,path:string,method='GET',value?:unknown){
 const r=await fetch(`${apiOrigin}${path}`,{method,headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},...(value!==undefined?{body:JSON.stringify(value)}:{})}),v=await r.json()
 if(!r.ok)throw Error(`${r.status===403?'Forbidden (403): ':''}${v.error??'Governance request failed.'}`);return v
}
export function useAccess(session:AuthSession|null){
 const [access,setAccess]=useState<SessionAccess|null>(null),[error,setError]=useState('')
 useEffect(()=>{setAccess(null);setError('');let active=true
  if(!session||!apiOrigin)return
  const load=async()=>{try{const [a,s]=await Promise.all([governanceCall(session,'/api/session'),governanceCall(session,'/api/governance')]);if(!roles.includes(a.role)||!Array.isArray(a.permissions))throw Error('Session permissions unavailable.');if(active){setAccess(a);setError('');await conversationCache.setContentCacheHours(s.browserContentCacheHours)}}catch(e){if(active){setAccess(null);setError(e instanceof Error?e.message:'Session permissions unavailable.')}}}
  void load();const timer=setInterval(()=>void load(),30000);return()=>{active=false;clearInterval(timer)}
 },[session?.accessToken])
 return {access,error,permissions:session?(access?.permissions??rolePermissions.VIEWER):rolePermissions.ADMIN}
}
export function ResourceHistory({session,type,id}:{session:AuthSession|null;type:string;id:string}){
 const allowed=usePermission('history.read'),[items,setItems]=useState<AuditEvent[]|null>(null),[next,setNext]=useState<string|undefined>(),[error,setError]=useState('')
 useEffect(()=>{setItems(null);setNext(undefined);setError('')},[id])
 const load=async(cursor?:string)=>{try{const q=new URLSearchParams({resourceType:type,resourceId:id,limit:'20'});if(cursor)q.set('cursor',cursor);const v=await governanceCall(session!,`/api/history?${q}`);setItems(v.items);setNext(v.nextCursor)}catch(e){setError(String(e))}}
 return session&&allowed?<div className="resource-history"><button className="text-link" onClick={()=>void load()}>View history</button>{error&&<p role="alert">{error}</p>}{items&&<><p>Recorded changes for this version</p>{items.map(e=><p key={e.id}>{new Date(e.occurredAt).toLocaleString()} · {e.actor.displayName??e.actor.userId} · {e.summary}</p>)}{!items.length&&<p>No recorded changes.</p>}{next&&<button onClick={()=>void load(next)}>Next history page</button>}</>}</div>:null
}
export function GovernancePanel({session,onDirty}:{session:AuthSession|null;onDirty:(dirty:boolean)=>void}){
 const manage=usePermission('roles.manage')&&!!session,audit=usePermission('audit.read')&&!!session,write=usePermission('settings.write')&&!!session,purge=usePermission('retention.execute')&&!!session
 const [savedSettings,setSavedSettings]=useState<GovernanceSettings>(defaultGovernance),[loaded,setLoaded]=useState(false),[savedAt,setSavedAt]=useState('')
 const [settings,setSettings]=useState<GovernanceSettings>(defaultGovernance),[assignments,setAssignments]=useState<RoleAssignment[]>([]),[roleCursor,setRoleCursor]=useState<string|undefined>(),[userId,setUserId]=useState(''),[role,setRole]=useState('VIEWER')
 const [events,setEvents]=useState<AuditEvent[]>([]),[filters,setFilters]=useState({from:'',to:'',actor:'',resourceType:'',action:''}),[cursor,setCursor]=useState<string|undefined>(),[detail,setDetail]=useState<AuditEvent|null>(null)
 const [plan,setPlan]=useState<{id:string;counts:Record<string,number>;scanned:number;complete:boolean;continuation:Record<string,string>;executed?:boolean}|null>(null),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const pending=pendingGovernanceSections(savedSettings,settings),dirty=pending.length>0
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false)},[dirty,onDirty])
 // Every settings edit invalidates the preview, including restoring saved values.
 useEffect(()=>{setPlan(null);setConfirmation('')},[settings])
 const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(false)}}
 const loadRoles=async(cursor?:string)=>{const v=await governanceCall(session!,`/api/roles${cursor?`?cursor=${cursor}`:''}`);setAssignments(v.items);setRoleCursor(v.nextCursor)}
 // Permission refreshes must not reload and overwrite working settings.
 useEffect(()=>{setLoaded(false);if(!session)return;let active=true
  void governanceCall(session,'/api/governance').then(response=>{if(!active)return;const value={...defaultGovernance,...response};setSavedSettings(value);setSettings(value);setLoaded(true)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load saved settings.')})
  return()=>{active=false}
 },[session?.accessToken])
 useEffect(()=>{if(!manage||!session)return;let active=true
  void governanceCall(session,'/api/roles').then(v=>{if(active){setAssignments(v.items);setRoleCursor(v.nextCursor)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Could not load roles.')})
  return()=>{active=false}
 },[session?.accessToken,manage])
 const loadAudit=async(next?:string)=>{const q=new URLSearchParams({limit:'50',...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))});if(next)q.set('cursor',next);const v=await governanceCall(session!,`/api/audit?${q}`);setEvents(v.items);setCursor(v.nextCursor);setDetail(null)}
 return <section className="page-content governance" aria-label="Governance"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION & PRIVACY</div><h1>Governance</h1><p>Access, change history and safe data retention.</p></div></div>{write&&<section className="panel" aria-label="Save all settings"><h2>Governance settings</h2><p role="status">{dirty?`Unsaved settings: ${pending.join(', ')}`:savedAt?`Saved ${savedAt}`:loaded?'All settings saved':'Loading saved settings…'}</p><p>Save all settings applies every pending change to privacy / browser cache, review reminders and retention.</p><div className="heading-actions"><button className="primary-button" disabled={busy||!loaded||!dirty} onClick={()=>{if(!dirty||!loaded)return;void perform(async()=>{const s=await governanceCall(session!,'/api/governance','PUT',settings);setSavedSettings(s);setSettings(s);setPlan(null);setSavedAt(new Date().toLocaleTimeString());await conversationCache.setContentCacheHours(s.browserContentCacheHours);setNotice('All governance settings saved. No data deleted.')})}}>Save all settings</button>{dirty&&<button className="outline-button" disabled={busy} onClick={()=>{setSettings(structuredClone(savedSettings));setPlan(null);setConfirmation('');setNotice('Settings changes discarded.')}}>Discard changes</button>}</div></section>}<div className="panel"><h2>Privacy & data inventory</h2><p>Stored server-side: EvaluationRecords, form snapshots, PolicyRuns, HumanReviews, alerts, role assignments, audit events and configuration.</p><p>Not stored server-side: raw voice transcripts, raw email bodies, raw message transcripts, Genesys OAuth tokens, signed media URLs or raw EML/ZIP.</p><p>Browser only: normalized conversation content, with the configured cache lifetime. Search results have an independent short lifetime.</p><p>Browser sandbox evaluation history is separate. Clear or reset it using the existing browser controls.</p><label>Browser conversation cache hours<input type="number" min="0" max="168" step="1" disabled={!write||busy||!loaded} value={settings.browserContentCacheHours} onChange={e=>{setPlan(null);setSettings({...settings,browserContentCacheHours:Number(e.target.value)})}}/></label><p>0 disables persistent conversation content. Default: 24 hours.</p><button className="outline-button" disabled={busy} onClick={()=>void perform(async()=>{await clearGenesysContentCache();setNotice('Cached conversation content cleared in this browser.')})}>Clear cached conversation content now</button></div>
 <section className="panel" aria-label="Review reminders"><h2>Review reminders</h2><p>Only reviews with an explicit due date are monitored.</p><div className="browser-filters"><label>Due soon hours<input aria-label="Due soon hours" type="number" min="1" max="168" step="1" disabled={!write||busy||!loaded} value={settings.reviewSla.dueSoonHours} onChange={e=>setSettings({...settings,reviewSla:{...settings.reviewSla,dueSoonHours:Number(e.target.value)}})}/><small>Hours before due time</small></label><label>No escalation<input type="checkbox" checked={settings.reviewSla.overdueEscalationHours===null} disabled={!write||busy||!loaded} onChange={e=>setSettings({...settings,reviewSla:{...settings.reviewSla,overdueEscalationHours:e.target.checked?null:48}})}/></label>{settings.reviewSla.overdueEscalationHours!==null&&<label>Escalation hours<input aria-label="Escalation hours" type="number" min="1" max="720" step="1" disabled={!write||busy||!loaded} value={settings.reviewSla.overdueEscalationHours} onChange={e=>setSettings({...settings,reviewSla:{...settings.reviewSla,overdueEscalationHours:Number(e.target.value)}})}/><small>Hours after due time</small></label>}</div>{write&&<div className="review-actions"><button className="outline-button" disabled={busy||dirty||!loaded} onClick={()=>{if(dirty||!loaded)return;void perform(async()=>{const result=await governanceCall(session!,'/api/review-sla/refresh','POST',{});setNotice(result.complete?`Review SLA refreshed: ${result.open} open reviews.`:'Review SLA scan incomplete')})}}>Refresh review SLA state</button></div>}</section>
 {write&&<div className="panel"><h2>Server retention</h2><p>Blank means retain indefinitely. Saving settings never deletes data. Evaluation purges also remove their dependent reviews. Active alerts are retained.</p><div className="browser-filters">{(['evaluationRetentionDays','reviewRetentionDays','policyRunRetentionDays','alertRetentionDays','auditRetentionDays','notificationDeliveryRetentionDays'] as const).map(k=><label key={k}>{({evaluationRetentionDays:'Evaluation retention days',reviewRetentionDays:'Review retention days',policyRunRetentionDays:'Policy run retention days',alertRetentionDays:'Resolved alert retention days',auditRetentionDays:'Audit retention days',notificationDeliveryRetentionDays:'Notification delivery retention days'})[k]}<input disabled={busy||!loaded} type="number" min="1" max="36500" value={settings[k]??''} placeholder="Indefinite" onChange={e=>{setPlan(null);setSettings({...settings,[k]:e.target.value===''?null:Number(e.target.value)})}}/></label>)}</div></div>}
 {purge&&<div className="panel"><h2>Retention preview & purge</h2><p>Preview uses saved settings. Each window scans at most 300 records. Counts below apply to this window; continue for more records.</p><button className="outline-button" disabled={busy||dirty||!loaded} onClick={()=>{if(dirty||!loaded)return;void perform(async()=>{setPlan(await governanceCall(session!,'/api/retention/preview','POST',{}));setConfirmation('')})}}>Preview retention</button>{dirty&&<p>Save or discard Settings changes before previewing retention. Refresh review SLA state also uses saved settings and is unavailable until changes are saved or discarded.</p>}{plan&&!dirty&&<><p>{plan.scanned} records scanned · {plan.complete?'Final window':'More windows remain'}</p><ul>{Object.entries(plan.counts).map(([k,v])=><li key={k}>{k}: {v} eligible for deletion</li>)}</ul>{!plan.executed?<><label>Type PURGE to confirm this window<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="danger-button" disabled={busy||confirmation!=='PURGE'} onClick={()=>void perform(async()=>{const result=await governanceCall(session!,'/api/retention/execute','POST',{planId:plan.id,confirmation});setPlan(result.plan);setConfirmation('');setNotice('Purge window completed and audited.')})}>Confirm purge window</button></>:<p>Window completed. Repeating this operation does not delete again.</p>}{!plan.complete&&<button className="outline-button" disabled={busy||!plan.executed} onClick={()=>void perform(async()=>{setPlan(await governanceCall(session!,'/api/retention/preview','POST',{cursors:plan.continuation}));setConfirmation('')})}>Preview next window</button>}</>}</div>}
 {manage&&<div className="panel"><h2>Role administration</h2><p>Assignments use Genesys user IDs from the server allowlist. The configured bootstrap owner retains ADMIN access.</p><div className="browser-filters"><label>Genesys user ID<input value={userId} onChange={e=>setUserId(e.target.value)}/></label><label>Assigned role<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><button className="primary-button" disabled={busy||!userId} onClick={()=>void perform(async()=>{await governanceCall(session!,`/api/roles/${encodeURIComponent(userId)}`,'PUT',{role});await loadRoles();setNotice('Role assignment saved.')})}>Assign role</button></div><OperationalTable rows={assignments} keyOf={r=>r.id} columns={[{key:'user',label:'User',value:r=>r.displayName??r.userId},{key:'role',label:'Role',value:r=>r.role},{key:'updated',label:'Updated',value:r=>r.updatedAt}]}/>{roleCursor&&<button onClick={()=>void perform(()=>loadRoles(roleCursor))}>Next role page</button>}</div>}
 {audit&&<div className="panel"><h2>Audit history</h2><div className="browser-filters">{Object.keys(filters).map(k=><label key={k}>{({from:'Audit from',to:'Audit to',actor:'Actor user ID',resourceType:'Resource type',action:'Audit action'})[k]}<input type={k==='from'||k==='to'?'date':'text'} value={filters[k as keyof typeof filters]} onChange={e=>{setCursor(undefined);setFilters({...filters,[k]:e.target.value})}}/></label>)}</div><button className="outline-button" disabled={busy} onClick={()=>void perform(()=>loadAudit())}>Load audit history</button><OperationalTable rows={events} keyOf={e=>e.id} onSelect={setDetail} columns={[{key:'time',label:'Time',value:e=>e.occurredAt},{key:'actor',label:'Actor',value:e=>e.actor.displayName??e.actor.userId},{key:'action',label:'Action',value:e=>e.action},{key:'resource',label:'Resource',value:e=>`${e.resourceType}: ${e.resourceId}`},{key:'summary',label:'Summary',value:e=>e.summary}]}/>{cursor&&<button disabled={busy} onClick={()=>void perform(()=>loadAudit(cursor))}>Next audit page</button>}{detail&&<div className="panel"><h3>Audit event detail</h3><p>{detail.id} · {detail.correlationId}</p><p>{detail.actor.userId} · {detail.resourceId}</p><pre>{JSON.stringify(detail.metadata,null,2)}</pre></div>}</div>}
 {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section>
}
