import { useEffect, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import { alertTypes } from './domain/operationalAlerts'
import type { NotificationDelivery, NotificationDestination, NotificationRule } from './domain/notifications'
import { governanceCall, usePermission } from './GovernancePanel'
import { OperationalTable } from './OperationalTable'
type Destination=NotificationDestination&{configured?:boolean;signed?:boolean;lastDelivery?:{state:string;updatedAt:string}}
const initialDestination={id:'',name:'',type:'WEBHOOK' as 'WEBHOOK'|'EMAIL',enabled:true,urlSecretRef:'',signingSecretRef:'',apiKeySecretRef:'',from:'',to:''}
const initialRule={id:'',name:'',enabled:true,severities:['ERROR'],alertTypes:[] as string[],destinationIds:[] as string[],notifyOnResolution:false,policyId:''}
export function NotificationsPanel({session}:{session:AuthSession|null}){
 const read=usePermission('notifications.read'),write=usePermission('notifications.write'),test=usePermission('notifications.test')
 const [destinations,setDestinations]=useState<Destination[]>([]),[rules,setRules]=useState<NotificationRule[]>([]),[deliveries,setDeliveries]=useState<NotificationDelivery[]>([]),[next,setNext]=useState<string|undefined>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [destination,setDestination]=useState<typeof initialDestination|null>(null),[rule,setRule]=useState<typeof initialRule|null>(null)
 const load=async()=>{if(!session)return;const [d,r,h]=await Promise.all(['destinations','rules','deliveries'].map(k=>governanceCall(session,`/api/notifications/${k}`)));setDestinations(d.items);setRules(r.items);setDeliveries(h.items);setNext(h.nextCursor)}
 useEffect(()=>{if(read&&session)void load().catch(e=>setError(String(e)))},[read,session?.accessToken])
 const perform=async(work:()=>Promise<void>,refresh=true)=>{setBusy(true);setError('');setNotice('');try{await work();if(refresh)await load()}catch(e){setError(e instanceof Error?e.message:'Notification request failed.')}finally{setBusy(false)}}
 const editDestination=(d:Destination)=>setDestination({...initialDestination,id:d.id,name:d.name,type:d.type,enabled:d.enabled,from:d.configuration.from??'',to:d.configuration.to?.join(', ')??''})
 const saveDestination=()=>perform(async()=>{
  const d=destination!,configuration=d.type==='WEBHOOK'?{...(d.urlSecretRef?{urlSecretRef:d.urlSecretRef}:{}),...(d.signingSecretRef?{signingSecretRef:d.signingSecretRef}:{})}:{provider:'RESEND',from:d.from,to:d.to.split(',').map(v=>v.trim()).filter(Boolean),...(d.apiKeySecretRef?{apiKeySecretRef:d.apiKeySecretRef}:{})}
  const id=d.id||crypto.randomUUID();await governanceCall(session!,`/api/notifications/destinations/${id}`,'PUT',{id,name:d.name,type:d.type,enabled:d.enabled,configuration});setDestination(null);setNotice('Notification destination saved.')
 })
 const saveRule=()=>perform(async()=>{const r=rule!,id=r.id||crypto.randomUUID();await governanceCall(session!,`/api/notifications/rules/${id}`,'PUT',{...r,id,policyId:r.policyId||undefined});setRule(null);setNotice('Notification rule saved.')})
 if(!read)return null
 return <section className="page-content notifications" aria-label="Notifications"><div className="panel"><div className="panel-heading"><h2>Notifications</h2><button className="outline-button" disabled={busy||!session} onClick={()=>void perform(load)}>Refresh notifications</button></div><p>Route new operational alerts to email or HTTPS webhooks. Delivery runs after each scheduler tick; existing alerts are not backfilled.</p>{!session?<p>Connect to Genesys Cloud to configure notifications.</p>:<>
 <div className="panel-heading"><h3>Destinations</h3>{write&&<button className="primary-button" onClick={()=>setDestination({...initialDestination})}>New destination</button>}</div>
 <OperationalTable rows={destinations} keyOf={d=>d.id} empty="No notification destinations configured." columns={[{key:'name',label:'Name',value:d=>d.name},{key:'type',label:'Type',value:d=>d.type},{key:'status',label:'Status',value:d=>d.enabled?'Enabled':'Disabled'},{key:'last',label:'Last delivery',value:d=>d.lastDelivery?`${d.lastDelivery.state} · ${d.lastDelivery.updatedAt}`:'—'},{key:'actions',label:'Actions',value:d=>d.name,render:d=><div className="heading-actions">{write&&<button className="outline-button" onClick={()=>editDestination(d)}>Edit {d.name}</button>}{test&&<button className="outline-button" disabled={busy||!d.enabled} onClick={()=>void perform(async()=>{await governanceCall(session!,`/api/notifications/destinations/${d.id}/test`,'POST');setNotice('Test notification queued. Delivery runs on the next scheduler tick.')})}>Send test to {d.name}</button>}</div>}]}/>
 {destination&&<form className="panel" aria-label="Destination form" onSubmit={e=>{e.preventDefault();void saveDestination()}}><h3>{destination.id?'Edit destination':'Create destination'}</h3><div className="browser-filters"><label>Destination name<input required value={destination.name} onChange={e=>setDestination({...destination,name:e.target.value})}/></label><label>Channel<select disabled={!!destination.id} value={destination.type} onChange={e=>setDestination({...destination,type:e.target.value as 'WEBHOOK'|'EMAIL'})}><option>WEBHOOK</option><option>EMAIL</option></select></label>{destination.type==='WEBHOOK'?<><label>Webhook URL secret reference<input required={!destination.id} placeholder="projects/…/secrets/aqm-notification-…/versions/latest" value={destination.urlSecretRef} onChange={e=>setDestination({...destination,urlSecretRef:e.target.value})}/></label><label>Signing secret reference (optional)<input value={destination.signingSecretRef} onChange={e=>setDestination({...destination,signingSecretRef:e.target.value})}/></label></>:<><label>Sender email<input required type="email" value={destination.from} onChange={e=>setDestination({...destination,from:e.target.value})}/></label><label>Recipient emails (comma separated)<input required value={destination.to} onChange={e=>setDestination({...destination,to:e.target.value})}/></label><label>Resend API key secret reference<input required={!destination.id} value={destination.apiKeySecretRef} onChange={e=>setDestination({...destination,apiKeySecretRef:e.target.value})}/></label></>}<label><input type="checkbox" checked={destination.enabled} onChange={e=>setDestination({...destination,enabled:e.target.checked})}/>Destination enabled</label></div><p>Use Secret Manager references. Leave references blank when editing to keep existing configuration.</p><div className="heading-actions"><button className="primary-button" disabled={busy} type="submit">Save destination</button><button className="outline-button" type="button" onClick={()=>setDestination(null)}>Cancel destination</button></div></form>}
 <div className="panel-heading"><h3>Rules</h3>{write&&<button className="primary-button" disabled={!destinations.length} onClick={()=>setRule({...initialRule})}>New rule</button>}</div>
 <OperationalTable rows={rules} keyOf={r=>r.id} empty="No notification rules configured." columns={[{key:'name',label:'Name',value:r=>r.name},{key:'severity',label:'Severity',value:r=>r.severities.join(', ')},{key:'types',label:'Alert types',value:r=>r.alertTypes.length?r.alertTypes.join(', '):'All alert types'},{key:'destinations',label:'Destinations',value:r=>r.destinationIds.map(id=>destinations.find(d=>d.id===id)?.name??id).join(', ')},{key:'status',label:'Status',value:r=>r.enabled?'Enabled':'Disabled'},{key:'actions',label:'Actions',value:r=>r.name,render:r=>write?<button className="outline-button" onClick={()=>setRule({...r,policyId:r.policyId??''})}>Edit rule {r.name}</button>:null}]}/>
 {rule&&<form className="panel" aria-label="Rule form" onSubmit={e=>{e.preventDefault();void saveRule()}}><h3>{rule.id?'Edit rule':'Create rule'}</h3><label>Rule name<input required value={rule.name} onChange={e=>setRule({...rule,name:e.target.value})}/></label><div className="browser-filters"><fieldset><legend>Severities</legend>{['INFO','WARNING','ERROR'].map(s=><label key={s}><input type="checkbox" checked={rule.severities.includes(s)} onChange={e=>setRule({...rule,severities:e.target.checked?[...rule.severities,s]:rule.severities.filter(v=>v!==s)})}/>{s}</label>)}</fieldset><fieldset><legend>Alert types (none means all)</legend>{alertTypes.map(t=><label key={t}><input type="checkbox" checked={rule.alertTypes.includes(t)} onChange={e=>setRule({...rule,alertTypes:e.target.checked?[...rule.alertTypes,t]:rule.alertTypes.filter(v=>v!==t)})}/>{t.replaceAll('_',' ')}</label>)}</fieldset><fieldset><legend>Rule destinations</legend>{destinations.map(d=><label key={d.id}><input type="checkbox" checked={rule.destinationIds.includes(d.id)} onChange={e=>setRule({...rule,destinationIds:e.target.checked?[...rule.destinationIds,d.id]:rule.destinationIds.filter(v=>v!==d.id)})}/>{d.name}</label>)}</fieldset></div><label>Policy ID (optional)<input value={rule.policyId} onChange={e=>setRule({...rule,policyId:e.target.value})}/></label><label><input type="checkbox" checked={rule.notifyOnResolution} onChange={e=>setRule({...rule,notifyOnResolution:e.target.checked})}/>Notify on resolution</label><label><input type="checkbox" checked={rule.enabled} onChange={e=>setRule({...rule,enabled:e.target.checked})}/>Rule enabled</label><div className="heading-actions"><button className="primary-button" disabled={busy} type="submit">Save rule</button><button className="outline-button" type="button" onClick={()=>setRule(null)}>Cancel rule</button></div></form>}
 <h3>Delivery history</h3><OperationalTable rows={deliveries} keyOf={d=>d.id} empty="No notification deliveries yet." columns={[{key:'destination',label:'Destination',value:d=>destinations.find(v=>v.id===d.destinationId)?.name??d.destinationId},{key:'event',label:'Event',value:d=>d.event},{key:'state',label:'State',value:d=>d.state},{key:'attempts',label:'Attempts',value:d=>d.attemptCount},{key:'last',label:'Updated',value:d=>d.updatedAt},{key:'error',label:'Error code',value:d=>d.lastErrorCode??'—'}]}/>{next&&<button className="outline-button" disabled={busy} onClick={()=>void perform(async()=>{const p=await governanceCall(session!,`/api/notifications/deliveries?cursor=${next}`);setDeliveries(p.items);setNext(p.nextCursor)},false)}>Next deliveries page</button>}
 </>}{error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div></section>
}
