import type { Option } from './domain/types'
import { creditLabel } from './authoringPresentation'
/** Shared editor preserves stable keys and external mappings when ordinary fields change. */
export function OptionEditor({type,options,onChange,readOnly=false}:{type:'choice'|'score';options:Option[];onChange:(options:Option[])=>void;readOnly?:boolean}) {
 const update=(i:number,patch:Partial<Option>)=>onChange(options.map((o,j)=>i===j?{...o,...patch}:o))
 const move=(i:number,by:number)=>{const next=structuredClone(options);[next[i],next[i+by]]=[next[i+by],next[i]];onChange(next)}
 return <section className="options-editor" aria-label={type==='score'?'Ordered levels':'Choices'}><h4>{type==='score'?'Ordered levels':'Choices'}</h4>{!readOnly&&<p className="field-note">Credit is the percentage awarded for this answer.{type==='choice'?' Leave blank for Not scored.':' Arrange levels in the order authors should see them.'}</p>}{options.map((o,i)=><div className="answer-option-row" key={i}>
 <strong>{String(i+1).padStart(2,'0')}</strong>
 {readOnly?<div className="answer-readonly"><strong>{o.label} · {creditLabel(o.credit)}</strong><p>{o.description}</p></div>:<>
 <label>Label<input aria-label={`Option ${i+1} label`} value={o.label} onChange={e=>update(i,{label:e.target.value})}/></label>
 <label className="answer-description">Description<textarea rows={2} aria-label={`Option ${i+1} description`} value={o.description} onChange={e=>update(i,{description:e.target.value})}/></label>
 <label>Credit (%)<input aria-label={`Option ${i+1} credit (%)`} type="number" min="0" max="100" step="any" placeholder={type==='choice'?'Not scored':'0–100'} value={o.credit===undefined?'':Number((o.credit*100).toFixed(6))} onChange={e=>update(i,{credit:e.target.value===''?undefined:Number(e.target.value)/100})}/></label>
 <div className="heading-actions"><button className="icon-button" disabled={i===0} aria-label={`Move option ${i+1} up`} onClick={()=>move(i,-1)}>↑</button><button className="icon-button" disabled={i===options.length-1} aria-label={`Move option ${i+1} down`} onClick={()=>move(i,1)}>↓</button><button className="icon-button" aria-label={`Remove option ${i+1}`} onClick={()=>onChange(options.filter((_,j)=>j!==i))}>×</button></div></>}
 <details className="option-advanced"><summary>Advanced details · answer {i+1}</summary><div className="editor-grid"><label>Stable key<input readOnly={readOnly} aria-label={`Option ${i+1} key`} value={o.key} onChange={e=>update(i,{key:e.target.value})}/></label><label>External/source value<input readOnly={readOnly} aria-label={`Option ${i+1} external/source value`} type="number" step="any" value={o.sourceValue??''} onChange={e=>update(i,{sourceValue:e.target.value===''?undefined:Number(e.target.value)})}/><small>Optional value retained when a scale maps to an external definition.</small></label></div></details>
 </div>)}{!readOnly&&<button className="outline-button" disabled={options.length>=(type==='score'?10:255)} onClick={()=>{let n=options.length+1;while(options.some(o=>o.key===`option_${n}`))n++;onChange([...options,{key:`option_${n}`,label:'',description:'',...(type==='score'?{credit:0}:{})}])}}>＋ Add {type==='score'?'level':'choice'}</button>}</section>
}
