import { coverageRate } from './domain/analytics'
import { automationHealthLabel, healthLabel, reviewStateLabel } from './overviewPresentation'
import { CoverageFunnel } from './CoverageFunnel'
import { qualityCoverageCopy, qualityPercent } from './analyticsPresentation'
import type { ReactNode } from 'react'
import type { OverviewSnapshot, OverviewSection, OverviewAlert, OverviewRun } from './domain/overview'
export const overviewTime=(value:string|null|undefined)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Europe/London',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—'
const countText=(count:number,label:string)=>`${count} ${label}${count===1?'':'s'}`
const percent=(value:number|null)=>value===null?'—':`${Math.round(value*100)}%`
function Section<T>({value,children}:{value:OverviewSection<T>;children:(data:T)=>ReactNode}){return value.complete?<>{children(value.data)}</>:<div role="status" className="overview-unavailable"><strong>{value.status==='incomplete'?'Data incomplete':'Unavailable'}</strong> · Refresh to try again.<details><summary>Technical details</summary>{value.reason}</details></div>}
function Metric({label,value,onClick}:{label:string;value:ReactNode;onClick?:()=>void}){return <div className="overview-metric"><small>{label}</small>{onClick?<button className="text-link" aria-label={`${label}: ${value}`} onClick={onClick}>{value} →</button>:<strong>{value}</strong>}</div>}
export interface OverviewActions {onExplore:(filters:Record<string,string>)=>void;onAnalytics:(tab:'quality'|'coverage',range:OverviewSnapshot['range'])=>void;onEditPolicy:(id:string)=>void;onRun:(id:string)=>void;onAlert:(id:string)=>void;onReview:(id:string)=>void;onPage:(page:'forms'|'policies'|'settings')=>void}
export function OverviewView({data,actions,onManual,capabilities}:{data:OverviewSnapshot;actions:OverviewActions;onManual:()=>void;capabilities:{reviewer:boolean;author:boolean;admin:boolean;canRun:boolean}}){
 const {reviewer,author,admin,canRun}=capabilities
 const alertAction=(a:OverviewAlert)=>a.evaluationId?actions.onReview(a.evaluationId):a.runId?actions.onRun(a.runId):actions.onAlert(a.id)
 const r=data.reviews,n=data.notifications,a=data.alerts,h=data.health
 const critical=data.analytics.complete?data.analytics.data.quality.criticalFailures:0
 const known=[r,n,a,data.analytics].every(s=>s.complete),issues=critical+(a.complete?a.data.errors+a.data.warnings:0)+(r.complete?r.data.escalated+r.data.overdue:0)+(n.complete?n.data.failed24h:0)
 const reviewState=reviewStateLabel(r)
 const runRow=(run:OverviewRun)=><button className="overview-run" key={run.id} onClick={()=>actions.onRun(run.id)}><span>{overviewTime(run.startedAt)}</span><strong>{run.policyName}</strong><span>{run.trigger==='scheduled'?'Scheduled':'Manual'}</span><span>{run.evaluationsSucceeded} evaluations{run.evaluationsFailed?` · ${run.evaluationsFailed} failed`:''}</span><span className="pill">{({'completed':'Completed','partial-failure':'Partial failure','failed':'Failed','running':'Running'} as Record<string,string>)[run.status]??run.status}</span></button>
 return <>
  <section className={`panel overview-attention ${issues?'has-attention':''}`} aria-label="Attention required"><div className="panel-heading"><h2>Attention required</h2><span className="pill">{known&&!issues?'All clear':issues?'Action needed':'Check data availability'}</span></div>
   {critical>0&&<div className="overview-quality-attention"><small className="attention-kind">QUALITY ATTENTION · Last {data.range.days} days</small><p>{critical} critical failure occurrences in evaluated conversations</p><button className="text-link" onClick={()=>actions.onExplore({source:'genesys-cloud',critical:'yes',from:data.range.from.slice(0,10),to:data.range.to.slice(0,10)})}>Inspect critical evaluations →</button></div>}
   {known&&!issues?<p>No issues requiring attention. No overdue reviews or failed notifications.</p>:<div className="overview-attention-counts"><small className="attention-kind">REVIEW &amp; SYSTEM ATTENTION</small>{a.complete&&<button className="text-link" onClick={()=>actions.onAlert('')}>{countText(a.data.errors,'error')}</button>}{r.complete&&<><button className="text-link" onClick={()=>actions.onExplore({dueState:'ESCALATED'})}>{countText(r.data.escalated,'escalated review')}</button><button className="text-link" onClick={()=>actions.onExplore({due:'overdue',dueState:'OVERDUE'})}>{countText(r.data.overdue,'overdue review')}</button></>}{a.complete&&<button className="text-link" onClick={()=>actions.onAlert('')}>{countText(a.data.warnings,'warning')}</button>}{n.complete&&<span>{n.data.failed24h} failed notification {n.data.failed24h===1?'delivery':'deliveries'} (24h)</span>}</div>}
   {!a.complete&&<Section value={a}>{()=>null}</Section>}{!r.complete&&<Section value={r}>{()=>null}</Section>}{!n.complete&&<Section value={n}>{()=>null}</Section>}
   <Section value={a}>{alerts=><div className="overview-alerts">{alerts.items.slice(0,2).map(item=><button className="overview-alert" key={item.id} onClick={()=>alertAction(item)}><span className={`pill ${item.severity==='ERROR'?'review-escalated':item.severity==='WARNING'?'overview-warning':''}`}>{item.severity==='ERROR'?'Error':item.severity==='WARNING'?'Warning':'Information'}</span><strong>{item.title}</strong><span>{item.evaluationId?'Open review':item.runId?'Open run':'Open alert'} →</span></button>)}{alerts.items.length>2&&<button className="text-link" onClick={()=>actions.onAlert('')}>View all active alerts →</button>}</div>}</Section>
  </section>
  <section className="panel overview-first-scan" aria-labelledby="overview-at-a-glance"><h2 id="overview-at-a-glance">At a glance</h2><div className="overview-summary-grid">
   <article className="overview-summary-card" role="region" aria-label="Quality summary"><h3>Quality</h3><p className="overview-summary-scope">Last {data.range.days} days</p><Section value={data.analytics}>{analytics=><><div className="overview-summary-metrics"><Metric label="Average quality" value={percent(analytics.quality.averageScore)} onClick={()=>actions.onAnalytics('quality',data.range)}/><Metric label="Evaluated conversations" value={analytics.quality.conversations}/><Metric label="Evaluations" value={analytics.quality.evaluations} onClick={()=>actions.onExplore({source:'genesys-cloud',from:data.range.from.slice(0,10),to:data.range.to.slice(0,10)})}/><Metric label="Pass rate" value={percent(analytics.quality.passRate)}/><Metric label="Critical failure occurrences" value={analytics.quality.criticalFailures} onClick={()=>actions.onExplore({source:'genesys-cloud',critical:'yes',from:data.range.from.slice(0,10),to:data.range.to.slice(0,10)})}/></div><button className="text-link" onClick={()=>actions.onAnalytics('quality',data.range)}>Explore quality →</button></>}</Section></article>
   <article className="overview-summary-card" role="region" aria-label="Coverage summary"><h3>Coverage</h3><p className="overview-summary-scope">Last {data.range.days} days</p><Section value={data.analytics}>{analytics=><>
    <div className="overview-summary-metrics"><Metric label="Evaluation coverage" value={qualityPercent(coverageRate(analytics.coverage.evaluated,analytics.coverage.eligible))}/><Metric label="Eligible" value={analytics.coverage.eligible}/><Metric label="Sampled" value={analytics.coverage.sampled}/><Metric label="Content available" value={analytics.coverage.evaluable}/><Metric label="Evaluated" value={analytics.coverage.evaluated}/><Metric label="Failed evaluation attempts" value={analytics.coverage.failed}/><Metric label="Sampling coverage" value={qualityPercent(coverageRate(analytics.coverage.sampled,analytics.coverage.eligible))}/></div>
    <button className="text-link" onClick={()=>actions.onAnalytics('coverage',data.range)}>Explore coverage →</button>
   </>}</Section></article>
   <article className="overview-summary-card" role="region" aria-label="Review work summary"><h3>Review work</h3><p className="overview-summary-scope">Current state</p><Section value={r}>{reviews=><div className="overview-summary-metrics"><Metric label="Open" value={reviews.open} onClick={()=>actions.onExplore({reviewQueue:'active'})}/><Metric label="Due soon" value={reviews.dueSoon} onClick={()=>actions.onExplore({dueState:'DUE_SOON'})}/><Metric label="Overdue" value={reviews.overdue} onClick={()=>actions.onExplore({due:'overdue',dueState:'OVERDUE'})}/><Metric label="Escalated" value={reviews.escalated} onClick={()=>actions.onExplore({dueState:'ESCALATED'})}/><Metric label="Unassigned" value={reviews.unassigned} onClick={()=>actions.onExplore({reviewStatus:'REVIEW_REQUESTED',assignment:'unassigned'})}/></div>}</Section><div className="overview-summary-actions">{reviewer&&<button className="text-link" onClick={()=>actions.onExplore({reviewQueue:'mine',assignment:'mine'})}>My review queue →</button>}<button className="text-link" onClick={()=>actions.onExplore({reviewQueue:'active'})}>All review work →</button></div></article>
   <article className="overview-summary-card" role="region" aria-label="Automation health summary"><h3>Automation health</h3><p className="overview-summary-scope">Current state</p><div className="overview-summary-metrics">
   <Metric label="Automation" value={automationHealthLabel(data)}/>
   <Metric label="Genesys" value={h.complete?healthLabel(h.data.genesysAutomation.status):'Unavailable'}/><Metric label="Jev" value={h.complete?healthLabel(h.data.jev.status):'Unavailable'}/>
   <Metric label="Scheduler" value={h.complete?healthLabel(h.data.scheduler.status):'Unavailable'}/><Metric label="Notifications" value={n.complete?n.data.failed24h?'Failed deliveries':n.data.pending?'Pending':'Healthy':n.status==='incomplete'?'Data incomplete':'Unavailable'}/><Metric label="Review SLA" value={reviewState}/>
  </div><details><summary>System details</summary><Section value={h}>{health=><p className="field-note">API {health.api} · Firestore {health.firestore} · Last scheduler tick {overviewTime(health.scheduler.lastSuccessfulTickAt)}. Genesys and Jev reflect durable run evidence.</p>}</Section><Section value={n}>{notifications=><p className="field-note">Notifications: {notifications.pending} pending · {notifications.failed24h} failed (24h) · Last success {overviewTime(notifications.lastSuccessfulAt)}</p>}</Section></details></article>
  </div></section>
  <section className="panel overview-quality-detail" aria-label="Quality detail"><h2>Quality trend</h2><p className="field-note">Last {data.range.days} days</p><Section value={data.analytics}>{analytics=><>
   <div className="overview-trend" aria-label="Quality trend">{analytics.qualityTrend.length?<div className="bar-chart">{analytics.qualityTrend.map(day=><div key={day.key} title={`${day.key}: ${percent(day.averageScore)} · ${day.count} evaluations`}><span>{percent(day.averageScore)}</span><div className="bar-track"><div className="bar-fill" style={{width:`${(day.averageScore??0)*100}%`}}/></div><small>{day.key.slice(5)} · {day.count} evaluations</small></div>)}</div>:<p>No quality history in this period.</p>}{analytics.quality.evaluations>0&&analytics.qualityTrend.length<3&&<p className="field-note">Limited history in this period. · {analytics.quality.evaluations} evaluations</p>}</div>
   <details className="overview-coverage-detail"><summary><strong>Coverage details</strong><span>{analytics.coverage.eligible} eligible · {analytics.coverage.sampled} sampled · {analytics.coverage.evaluable} content available · {analytics.coverage.evaluated} evaluated</span></summary>
    <p className="field-note">Genesys Cloud · Last {data.range.days} days · All policies. {qualityCoverageCopy}</p>{Object.values(analytics.runCounts).every(count=>count===0)?<p>Coverage will appear after a monitoring policy run.</p>:<CoverageFunnel counts={analytics.coverage} showGaps/>}<button className="text-link" onClick={()=>actions.onAnalytics('coverage',data.range)}>Explore coverage →</button>
   </details>
  </>}</Section></section>
  <section className="panel" aria-label="Upcoming automation"><div className="panel-heading"><h2>Automation</h2>{canRun&&<button className="outline-button" onClick={onManual}>Run a policy now</button>}</div>
   <Section value={data.analytics}>{analytics=><p>{analytics.runCounts.completed} completed · {analytics.runCounts.partial} partial · {analytics.runCounts.failed} failed · {analytics.runCounts.running} running in the last {data.range.days} days</p>}</Section>
   <h3>Last automated run</h3><Section value={data.lastAutomatedRun}>{last=>last?<>{runRow(last)}<p className="field-note">Latest successful scheduled execution.</p></>:<p>No successful automated run recorded yet.</p>}</Section>
   <h3>Upcoming scheduled work</h3><Section value={data.schedules}>{schedules=><>{schedules.items.length?schedules.items.map(s=><div className="overview-schedule" key={s.id}><strong>{s.policyName}</strong><span>{s.frequency}</span><span>Next due {overviewTime(s.nextDueAt)}</span><span>Last success {overviewTime(s.lastSuccessfulAt)}</span><button className="text-link" onClick={()=>actions.onEditPolicy(s.policyId)}>View{canRun?'/Edit':''} policy →</button></div>):<p>No enabled schedules. Next scheduled run: —</p>}</>}</Section>
  </section>
  <section className="panel" aria-label="Recent runs"><h2>Recent runs</h2><Section value={data.recentRuns}>{runs=>runs.items.length?<div className="overview-runs">{runs.items.map(runRow)}</div>:<p>No runs recorded yet.</p>}</Section></section>
  {(author||admin)&&<div className="overview-actions">{author&&<><button className="outline-button" onClick={()=>actions.onPage('forms')}>Evaluation Forms →</button><button className="outline-button" onClick={()=>actions.onPage('policies')}>Policies →</button></>}{admin&&<><button className="outline-button" onClick={()=>actions.onAlert('')}>Open alerts →</button><button className="outline-button" onClick={()=>actions.onPage('settings')}>Settings →</button></>}</div>}
 </>
}
