import { useEffect, useRef, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { EvaluationForm, InteractionPolicy } from './domain/types'
import { apiOrigin } from './domain/manualClient'
import { isOperationalForm } from './domain/formLifecycle'
import { clonePolicy, filterPolicies, MAX_FIXED_SAMPLE, newPolicy, POLICY_FIELDS, samePolicyDefinition, validatePolicy } from './domain/policyAuthoring'
import { loadPolicyCollection, policyCall } from './domain/policyClient'
import type { Schedule } from './server/schedules'
import { OperationalTable, type Column } from './OperationalTable'
import { ResourceHistory, usePermission } from './GovernancePanel'
const stamp=(v?:string)=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Europe/London'}):'—'
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
const scheduleLabel=(s?:Schedule)=>!s||s.frequency==='MANUAL'?'Manual':`${s.frequency==='WEEKLY'?`Weekly on ${weekdays[(s.weekday??1)-1]}`:'Daily'} at ${s.localTime} Europe/London${s.enabled?'':' (paused)'}`
const sample=(p:InteractionPolicy)=>p.sampling?.strategy==='percentage'?`${p.sampling.percentage}%`:p.sampling?.strategy==='fixed_count'?`Fixed ${p.sampling.count}`:'All eligible'
const scheduleConfig=(s:Schedule)=>JSON.stringify([s.id,s.policyId,s.enabled,s.frequency,s.timezone,s.localTime,s.weekday])
const initialSchedule=(id:string):Schedule=>({id:`schedule_${id}`,policyId:id,enabled:false,frequency:'MANUAL',timezone:'Europe/London',localTime:'02:00',weekday:1,version:1})
export function PoliciesPage({session,policies:localPolicies,forms:localForms,onChange,onRuns,selectedId,onSelect,onDirty}:{session:AuthSession|null;policies:InteractionPolicy[];forms:EvaluationForm[];onChange:(p:InteractionPolicy[])=>void;onRuns:(id:string)=>void;selectedId:string|null;onSelect:(id:string)=>void;onDirty:(dirty:boolean)=>void}) {
 const connected=!!session&&!!apiOrigin,write=usePermission('policies.write'),scheduleWrite=usePermission('schedules.write'),read=usePermission('policies.read')
 const [remote,setRemote]=useState<InteractionPolicy[]>([]),[forms,setForms]=useState<EvaluationForm[]>([]),[schedules,setSchedules]=useState<Schedule[]>([])
 const [drafts,setDrafts]=useState<Record<string,InteractionPolicy>>({}),[scheduleDrafts,setScheduleDrafts]=useState<Record<string,Schedule>>({})
 const [status,setStatus]=useState('All'),[frequency,setFrequency]=useState('All'),[assignment,setAssignment]=useState('All')
 const [loading,setLoading]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const sequence=useRef(0)
 const call=<T,>(path:string,method='GET',value?:unknown)=>policyCall<T>(apiOrigin,session!,path,method,value)
 const refresh=async()=>{
  if(!connected||!read)return
  const n=++sequence.current;setLoading(true);setError('')
  try{
   const [p,f,s]=await Promise.all([loadPolicyCollection<InteractionPolicy>(call,'/api/policies'),loadPolicyCollection<EvaluationForm>(call,'/api/forms'),loadPolicyCollection<Schedule>(call,'/api/schedules')])
   if(n!==sequence.current)return
   setRemote(p);setForms(f);setSchedules(s);setLoaded(true);setDrafts({});setScheduleDrafts({});setNotice('')
  }catch(e){if(n===sequence.current){setError(e instanceof Error?e.message:'Could not load durable policies.');setLoaded(false)}}finally{if(n===sequence.current)setLoading(false)}
 }
 useEffect(()=>{setRemote([]);setForms([]);setSchedules([]);setLoaded(false);setDrafts({});setScheduleDrafts({});void refresh();return()=>{sequence.current++}},[session?.accessToken,read])
 const authority=connected?remote:localPolicies,availableForms=connected?forms:localForms
 const rows=[...authority.map(p=>drafts[p.id]??p),...Object.values(drafts).filter(p=>!authority.some(a=>a.id===p.id))]
 const policy=rows.find(p=>p.id===selectedId),saved=authority.find(p=>p.id===selectedId)
 const savedSchedule=schedules.find(s=>s.policyId===selectedId),schedule=policy?(scheduleDrafts[policy.id]??savedSchedule??initialSchedule(policy.id)):undefined
 const dirty=!!policy&&(!saved||!samePolicyDefinition(saved,policy)),scheduleDirty=!!schedule&&!!scheduleDrafts[schedule.policyId]&&scheduleConfig(schedule)!==scheduleConfig(savedSchedule??initialSchedule(schedule.policyId))
 const anyDirty=Object.values(drafts).some(p=>!authority.some(a=>a.id===p.id&&samePolicyDefinition(a,p)))||Object.values(scheduleDrafts).some(s=>scheduleConfig(s)!==scheduleConfig(schedules.find(a=>a.policyId===s.policyId)??initialSchedule(s.policyId)))
 useEffect(()=>{onDirty(anyDirty);return()=>onDirty(false)},[anyDirty,onDirty])
 const update=(p:InteractionPolicy)=>{setDrafts(current=>({...current,[p.id]:p}));setNotice('');setError('')}
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}}
 const save=()=>perform(async()=>{
  if(!policy)return
  const errors=validatePolicy(policy,availableForms);if(errors.length)throw Error(errors.join(' '))
  const item=connected?(await call<{item:InteractionPolicy}>(`/api/policies/${policy.id}`,'PUT',{...policy,expectedVersion:saved?saved.version??1:null})).item:{...policy,version:saved?(saved.version??1)+(dirty?1:0):1,createdAt:saved?.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString()}
  if(connected)setRemote(current=>[...current.filter(p=>p.id!==item.id),item]);else onChange([...localPolicies.filter(p=>p.id!==item.id),item])
  setDrafts(current=>{const next={...current};delete next[item.id];return next});setNotice(`Saved ${stamp(item.updatedAt)}`)
 })
 const duplicate=()=>perform(async()=>{
  if(!policy||!saved||dirty)throw Error('Save the policy before duplicating it.')
  const item=connected?(await call<{item:InteractionPolicy}>(`/api/policies/${policy.id}/clone`,'POST',{})).item:clonePolicy(policy,`policy_${crypto.randomUUID().replaceAll('-','')}`)
  if(connected)setRemote(current=>[...current,item]);else onChange([...localPolicies,item])
  onSelect(item.id);setNotice('Duplicate saved disabled, with no schedule or operational history.')
 })
 const saveSchedule=()=>perform(async()=>{
  if(!schedule||!saved)throw Error('Save the policy before saving its schedule.')
  const {item}=await call<{item:Schedule}>(`/api/schedules/${schedule.id}`,'PUT',{id:schedule.id,policyId:schedule.policyId,enabled:schedule.frequency!=='MANUAL'&&schedule.enabled,frequency:schedule.frequency,timezone:schedule.timezone,localTime:schedule.localTime,weekday:schedule.weekday,version:1})
  setSchedules(current=>[...current.filter(s=>s.id!==item.id),item]);setScheduleDrafts(current=>{const next={...current};delete next[item.policyId];return next});setNotice('Schedule saved. Policy changes have their own Save changes button.')
 })
 const frequencyFor=(id:string)=>{const s=schedules.find(s=>s.policyId===id);return s?.frequency??'MANUAL'}
 const columns:Column<InteractionPolicy>[]=[{key:'name',label:'Name',value:p=>p.name,width:'220px',render:p=><button className="text-link" onClick={()=>onSelect(p.id)}>{p.name}</button>},{key:'enabled',label:'Status',value:p=>p.enabled?'Enabled':'Disabled'},{key:'version',label:'Version',value:p=>p.version??1,render:p=>`v${p.version??1}`},{key:'criteria',label:'Criteria',value:p=>p.criteria.anyOf.map(g=>g.map(c=>`${c.field} ${c.operator} ${c.value||'…'}`).join(' AND ')).join(' OR ')},{key:'forms',label:'Assigned forms',value:p=>p.evaluationFormIds.map(id=>{const f=availableForms.find(f=>f.id===id);return f?`${f.name} v${f.version}`:`Missing: ${id}`}).join(', ')||'None'},{key:'sampling',label:'Sampling',value:sample},{key:'schedule',label:'Schedule',value:p=>scheduleLabel(schedules.find(s=>s.policyId===p.id))},{key:'modified',label:'Last modified',value:p=>p.updatedAt??'',render:p=>stamp(p.updatedAt)}]
 const issues=policy?validatePolicy(policy,availableForms):[]
 return <div className="page-content policies-page"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION</div><h1>Policies</h1><p>{connected?'Durable server policies · exact published form versions · optional daily or weekly automation.':'Local/demo policy sandbox · saved in this browser only. Connect in Settings for durable authoring.'}</p></div><div className="heading-actions">{connected&&<button className="outline-button" disabled={busy||loading} onClick={()=>{if(!anyDirty||window.confirm('Discard unsaved policy and schedule edits and refresh?'))void refresh()}}>Refresh durable policies</button>}{write&&(!connected||loaded)&&<button className="primary-button" disabled={busy} onClick={()=>{const p=newPolicy(`policy_${crypto.randomUUID().replaceAll('-','')}`);update(p);onSelect(p.id)}}>＋ New policy</button>}</div></div>
 {connected&&!read?<p role="alert">You do not have permission to read policies.</p>:<><div className="browser-filters"><label>Status<select aria-label="Policy status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Enabled','Disabled'].map(s=><option key={s}>{s}</option>)}</select></label><label>Schedule<select aria-label="Policy schedule filter" value={frequency} onChange={e=>setFrequency(e.target.value)}>{[['All','All'],['MANUAL','Manual'],['DAILY','Daily'],['WEEKLY','Weekly']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Forms<select aria-label="Policy forms filter" value={assignment} onChange={e=>setAssignment(e.target.value)}><option>All</option><option value="Assigned">Has assigned forms</option><option value="Unassigned">No assigned forms</option></select></label></div>
 {(!connected||loaded)&&<OperationalTable stateKey="policies" rows={filterPolicies(rows,status,frequency,assignment,frequencyFor)} columns={columns} keyOf={p=>p.id} onSelect={p=>onSelect(p.id)}/>}{loading&&<p role="status">Loading durable policies…</p>}
 {error&&<p role="alert" className="inline-error">{error}</p>}
 {policy&&(!connected||loaded)&&<section className="policy-detail"><div className="panel"><div className="panel-heading"><div><span className="mini-label">{connected?'DURABLE POLICY':'LOCAL/DEMO POLICY'} · v{policy.version??1}</span><h2>{policy.name}</h2></div><div className="heading-actions"><button className="outline-button" onClick={()=>onRuns(policy.id)}>View runs</button>{write&&<><button className="outline-button" disabled={busy||dirty||!saved} onClick={()=>void duplicate()}>Duplicate policy</button><button className="primary-button" disabled={busy||!dirty} onClick={()=>void save()}>Save changes</button></>}</div></div><p role="status">{dirty?'Unsaved changes':notice.startsWith('Saved ')?notice:`Saved ${stamp(saved?.updatedAt)}${connected?' to server':' in this browser'}`}</p>
 <fieldset className="permission-controls" disabled={!write||busy}><div className="editor-grid"><label>Policy name<input value={policy.name} onChange={e=>update({...policy,name:e.target.value})}/></label><label>Description<input value={policy.description} onChange={e=>update({...policy,description:e.target.value})}/></label></div><label className="check-label"><input type="checkbox" checked={policy.enabled} onChange={e=>update({...policy,enabled:e.target.checked})}/>Enabled (requires Save changes)</label>
 <h3>Interaction criteria</h3><p>Match ALL conditions in any one group. Groups are joined with OR.</p>{policy.criteria.anyOf.map((group,gi)=><div key={gi}>{gi>0&&<b className="logic-or">OR</b>}<div className="criterion-group"><div className="criterion-heading"><strong>Match ALL</strong><button className="text-link" onClick={()=>update({...policy,criteria:{anyOf:policy.criteria.anyOf.filter((_,i)=>i!==gi)}})}>Remove OR group</button></div>{group.map((condition,ci)=><div className="criterion-row" key={ci}><select aria-label="Condition field" value={condition.field} onChange={e=>{const p=structuredClone(policy);p.criteria.anyOf[gi][ci]={...condition,field:e.target.value as typeof condition.field,operator:'equals'};update(p)}}>{POLICY_FIELDS.map(f=><option key={f}>{f}</option>)}</select><select aria-label="Condition operator" value={condition.operator} onChange={e=>{const p=structuredClone(policy);p.criteria.anyOf[gi][ci].operator=e.target.value as typeof condition.operator;update(p)}}><option value="equals">equals</option>{condition.field==='tag'&&<option value="includes">includes tag</option>}</select><input aria-label="Criteria value" value={condition.value} onChange={e=>{const p=structuredClone(policy);p.criteria.anyOf[gi][ci].value=e.target.value;update(p)}}/><button className="icon-button" aria-label="Remove condition" onClick={()=>{const p=structuredClone(policy);p.criteria.anyOf[gi].splice(ci,1);update(p)}}>×</button></div>)}<button className="outline-button" onClick={()=>{const p=structuredClone(policy);p.criteria.anyOf[gi].push({field:'topic',operator:'equals',value:''});update(p)}}>Add condition</button></div></div>)}<button className="outline-button" onClick={()=>update({...policy,criteria:{anyOf:[...policy.criteria.anyOf,[{field:'topic',operator:'equals',value:''}]]}})}>Add OR group</button>
 <h3>Sampling</h3><div className="editor-grid"><label>Sampling strategy<select value={policy.sampling?.strategy??'all'} onChange={e=>update({...policy,sampling:e.target.value==='percentage'?{strategy:'percentage',percentage:10}:e.target.value==='fixed_count'?{strategy:'fixed_count',count:3}:{strategy:'all'}})}><option value="all">All eligible</option><option value="percentage">Percentage</option><option value="fixed_count">Fixed count</option></select></label>{policy.sampling?.strategy==='percentage'&&<label>Percentage<input type="number" min="0" max="100" value={policy.sampling.percentage} onChange={e=>update({...policy,sampling:{...policy.sampling as {strategy:'percentage';percentage:number},percentage:Number(e.target.value)}})}/><small>0 selects none; 100 selects all.</small></label>}{policy.sampling?.strategy==='fixed_count'&&<label>Fixed count<input type="number" min="1" max={MAX_FIXED_SAMPLE} value={policy.sampling.count} onChange={e=>update({...policy,sampling:{...policy.sampling as {strategy:'fixed_count';count:number},count:Number(e.target.value)}})}/></label>}<label>Sample seed (optional)<input value={policy.sampling?.seed??''} onChange={e=>update({...policy,sampling:{...(policy.sampling??{strategy:'all'}),seed:e.target.value}})}/></label></div>
 <h3>Published evaluation forms</h3><p>Assignments pin the exact form ID and version. New versions do not replace these pins.</p><div className="form-checks">{availableForms.filter(isOperationalForm).map(f=><label key={f.id}><input type="checkbox" checked={policy.evaluationFormIds.includes(f.id)} onChange={e=>update({...policy,evaluationFormIds:e.target.checked?[...policy.evaluationFormIds,f.id]:policy.evaluationFormIds.filter(id=>id!==f.id)})}/>{f.name} · v{f.version} · {f.questions.filter(q=>q.enabled).length} questions · {f.scoring.mode??'weighted'} · {f.id}</label>)}</div>{policy.evaluationFormIds.filter(id=>!availableForms.some(f=>f.id===id&&isOperationalForm(f))).map(id=><label className="check-label" key={id}><input type="checkbox" checked onChange={()=>update({...policy,evaluationFormIds:policy.evaluationFormIds.filter(v=>v!==id)})}/>Missing or non-operational: {id} (uncheck to remove)</label>)}
 </fieldset></div>
 <div className="panel"><h3>Readiness</h3><div className="health-grid"><div><small>Policy</small><strong>{policy.enabled?'Enabled':'Disabled'}</strong></div><div><small>Forms</small><strong>{policy.evaluationFormIds.filter(id=>availableForms.some(f=>f.id===id&&isOperationalForm(f))).length} published {policy.evaluationFormIds.filter(id=>availableForms.some(f=>f.id===id&&isOperationalForm(f))).length===1?'form':'forms'} assigned</strong></div><div><small>Sampling</small><strong>{sample(policy)}</strong></div><div><small>Schedule (saved)</small><strong>{scheduleLabel(savedSchedule)}</strong></div><div><small>Next run</small><strong>{stamp(savedSchedule?.nextDueAt)}</strong></div></div>{!policy.evaluationFormIds.length&&<p className="inline-error">No forms assigned; runs cannot evaluate interactions.</p>}{!policy.enabled&&savedSchedule?.enabled&&<p className="inline-error">Disabled policy with enabled schedule. Scheduled attempts will not evaluate this policy.</p>}{issues.length>0&&<ul className="inline-error">{issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>}</div>
 {connected&&schedule&&<div className="panel"><h3>Automation</h3><p>Daily evaluates the previous day; weekly evaluates the previous Monday–Sunday. Policy and schedule save separately.</p><fieldset className="permission-controls" disabled={!scheduleWrite||busy||!saved}><div className="editor-grid"><label>Automation<select aria-label="Automation" value={schedule.frequency} onChange={e=>setScheduleDrafts(current=>({...current,[policy.id]:{...schedule,frequency:e.target.value as Schedule['frequency'],enabled:e.target.value!=='MANUAL'}}))}><option value="MANUAL">Manual</option><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option></select></label>{schedule.frequency==='WEEKLY'&&<label>Weekday<select value={schedule.weekday??1} onChange={e=>setScheduleDrafts(current=>({...current,[policy.id]:{...schedule,weekday:Number(e.target.value)}}))}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((day,i)=><option value={i+1} key={day}>{day}</option>)}</select></label>}{schedule.frequency!=='MANUAL'&&<><label>Local time<input type="time" value={schedule.localTime} onChange={e=>setScheduleDrafts(current=>({...current,[policy.id]:{...schedule,localTime:e.target.value}}))}/></label><label>Timezone<input readOnly value="Europe/London"/></label><label className="check-label"><input type="checkbox" checked={schedule.enabled} onChange={e=>setScheduleDrafts(current=>({...current,[policy.id]:{...schedule,enabled:e.target.checked}}))}/>Schedule enabled</label></>}</div>{scheduleWrite&&<button className="outline-button" disabled={!scheduleDirty} onClick={()=>void saveSchedule()}>Save schedule</button>}</fieldset>{!saved&&<p>Save the policy first to configure its schedule.</p>}<p role="status">{scheduleDirty?'Unsaved schedule changes':'Schedule matches server'}</p><p>Next due: {stamp(savedSchedule?.nextDueAt)} · Last attempted: {stamp(savedSchedule?.lastAttemptedAt)} · Last successful: {stamp(savedSchedule?.lastSuccessfulAt)}</p></div>}
 {connected&&<ResourceHistory session={session} type="policy" id={policy.id}/>}</section>}</>}
 {notice&&!notice.startsWith('Saved ')&&<p role="status">{notice}</p>}
 </div>
}
