import { useEffect, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { EvaluationForm, QuestionGroupAsset } from './domain/types'
import { apiOrigin } from './domain/manualClient'
import { assertAssetWrite, nextAssetVersion, transitionAsset } from './domain/groupAssets'
import { seedGroupAssets } from './domain/seedGroupAssets'
import { OperationalTable } from './OperationalTable'
import { GroupedFormEditor, type QuestionEditorRenderer } from './GroupedFormEditor'
import { newItem } from './domain/scorecard'
const storage='genesys-aqm-v08-group-assets'
export function useGroupAssets(session:AuthSession|null){
  const [assets,setAssets]=useState<QuestionGroupAsset[]>(()=>{try{return JSON.parse(localStorage.getItem(storage)??'null')??structuredClone(seedGroupAssets)}catch{return structuredClone(seedGroupAssets)}}),[error,setError]=useState('')
  useEffect(()=>{localStorage.setItem(storage,JSON.stringify(assets))},[assets])
  useEffect(()=>{if(!session||!apiOrigin)return;let cancelled=false;const load=async()=>{let cursor:string|undefined;const items:QuestionGroupAsset[]=[];do{const response=await fetch(`${apiOrigin}/api/question-groups?limit=100${cursor?`&cursor=${cursor}`:''}`,{headers:{Authorization:`Bearer ${session.accessToken}`}});if(!response.ok)throw Error('Could not load durable Question Groups.');const page=await response.json() as {items:QuestionGroupAsset[];nextCursor?:string};items.push(...page.items);cursor=page.nextCursor;if(items.length>=1000&&cursor)throw Error('Reusable library exceeds the bounded 1000-version editor limit.')}while(cursor);if(!cancelled){setAssets(current=>[...items,...current.filter(a=>!items.some(item=>item.id===a.id))]);setError('')}};void load().catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:'Library unavailable.')});return()=>{cancelled=true}},[session?.accessToken])
  const save=async(asset:QuestionGroupAsset)=>{assertAssetWrite(assets.find(a=>a.id===asset.id),asset);if(session&&apiOrigin){const response=await fetch(`${apiOrigin}/api/question-groups/${asset.id}`,{method:'PUT',headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(asset)});const body=await response.json() as {error?:string};if(!response.ok)throw Error(body.error??'Could not save reusable group.')}setAssets(current=>[...current.filter(a=>a.id!==asset.id),asset])}
  return {assets,save,error}
}
export function QuestionGroupsPage({assets,onSave,forms,renderEditor,connected}:{assets:QuestionGroupAsset[];onSave:(asset:QuestionGroupAsset)=>Promise<void>;forms:EvaluationForm[];renderEditor:QuestionEditorRenderer;connected:boolean}){
  const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<QuestionGroupAsset|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const asset=draft??assets.find(a=>a.id===selected),editable=asset?.status==='DRAFT'
  const perform=async(next:QuestionGroupAsset)=>{setBusy(true);setError('');try{await onSave(next);setSelected(next.id);setDraft(null);setNotice(`${next.name} v${next.version} saved as ${next.status}${connected?' to the durable library':' in this browser'}.`)}catch(reason){setError(reason instanceof Error?reason.message:'Could not save asset.')}finally{setBusy(false)}}
  const add=()=>{const id=`asset_${crypto.randomUUID().replaceAll('-','')}`,now=new Date().toISOString();setDraft({id,familyId:id,name:'New reusable group',description:'',version:1,status:'DRAFT',questions:[newItem()],createdAt:now,updatedAt:now});setSelected(id)}
  const asForm=(a:QuestionGroupAsset):EvaluationForm=>({id:a.id,name:a.name,description:a.description,version:a.version,status:a.status==='DRAFT'?'DRAFT':a.status,enabled:a.status==='PUBLISHED',questions:a.questions.map(q=>({...q,groupId:'asset_questions'})),groups:[{id:'asset_questions',name:a.name,description:a.description,condition:a.condition,scoring:a.scoring}],scoring:{yesThreshold:.65,passScore:.7,criticalQuestionIds:[]}})
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION</div><h1>Question Groups</h1><p>Versioned reusable templates. Forms retain independent snapshots.</p></div><button className="primary-button" onClick={add}>New group asset</button></div>{!connected&&<p className="field-note">Library edits are saved in this browser. Connect to the automation service for durable storage.</p>}
    <OperationalTable rows={assets} keyOf={a=>a.id} onSelect={a=>{setSelected(a.id);setDraft(null);setError('')}} columns={[{key:'name',label:'Name',value:a=>a.name},{key:'status',label:'Status',value:a=>a.status},{key:'version',label:'Version',value:a=>a.version,render:a=>`v${a.version}`},{key:'questions',label:'Questions',value:a=>a.questions.length},{key:'used',label:'Used by forms',value:a=>forms.filter(f=>f.groups?.some(g=>g.sourceAsset?.assetId===a.id)).length},{key:'updated',label:'Last modified',value:a=>a.updatedAt,render:a=>new Date(a.updatedAt).toLocaleDateString()}]}/>
    {connected&&<button className="outline-button" disabled={busy} onClick={async()=>{setBusy(true);try{for(const seed of seedGroupAssets)if(!assets.some(a=>a.id===seed.id&&a.status==='RETIRED'))await onSave(seed);setNotice('Starter library saved to the durable service.')}catch(reason){setError(reason instanceof Error?reason.message:'Seed save failed.')}finally{setBusy(false)}}}>Save starter library to server</button>}
    {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {asset&&<section className="asset-detail"><div className="panel form-meta"><div className="panel-heading"><h2>{asset.name} · v{asset.version} · {asset.status}</h2><div className="heading-actions">{editable?<><button className="outline-button" disabled={busy} onClick={()=>void perform(asset)}>Save draft asset</button><button className="primary-button" disabled={busy} onClick={()=>{try{void perform(transitionAsset(asset,'PUBLISHED',new Date().toISOString()))}catch(reason){setError(reason instanceof Error?reason.message:'Publish failed.')}}}>Publish group asset</button></>:<><button className="outline-button" disabled={busy} onClick={()=>{const next=nextAssetVersion(asset,assets,new Date().toISOString());setDraft(next);setSelected(next.id)}}>Edit as new version</button>{asset.status==='PUBLISHED'&&<button className="outline-button" disabled={busy} onClick={()=>void perform(transitionAsset(asset,'RETIRED',new Date().toISOString()))}>Retire group asset</button>}</>}</div></div><div className="editor-grid"><label>Asset name<input readOnly={!editable} value={asset.name} onChange={e=>setDraft({...asset,name:e.target.value})}/></label><label>Asset description<input readOnly={!editable} value={asset.description} onChange={e=>setDraft({...asset,description:e.target.value})}/></label></div></div>
    <GroupedFormEditor key={asset.id} assetMode form={asForm(asset)} readOnly={!editable} renderEditor={renderEditor} onChange={form=>setDraft({...asset,updatedAt:new Date().toISOString(),condition:form.groups?.[0].condition,scoring:form.groups?.[0].scoring,questions:form.questions.map(q=>{const item={...q};delete item.groupId;delete item.sourceAssetQuestionId;return item})})}/></section>}
  </div>
}
