import { useDetailFocus } from './useDetailFocus'
import { LibraryFilters } from './LibraryFilters'
import { filterLibrary } from './domain/authoring'
import { downloadDefinition, exportDefinition, importDefinition, readImport } from './domain/portability'
import { ResourceHistory, usePermission } from './GovernancePanel'
import { useEffect, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import type { AnswerSetAsset, EvaluationForm, QuestionGroupAsset } from './domain/types'
import { apiOrigin } from './domain/manualClient'
import { assertAssetWrite, groupAssetDirty, validateGroupAsset, nextAssetVersion, transitionAsset } from './domain/groupAssets'
import type { SavedCollection } from './useSavedConfiguration'
import { seedGroupAssets } from './domain/seedGroupAssets'
import { OperationalTable } from './OperationalTable'
import { GroupedFormEditor, type QuestionEditorRenderer } from './GroupedFormEditor'
import { newItem } from './domain/scorecard'
const storage='genesys-aqm-v08-group-assets'
export function useGroupAssets(session:AuthSession|null,saved:SavedCollection<QuestionGroupAsset>){
  const [localGroups,setLocalGroups]=useState<QuestionGroupAsset[]>(()=>{try{return JSON.parse(localStorage.getItem(storage)??'null')??structuredClone(seedGroupAssets)}catch{return structuredClone(seedGroupAssets)}})
  const connected=!!session&&!!apiOrigin,assets=connected?saved.items:localGroups
  useEffect(()=>{try{localStorage.setItem(storage,JSON.stringify(localGroups))}catch{ /* Explicit save reports failure. */ }},[localGroups])
  const save=async(asset:QuestionGroupAsset)=>{
    assertAssetWrite(assets.find(a=>a.id===asset.id),asset)
    if(connected){const response=await fetch(`${apiOrigin}/api/question-groups/${asset.id}`,{method:'PUT',headers:{Authorization:`Bearer ${session!.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(asset)});const body=await response.json() as {item:QuestionGroupAsset;error?:string};if(!response.ok)throw Error(body.error??'Could not save reusable group.');saved.accept(body.item)}
    else{const next=[...localGroups.filter(a=>a.id!==asset.id),asset];localStorage.setItem(storage,JSON.stringify(next));setLocalGroups(next)}
  }
  const accept=(asset:QuestionGroupAsset)=>connected?saved.accept(asset):setLocalGroups(current=>[...current.filter(a=>a.id!==asset.id),asset])
  return {assets,localGroups,save,accept,error:saved.error}
}
export function QuestionGroupsPage({answerSets=[],onSaveAnswerSet,formsReady,savedState,localGroups,assets,onSave,forms,renderEditor,connected,session,onImported,onDirty}:{answerSets?:AnswerSetAsset[];onSaveAnswerSet?:(a:AnswerSetAsset)=>Promise<void>;formsReady:boolean;savedState:SavedCollection<QuestionGroupAsset>;localGroups:QuestionGroupAsset[];onDirty:(name:string|null)=>void;onImported:(asset:QuestionGroupAsset)=>void;assets:QuestionGroupAsset[];onSave:(asset:QuestionGroupAsset)=>Promise<void>;forms:EvaluationForm[];renderEditor:QuestionEditorRenderer;connected:boolean;session:AuthSession|null}){
  const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<QuestionGroupAsset|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const [savedAt,setSavedAt]=useState('')
  const [status,setStatus]=useState('All'),[latest,setLatest]=useState(false),[usage,setUsage]=useState('All')
  const filtered=filterLibrary(assets,status,latest,usage,a=>a.status,a=>forms.some(f=>f.groups?.some(g=>g.sourceAsset?.assetId===a.id)))
  const canWrite=usePermission('groups.write')
  const asset=draft??assets.find(a=>a.id===selected),editable=canWrite&&asset?.status==='DRAFT'
  const focus=useDetailFocus(asset?.id)
  const dirty=groupAssetDirty(asset,assets.find(a=>a.id===asset?.id))
  useEffect(()=>{onDirty(dirty?asset!.name:null);return()=>onDirty(null)},[dirty,asset?.name,onDirty])
  const mayLeave=()=>!dirty||window.confirm(`You have unsaved changes to ${asset!.name}. Leave this group and discard them?`)
  const perform=async(next:QuestionGroupAsset)=>{setBusy(true);setError('');try{const errors=validateGroupAsset(next);if(errors.length)throw Error(errors.join(' '));await onSave(next);setSavedAt(new Date().toLocaleTimeString());setSelected(next.id);setDraft(null);setNotice(`${next.name} v${next.version} saved as ${next.status}${connected?' to the durable library':' in this browser'}.`)}catch(reason){setError(reason instanceof Error?reason.message:'Could not save asset.')}finally{setBusy(false)}}
  const add=()=>{if(busy||!mayLeave())return;setNotice('');setSavedAt('');const id=`asset_${crypto.randomUUID().replaceAll('-','')}`,now=new Date().toISOString();setDraft({id,familyId:id,name:'New reusable group',description:'',version:1,status:'DRAFT',questions:[newItem()],createdAt:now,updatedAt:now});setSelected(id)}
  const asForm=(a:QuestionGroupAsset):EvaluationForm=>({id:a.id,name:a.name,description:a.description,version:a.version,status:a.status==='DRAFT'?'DRAFT':a.status,enabled:a.status==='PUBLISHED',questions:a.questions.map(q=>({...q,groupId:'asset_questions'})),groups:[{id:'asset_questions',name:a.name,description:a.description,condition:a.condition,scoring:a.scoring}],scoring:{yesThreshold:.65,passScore:.7,criticalQuestionIds:[]}})
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION</div><h1 ref={focus.fallbackRef} tabIndex={-1}>Question Groups</h1><p>Versioned reusable templates. Forms retain independent snapshots.</p></div>{canWrite&&<div className="heading-actions"><label className="outline-button">Import reusable group<input className="sr-only" type="file" accept=".json,application/json" aria-label="Import reusable group" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file||busy||!mayLeave())return;setError('');setBusy(true);try{const value=await readImport(file);if(connected&&session&&apiOrigin){const reply=await fetch(`${apiOrigin}/api/question-groups/import`,{method:'POST',headers:{Authorization:`Bearer ${session.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(value)});const payload=await reply.json();if(!reply.ok)throw Error(payload.error??'Import failed.');onImported(payload.item);setSavedAt(new Date().toLocaleTimeString());setSelected(payload.item.id);setDraft(null);setNotice('Reusable group imported as a new DRAFT.')}else await perform(importDefinition('group',value,`asset_${crypto.randomUUID().replaceAll('-','')}`,new Date().toISOString()))}catch(reason){setError(String(reason))}finally{setBusy(false)}}}/></label><button className="primary-button" disabled={busy} onClick={add}>New reusable question group</button></div>}</div>{!connected&&<p className="field-note">Library edits are saved in this browser. Connect to the automation service for durable storage.</p>}
    {connected&&<section aria-label="Saved Question Groups"><h2>Saved in AQM · {assets.length} saved {assets.length===1?'group':'groups'}</h2><button className="outline-button" disabled={busy||savedState.loading} onClick={()=>void savedState.refresh()}>Refresh saved groups</button>{savedState.loading&&<p role="status">Loading saved reusable question groups…</p>}{savedState.error&&<p role="alert">Saved reusable question groups unavailable: {savedState.error}</p>}</section>}
    {connected&&!formsReady&&<p role="status">Saved form usage unavailable until saved forms load.</p>}<LibraryFilters status={status} onStatus={setStatus} latest={latest} onLatest={setLatest} usage={usage} onUsage={setUsage}/><OperationalTable tableLabel="Reusable question groups table" selectionControl={{columnKey:'name',label:a=>`Open reusable question group ${a.name} v${a.version}`}} rows={filtered} keyOf={a=>a.id} onSelect={a=>{if(busy||!mayLeave())return;focus.capture();setSelected(a.id);setDraft(null);setError('');setNotice('');setSavedAt('')}} columns={[{key:'name',label:'Name',value:a=>a.name},{key:'status',label:'Status',value:a=>a.status},{key:'version',label:'Version',value:a=>a.version,render:a=>`v${a.version}`},{key:'questions',label:'Questions',value:a=>a.questions.length},{key:'used',label:'Used by forms',value:a=>!formsReady?'Unavailable':forms.filter(f=>f.groups?.some(g=>g.sourceAsset?.assetId===a.id)).length},{key:'updated',label:'Last modified',value:a=>a.updatedAt,render:a=>new Date(a.updatedAt).toLocaleDateString()}]}/>
    {connected&&<details className="panel local-library"><summary>Local drafts &amp; starter examples · {localGroups.length} groups</summary><p>Preserved in this browser. Not saved in AQM. Saved form authoring offers only published saved groups.</p>{localGroups.map(local=><div key={local.id} className="panel"><strong>{local.name} · v{local.version}</strong><p>Not saved in AQM · local copy</p><button className="outline-button" onClick={()=>downloadDefinition('group',local)}>Export local JSON</button>{canWrite&&<button className="outline-button" disabled={busy} onClick={()=>{if(!mayLeave())return;const next=importDefinition('group',exportDefinition('group',local),`asset_${crypto.randomUUID().replaceAll('-','')}`,new Date().toISOString());void perform(next)}}>Save as AQM draft</button>}</div>)}</details>}
    {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {asset&&<section className="asset-detail"><div className="panel form-meta"><div className="panel-heading"><h2 ref={focus.headingRef} tabIndex={-1}>{asset.name} · v{asset.version} · {asset.status}</h2><div className="heading-actions"><button className="outline-button" disabled={busy} onClick={()=>{if(!mayLeave())return;setSelected(null);setDraft(null);focus.restore()}}>Close details</button><button className="outline-button" onClick={()=>{try{downloadDefinition('group',asset)}catch(reason){setError(String(reason))}}}>Export JSON</button>{editable?<><button className="outline-button" disabled={busy} onClick={()=>void perform(asset)}>Save changes</button><button className="primary-button" disabled={busy} onClick={()=>{try{void perform(transitionAsset(asset,'PUBLISHED',new Date().toISOString()))}catch(reason){setError(reason instanceof Error?reason.message:'Publish failed.')}}}>Publish reusable question group</button></>:canWrite?<><button className="outline-button" disabled={busy} onClick={()=>{if(!mayLeave())return;setNotice('');setSavedAt('');const next=nextAssetVersion(asset,assets,new Date().toISOString());setDraft(next);setSelected(next.id)}}>Edit as new version</button>{asset.status==='PUBLISHED'&&<button className="outline-button" disabled={busy} onClick={()=>void perform(transitionAsset(asset,'RETIRED',new Date().toISOString()))}>Retire reusable question group</button>}</>:null}</div></div>{!editable&&<p className="field-note">{!canWrite?'You have read-only access. Your role cannot edit this configuration.':asset.status==='PUBLISHED'?'Published version is read-only. Create a new version to edit.':'Retired version is read-only. Create a new version to edit.'}</p>}{editable&&<p role="status">{dirty?'Unsaved changes':savedAt?`Saved ${savedAt}${connected?'':' · Saved in this browser'}`:'Saved'+(connected?'':' in this browser')}</p>}<div className="editor-grid"><label>Reusable question group name<input readOnly={!editable||busy} value={asset.name} onChange={e=>setDraft({...asset,name:e.target.value})}/></label><label>Reusable question group description<input readOnly={!editable||busy} value={asset.description} onChange={e=>setDraft({...asset,description:e.target.value})}/></label></div></div>
    <ResourceHistory session={session} type="group" id={asset.id}/><GroupedFormEditor answerSets={answerSets} onSaveAnswerSet={onSaveAnswerSet} key={asset.id} assetMode form={asForm(asset)} readOnly={!editable||busy} renderEditor={renderEditor} onChange={form=>setDraft({...asset,updatedAt:new Date().toISOString(),condition:form.groups?.[0].condition,scoring:form.groups?.[0].scoring,questions:form.questions.map(q=>{const item={...q};delete item.groupId;delete item.sourceAssetQuestionId;return item})})}/></section>}
  </div>
}
