import { withEvaluationScopeLabels } from './evaluationAvailability'
import { ResponsiveViewSwitcher, analyticsViews } from './ResponsiveViewSwitcher'
import { useEffect, useRef, useState } from 'react'
import type { AuthSession } from './domain/genesysAuth'
import { analyticsCohortKeys, analyticsQuestionFilters } from './domain/navigation'
import type { Breakdown } from './domain/analytics'
import { CoverageFunnel } from './CoverageFunnel'
import { formLabel,formLabels,formReference,lowestApplicable,questionTitle,sampleLabel,sourceLabel,qualityPercent as pct,qualityCoverageCopy,cohortDateLabel } from './analyticsPresentation'
import { loadPolicyCollection,policyCall } from './domain/policyClient'
import type { EvaluationForm,InteractionPolicy } from './domain/types'
import { OperationalTable, type Column } from './OperationalTable'
const origin=(import.meta.env.VITE_AQM_API_ORIGIN??'').trim().replace(/\/$/,'')
type Result={runCounts?:{completed:number;partial:number;failed:number;running:number};scope:'complete';recordsScanned:number;runsScanned:number;metrics:{evaluations:number;conversations:number;averageScore:number|null;passRate:number|null;criticalFailures:number;criticalFailureRate:number|null;reviewRequested:number;reviewed:number;inReview:number};byAgent:Breakdown[];byQueue:Breakdown[];byForm:Breakdown[];byQuestion:Breakdown[];byGroup?:Breakdown[];byDay:Breakdown[];scoreDistribution:Array<{band:string;count:number}>;coverage:{candidate:number;eligible:number;sampled:number;evaluable:number;evaluated:number;successful:number;failed:number};coverageByQueue:Array<{key:string;eligible:number;sampled:number;evaluated:number}>;coverageByAgent:Array<{key:string;agentId:string;eligible:number;sampled:number;evaluated:number}>;queueCoverageRunCount:number}
type AnalyticsTab='overview'|'agents'|'queues'|'forms'|'questions'|'groups'|'coverage'
export function ServerAnalytics({session,onExplore}:{session:AuthSession|null;onExplore:(filters:Record<string,string>)=>void}){
  const [data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0),[filtersOpen,setFiltersOpen]=useState(false)
  const [names,setNames]=useState<Record<string,string>>({}),[policies,setPolicies]=useState<InteractionPolicy[]>([]),[policyError,setPolicyError]=useState(''),[options,setOptions]=useState<{agents:string[];queues:string[]}>({agents:[],queues:[]})
  useEffect(()=>{let cancelled=false;setNames({});setPolicies([]);setOptions({agents:[],queues:[]});if(!session||!origin)return;const call=<T,>(path:string)=>policyCall<T>(origin,session,path);void loadPolicyCollection<InteractionPolicy>(call,'/api/policies').then(items=>{if(!cancelled){setPolicies(items);setPolicyError('')}}).catch(()=>{if(!cancelled)setPolicyError('Policy names unavailable. Use the identifier in Advanced filters.')});void loadPolicyCollection<EvaluationForm>(call,'/api/forms').then(items=>{if(!cancelled)setNames(previous=>({...previous,...Object.fromEntries(items.filter(item=>item.status==='PUBLISHED').map(item=>[`${item.id}@${item.version}`,`${item.name} v${item.version}`]))}))}).catch(()=>{});return()=>{cancelled=true}},[session?.accessToken])
  const [tab,setTab]=useState<AnalyticsTab>((() => {const value=new URLSearchParams(location.search).get('analyticsTab');return ['overview','agents','queues','forms','questions','groups','coverage'].includes(value??'')?value as AnalyticsTab:'overview'})())
  const [from,setFrom]=useState(new URLSearchParams(location.search).get('from')??''),[to,setTo]=useState(new URLSearchParams(location.search).get('to')??''),[source,setSource]=useState(new URLSearchParams(location.search).get('source')??''),[policy,setPolicy]=useState(new URLSearchParams(location.search).get('policy')??''),[form,setForm]=useState(new URLSearchParams(location.search).get('form')??''),[agent,setAgent]=useState(new URLSearchParams(location.search).get('agent')??''),[queue,setQueue]=useState(new URLSearchParams(location.search).get('queue')??''),[channel,setChannel]=useState(new URLSearchParams(location.search).get('channel')??''),[mode,setMode]=useState(new URLSearchParams(location.search).get('mode')??'')
  const cohort={from,to,source,policy,form,agent,queue,channel,mode}
  useEffect(()=>{const url=new URL(location.href);for(const key of analyticsCohortKeys)cohort[key]?url.searchParams.set(key,cohort[key]):url.searchParams.delete(key);url.searchParams.set('analyticsTab',tab);history.replaceState(null,'',url)},[from,to,source,policy,form,agent,queue,channel,mode,tab])
  const sequence=useRef(0)
  useEffect(()=>{sequence.current++;setData(null);setLoading(!!session);if(!session||!origin){setData(null);return}const timer=setTimeout(async()=>{const current=++sequence.current;setLoading(true);setError('');try{const url=new URL(`${origin}/api/analytics`);for(const [key,value] of Object.entries({from:from?`${from}T00:00:00.000Z`:'',to:to?`${to}T23:59:59.999Z`:'',source,policy,form,agent,queue,channel,mode}))if(value)url.searchParams.set(key,value);const reply=await fetch(url,{headers:{Authorization:`Bearer ${session.accessToken}`}});const body=await reply.json() as Result&{error?:string};if(!reply.ok)throw new Error(body.error??`HTTP ${reply.status}`);if(current===sequence.current){setData(body);setNames(previous=>({...previous,...formLabels(body.byForm)}));setOptions(previous=>({agents:[...new Set([...previous.agents,...body.byAgent.map(item=>item.key)])].sort(),queues:[...new Set([...previous.queues,...body.byQueue.map(item=>item.key)])].sort()}))}}catch(reason){if(current===sequence.current){setData(null);setError(reason instanceof Error?reason.message:'Analytics unavailable.')}}finally{if(current===sequence.current)setLoading(false)}},250);return()=>clearTimeout(timer)},[session?.accessToken,from,to,source,policy,form,agent,queue,channel,mode,retry])
  const rows=data?.[tab==='agents'?'byAgent':tab==='queues'?'byQueue':tab==='forms'?'byForm':tab==='questions'?'byQuestion':tab==='groups'?'byGroup':'byDay']??[]
  const exact=tab==='questions'||tab==='groups'
  const identity=(item:Breakdown)=>tab==='questions'?questionTitle(item):tab==='forms'?formLabel(formReference(item),names):item.key
  const explore=(filters:Record<string,string>,labels:Record<string,string>={})=>onExplore(withEvaluationScopeLabels(filters,{form:formLabel(filters.form,names),...labels}))
  const inspect=(item:Breakdown,kind=tab)=>{if(kind==='questions')explore(analyticsQuestionFilters(cohort,item.formRef??form,item.questionId??''),{question:questionTitle(item)});else if(kind==='groups')explore({...cohort,form:item.formRef??form,cohort:'analytics'});else if(kind==='queues'||kind==='agents')explore({...cohort,[kind==='queues'?'queue':'agent']:item.key,cohort:'analytics'});else if(kind==='forms'){setForm(formReference(item));setTab('questions')}}
  const columns:Column<Breakdown>[]=[
   {key:'name',label:tab==='questions'?'Question':tab==='groups'?'Group':tab==='forms'?'Form version':tab==='queues'?'Queue':'Agent',value:identity,width:'200px'},
   ...(exact?[{key:'form',label:'Form version',value:(item:Breakdown)=>formLabel(item.formRef??form,names)}]:[]),
   {key:'count',label:tab==='questions'?'Applicable answers':tab==='groups'?'Applicable evaluations':'Evaluations',value:item=>exact?item.applicableCount??item.count:item.count},
   {key:'quality',label:tab==='groups'?'Average AI score':'Average quality',value:item=>item.averageScore??-1,render:item=>pct(item.averageScore)},
   ...(tab==='groups'?[
    {key:'human',label:'Average human score',value:(item:Breakdown)=>item.humanAverageScore??-1,render:(item:Breakdown)=>pct(item.humanAverageScore)},
    {key:'gap',label:'Human − AI difference',value:(item:Breakdown)=>item.meanScoreDifference??-1,render:(item:Breakdown)=>item.meanScoreDifference==null?'—':`${(item.meanScoreDifference*100).toFixed(1)} pp`},
    {key:'reviewed',label:'Reviewed count',value:(item:Breakdown)=>item.reviewedCount??0},
    {key:'groupCritical',label:'Critical group failures',value:(item:Breakdown)=>item.criticalGroupFailures??0},
   ]:[{key:'critical',label:'Critical failure occurrences',value:(item:Breakdown)=>item.criticalFailures}]),
   ...(!exact?[{key:'pass',label:'Pass rate',value:(item:Breakdown)=>item.passRate??-1,render:(item:Breakdown)=>pct(item.passRate)}]:[]),
   ...(tab==='questions'?[
    {key:'uncertainty',label:'Uncertainty',value:(item:Breakdown)=>item.uncertaintyRate??-1,render:(item:Breakdown)=>pct(item.uncertaintyRate)},
    {key:'confidence',label:'Average confidence',value:(item:Breakdown)=>item.averageConfidence??-1,render:(item:Breakdown)=>pct(item.averageConfidence)},
   ]:[]),
   {key:'inspect',label:'Investigate',value:()=>'',render:item=>tab==='forms'?<button className="text-link" onClick={()=>inspect(item)}>View questions →</button>:<button className="text-link" onClick={()=>inspect(item)}>{tab==='groups'?'Inspect form evaluations →':'Inspect evaluations →'}</button>},
  ]
  const weakestQuestion=lowestApplicable(data?.byQuestion??[],true),weakestGroup=lowestApplicable(data?.byGroup??[],true),weakestQueue=lowestApplicable(data?.byQueue??[])
  const changeFilters=()=>{setFiltersOpen(true);setTimeout(()=>document.getElementById('quality-from')?.focus(),0)}
  const selectedPolicy=policies.find(item=>item.id===policy)?.name??'Selected policy (name unavailable)'
  const scope=[sourceLabel(source),policy?selectedPolicy:'All policies',form?formLabel(form,names):'All published forms',queue,agent,channel,mode==='scheduled'?'Scheduled':mode==='manual'?'Manual':''].filter(Boolean).join(' · ')
  return <div className="page-content quality-analytics">
   <div className="page-heading"><div><div className="eyebrow">QUALITY ANALYTICS</div><h1>Quality analytics</h1><p>Understand quality, coverage and where to investigate.</p></div></div>
   <section className="panel cohort-summary" aria-label="Selected quality cohort"><div><strong>{cohortDateLabel(from,to)}</strong><p>{scope}</p>{data&&<small>{data.metrics.evaluations} evaluations · {data.metrics.conversations} evaluated conversations</small>}</div><button className="outline-button" aria-expanded={filtersOpen} onClick={filtersOpen?()=>setFiltersOpen(false):changeFilters}>Change filters</button></section>
   <details className="panel analytics-filter-disclosure" open={filtersOpen} onToggle={event=>setFiltersOpen(event.currentTarget.open)}><summary>Quality filters</summary><div className="browser-filters analytics-filter-bar">
    <label>From<input id="quality-from" type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label>
    <label>Source<select aria-label="Source" value={source} onChange={event=>setSource(event.target.value)}><option value="">All sources</option><option value="genesys-cloud">Genesys Cloud</option><option value="synthetic">Synthetic</option><option value="uploaded">Uploaded</option></select></label>
    <label>Form<select aria-label="Form" value={form} onChange={event=>setForm(event.target.value)}><option value="">All published forms</option>{form&&!names[form]&&<option value={form}>{formLabel(form,names)}</option>}{Object.entries(names).sort((a,b)=>a[1].localeCompare(b[1])).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    <label>Queue<input list="quality-queues" value={queue} onChange={event=>setQueue(event.target.value)}/><datalist id="quality-queues">{options.queues.map(value=><option key={value} value={value}/>)}</datalist></label>
    <label>Agent<input list="quality-agents" value={agent} onChange={event=>setAgent(event.target.value)}/><datalist id="quality-agents">{options.agents.map(value=><option key={value} value={value}/>)}</datalist></label>
    <details className="advanced-quality-filters"><summary>Advanced filters</summary>{policies.length?<label>Policy<select aria-label="Policy" value={policy} onChange={event=>setPolicy(event.target.value)}><option value="">All policies</option>{policy&&!policies.some(item=>item.id===policy)&&<option value={policy}>Selected policy (name unavailable)</option>}{policies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:<label>Policy identifier<input value={policy} onChange={event=>setPolicy(event.target.value)}/></label>}{policyError&&<p>{policyError}</p>}<label>Channel<input value={channel} onChange={event=>setChannel(event.target.value)}/></label><label>Trigger<select aria-label="Trigger" value={mode} onChange={event=>setMode(event.target.value)}><option value="">All</option><option value="manual">Manual</option><option value="scheduled">Scheduled</option></select></label></details>
   </div></details>
   {!session&&<p>Connect in Settings to access Saved AQM analytics.</p>}{loading&&<p role="status">Loading quality analytics…</p>}
   {error&&<div role="alert"><p className="inline-error">Quality analytics could not be loaded.</p><button className="outline-button" onClick={()=>setRetry(value=>value+1)}>Retry</button><details><summary>Technical details</summary><p>{error}</p></details></div>}
   {data&&<><ResponsiveViewSwitcher label="Analytics views" options={analyticsViews} value={tab} onChange={setTab}/>
    {tab==='overview'?<><div className="metrics-grid quality-metrics">
     <div className="metric panel"><small>Average quality</small><strong>{pct(data.metrics.averageScore)}</strong></div>
     <div className="metric panel"><small>Evaluated conversations</small><strong>{data.metrics.conversations}</strong><span>{data.metrics.evaluations} evaluations</span></div>
     <div className="metric panel"><small>Pass rate</small><strong>{pct(data.metrics.passRate)}</strong></div>
     <div className="metric panel"><small>Evaluations with critical failure</small><strong>{pct(data.metrics.criticalFailureRate)}</strong><span>{data.metrics.criticalFailures} failure occurrences</span></div>
     <div className="metric panel quality-review-state"><small>Review state</small><strong>{data.metrics.reviewRequested} Awaiting review</strong><span>{data.metrics.inReview??0} In progress · {data.metrics.reviewed} Reviewed</span></div>
    </div>{!data.metrics.evaluations?<section className="panel analytics-panel"><h2>No evaluations match this scope.</h2><p>Quality analytics will appear after evaluations are completed.</p><button className="outline-button" onClick={changeFilters}>Change filters</button></section>:<section className="panel analytics-panel" aria-label="What stands out"><h2>What stands out</h2><div className="insight-grid">
     {data.metrics.criticalFailures>0&&<article><small>Quality attention</small><strong>{data.metrics.criticalFailures} critical failure occurrences recorded</strong><p>Across {data.metrics.evaluations} evaluations · {pct(data.metrics.criticalFailureRate)} of evaluations have a critical failure</p><button className="text-link" onClick={()=>explore({...cohort,critical:'yes',cohort:'analytics'})}>Inspect critical evaluations →</button></article>}
     {weakestQuestion&&<article><small>Lowest average question in this cohort</small><strong>{formLabel(weakestQuestion.formRef!,names)} · {questionTitle(weakestQuestion)}</strong><p>{pct(weakestQuestion.averageScore)} average · {sampleLabel(weakestQuestion,'question')}{weakestQuestion.criticalFailures>0?` · ${weakestQuestion.criticalFailures} critical failures`:''}</p><button className="text-link" onClick={()=>inspect(weakestQuestion,'questions')}>Inspect evaluations →</button></article>}
     {weakestQueue&&<article><small>Lowest average queue among queues with evaluated conversations</small><strong>{weakestQueue.key}</strong><p>{pct(weakestQueue.averageScore)} average · {sampleLabel(weakestQueue,'queue')}</p><button className="text-link" onClick={()=>inspect(weakestQueue,'queues')}>Inspect evaluations →</button></article>}
     {weakestGroup&&<article><small>Lowest average group in this cohort</small><strong>{formLabel(weakestGroup.formRef!,names)} · {weakestGroup.key}</strong><p>{pct(weakestGroup.averageScore)} AI average · {sampleLabel(weakestGroup,'group')}</p><button className="text-link" onClick={()=>{setForm(weakestGroup.formRef!);setTab('groups')}}>View group comparison →</button></article>}
    </div><p className="field-note">Comparisons describe this selected cohort. Sample sizes vary; rankings do not establish statistical significance or a cause.</p></section>}
    <div className="analytics-grid"><section className="panel analytics-panel"><h2>Quality by day</h2>{data.byDay.filter(item=>item.averageScore!==null).length<3&&<p>Limited history in this period.</p>}<div className="quality-days">{data.byDay.map(item=><div key={item.key}><time>{item.key}</time><div className="bar-track"><span style={{width:`${(item.averageScore??0)*100}%`}}/></div><strong>{pct(item.averageScore)}</strong><small>{item.count} evaluations</small></div>)}</div></section><section className="panel analytics-panel"><h2>Score distribution</h2><div className="bar-list">{data.scoreDistribution.map(item=><div className="bar-row" key={item.band}><strong>{item.band}</strong><div className="bar-track"><span style={{width:`${data.metrics.evaluations?item.count/data.metrics.evaluations*100:0}%`}}/></div><b>{item.count}</b></div>)}</div></section></div></>:tab==='coverage'?<>
     <section className="panel analytics-panel" aria-label="Coverage scope"><h2>Coverage scope</h2><p>{cohortDateLabel(from,to)} · {sourceLabel(source)} · {policy?selectedPolicy:'All policies'}</p><p>{qualityCoverageCopy}</p><p className="field-note">Date, source and policy filter monitoring runs. Form, queue, agent, channel and trigger quality filters do not change overall coverage denominators.</p>{data.runCounts&&Object.values(data.runCounts).every(count=>count===0)?<p>Coverage will appear after a monitoring policy run.</p>:<CoverageFunnel counts={data.coverage} showGaps/>}</section>
     <p className="field-note">Content available is not recorded by queue or agent. Breakdowns include only runs carrying that evidence; older runs may not include it. Viewing evaluated quality narrows evaluations without changing historical coverage.</p><div className="analytics-grid">{(['queue','agent'] as const).map(kind=><section className="panel analytics-panel" key={kind}><h2>Coverage by {kind}</h2>{kind==='queue'&&<p>{data.queueCoverageRunCount} runs carry queue coverage evidence.</p>}{(kind==='queue'?data.coverageByQueue:data.coverageByAgent).map(item=><div className="coverage-breakdown" key={item.key}><strong>{item.key}</strong><p>{item.eligible} Eligible · {item.sampled} Sampled · {item.evaluated} Evaluated</p><button className="text-link" onClick={()=>{kind==='queue'?setQueue(item.key):setAgent(item.key);setTab(kind==='queue'?'queues':'agents')}}>View evaluated quality →</button></div>)}</section>)}</div>
    </>:<><p className="field-note">{tab==='groups'?'Human comparison uses completed reviews only. Reviewed count is the sample for human averages; differences do not measure population accuracy. Group investigation opens the exact form cohort.':tab==='questions'?'Each question is kept separate by exact form version. Inspect evaluations to see applicable answers.':'Inspect evaluations to investigate this selected cohort.'}</p>{tab==='questions'&&<details><summary>About confidence &amp; uncertainty</summary><p>Confidence is provider/model confidence for the prepared decision. It is not human agreement or empirical accuracy. Uncertainty counts Yes/No probabilities from 40–60%, or other answers with confidence below 60%.</p></details>}<OperationalTable selectionControl={{columnKey:'name',label:item=>`Investigate ${identity(item)}`}} tableLabel={`Quality analytics ${tab} table`} rows={rows} columns={columns} keyOf={item=>`${item.formRef??''}|${item.questionId??item.groupId??item.key}`} onSelect={item=>inspect(item)} stateKey={`analytics.${tab}`} empty="No evaluations match this scope."/></>}
    <details className="panel analytics-panel"><summary>Data scope &amp; technical details</summary><p>Saved AQM analytics · complete API aggregation. {data.recordsScanned} records scanned · {data.runsScanned} runs scanned. Form tests are excluded from quality. Complete totals are returned, or an explicit size error; backend limits are 2,000 evaluation records, 500 runs and 2,000 human reviews.</p><p>Critical failure occurrences include question and group failures; the rate counts evaluations with at least one such failure.</p><pre>{JSON.stringify({filters:cohort,provenance:exact?rows.map(item=>({formRef:item.formRef,questionId:item.questionId,groupId:item.groupId})):undefined},null,2)}</pre></details>
   </>}
  </div>
}
