import { useState } from 'react'
import { costBounds, costPreset, estimateCost, type CostInputs } from './economics'
import { claims } from './claims'
const labels: Record<keyof CostInputs, string> = { volume: 'Conversation volume', percentage: 'Selected percentage', forms: 'Average forms per selected conversation', requests: 'Average requests / waves per form', tokens: 'Average total billed input tokens per request' }
export function CostCalculator() {
  const [values, setValues] = useState<Record<keyof CostInputs, string>>(() => Object.fromEntries(Object.entries(costPreset).map(([key, value]) => [key, String(value)])) as Record<keyof CostInputs, string>)
  const result = Object.values(values).some(value => !value.trim()) ? null : estimateCost(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as unknown as CostInputs)
  const control = (key: keyof CostInputs) => <label key={key}>{labels[key]}<input type="number" min={costBounds[key][0]} max={costBounds[key][1]} step={key === 'volume' || key === 'tokens' ? 1 : 'any'} value={values[key]} onChange={event => setValues(current => ({ ...current, [key]: event.target.value }))}/></label>
  return <section id="economics" className="showcase-section" aria-label="Illustrative cost calculator"><span className="eyebrow">EXPLORE THE ECONOMICS</span><h2>A small model bill. An honest starting point.</h2><p>Browser-only planning estimates, not measured bills or total operating cost.</p><div className="cost-layout"><div className="panel cost-controls">{control('volume')}{control('percentage')}<details><summary>Advanced assumptions</summary>{control('forms')}{control('requests')}{control('tokens')}</details></div><div className="panel cost-result" aria-live="polite"><small>ESTIMATED MODEL INPUT COST · USD</small><strong>{result ? `$${result.cost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : 'Check inputs'}</strong>{result ? <p>{result.selected.toLocaleString()} selected conversations · {result.evaluations.toLocaleString()} estimated form evaluations · {result.requests.toLocaleString()} estimated AI requests.</p> : <p role="alert">Enter finite values within the displayed limits.</p>}<p>Preset: 100,000 selected conversations × 1 form × 1 request × 8,000 input tokens. Two requests per form doubles the estimate to $67.20.</p><p>Average forms and requests can be fractional planning equivalents. Tokens include transcript and questions in each request; repeated transcript input across conditional waves counts again.</p><p><a href={claims.price.source}>Official Jev 1.13 pricing</a>: ${claims.price.value}/M input tokens; output free. Checked {claims.price.checkedAt}; rates may change.</p><p className="cost-exclusions"><strong>Excluded:</strong> transcription, Genesys licensing/retrieval, Cloud Run/Firestore/network, retries, taxes and human review. Not a throughput commitment.</p></div></div></section>
}
