import { useState } from 'react'
import { costBounds, costPreset, estimateCost, type CostInputs } from './economics'
import { claims } from './claims'
const labels: Record<keyof CostInputs, string> = { volume: 'Conversations per month', percentage: 'Selected percentage', forms: 'Average forms per selected conversation', requests: 'Average AI requests per form', tokens: 'Average input tokens per AI request' }
const number = (value: number) => value.toLocaleString('en-US', { maximumFractionDigits: 2 })
export function CostCalculator() {
  const [values, setValues] = useState<Record<keyof CostInputs, string>>(() => Object.fromEntries(Object.entries(costPreset).map(([key, value]) => [key, String(value)])) as Record<keyof CostInputs, string>)
  const inputs = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as unknown as CostInputs
  const errors = (Object.keys(costBounds) as Array<keyof CostInputs>).filter(key => !values[key].trim() || !Number.isFinite(inputs[key]) || inputs[key] < costBounds[key][0] || inputs[key] > costBounds[key][1])
  const result = errors.length ? null : estimateCost(inputs)
  const cost = result ? result.cost > 0 && result.cost < .01 ? 'Less than $0.01/month' : `$${result.cost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}/month` : 'Check inputs'
  const control = (key: keyof CostInputs) => <label key={key}>{labels[key]}<input type="number" aria-label={labels[key]} min={costBounds[key][0]} max={costBounds[key][1]} step={key === 'volume' || key === 'tokens' ? 1 : 'any'} aria-invalid={errors.includes(key)} aria-describedby={`cost-${key}-help`} value={values[key]} onChange={event => setValues(current => ({ ...current, [key]: event.target.value }))}/><small id={`cost-${key}-help`}>{key === 'tokens' ? 'Illustrative medium-length transcript plus quality questions. ' : ''}{number(costBounds[key][0])}–{number(costBounds[key][1])}{key === 'percentage' ? '%' : ''}</small></label>
  return <section id="economics" className="showcase-section" aria-label="Illustrative cost calculator"><span className="eyebrow">EXPLORE THE ECONOMICS</span><h2>A small model bill. An honest starting point.</h2><p>Structured, batched questions and very low model input cost make broader evaluation economically attractive. This is an illustrative planning estimate — model input cost only.</p><div className="cost-layout"><div className="panel cost-controls">{control('volume')}{control('percentage')}<details><summary>Advanced assumptions</summary>{control('forms')}{control('requests')}{control('tokens')}</details></div><div className="panel cost-result" aria-live="polite"><small>ESTIMATED JEV MODEL INPUT COST · USD</small><strong>{cost}</strong>{result ? <><p>{number(result.selected)} conversations/month selected · {number(result.evaluations)} form evaluations · {number(result.requests)} AI requests · {number(result.requests * inputs.tokens / 1_000_000)}M input tokens/month.</p><p>Current assumptions: {number(inputs.volume)} conversations/month · {inputs.percentage}% selected · {inputs.forms} form(s) per conversation · {inputs.requests} AI request(s) per form · {number(inputs.tokens)} input tokens per request.</p>{result.cost > 0 && result.cost < .01 && <p>The estimate is positive: ${result.cost.toPrecision(3)} per month before rounding.</p>}</> : <div role="alert">{errors.map(key => <p key={key}>{labels[key]} must be between {number(costBounds[key][0])} and {number(costBounds[key][1])}{key === 'percentage' ? '%' : ''}. Enter a value for this field{['forms', 'requests', 'tokens'].includes(key) ? ' under Advanced assumptions' : ''}.</p>)}</div>}<p>Input includes transcript and quality questions. Repeated transcript input across conditional requests counts again. Average forms and requests may be fractional planning equivalents.</p><p><a href={claims.price.source}>Official Jev 1.13 pricing</a>: ${claims.price.value}/M input tokens; output free. Checked {claims.price.checkedAt}; rates may change.</p><p className="cost-exclusions"><strong>Excluded:</strong> transcription, Genesys licensing/retrieval, hosting, storage and network costs, retries, taxes and human review. Validate capacity during the pilot.</p></div></div></section>
}
