import { useEffect, useRef, useState } from 'react'
import { DemoRepository, caseConversation, demoForm } from './fixtures'
import { demoStep } from './routing'
const chapters = ['The customer case', 'Define quality', 'Evaluate at scale', 'Human challenge', 'Manage & pilot']
const percent = (value: number | null | undefined) => value == null ? '—' : `${Math.round(value * 100)}%`
export default function Demo({ onExit, onLive, connected = false, onConnect, repository }: { onExit: (pilot?: boolean) => void; onLive: () => void; connected?: boolean; onConnect: () => void; repository?: DemoRepository }) {
  const [store, setStore] = useState(() => { const example = repository ?? new DemoRepository(); example.saveReview(true); return example })
  const [step, setStep] = useState(() => demoStep(new URLSearchParams(location.search)))
  const heading = useRef<HTMLHeadingElement>(null)
  const record = store.case(), review = store.humanReview()
  const answers = record.questions.filter(question => question.status === 'ANSWERED')
  const weak = store.cohort().filter(item => item.questions.find(question => question.id === 'next-step')?.credit === 0).length
  const go = (next: number) => {
    const url = new URL(location.href)
    url.search = new URLSearchParams({ page: 'demo', tour: 'quality', step: String(next) }).toString()
    history.pushState(null, '', url); setStep(next)
  }
  useEffect(() => {
    const url = new URL(location.href)
    url.search = new URLSearchParams({ page: 'demo', tour: 'quality', step: String(step) }).toString()
    history.replaceState(null, '', url)
    heading.current?.focus({ preventScroll: true }); window.scrollTo(0, 0)
  }, [step])
  useEffect(() => {
    const back = () => setStep(demoStep(new URLSearchParams(location.search)))
    window.addEventListener('popstate', back)
    return () => window.removeEventListener('popstate', back)
  }, [])
  const restart = () => { const example = new DemoRepository(); example.saveReview(true); setStore(example); go(1) }
  return <div className="demo-shell"><header className="showcase-header"><img className="ipi-logo" src={`${import.meta.env.BASE_URL}IPIlogo.svg`} alt="IPI"/><strong>IPI AQM</strong><span className="demo-indicator">Interactive demo · fictional data · no live requests</span></header><div className="demo-layout"><aside className="tour-rail" aria-label="Guided product story"><p className="eyebrow">FIVE-MINUTE CUSTOMER CASE</p><ol>{chapters.map((title, index) => <li key={title}><button className="text-link" aria-current={step === index + 1 ? 'step' : undefined} onClick={() => go(index + 1)}>{title}</button></li>)}</ol><p>One conversation, from agreed quality to a pilot decision.</p></aside><main className="demo-content" data-tour={`chapter-${step}`}><div className="chapter-heading"><p className="eyebrow">Chapter {step} of {chapters.length}</p><h1 ref={heading} tabIndex={-1}>{chapters[step - 1]}</h1><progress max={chapters.length} value={step} aria-label="Tour progress"/></div>
    {step === 1 && <><section className="panel case-context"><h2>Was Jamie given a clear next step?</h2><p>Jamie needs account access before the next shift. Alex restores access, but the team settings are still missing.</p></section><section className="panel case-transcript" aria-label="Conversation transcript"><h2>Jamie Taylor with Alex Morgan</h2>{caseConversation.messages.filter(message => message.speaker !== 'system').map(message => <div key={message.id} className={`case-message ${message.speaker}`}><strong>{message.speaker === 'customer' ? 'Jamie' : 'Alex'}</strong><p>{message.text}</p></div>)}</section><p className="story-conclusion">Access is restored. “Later” leaves Jamie without an agreed timeline.</p></>}
    {step === 2 && <><section className="panel"><h2>What does good mean?</h2><p>Quality is defined explicitly. AI doesn’t invent the scoring model.</p><p>{demoForm.name} · Published version {demoForm.version}</p><div className="rubric-list">{demoForm.questions.filter(question => question.id !== 'escalated').map(question => <article key={question.id}><h3>{question.title}</h3><p>{question.instructions}</p><p><strong>{question.type === 'noul' ? 'Yes / No' : 'Clear next step / Timeline not agreed'}</strong></p>{question.id === 'next-step' && <p>Action <em>and</em> timeline must be agreed. Clear earns 100% credit; missing timeline earns 0%. This criterion has double weight within Resolution and is critical: a failure means the form fails.</p>}</article>)}</div><p>Customer care contributes one third of the score; Resolution contributes two thirds. The pass threshold is 75%.</p><p className="field-note">If the issue is unresolved, an additional question asks who owns the escalation. It does not apply to Jamie’s resolved access issue.</p></section><section className="panel"><h2>Reuse agreed standards</h2><p>Reusable Question Groups let authors use common criteria across forms. Each published form keeps its own versioned snapshot.</p><details><summary>Future roadmap: reusable answer scales</summary><p>Reusable Answer Sets would let authors share choices or ordered rating scales across questions. Planned for V0.19; not yet implemented.</p></details></section></>}
    {step === 3 && <><section className="panel" aria-label="Prepared evaluation"><h2>Jev answers. AQM scores.</h2><p>Jev answers specific quality questions in predefined formats. Related questions can be batched in one AI request; AQM applies the agreed scoring rules.</p><div className="answer-list">{answers.map(question => <article key={question.id}><h3>{question.title}</h3><dl><dt>AI answer</dt><dd>{question.outcome}</dd><dt>Credit</dt><dd>{percent(question.credit)}</dd></dl>{question.id === 'next-step' && <><p>Evidence to inspect: “They should return later. Try signing in again.”</p><p>AI confidence: {percent(question.confidence)}. Confidence is not measured correctness.</p></>}</article>)}</div><div className="story-score"><small>ORIGINAL AI SCORE</small><strong>{percent(record.overallScore)}</strong><span>{record.passed ? 'Pass' : 'Fail'} · all three applicable answers earned full credit</span></div><p>The AI accepted “later” as a clear timeline. That judgment deserves a human challenge.</p></section><section className="panel"><h2>Broader coverage becomes attractive</h2><p>Structured, batched questions and Jev’s very low model input cost make broader evaluation economically attractive.</p><p>In this example, a policy selects 24 of 48 eligible conversations (50%) from one customer-service queue. Each uses the same published form. Conditional questions need another request only when they apply.</p><p className="field-note">The calculator on Welcome lets you change volume, selection and request assumptions. Model cost is one component of a pilot’s operating cost.</p></section></>}
    {step === 4 && <section className="panel human-review" aria-label="Independent human review"><h2>“Later” is not an agreed timeline.</h2><div className="review-answer-grid"><div className="review-ai"><small>ORIGINAL AI ANSWER</small><strong>Yes, next step clear</strong><p>Clear next step · 100% credit</p></div><div className="review-human"><small>PREPARED HUMAN REVIEW</small><strong>No, timeline not agreed</strong><p>Timeline not agreed · 0% credit</p></div></div><div className="comparison-scores"><div className="story-score"><small>ORIGINAL AI SCORE · UNCHANGED</small><strong>{percent(record.overallScore)}</strong><span>Pass</span></div><div className="story-score"><small>HUMAN REVIEW SCORE</small><strong>{percent(review.humanOverallScore)}</strong><span>Fail · critical next-step criterion</span></div><div className="story-score"><small>DIFFERENCE</small><strong>{Math.round((review.comparison.absoluteScoreDifference ?? 0) * 100)}</strong><span>percentage points</span></div></div><p>The human agrees on empathy and restored access, but gives no credit for the missing timeline. The same weighted rules produce the human score.</p><p className="story-conclusion">Human review doesn’t rewrite the AI result. It creates independent evidence for calibration.</p><p>Example review completed. The original AI result is unchanged. Two answers agree; one differs. This single review does not establish AI accuracy across a population.</p><details><summary>Inspect the review audit</summary><p>Quality lead reviewed the same published form version. The review keeps separate answers, notes, reviewer identity and completion time.</p><p>Completed 3 October 2026, 13:00 Europe/London.</p></details></section>}
    {step === 5 && <><section className="panel management-conclusion"><span className="eyebrow">MANAGEMENT INSIGHT</span><h2>Resolution guidance needs attention</h2><p><strong>{store.cohort().length} evaluations</strong> matched the same quality question; <strong>{weak} showed weak next-step guidance</strong>. In the one completed human review, the reviewer challenged one AI judgment.</p><p>Investigate missing timelines, coach clear commitments, and refine the criterion with reviewers. These example counts illustrate a management decision, not population statistics.</p><details><summary>Inspect examples</summary><p>Jamie’s AI result passed, but human review identified the ambiguous “later”. The wider example set includes {weak} answers with no agreed timeline.</p><button className="outline-button" onClick={() => go(4)}>Inspect Jamie’s review</button></details></section><section className="panel"><h2>Who owns the next action?</h2><dl className="demo-definition"><dt>Scheduled evaluation</dt><dd>Customer-service queue · daily at 08:00 Europe/London.</dd><dt>Review deadline</dt><dd>Quality lead · due 3 October at 17:00; Jamie’s review is complete.</dd><dt>Auditability</dt><dd>Keep the published form, original AI result and independent human review together.</dd><dt>Attention required</dt><dd>A quality alert directs the lead to investigate resolution guidance and agree coaching.</dd></dl></section><section className="panel pilot-outline"><h2>Agree a focused pilot</h2><ol><li>Agree one queue or use case and an accountable quality lead.</li><li>Choose representative conversations.</li><li>Define the evaluation form.</li><li>Run AI and human comparison.</li><li>Measure quality insight, agreement/calibration, coverage, model cost and reviewer effort.</li><li>Decide whether broader rollout is justified.</li></ol></section></>}
    <nav className="tour-controls" aria-label="Tour controls"><button className="outline-button" disabled={step === 1} onClick={() => go(step - 1)}>Back</button><button className="primary-button" onClick={() => step < chapters.length ? go(step + 1) : onExit(true)}>{step < chapters.length ? 'Next' : 'Plan a pilot'}</button><button className="outline-button" onClick={() => onExit()}>Exit demo</button></nav><details className="story-options"><summary>More options</summary><button className="outline-button" onClick={onLive}>{connected ? 'Open AQM →' : 'Explore the prototype →'}</button>{!connected && <button className="text-link" onClick={onConnect}>Connect Genesys Cloud</button>}<button className="text-link" onClick={restart}>Restart</button><p className="field-note">Refreshing restarts this example. Exploring the prototype opens the workspace with sample conversations.</p></details>
  </main></div></div>
}
