import { useEffect, useRef, useState } from 'react'
import { OverviewView, type OverviewActions } from '../OverviewView'
import { OperationalTable } from '../OperationalTable'
import { Transcript } from '../Transcript'
import { GroupResultsPanel } from '../GroupResultsPanel'
import { GroupedFormEditor } from '../GroupedFormEditor'
import { ReviewScoreSummary } from '../ReviewScoreSummary'
import { questionBreakdown } from '../domain/analytics'
import { analyticsQuestionFilters } from '../domain/navigation'
import { reviewDueState } from '../domain/reviewSla'
import { DemoRepository, caseConversation, demoCapabilities, demoClock, demoForm, demoPolicy } from './fixtures'
import { demoStep } from './routing'
const chapters = [
  { title: 'Understand the operation', view: 'Overview', explanation: 'Quality, controlled coverage and review workload tell us where to investigate. These numbers are derived from 24 prepared records, not live monitoring.' },
  { title: 'Decide what to evaluate', view: 'Policies', explanation: 'One queue, a deterministic 50% sample and the exact v3 form define this example. Coverage is controlled; runtime limits remain unchanged.' },
  { title: 'Define what good looks like', view: 'Evaluation Forms', explanation: 'A reusable care group and weighted, critical resolution criteria make the score explainable. Escalation only applies when Issue resolved is No.' },
  { title: 'Inspect a conversation', view: 'Conversation review', explanation: 'Jamie regains access, but “later” is not a timeline. Reveal prepared typed answers, then question the ambiguous next-step judgment. No inference occurs.' },
  { title: 'Follow the evidence', view: 'Analytics', explanation: 'An exact form-version and question cohort keeps the investigation truthful. Follow Clear next step to the same fictional evaluation.' },
  { title: 'Keep people in control', view: 'My reviews', explanation: 'The scripted human reviewer disagrees about the timeline. Save and complete in demo memory; the original AI answer stays unchanged.' },
  { title: 'Operate and govern', view: 'Governance', explanation: 'Schedules, review SLA, audit and delivery configuration make this more than a model demonstration. All statuses here are simulated; nothing is scheduled or sent.' },
]
const percent = (value: number | null | undefined) => value == null ? '—' : `${Math.round(value * 100)}%`
export default function Demo({ onExit, onLive, repository }: { onExit: (pilot?: boolean) => void; onLive: () => void; repository?: DemoRepository }) {
  const [store, setStore] = useState(() => repository ?? new DemoRepository())
  const [step, setStep] = useState(() => demoStep(new URLSearchParams(location.search)))
  const [revealed, setRevealed] = useState(false)
  const [cohort, setCohort] = useState(false)
  const [revision, setRevision] = useState(0)
  const [notice, setNotice] = useState('')
  const heading = useRef<HTMLHeadingElement>(null)
  const record = store.case(), review = store.humanReview(), chapter = chapters[step - 1]
  const go = (next: number) => {
    const url = new URL(location.href)
    url.search = new URLSearchParams({ page: 'demo', tour: 'quality', step: String(next) }).toString()
    window.history.pushState(null, '', url)
    setStep(next); setNotice(''); setCohort(false)
  }
  useEffect(() => {
    const url = new URL(location.href)
    url.search = new URLSearchParams({ page: 'demo', tour: 'quality', step: String(step) }).toString()
    history.replaceState(null, '', url)
    heading.current?.focus()
    heading.current?.scrollIntoView({ block: 'start' })
  }, [step])
  useEffect(() => {
    const back = () => { setStep(demoStep(new URLSearchParams(location.search))); setCohort(false); setNotice('') }
    window.addEventListener('popstate', back)
    return () => window.removeEventListener('popstate', back)
  }, [])
  const unsupported = () => setNotice('Unavailable in this scripted demo. No live action or request was made.')
  const actions: OverviewActions = { onExplore: filters => go(filters.reviewQueue || filters.reviewStatus || filters.dueState ? 6 : 5), onAnalytics: () => go(5), onEditPolicy: () => go(2), onRun: () => go(7), onAlert: () => go(7), onReview: () => go(4), onPage: page => go(page === 'forms' ? 3 : page === 'policies' ? 2 : 7) }
  const restart = () => { setStore(new DemoRepository()); setRevealed(false); setCohort(false); setRevision(0); go(1) }
  const result = <section className="panel" aria-label="Prepared evaluation"><span className="pill">Prepared example — no AI request made</span><h2>{record.form.name} v{record.form.version}</h2><p>AI score {percent(record.overallScore)} · {record.passed ? 'Pass' : 'Fail'} · actual AI requests: 0.</p><p>Illustrated execution: one batched wave answers care and resolution; a conditional follow-up wave is only needed if escalation applies. This case skips escalation.</p><GroupResultsPanel record={record}/><OperationalTable tableLabel="Prepared typed answers" rows={record.questions} keyOf={question => question.id} columns={[{ key: 'question', label: 'Question', value: question => question.title }, { key: 'type', label: 'Type', value: question => question.type }, { key: 'outcome', label: 'Answer', value: question => question.outcome }, { key: 'confidence', label: 'Confidence / Yes probability', value: question => percent(question.confidence ?? question.probability) }, { key: 'credit', label: 'Credit', value: question => percent(question.credit) }]}/><p className="field-note">Typed answers can be wrong. Confidence is not measured correctness.</p></section>
  return <div className="demo-shell" data-revision={revision}><header className="showcase-header"><img className="ipi-logo" src={`${import.meta.env.BASE_URL}IPIlogo.svg`} alt="IPI"/><strong>IPI AQM</strong><span className="demo-indicator">Interactive demo · fictional data · no live requests</span><button className="outline-button" onClick={() => onExit()}>Exit demo</button></header><div className="demo-layout"><aside className="tour-rail" aria-label="Guided product story"><p className="eyebrow">FIVE-MINUTE PRODUCT STORY</p><p>Chapter {step} of 7</p><progress max={7} value={step} aria-label="Tour progress"/><h1 ref={heading} tabIndex={-1}>{chapter.title}</h1><p>{chapter.explanation}</p><nav aria-label="Tour controls"><button className="outline-button" disabled={step === 1} onClick={() => go(step - 1)}>Back</button><button className="primary-button" onClick={() => step < 7 ? go(step + 1) : onExit(true)}>{step < 7 ? 'Next' : 'Finish tour'}</button><button className="text-link" disabled={step === 7} onClick={() => go(step + 1)}>Skip chapter</button><button className="text-link" onClick={restart}>Restart</button></nav><p className="demo-clock">Demo clock: 3 Oct 2026, 13:00 Europe/London</p><p className="field-note">Read-only authored examples; only the scripted human review changes in memory. Reload reseeds this story.</p><button className="text-link" onClick={onLive}>Open AQM →</button><p className="field-note">Explicitly leaves demo and mounts real application services.</p></aside><main className="demo-content" data-tour={`chapter-${step}`}><div className="page-heading"><div><span className="eyebrow">FICTIONAL CUSTOMER SERVICE TEAM</span><h2>{chapter.view}</h2></div><span className="pill">Simulated · {demoClock.slice(0, 10)}</span></div>{notice && <p role="status" className="demo-banner">{notice}</p>}
    {step === 1 && <OverviewView data={store.overview()} actions={actions} onManual={unsupported} capabilities={demoCapabilities}/>}
    {step === 2 && <><section className="panel"><h2>{demoPolicy.name} v{demoPolicy.version}</h2><p>{demoPolicy.description}</p><dl className="demo-definition"><dt>Criteria</dt><dd>Queue equals {demoPolicy.criteria.anyOf[0][0].value}</dd><dt>Deterministic sample</dt><dd>50% · fictional-quality seed · 24 of 48 eligible conversations</dd><dt>Pinned form snapshot</dt><dd><button className="text-link" onClick={() => go(3)}>{demoForm.name} v{demoForm.version} →</button></dd><dt>Schedule</dt><dd>Simulated daily at 08:00 Europe/London; next 4 Oct 2026</dd></dl><p className="field-note">Read-only. No policy execution or configuration save is available.</p></section><button className="outline-button" onClick={unsupported}>Why is running unavailable?</button></>}
    {step === 3 && <><section className="panel"><h2>{demoForm.name} v{demoForm.version}</h2><p>Published fictional snapshot · group-weighted scoring · pass threshold {percent(demoForm.scoring.passScore)}</p><p>Read-only authored form. Conditional escalation applies only when Issue resolved is No.</p></section><GroupedFormEditor form={demoForm} readOnly onChange={unsupported} renderEditor={question => <article className="panel"><h3>{question.title}</h3><p>{question.instructions}</p><p>Type: {question.type} · weight {question.weight}{demoForm.scoring.criticalQuestionIds.includes(question.id) ? ' · Critical question' : ''}</p>{question.options.map(option => <p key={option.key}>{option.label} · credit {option.credit}</p>)}</article>}/></>}
    {step === 4 && <><Transcript conversation={caseConversation}/><button className="primary-button" onClick={() => setRevealed(true)}>Show example evaluation</button>{revealed && result}</>}
    {step === 5 && <><section className="panel"><h2>Quality → exact question cohort</h2><p>Form: {demoForm.name} v{demoForm.version} · 2 Oct 2026 · fictional voice data only.</p><OperationalTable tableLabel="Exact question cohorts" rows={questionBreakdown(store.list()).filter(item => item.questionId === 'next-step')} keyOf={item => item.key} onSelect={() => { const filters = analyticsQuestionFilters({ from: '2026-10-02', to: '2026-10-02', source: 'synthetic' }, `${demoForm.id}@${demoForm.version}`, 'next-step'); const url = new URL(location.href); for (const [key, value] of Object.entries(filters)) if (value) url.searchParams.set(key, value); history.replaceState(null, '', url); setCohort(true) }} selectionControl={{ columnKey: 'question', label: () => 'Investigate Clear next step' }} columns={[{ key: 'question', label: 'Question', value: () => 'Clear next step' }, { key: 'count', label: 'Evaluations', value: item => item.count }, { key: 'score', label: 'Average credit', value: item => percent(item.averageScore) }]}/></section>{cohort && <section className="panel"><h2>Exact cohort · {store.cohort().length} evaluations</h2><p>{demoForm.id}@{demoForm.version} · next-step · no unrelated records.</p><OperationalTable tableLabel="Cohort evaluations" preserveOrder rows={store.cohort()} keyOf={item => item.id} onSelect={item => item.id === record.id ? go(4) : setNotice('This snapshot belongs to the exact cohort; the scripted transcript follows fictional-evaluation-1.')} selectionControl={{ columnKey: 'evaluation', label: item => `Inspect ${item.id}` }} columns={[{ key: 'evaluation', label: 'Evaluation', value: item => item.id }, { key: 'form', label: 'Form version', value: item => `${item.form.name} v${item.form.version}` }, { key: 'answer', label: 'Next step answer', value: item => item.questions.find(question => question.id === 'next-step')!.outcome }]}/></section>}</>}
    {step === 6 && <section className="panel human-review" aria-label="Demo human review"><h2>My reviews → {record.id}</h2><p>Fictional quality lead · {review.status.replaceAll('_', ' ')} · {reviewDueState(review, demoClock)} · due 3 Oct 2026, 17:00 Europe/London</p><p>Same pinned {demoForm.name} v{demoForm.version}. Original AI result remains immutable.</p><ReviewScoreSummary aiScore={record.overallScore} humanScore={review.humanOverallScore} agreements={review.comparison.agreements} answered={review.comparison.total} gap={review.comparison.absoluteScoreDifference} completed={review.status === 'REVIEWED'}/><div className="review-answer-grid"><div className="review-ai"><small>PREPARED AI ANSWER</small><strong>Clear next step</strong></div><div className="review-human"><small>SCRIPTED HUMAN JUDGMENT</small><strong>Timeline not agreed</strong><p>“Later” is not an agreed timeline.</p></div></div><div className="heading-actions"><button className="outline-button" disabled={review.status === 'REVIEWED'} onClick={() => { store.saveReview(false); setRevision(value => value + 1); setNotice('Review progress saved in DEMO memory only.') }}>Save scripted disagreement</button><button className="primary-button" disabled={review.status === 'REVIEWED'} onClick={() => { store.saveReview(true); setRevision(value => value + 1); setNotice('Review completed in DEMO memory. The original AI result is preserved.') }}>Complete review</button></div>{review.status === 'REVIEWED' && <div className="demo-banner">Calibration: {review.comparison.agreements} agreements · {review.comparison.disagreements} disagreement. Only this completed review contributes to this comparison.</div>}<details><summary>Demo review audit ({review.events.length} events)</summary>{review.events.map((event, index) => <p key={index}>{event.kind.replaceAll('_', ' ')} · revision {event.revision} · {event.at}</p>)}</details></section>}
    {step === 7 && <><section className="panel"><h2>Operate with explicit controls</h2><dl className="demo-definition"><dt>Scheduling</dt><dd>Simulated daily, 08:00 Europe/London · next 4 Oct 2026 · not enabled on any server</dd><dt>Review SLA</dt><dd>Due soon window: 24 hours · escalation after 48 overdue hours · case state: {reviewDueState(review, demoClock)}</dd><dt>Alerts</dt><dd>Prepared warning: resolution guidance needs calibration</dd><dt>Delivery configuration</dt><dd>Simulated, disabled destination · no external notification sent</dd><dt>Retention and audit</dt><dd>Read-only explanation; no purge or configuration write</dd></dl><details><summary>Scripted audit</summary>{review.events.map((event, index) => <p key={index}>{event.kind.replaceAll('_', ' ')} · {event.at}</p>)}</details><button className="outline-button" onClick={unsupported}>Why are live governance actions unavailable?</button></section><section className="panel"><h2>Ready to explore a pilot?</h2><p>Agree a narrow scope, representative content and human calibration before validating accuracy, operating costs and capacity.</p><button className="primary-button" onClick={() => onExit(true)}>Explore a pilot</button></section></>}
  </main></div></div>
}
